mongodb/mongo-c-driver

- src/libbson/doc/bson_decimal128_t.rst
- src/libbson/doc/bson_value_t.rst
Refer: CDRIVER-4586
Also clarify the meaning and structure of bson_decimal128_t
> CDRIVER-4586: Add missing docs for v_decimal128 in bson_value_t

- src/libmongoc/CMakeLists.txt
This fixes installation when the target file's destination is not at the guessed location (e.g. multiconf installs)
> Don't guess a target's filepath for the install rule

- src/libmongoc/tests/json/client_side_encryption/unified/rewrapManyDataKey.json
A simple test file sync to resolve CDRIVER-4559. Verified by [this patch](https://spruce.mongodb.com/version/642d91a50ae6066ca40db27a) (many tasks failing due to unrelated issues).
> CDRIVER-4559 Sync unified client side encryption test files with 1d5630db

- src/libmongoc/doc/mongoc_client_encryption_encrypt_range_opts_set_min_max.rst
- src/libmongoc/doc/mongoc_client_encryption_encrypt_range_opts_set_precision.rst
- src/libmongoc/doc/mongoc_client_encryption_encrypt_range_opts_set_sparsity.rst
Fixes typos dating back to https://github.com/mongodb/mongo-c-driver/commit/7a6b6369eb918bc2698fd6dc3aeab12845176a36 for #1152.
> CDRIVER-4394 fix function names in range index docs

- src/libmongoc/tests/test-mongoc-collection.c
- Drop test collection with `writeConcern=majority` in `test_count_read_concern_live`
Verified with this patch: https://spruce.mongodb.com/version/64306c5be3c331e640d0ec57
This PR intends to address recently observed failures in the `/Collection/count/read_concern_live` test.
Here is an [example failure](https://spruce.mongodb.com/task/mongo_c_driver_sanitizers_matrix_asan_asan_sasl_cyrus_openssl_ubuntu1804_clang_test_latest_replica_auth_8aced03a963e70182b79d883e881f239766b09bf_23_04_06_18_37_29/logs?execution=0) with relevant logs:
```
[2023/04/06 19:22:39.014] FAIL:/data/mci/af9f1bf18f00ea2288ac8214a6caa522/mongoc/src/libmongoc/tests/test-mongoc-collection.c:2288  test_count_read_concern_live()
[2023/04/06 19:22:39.014]   count == 0
[2023/04/06 19:22:39.044] …
```
> Drop test collection with `writeConcern=majority`

- build/future_function_templates/future-value.c.template
- src/kms-message/src/kms_crypto_none.c
- src/kms-message/src/kms_crypto_windows.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c
- src/libmongoc/tests/bsonutil/bson-match.c
- src/libmongoc/tests/mock_server/future-value.c
- src/libmongoc/tests/mock_server/mock-server.c
- src/libmongoc/tests/mock_server/sync-queue.c
- src/libmongoc/tests/test-conveniences.c
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/unified/test-diagnostics.c
Addresses the current [scan-build-macos-1100-clang](https://spruce.mongodb.com/task/mongo_c_driver_scan_build_matrix_scan_build_macos_1100_clang_abb0bb7da8230d342dac5061623c1e4936ed46d9_23_04_14_14_11_58/logs?execution=1) task failure.
This warning seems to be emitted only on occasion as the codebase changes (inconsistent scan-build behavior?). This PR does a thorough find-and-replace of _all_ instances (except those in bundled zlib) to hopefully squash this warning for good.
> Find and replace all -Wstrict-prototypes violations

- .evergreen/config_generator/components/funcs/fetch_det.py
- .evergreen/config_generator/components/funcs/run_simple_http_server.py
- .evergreen/config_generator/etc/sanitizers/test.py
- .evergreen/config_generator/etc/sasl/test.py
- .evergreen/config_generator/requirements.txt
- .evergreen/generated_configs/functions.yml
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/integration-tests.sh
- .evergreen/scripts/run-tests.sh
- .evergreen/scripts/simple_http_server.py
- src/libmongoc/tests/test-mongoc-http.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1179. Partially resolves CDRIVER-4134. Verified by [this patch](https://spruce.mongodb.com/version/6439af08850e6141fdb1a681).
Due to [continued failure](https://spruce.mongodb.com/version/mongo_c_driver_abb0bb7da8230d342dac5061623c1e4936ed46d9/tasks) of the `/http` tests, this PR replaces use of `httpbin.org` with a simple Python HTTP server we run instead.
~Note: some tasks still fail on the rhel70 and windows-64-vs2017 distros, but deliberately deferring them to a followup PR to unblock _most_ of the other tasks that currently fail that this PR addresses.~ Identified the issue being due to the absence of a `python3` binary when `simple_http_server.py` is directly invoked.
Uses the Python `http` package. It is a simple HTTP …
> CDRIVER-4134 Use simple HTTP server for /http tests

- src/libmongoc/doc/mongoc_apm_command_failed_get_server_connection_id.rst
- src/libmongoc/doc/mongoc_apm_command_failed_get_server_connection_id_int64.rst
- src/libmongoc/doc/mongoc_apm_command_failed_t.rst
- src/libmongoc/doc/mongoc_apm_command_started_get_server_connection_id.rst
- src/libmongoc/doc/mongoc_apm_command_started_get_server_connection_id_int64.rst
- src/libmongoc/doc/mongoc_apm_command_started_t.rst
- src/libmongoc/doc/mongoc_apm_command_succeeded_get_server_connection_id.rst
- src/libmongoc/doc/mongoc_apm_command_succeeded_get_server_connection_id_int64.rst
- src/libmongoc/doc/mongoc_apm_command_succeeded_t.rst
- src/libmongoc/src/mongoc/mongoc-apm.c
- src/libmongoc/src/mongoc/mongoc-apm.h
- src/libmongoc/tests/unified/entity-map.c
- Add `connection_id` functions returning int64:
- `mongoc_apm_command_started_get_server_connection_id_int64`
- `mongoc_apm_command_succeeded_get_server_connection_id_int64`
- `mongoc_apm_command_failed_get_server_connection_id_int64`
- Deprecate `connection_id` functions returning int32
CDRIVER-4593 and CDRIVER-4557 applied fixes to parsing `connectionId` to handle `int32`, `int64`, and `double`. No further fix was needed.
This PR intends to satisfy the requirement of DRIVERS-2503:
> If the client and server connectionId fields are part of the driver's public API, you may have to add new int64 connectionId fields and deprecate the existing int32 fields.
> CDRIVER-4557 add int64 `connection_id` functions

- .evergreen/config_generator/components/scan_build.py
- .evergreen/generated_configs/tasks.yml
The `scan-build-ubuntu1404-clang` has been [failing in Evergreen](https://spruce.mongodb.com/task/mongo_c_driver_scan_build_matrix_scan_build_ubuntu1404_clang_4249c975ac2835a9e4329996e48986c368c81776_23_04_26_13_03_02/) attempting to clone libmongocrypt:
```
[2023/04/26 13:05:28.278] fatal: unable to access 'https://github.com/mongodb/libmongocrypt/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
[2023/04/26 13:05:28.279] Command 'subprocess.exec' in function 'scan-build' failed: process encountered problem: exit code 128.
```
I expect the distro needs to be updated to install necessary CA certificates (similar to BUILD-14189).
This PR proposes removing the `scan-build-ubuntu1404-clang` task. I expect this task does not add much (if any) …
> remove `scan-build-ubuntu1404-clang` task

- src/libmongoc/src/mongoc/mongoc-cluster.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1248. Missed a codepath removal. Verified by [this patch](https://spruce.mongodb.com/version/644aeda4850e61dec7cce419) (with proper assertions this time).
> CDRIVER-4629 Remove OP_QUERY codepath in mongoc_cluster_run_command_monitored

- src/libmongoc/CMakeLists.txt
- src/libmongoc/doc/mongoc_collection_command_simple.rst
- src/libmongoc/doc/mongoc_collection_stats.rst
- src/libmongoc/doc/tutorial.rst
- src/libmongoc/examples/example-collection-command.c
- src/libmongoc/examples/tutorial/executing.c
- src/libmongoc/tests/json/client_side_encryption/legacy/bypassedCommand.json
- src/libmongoc/tests/test-mongoc-collection.c
- src/libmongoc/tests/test-mongoc-sample-commands.c
- Remove use of `collStats`
From DRIVERS-2232:
> For drivers that have helpers for collStats or currentOp, the helpers should be adjusted to use the $collStats / $currentOp aggregation pipeline stages.  Alternatively, drivers can deprecate these helpers for future removal.  This is left to the discretion of drivers.
`mongoc_collection_stats` is already deprecated. Examples using `mongoc_collection_stats` were updated to use aggregation with the `$collStats` pipeline stage. There is no helper for `currentOp`.
---
Example code was moved from .rst files into the `examples` directory and included with the `literalinclude` directive. This is intended to have the examples compile in Evergreen.
---
The `runCommand Example 2` example, which used `collStats`, was removed. This example was added …
> CDRIVER-4556 Remove use of `collStats`

- .evergreen/scripts/compile-libmongocrypt.sh
- src/libmongoc/src/mongoc/mongoc-crypt.c
- use libmongocrypt 1.8.0-alpha1
- remove use of `mongocrypt_setopt_fle2v2`
Verified with this patch: https://spruce.mongodb.com/version/645000960305b9b9e28f5371
This PR is a follow-up to https://github.com/mongodb/mongo-c-driver/pull/1228
Queryable Encryption v2 is enabled by default in libmongocrypt 1.8.0-alpha1. libmongocrypt 1.8.0-alpha1 removes the symbol `mongocrypt_setopt_fle2v2` from the public API. `mongocrypt_setopt_fle2v2` was added in libmongocrypt 1.8.0-alpha0.
> CDRIVER-4584 use libmongocrypt 1.8.0-alpha1

- src/libmongoc/tests/test-mongoc-client.c
GCC 13 warns that `pool` may be used uninitialized. This is a false positive because pool will only be used in the case that it is initialized, but by initializing it to NULL we can avoid this warning.
> CDRIVER-4633 Fix compiler warning

- .evergreen/.codecov.yml
- .evergreen/config_generator/etc/cse/compile.py
- .evergreen/generated_configs/functions.yml
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/functions.py
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/run-tests.sh
Resolves CDRIVER-4621. Verified by [this patch](https://spruce.mongodb.com/version/6452b700a4cf47cc42d991bf).
Replaced the deprecated codecov-bash command with the new Codecov Uploader. Also applied verbosity-reduction filters to reduce the output of code coverage commands.
Fixed the coverage task so it actually compiles with CSE enabled before running CSE tests. The coverage task currently skips most of the CSE tests it's supposed to run due to CSE being disabled, producing an abysmal coverage report. 🥴
Added `test-coverage-latest-replica-set-auth-sasl-openssl` to account for the `-cse` task limiting tests to CSE tests only (since https://github.com/mongodb/mongo-c-driver/pull/1201).
Removed `-DENABLE_CLIENT_SIDE_ENCRYPTION=ON` in `EXTRA_CONFIGURE_FLAGS` for CSE tasks, as it is …
> CDRIVER-4621 Replace codecov-bash with new Codecov Uploader

- src/libmongoc/src/mongoc/mongoc-async-cmd-private.h
- src/libmongoc/src/mongoc/mongoc-async-cmd.c
- src/libmongoc/src/mongoc/mongoc-cluster-private.h
- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/src/mongoc/mongoc-rpc-private.h
- src/libmongoc/src/mongoc/mongoc-rpc.c
- src/libmongoc/src/mongoc/mongoc-server-monitor.c
Motivated by CDRIVER-4625. Moves the `_mongoc_rpc_prep_command`, `_mongoc_rpc_compress`, and `_mongoc_rpc_decompress_if_necessary` functions into the components where they are actually required. This significantly reduces the internal component dependencies required by the mongoc-rpc component.
> Reduce internal component dependencies for mongoc-rpc

- src/libmongoc/src/mongoc/mongoc-topology-scanner.c
- src/libmongoc/tests/test-mongoc-client.c
- src/libmongoc/tests/test-mongoc-speculative-auth.c
This PR fixes an issue where the result of a previous speculative authentication is kept around despite the authentication state being reset. This causes single-threaded clients to assume a connection is authenticated when it isn't. Due to a speculative authentication response being present, subsequent handshakes will not attempt speculative authentication. However, when checking the response of the handshake, the previous speculative authentication response is reused.
When using SCRAM authentication, the previous result is no longer valid and continuing the SCRAM conversation will immediately fail as the server rejects the contents. This leads to authentication being reset and a regular authentication cycle to commence.
When using X.509, the presence of a `speculativeAuthenticate` field …
> CDRIVER-4635 Reset speculative_auth_response when resetting auth state

- src/libmongoc/src/mongoc/mongoc-counters.c
Hi,
This patch tries to fix an unexpected crash we have been witnessing in one of our production environment as /dev/shm was somehow (almost) full.
Indeed `ftruncate` doesn't ensure memory is properly allocated, it only changes the file size from the VFS point of view, but doesn't actually allocate any memory. So `ftruncate` might work despite we have no memory left, and later when trying to zero-memset the mmapped buffer, we might actually get a SIGBUS signal crashing the whole process.
Instead, make sure we can allocate the whole shared memory using `posix_fallocate` and gracefully handle allocation problems, without crashing.
The chromium project faced a similar issue in the past: https://bugs.chromium.org/p/chromium/issues/detail?id=951431
As a complementary, here is how to reproduce …
> CDRIVER-4627 Avoid unexpected crash with SIGBUS when trying to allocate a /dev/shm shared memory but there is not enough memory

- src/libmongoc/doc/conf.py
- src/libmongoc/doc/mongoc_collection_find_and_modify.rst
- src/libmongoc/doc/mongoc_collection_find_and_modify_with_opts.rst
- src/libmongoc/doc/mongoc_find_and_modify_opts_append.rst
- src/libmongoc/doc/mongoc_find_and_modify_opts_set_bypass_document_validation.rst
- src/libmongoc/doc/mongoc_find_and_modify_opts_t.rst
Update the documentation of `mongoc_collection_find_and_modify` and `mongoc_collection_find_and_modify_with_opts` to clarify the `reply` contains the full server reply.
See CDRIVER-4173. The current documentation suggested:
> Returns either the document before or after modification based on the _new parameter.
This is really referring to the `value` field inside the server reply:
```js
{
"lastErrorObject": {
"n": 1,
"updatedExisting": true
},
"value": "<here is the document>",
"ok": 1.0
}
```
> CDRIVER-4173 clarify the `reply` contains the full server reply

- src/libbson/doc/bson_iter_find.rst
- src/libbson/doc/bson_iter_find_case.rst
- src/libbson/doc/bson_iter_find_w_len.rst
- src/libbson/doc/bson_t.rst
- src/libbson/tests/test-bson.c
- test bson_t behavior with duplicate keys
- note `bson_iter_find_*` advances to the first key
- note undefined server behavior with duplicate keys
It is possible to constructing `bson_t` with duplicate keys by manually appending, reading BSON data, or parsing JSON. The [BSON specification](https://bsonspec.org) does not require keys be unique. The motivation for testing behavior of `bson_t` with duplicate keys was to ensure this behavior is not unintentionally changed in the future.
DRIVERS-612 notes:
> The documentation MUST mention that the server's behavior related to duplicate key names is undefined
> CDRIVER-2982 test and document duplicate key handling

- src/libbson/src/bson/bson-iter.h
Addresses several implicit conversion warnings primarily due to the use of `BSON_UINT<N>_FROM_LE`.
Using the same local environment as described in prior Reducing Warnings PRs, this PR reduces total warnings by:
- GCC: 4086 -> 2711 (-33.7%)
- Clang: 3803 -> 1708 (-55.1%)
and reduces unique warnings by:
- GCC: 944 -> 939 (-0.5%)
- Clang: 1106 -> 1101 (-0.5%)
> Reducing Warnings - Implicit signed conversions in bson-iter.h

- .evergreen/.codecov.yml
Followup to https://github.com/mongodb/mongo-c-driver/pull/1257. Updates the filter list to properly exclude the `tests` directory under `src/libbson` and `src/libmongoc`, as `src/*/tests` does not behave as intended.
> Fix coverage filter to ignore test directories

- src/libmongoc/doc/mongoc_client_encryption_rewrap_many_datakey.rst
- src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
- src/libmongoc/src/mongoc/mongoc-crypt.c
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
- return error if `masterKey` is set, but `provider` is not set for `rewrapManyDataKey`
- add prose test specified in DRIVERS-2441
The specified API for `rewrapManyDataKey` does not permit calling with a set `masterKey` without a `provider`.
```typescript
class ClientEncryption {
rewrapManyDataKey(filter: Document, opts: RewrapManyDataKeyOpts | null): RewrapManyDataKeyResult;
}
class RewrapManyDataKeyOpts {
provider: String
masterKey: Optional<Document>
}
```
Some driver implementations do not represent `RewrapManyDataKeyOpts` as a separate type. Instead, the `provider` and `masterKey` are both optional arguments to `RewrapManyDataKey`.
The C driver API permits setting `masterKey` without `provider`:
```c
MONGOC_EXPORT (bool)
mongoc_client_encryption_rewrap_many_datakey ( …
```
> CDRIVER-4498 return error if `masterKey` is set, but `provider` is not set

- src/libmongoc/tests/json/collection-management/timeseries-collection.json
- sync timeseries-collection.json test to https://github.com/mongodb/specifications/commit/0fa17f36d4bd4def1dd5acd30264f0e2cc026d6d
DRIVERS-2546 notes there are two new options for the `create` command:
> Note this project will require DBX changes (at least in some drivers) to add the new "timeseries.bucketMaxSpanSeconds" and "timeseries.bucketRoundingSeconds" fields for the [create command](https://www.mongodb.com/docs/v6.0/reference/command/create/#command-fields)
New options to the `create` command do not require code or documentation changes in the C driver. `mongoc_database_create_collection` accepts a `bson_t` argument for options and passes options to the `create` command with [the call to `_mongoc_client_command_with_opts`](https://github.com/mongodb/mongo-c-driver/blob/9c14bae958b …
> CDRIVER-4582 sync timeseries-collection.json test

- src/libmongoc/doc/installing.rst
- Document install of `libmongoc-dev` and `libbson-dev` packages.
- Document install of `mongo-c-driver-devel` and `libbson-devel` packages.
The [Install libmongoc with a Package Manager](https://mongoc.org/libmongoc/1.23.4/installing.html#install-libmongoc-with-a-package-manager) instructions show install of the `libmongoc-1.0-0` package.
The `libmongoc-1.0-0` package does not include headers:
```
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libmongoc-1.0.so.0.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libmongoc-1.0-0
/usr/share/doc/libmongoc-1.0-0/NEWS.gz
/usr/share/doc/libmongoc-1.0-0/README.rst
/usr/share/doc/libmongoc-1.0-0/THIRD_PARTY_NOTICES.gz
/usr/share/doc/libmongoc-1.0-0/copyright
/usr/share/lintian
/usr/share/lintian/overrides …
```
> CDRIVER-3717 show dev packages in install instructions

- .evergreen/scripts/compile-libmongocrypt.sh
- src/libmongoc/doc/mongoc_auto_encryption_opts_set_bypass_query_analysis.rst
- src/libmongoc/doc/mongoc_auto_encryption_opts_set_encrypted_fields_map.rst
- src/libmongoc/doc/mongoc_client_encryption_create_encrypted_collection.rst
- src/libmongoc/doc/mongoc_client_encryption_encrypt.rst
- src/libmongoc/doc/mongoc_client_encryption_encrypt_opts_set_algorithm.rst
- src/libmongoc/doc/mongoc_client_encryption_encrypt_opts_set_contention_factor.rst
- src/libmongoc/doc/mongoc_client_encryption_encrypt_opts_set_query_type.rst
- src/libmongoc/doc/queryable-encryption.rst
- update libmongocrypt test dependency to 1.8.0
- remove "Public Technical Preview" from QE API for equality
- revise Queryable Encryption page to document backwards break
Changes are requested in the "Downstream Changes Summary" of DRIVERS-2614
> CDRIVER-4638 Remove "Public Technical Preview" from Queryable Encryption Equality API

- .evergreen/config_generator/components/mock_server.py
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/functions.py
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- src/libmongoc/tests/test-mongoc-counters.c
- src/libmongoc/tests/test-mongoc-loadbalanced.c
This PR partially resolves CDRIVER-4645.
- Remove some unused tasks from legacy Evergreen config.
- Add a `mock-server-test` variant.
Here is a patch build for the new `mock-server-test` variant: https://spruce.mongodb.com/version/646a3d470305b97abfa79790
[This validate.py script](https://gist.github.com/kevinAlbs/f6e45a6f9cbc16f95f87d2b789abb516) can print unused tasks. Before these changes, this is the output:
```
% evergreen evaluate ./.evergreen/config.yml > evaluated.yml
% python validate.py                                        
`tasks` not referenced in `buildvariants` or `task_groups`:
-authentication-tests-openssl-static
-debug-compile-asan-clang
-debug-compile-asan-clang-openssl
-debug-compile-asan-openssl-cse
-debug-compile-compression
-debug-compile-sasl-darwinssl-cse …
```
> CDRIVER-4645 add `mock-server-test` variant

- src/libbson/src/bson/bson-atomic.c
- src/libbson/src/bson/bson-atomic.h
- src/libbson/src/bson/bson-context.c
bson_atomic_int32_fetch_add  is generated with the type DECL_ATOMIC_INTEGRAL_INT32, but is coded as int32_t in two places. This results in an incompatible pointer types error when MSVC is true from the bson-atomic.h file.
This patch resolves the error, tested and resolved with clang-cl for compatibility.
> bson_atomic_int32_fetch_add uses a header declared type for the int32_t argument

- src/libmongoc/src/mongoc/mongoc-client-private.h
- Increase `WIRE_VERSION_MAX` to `WIRE_VERSION_7_0`.
- Add macro for `WIRE_VERSION_3_6`.
> CDRIVER-4601 Bump maxWireVersion for MongoDB 7.0

- build/calc_release_version.py
Evergreen patch build: https://spruce.mongodb.com/version/646e3c8932f417f4c6dc9c06/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-4603 use setuptools rather than distutils (deprecated) for version calc

- .evergreen/config_generator/components/funcs/fetch_source.py
- .evergreen/generated_configs/functions.yml
- build/calc_release_version.py
Followup to https://github.com/mongodb/mongo-c-driver/pull/1281. Verified by [this patch](https://spruce.mongodb.com/version/6477be24c9ec4461a977c483).
Rather than dealing with Python binary detection in the EVG `fetch-source` function (which is complicated by the fact that it is run as a pre command before `fetch-det`, `tools/python.sh` does not cover all the required use cases, and we do not want to re-implement the `find-python3.sh` DET script here), implement a fallback strategy to attempt to use the newest, recommended package `packaging` before alternatives.
Note: attempts to [ensure `packaging` is installed](https://parsley.mongodb.com/evergreen/mongo_c_driver_clang35_debug_compile_nosasl_openssl_patch_6cbb08bd7cdd1dd7e7d30d374212a002955d0789_6477ba130ae6064cdc9864c5_23_05_31_21_20_ …
> CDRIVER-4603 Apply fallback for packaging -> pkg_resources -> distutils

- tools/platform.sh
When in WSL, the environment is (for all intents and purposes) equivalent to being on the corresponding Linux OS. It is incorrect to treat the OS as Windows in such an environment.
> Do not treat a WSL Linux environment as Windows

- build/cmake/SphinxBuild.cmake
The [make-release-archive](https://parsley.mongodb.com/evergreen/mongo_c_driver_releng_make_release_archive_cf8755017c4716ff28d3d88aff3fb11aa579ce58_23_05_26_00_03_16/0/task?bookmarks=0,641&shareLine=520) task is currently flaky on waterfall and blocking most of the Release variant tasks due to the following error:
```
Exception occurred:
File "/home/ubuntu/.cache/pypoetry/virtualenvs/mongo-c-driver-jXmnJTn7-py3.10/lib/python3.10/site-packages/sphinx/environment/__init__.py", line 612, in get_doctree
doctree = pickle.load(f)
EOFError: Ran out of input
```
An attempt was made to upgrade Sphinx to 3.1.1 due to [documented fixes to parallel builds](https://www.sphinx-doc.org/en/master/changes.html#release-3-1-1-released-jun-14-2020), but failed due to the [following …
> Revert Sphinx parallel build of HTML docs

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
A small followup to https://github.com/mongodb/mongo-c-driver/pull/1294 that also migrates MinGW tasks in the legacy config to the `windows-vsCurrent` distro from `windows-64-vs2013` for consistency. Verified by [this patch](https://spruce.mongodb.com/version/647e0a587742ae93798b684f/tasks).
> Move all MinGW tasks to windows-vsCurrent distro

- src/libbson/doc/bson_iter_as_double.rst
Fixed the bson_iter_as_double documentation to display the correct return type.
> CDRIVER-4620: Changed bson_iter_as_double documentation to return double instead of bool

- src/libmongoc/tests/json-test-monitoring.c
- src/libmongoc/tests/json/client_side_encryption/legacy/fle2v2-CreateCollection.json
- src/libmongoc/tests/test-conveniences.c
- Prohibit extra fields when matching `command` subdocuments in the legacy specification test runner
- Add missing call to `visitor_fn` when matching arrays
- Copy fle2v2-CreateCollection from https://github.com/mongodb/specifications/commit/e59a0ac6daa19e7605b0a1d2c667a67367d52edd
Described in https://github.com/mongodb/specifications/pull/1429. The expected behavior for matching command-started events in the legacy Client-Side Encryption test format is to only allow extra fields at the top level of the `command` document.
Example expectation:
```json
{
"command_started_event": {
"command": {
"create": "encryptedCollection",
"encryptedFields": {
"fields": [
{
"path": "firstName",
"bsonType": "string",
"keyId": {
"$binary": {
"subType": "04",
"base64": "AAAAAAAAAAAAAAAAAAAAAA=="
}
}
}
]
} …
```
> CDRIVER-4657 Prohibit extra fields when matching `command` subdocuments

- NEWS
- src/libbson/NEWS
Resolves CDRIVER-4542 and CDRIVER-4541.
> Document dropping support of Ubuntu 14.04 and Debian 8.1

- src/libmongoc/src/mongoc/mongoc-sspi.c
Do not pass username to SSPI when password is not set
This is intended to fix an [observed error](https://jira.mongodb.org/browse/HELP-24935?focusedCommentId=5412230&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-5412230) when authenticating with GSSAPI with Windows SSPI. This appears to be the caused by the issue described in DRIVERS-2180.
The URI for GSSAPI may omit the password. The [Auth specification for GSSAPI](https://github.com/mongodb/specifications/blob/840e6d49c354656bff11b2622f0d3001b39d9403/source/auth/auth.rst#gssapi) notes:
> password
> MAY be specified. If omitted, drivers MUST NOT pass the username without password to SSPI on Windows and instead use the default credentials.
When the username is set and password omited from the URI, the C …
> CDRIVER-4291 do not pass username to SSPI when password is not set

- src/libmongoc/tests/test-mcd-rpc.c
Patch to https://github.com/mongodb/mongo-c-driver/pull/1296 addressing compilation failure on Windows tasks due to `mongoc_iovec_t::iov_base` being `char*` instead of `void*`, triggering distinct pointer type comparison/conversion warnings.
> Address distinct pointer type warnings on Windows

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
also, use image rhel90-arm64-small for rpm-package-build
Evergreen patch build: https://spruce.mongodb.com/version/6484c2f93e8e86f9718410d6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The switch to rhel90-arm64-small  also turns the task green again.
> sync RPM spec file from downstream

- src/libbson/doc/bson_array_as_canonical_extended_json.rst
- src/libbson/doc/bson_array_as_json.rst
- src/libbson/doc/bson_array_as_relaxed_extended_json.rst
- src/libbson/doc/bson_json_opts_set_outermost_array.rst
- src/libbson/doc/bson_json_opts_t.rst
- src/libbson/doc/bson_t.rst
- src/libbson/doc/includes/seealso/bson-as-json.txt
- src/libbson/src/bson/bson-json-private.h
- src/libbson/src/bson/bson-json.c
- src/libbson/src/bson/bson-json.h
- src/libbson/src/bson/bson.c
- src/libbson/src/bson/bson.h
- src/libbson/tests/test-json.c
- Added functions to `bson_array_as_json` to mimic the functionality of `bson_as_json` and allow for legacy, relaxed, and canonical json output
- Added a new option to `bson_json_opts_t` to specify if the BSON is an outermost array
- Added a function to set this new option as we cannot change the `bson_json_opts_t` initializer
- Included necessary additional tests
- Tested in conjunction with https://github.com/mongodb/mongo-cxx-driver/pull/976
> CDRIVER-4659 Add extended json output capability for `bson_array_as_json`

- src/libmongoc/tests/test-mongoc-collection.c
Minor improvement: libbson headers included from libmongoc (both library and tests) are always specified with the `bson/` prefix.
> Consistent include pattern for libbson header in test-mongoc-collection.c

- build/opts_templates/mongoc-opts.c.template
- src/libmongoc/src/mongoc/mongoc-opts.c
- src/libmongoc/tests/test-mongoc-bulk.c
- do not assert `client` is not NULL in option parsing.
Follow up to https://github.com/mongodb/mongo-c-driver/pull/1302. `client` may expectedly be NULL when parsing options. See the included regression test for an example.
> CDRIVER-4665 do not assert `client` in option parsing

- src/libmongoc/doc/mongoc_cursor_new_from_command_reply.rst
- src/libmongoc/doc/mongoc_cursor_new_from_command_reply_with_opts.rst
- src/libmongoc/src/mongoc/mongoc-cursor-cmd.c
- src/libmongoc/tests/test-mongoc-cursor.c
Patch build: https://spruce.mongodb.com/version/6495b91ed1fe075c5a548f5a
Return an error if `mongoc_cursor_new_from_command_reply(_with_opts)` is called with a non-zero cursor ID and no server ID.
`mongoc_cursor_new_from_command_reply_with_opts` is expected to be used by drivers wrapping the C driver to create a `mongoc_cursor_t` from a server reply.
The server reply indicates whether a cursor is completed by a non-zero `cursor.id` field. Example with `mongosh`:
```js
> db.coll.drop()
true
> db.coll.insertMany([{_id:0},{_id:1}])
{ acknowledged: true, insertedIds: { '0': 0, '1': 1 } }
> db.runCommand({find: "coll", batchSize: 1})
{
cursor: {
firstBatch: [ { _id: 0 } ],
id: Long("2413824932427886184"),
ns: 'test.coll'
},
ok: 1,
'$clusterTime': {
clusterTime: Timestamp({ t: 1687535574, i: 3 …
```
> CDRIVER-3969 error when creating uncompleted cursor with no server ID

- build/cmake/MongoC-Warnings.cmake
- build/cmake/make_dist/MakeDist.cmake
- build/cmake/make_dist/MakeDistCheck.cmake
- build/cmake/make_dist/MakeDistFiles.cmake
- src/libmongoc/CMakeLists.txt
- src/libmongoc/doc/advanced-connections.rst
Remove unnecessary cmake version checks.
As of 3165a356473a1d50d1142d7071bd46bb5bb81c2a the minimum required cmake version has increased to 3.15. This PR removes cmake version checks and documentation that assumes older cmake versions could be used.
> remove unnecessary cmake version checks

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
- .evergreen/scripts/integration-tests.sh
A change in driver-evergreen-tools caused changes in download behavior, making the legacy shell unavailable for `integration-tests.sh`. This change prevents the install thereof and updates `integration-tests.sh` to not use the legacy shell.
> Fixes for running integration tests on Ubuntu 22.04+

- src/libmongoc/tests/test-mongoc-cursor.c
- Set `serverId` with cursor reply in mock server tests.
Patch build: https://spruce.mongodb.com/version/64a31761d6d80a59abafb6fa
This is a follow-up to https://github.com/mongodb/mongo-c-driver/pull/1321 intended to fix the `mock-server-test` task.
Some mock server tests were not updated in https://github.com/mongodb/mongo-c-driver/pull/1321 resulting in test failures in the `mock-server-test` task ([example](https://spruce.mongodb.com/task/mongo_c_driver_mock_server_test_mock_server_test_80bf069a1715b3ec86d478f3ce6226d44b7a00f9_23_06_30_19_24_27/logs?execution=0)):
```
[2023/06/30 19:34:11.873] FAIL:/data/mci/9db2b61a88bd7d9576782354fa709a71/mongoc/src/libmongoc/tests/test-mongoc-cursor.c:1126  test_cursor_new_tailable_await()
[2023/06/30 19:34:11.873]   !mongoc_cursor_error (cursor, …
```
> CDRIVER-3969 set serverId with mocked cursor reply

- debian/build_snapshot.sh
This change will make it so that patch builds triggered from GitHub PRs will not fail because of the version calculation returning a wrong result. It switches to using the version number from the Debian changelog.
> more robust version calculation in Debian snapshot builds

- src/libmongoc/src/mongoc/mongoc-cluster-aws.c
https://jira.mongodb.org/browse/CDRIVER-4694
This fixes an assert failure during MONGODB-AWS auth when an application is bundled with both libmongoc and libmongocrypt, and libmongocrypt's KMS library is used.
---
Note: this is pending test with the PHP driver. I'll follow up once I confirm it resolves the issue.
> CDRIVER-4694 calculate payload length for kms_request_append_payload()

- CONTRIBUTING.md
- src/libmongoc/tests/json-test.c
- fix possible leak in `run_json_general_test`
- document example use of `MONGOC_JSON_SUBTEST`
CDRIVER-3008 includes the reported leak discovered by Coverity. The leak can be reproduced with:
```
export MONGOC_JSON_SUBTEST="Aggregate with deterministic encryption"
./cmake-build/src/libmongoc/test-libmongoc -d --no-fork -l "/client_side_encryption/legacy/aggregate"
```
LSan reports:
```
==52500==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x102f515b0 in wrap_malloc+0x8c (libclang_rt.asan_osx_dynamic.dylib:arm64+0x515b0) (BuildId: 2d3005610c2a36e7a5269cbe22ab009f32000000200000000100000000000b00)
#1 0x100fb4c90 in bson_malloc bson-memory.c:100
#2 0x100fd6508 in bson_strdup bson-string.c:331
#3 0x10087c818 in _mongoc_getenv …
```
> CDRIVER-3008 fix possible leak in `run_json_general_test`

- src/libbson/src/bson/bson-dsl.h
- src/libbson/tests/test-bson.c
- src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/src/mongoc/mongoc-server-description.c
- src/libmongoc/src/mongoc/mongoc-topology-description.c
- src/libmongoc/src/mongoc/mongoc-topology.c
- assert returned values of `bson_init_static`
Addresses Coverity issues with CIDs: 134030, 134029, 120108, and 120107.
The test macro `ASSERT` was used in test code. `BSON_ASSERT` was used in driver code.
`bson_init_static` returns false on failure. Failure may occur if the input BSON data is invalid. Callers ignoring the returned value have been updated to assert to result in an early error on invalid BSON data input.
> CDRIVER-2928 assert returned values of `bson_init_static`

- CMakeLists.txt
- src/libbson/CMakeLists.txt
- src/libbson/src/bson/bson-config.h.in
- src/libbson/src/bson/bson-error.c
Attempts to resolve CDRIVER-4679 by preferring the XSI-compliant version of `strerror_r` when available by using a more accurate feature test macros condition. The GNU extension is used as a fallback instead. An additional `#error` was added to hopefully improve the resulting compilation error if a supported `strerror_r` implementation cannot be found.
Verified by [this patch](https://spruce.mongodb.com/version/64b8210ac9ec44c255145475). Note: _not_ yet verified on Alpine Linux as described in CDRIVER-4679 as the corresponding EVG distro is not available, so not entirely confident this actually addresses the originally reported issue.
> CDRIVER-4679 Prefer XSI-compliant strerror_r when available

- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/tests/mock_server/mock-server.c
- assert return value of `mcd_rpc_message_to_iovecs`.
Addresses Coverity issue with CID 138246: "Dereference null return value". I do not expect these calls to `mcd_rpc_message_to_iovecs` to possibly fail given the current implementation. The added `BSON_ASSERT` is consistent with other calls. If future changes to `mcd_rpc_message_to_iovecs` result in a condition where `mcd_rpc_message_to_iovecs` may return NULL, this may prevent a NULL dereference.
> assert return of `mcd_rpc_message_to_iovecs`

- src/libmongoc/src/mongoc/mcd-azure.c
- remove excess duplicate call to `_mongoc_http_response_cleanup`
Addresses Coverity issues with CIDs: 133796, 133795
This issue was flagged by Coverity as a possible "Double free". But I expect the duplicate call to `_mongoc_http_response_cleanup` does not result in a double free.
`_mongoc_http_send` [zeroes the output `res`](https://github.com/mongodb/mongo-c-driver/blob/ba5ab6de26a874d33b0abc3d2b46961a69380e7a/src/libmongoc/src/mongoc/mongoc-http.c#L121). Fields in `res` are [set at the end](https://github.com/mongodb/mongo-c-driver/blob/ba5ab6de26a874d33b0abc3d2b46961a69380e7a/src/libmongoc/src/mongoc/mongoc-http.c#L306-L321) of the call when success is guaranteed.
Nonetheless, removing the duplicate call to `_mongoc_http_response_cleanup` seems like an improvement. If future changes …
> CDRIVER-4698 remove excess duplicate call

- src/libbson/src/bson/bson.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1344.
> Address C4267 size_t conversion warnings

- src/libmongoc/src/mongoc/mongoc-topology-scanner.c
- src/libmongoc/tests/test-mongoc-client.c
- Fix leak on repeated attempts to authenticate.
Verified with this patch build: https://spruce.mongodb.com/version/64c404bf61837d707d406bd7/
This PR is a follow up to https://github.com/mongodb/mongo-c-driver/pull/1258 to free fields in `node->scram` when resetting the authentication state.
Without the included fix, the newly added `/Client/failure_to_auth` test reports leaks with LSan:
```
=================================================================
==22270==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 4096 byte(s) in 1 object(s) allocated from:
#0 0x104e095b0 in wrap_malloc+0x8c (libclang_rt.asan_osx_dynamic.dylib:arm64+0x515b0) (BuildId: 2d3005610c2a36e7a5269cbe22ab009f32000000200000000100000000000b00)
#1 0x1031edb2c in bson_malloc bson-memory.c:100
#2 0x1028c5228 …
```
> CDRIVER-4699 fix leak on repeated attempts to authenticate

- src/libmongoc/tests/test-mongoc-handshake.c
- Do not override handshake arch in tests
Verified with this patch build: https://spruce.mongodb.com/version/64c960a3a4cf47d15d5590ab
Intended to fix the `sasl-cyrus-openssl-ubuntu1804-arm64-gcc-test-7.0-server-auth` task failing with this log:
```
[2023/08/01 18:19:55.889] Begin /MongoDB/handshake/faas/valid_aws, seed 4162539160
[2023/08/01 18:19:55.989] FAIL
[2023/08/01 18:19:55.989] Assert Failure:
[2023/08/01 18:19:55.989]   "aarch64"
[2023/08/01 18:19:55.989]   !=
[2023/08/01 18:19:55.989]   "x86_64"
[2023/08/01 18:19:55.989]  /data/mci/40006473c9ffecd981bc61b252685b65/mongoc/src/libmongoc/tests/test-mongoc-handshake.c:145  _check_arch_string_valid()
```
> CDRIVER-4493 do not override handshake arch in tests

- src/libmongoc/src/mongoc/mongoc-topology.c
- src/libmongoc/tests/test-mongoc-topology.c
- Remove locks during single-threaded scanning
Verified with this patch build: https://spruce.mongodb.com/version/64c8f895850e61ecb19a8c27
This change is intended to resolve a possible deadlock reported in CDRIVER-4666.
`mongoc_topology_scanner_scan` may call the callback `_mongoc_topology_scanner_setup_err_cb` on error. `_mongoc_topology_scanner_setup_err_cb` modifies the topology description. This results in a recursive lock of the topology description modification mutex from possible code paths:
1. `mongoc_topology_reconcile` (callers lock) -> `_mongoc_topology_reconcile_add_nodes` -> `mongoc_topology_scanner_scan` (locks again if setup fails)
2. `_mongoc_topology_scanner_cb` (locks) -> `mongoc_topology_scanner_scan` (locks again if setup fails)
These code-paths are only expected for …
> CDRIVER-4666 remove locks during single-threaded scanning

- CMakeLists.txt
- src/libbson/CMakeLists.txt
- src/libbson/src/bson/bson-config.h.in
- src/libbson/src/bson/bson-error.c
This PR reverts https://github.com/mongodb/mongo-c-driver/pull/1350 and re-addresses CDRIVER-4679 using a more nuanced solution. Given the information that [strerror_r is scheduled to be marked as obsolete](https://www.austingroupbugs.net/view.php?id=655) in the upcoming POSIX Issue, this PR favors using `strerror_l` instead of `strerror_r`, which is not susceptible to the GNU extension and musl library compatibility problems documented in https://github.com/mongodb/mongo-c-driver/pull/1350. Per the provided link:
> The strerror_r function is problematic because there are historically at least two versions, and at least one major implementation, the GNU C Library, seems committed to providing a version incompatible with the version specified in the standard. While an attempt is made in …
> CDRIVER-4679 Revert BSON_HAVE_XSI_STRERROR_R and use strerror_l instead

- src/libmongoc/CMakeLists.txt
Fixes compilation failures on EVG due to unexpected use of the deprecated `ASN1_STRING_data` function triggering warnings. Verified by [this patch](https://spruce.mongodb.com/version/64cc1917c9ec4458a5c8fc16).
The CMake variable `HAVE_ASN1_STRING_GET0_DATA` was being incorrectly set using `check_library_exists`, whose purpose is to check if a _library_ containing the specified _function_ (ABI) exists. This was being done even before the actual SSL library to be linked with was determined (setting of `SSL_LIBRARIES`). Potential problems with checking for the presence of a function are also noted in documentation for [CheckFunctionExists](https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html).
This PR fixes `ASN1_STRING_get0_data` detection by using the correct …
> Fix detection of ASN1_STRING_get0_data

- poetry.lock
- pyproject.toml
- tools/poetry.sh
This fixes an issue on newer Python installs that don't have `distutils` handy, as well as address a dependabot PR that could not merge correctly (#1284). Also, hold back PyYAML to avoid Cython-related issues (fixed in PyYAML 6, but Shrub requires PyYAML 5)
> Update Poetry and requests

- src/libmongoc/tests/test-libmongoc.c
Addresses a test suite regression introduced in https://github.com/mongodb/mongo-c-driver/pull/1220 (CDRIVER-2964). The UB is triggered when accessing the `suite` variable on this line: https://github.com/mongodb/mongo-c-driver/blob/b06a0018f377889a7e18928795f7e60bac3b4d7c/src/libmongoc/tests/test-libmongoc.c#L219
The `suite` variable is accessed as "a pointer to `TestSuite`", when its value is in fact "a pointer to _a pointer to_ `TestSuite`" as (incorrectly) set on this line: https://github.com/mongodb/mongo-c-driver/blob/b06a0018f377889a7e18928795f7e60bac3b4d7c/src/libmongoc/tests/test-libmongoc.c#L2682
When detected, ASAN reports the resulting UB in the form of a difficult-to-diagnose stack-use-after-free error. The actual cause is access of the `suite` _parameter_ in …
> Fix test suite log handler UB due to incorrect argument

- CMakeLists.txt
- build/cmake/BuildVersion.cmake
- The computation of BUILD_VERSION is now lifted above project(), which allows us to use that value in the project() call itself, giving us correct PROJECT_VERSION values throughout.
- Define BUILD_VERSION using mongo_setting(), and use the calc_release_version.py to compute its default value.
---
Possible concerns:
- The `LoadVersion` and `ParseVersion` are extremely similar, but both are required to get the project to work. Some locations refer to the `_VERSION_PATCH` suffix, while others use `_MICRO_VERSION` suffix. These could/should probably be consolidated to a single variable set.
- It isn't clear what the purpose of `BUILD_VERSION` (as a cache variable) serves when `VERSION_CURRENT` (the text file) will usually take precedence.
> Cleanup and relocate BUILD_VERSION calculation

- build/calc_release_version.py
- build/calc_release_version_selftest.sh
This changeset adds some minor stylistic changes and a significant speedup for calc_release_version. Refer to 18b2dded7ade19b5b50ac8e46f99aef93dfe346d for details.
> Speedup of calc_release_version.py

- src/libmongoc/src/mongoc/mongoc-topology.c
- src/libmongoc/src/mongoc/mongoc-uri.c
- src/libmongoc/src/mongoc/mongoc-util-private.h
- src/libmongoc/src/mongoc/mongoc-util.c
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-mongoc-topology.c
- src/libmongoc/tests/test-mongoc-uri.c
https://jira.mongodb.org/browse/CDRIVER-4682
The log messages are specified in [DRIVERS-2583](https://jira.mongodb.org/browse/DRIVERS-2583).
> CDRIVER-4682 log informational message for nongenuine hosts

- .evergreen/config_generator/components/kms_divergence_check.py
Followup to https://github.com/mongodb/mongo-c-driver/pull/1381. Addresses this very unhelpful error during EVG config generation:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File ".evergreen/config_generator/generate.py", line 34, in main
m.generate()
File ".evergreen/config_generator/generators/functions.py", line 13, in generate
functions.update(component.functions())
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
> Fix ValueError error during config generation

- src/libbson/examples/bson-streaming-reader.c
- src/libbson/src/bson/bson-dsl.md
- src/libbson/src/bson/bson-memory.c
- src/libbson/src/bson/bson.c
- src/libmongoc/src/mongoc/mongoc-cluster-aws.c
- src/libmongoc/src/mongoc/mongoc-cluster-sspi.c
- src/libmongoc/src/mongoc/mongoc-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-sspi.c
- src/libmongoc/tests/TestSuite.c
- src/libmongoc/tests/TestSuite.h
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-mongoc-matcher.c
Patch build: https://spruce.mongodb.com/version/64e928f59ccd4e4f7ecb296e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Note: The failure of authentication-tests-openssl on zSeries is spurious. I checked and it is also failing on master.
> CDRIVER-4536 replace calls to malloc/calloc/free with bson wrapper equivalents

- src/libmongoc/tests/unified/runner.c
Drive-by fix discovered during CDRIVER-4702 work.
> Address potential leak in unified test runner on killAllAssertions error

- src/libmongoc/doc/advanced-connections.rst
- src/libmongoc/doc/data-compression.rst
- src/libmongoc/doc/guides.rst
- src/libmongoc/doc/tutorial.rst
It looks to me like we already have sufficient documentation of how to use data compression. In this PR I relocated it to a top-level document (as indicated in the ticket) and added appropriate additional links.
> CDRIVER-4710 move data compression doc to top-level

- .evergreen/config_generator/components/earthly.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
- .evergreen/scripts/cmake.sh
- .evergreen/scripts/find-cmake-latest.sh
- .evergreen/scripts/find-cmake-version.sh
- Earthfile
- build/cmake/ResSearch.cmake
- tools/download.sh
- tools/earthly.sh
The prior attempt to use Earthly (PR #987) used a very loose meaning of the word "basic", and is too much to review in a single pass. This time around, that build process and needs are much better understood since the opening of that changeset, so I am confident that this is more tractable and can be incrementally improved in the future.
---
This PR adds an `Earthfile`, an earthly shim alike `poetry.sh`, and makes a few supporting modifications other scripts.
In this changeset, the Earthfile only defines targets for a very simple build and a "Can we link a user application against this?" test. Currently, it defines platforms for Ubuntu 22.04, Alpine, and Arch Linux. We do not yet have existing CI for neither Ubuntu 22.04 nor Alpine, which have both been "TODO" for a long time. There is an …
> An Even-More-Basic Earthly Project

- .evergreen/config_generator/components/funcs/prepare_kerberos.py
- .evergreen/generated_configs/functions.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/scripts/run-auth-tests.sh
Replace check of existence of `/etc/krb5.conf` with presence of `kinit` command.
Fixes failing `authentication-tests-darwinssl` task.
Changes verified with this patch build: https://spruce.mongodb.com/version/64ff5b602fbabe466a2b35d1/
The condition in `prepare-kerberos` checked for existence of `/etc/krb5.conf`:
```sh
if test "${keytab|}" && [[ -f /etc/krb5.conf ]]; then
```
[A patch build](https://spruce.mongodb.com/task/mongo_c_driver_darwin_authentication_tests_darwinssl_patch_5c101ce5a565ffa9d160b6e44fb276b502b57157_64fbcaf11e2d17299e8c0ead_23_09_09_01_31_32/logs?execution=0) with more logging showed the `/etc/krb5.conf` file does not exist on the macOS host:
```
/etc/krb5.conf does not exist
```
`man kinit` on macOS notes the expected default path to be `/etc/krb5.conf`:
``` …
```
> fix `authentication-tests-darwinssl`

- CONTRIBUTING.md
Previously, following the testing instructions in CONTRIBUTING.md results in the following error:
```
"error":"NonExistentPath: Data directory /data/db not found. Create the missing directory or specify another path using (1) the --dbpath command line option, or (2) by adding the 'storage.dbPath' option in the configuration file."
```
This adds the dbpath to the command line so that way one can copy and paste the instructions in order to run tests.
Also, prefer to use the newer mongosh over mongo.
> Fix testing instructions

- .evergreen/scripts/find-cmake-latest.sh
This _might_ address [flaky task failures](https://parsley.mongodb.com/evergreen/cxx_driver_auth__os~windows_2k8_mongodb_version~latest_compile_and_test_auth_with_shared_libs_60a3e7c4bf04079116c37a7eb9de5d30f67c02cb_23_09_13_19_02_31/0/task?bookmarks=0,366&shareLine=289) observed in the CXX Driver EVG waterfall due to the following error (cached CMake binary no longer binary/script-compatible with Git?):
```
0 [main] sh (1044) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xFB6410/0xE56410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' …
```
> Bump patch version of latest CMake version to 3.25.3

- src/libmongoc/src/mongoc/mongoc-topology.c
- src/libmongoc/tests/test-mongoc-topology.c
- Detect non-MongoDB host names before SRV lookup.
CDRIVER-4682 requires the driver to detect connection to a non-MongoDB server and log a message.
CDRIVER-4682 was initially implemented to detect after SRV lookup. Requirements were later changed to detect before SRV lookup:
> If SRV is used, this check should be done on the SRV's `{hostname}.{domainname}` prior to SRV lookup (ex: xyz.mongodb.net).
As a drive-by improvement, `test_detect_nongenuine_hosts` is updated to print the input URI string on test failure.
> CDRIVER-4682 Detect non-MongoDB host names before SRV lookup.

- .evergreen/scripts/find-cmake-version.sh
Followup to https://github.com/mongodb/mongo-c-driver/pull/1403. Addresses the following error observed in CXX Driver patch builds (see https://github.com/mongodb/mongo-cxx-driver/pull/1023):
```
find-cmake-version.sh: line 171: extension: unbound variable
```
`download_args` is only required in `cmake_download_binary()`, which is only invoked when `$platform` variables (including `$extension`) are set.
> Address nounset errors in find-cmake-version.sh

- .evergreen/config.yml
- .evergreen/config_generator/components/funcs/restore_instance_profile.py
- .evergreen/generated_configs/functions.yml
- Conditionally restore the AWS instance profile after task
Changes verified with [this patch build](https://spruce.mongodb.com/version/650b42742a60ed69ab93574e). 
The description of DRIVERS-2639 describes the motivation.
Changes were copied and modified from https://github.com/mongodb/mongo-python-driver/pull/1218/files
> CDRIVER-4677 conditionally restore AWS instance profile

- .evergreen/scripts/run-mock-server-tests.sh
- src/libmongoc/tests/test-happy-eyeballs.c
set `MONGOC_TEST_IPV4_AND_IPV6_HOST` in mock server tests to unskip `/TOPOLOGY/happy_eyeballs*` tests
The `/TOPOLOGY/happy_eyeballs` tests are [currently skipped](https://parsley.mongodb.com/evergreen/mongo_c_driver_mock_server_test_mock_server_test_8a0e9c28b32724c5eb1493bc100fddb505433671_23_09_26_15_17_45/0/task?bookmarks=0,7275&shareLine=6428) due to missing environment requirements (`test_framework_skip_if_no_dual_ip_hostname`).
`export MONGOC_TEST_IPV4_AND_IPV6_HOST="ipv4_and_ipv6.test.build.10gen.cc"` is added to `run-mock-server-tests.sh` to unskip the test.
The mock-server-test task was [run repeatedly 5 times](https://spruce.mongodb.com/task/mongo_c_driver_mock_server_test_mock_server_test_patch_015c4497c2e98469d31eedf0213e0e7500105f31_65142d739ccd4ec58892d9cd_23_09_27_13_26_14/lo …
> CDRIVER-3727 unskip `/TOPOLOGY/happy_eyeballs*` tests

- .evergreen/etc/skip-tests.txt
Unskip `/crud/unified/aggregate-out-readConcern`
The referenced error appears resolved by SERVER-59924:
```
PlanExecutor error during aggregation :: caused by :: failed while running command { internalRenameIfOptionsAndIndexesMatch: 1, from: "crud-v2.tmp.agg_out.ac0577cb-2c92-4503-9543-6b14faa3c944", to: "crud-v2.other_test_collection", collectionOptions: {}, indexes: [ { v: 2, key: { _id: 1 }, name: "_id_" } ], writeConcern: { w: "majority", wtimeout: 0, provenance: "implicitDefault" } } :: caused by :: Request sent without attaching database version
```
Unskipping running `*sharded*` tasks on `sanitizers-matrix-asan` variant three times [resulted in success](https://spruce.mongodb.com/version/6515854a2a60ed1234d9c76f).
> CDRIVER-4161 unskip `/crud/unified/aggregate-out-readConcern`

- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-libmongoc.h
- src/libmongoc/tests/test-mongoc-sdam-monitoring.c
- src/libmongoc/tests/test-mongoc-thread.c
- src/libmongoc/tests/test-mongoc-topology.c
- src/libmongoc/tests/test-mongoc-usleep.c
Remove unused `test_framework_skip_if_time_sensitive` skip.
`test_framework_skip_if_time_sensitive` was introduced in CDRIVER-3549 to skip mock server tests observed to fail on macOS hosts. As of https://github.com/mongodb/mongo-c-driver/pull/1277, mock server tests are only run on ubuntu2204-small distro. Removing the skip to enable running tests locally on macOS. Running locally repeatedly did not result in failure.
> CDRIVER-3549 remove unused `test_framework_skip_if_time_sensitive`

- .evergreen/etc/skip-tests.txt
- CDRIVER-4337 unskip `/command_monitoring/unified/redacted-commands`
- CDRIVER-4336 unskip `/versioned_api` tests
The reported error references `127.0.0.1:8000`. Port 8000 is used by the load balanced tests. Load balanced tests were removed during Evergreen config migration. New load balancer tasks proposed in https://github.com/mongodb/mongo-c-driver/pull/1414 were used to run patch builds to test.
Tests with the loadbalanced variant for the `/versioned_api` tests were run in a patch build three times and succeeded each time: https://spruce.mongodb.com/version/651ac700d1fe0718dd9615a0
Tests with the loadbalanced variant for the `/command_monitoring/unified/redacted-commands`
tests were run in a patch build three times and succeeded each time: …
> Unskip tests failing to connect to port 8000

- .evergreen/etc/skip-tests.txt
- CDRIVER-4340 unskip `/Client` tests
- CDRIVER-4339 unskip `/streamable/topology_version/update`
- CDRIVER-4338 unskip `/Topology/request_scan_on_error`
- `/Client` tests were unskipped and run in a patch build: https://spruce.mongodb.com/version/651b1f640305b92a0664d607
- `/streamable/topology_version/update` test was unskipped and run in a patch build: https://spruce.mongodb.com/version/651b1d733e8e86d0cea86480
- `/Topology/request_scan_on_error` test was unskipped and run in a patch build: https://spruce.mongodb.com/version/651b136a850e61b816afadd9
Restarting tasks three times resulted in success each time.
As of https://github.com/mongodb/mongo-c-driver/pull/1277, mock server tests are only run on ubuntu2204-small distro. The flaky test failures may no longer be applicable.
> Unskip passing mock server tests

- .evergreen/etc/skip-tests.txt
- unskip `/versioned_api/transaction-handling`
Tests were unskipped and run in a patch build: https://spruce.mongodb.com/version/651ac07c2fbabec06e975fa7/ on the "Versioned API Tests" variant. The result of three repeated runs was success.
> CDRIVER-4335 unskip `/versioned_api/transaction-handling`

- .evergreen/etc/skip-tests.txt
- unskip `/Topology/server_removed/single`
As of https://github.com/mongodb/mongo-c-driver/pull/1277, mock server tests are only run on ubuntu2204-small distro. The flaky test failure may no longer be applicable.
Test was unskipped and run in a patch build: https://spruce.mongodb.com/version/651d5efe9ccd4ecaf0fd37a8
Result of three runs was success.
> CDRIVER-4343 unskip `/Topology/server_removed/single`

- .evergreen/etc/skip-tests.txt
- src/libmongoc/tests/test-mongoc-server-selection-errors.c
- src/libmongoc/tests/test-mongoc-topology.c
- unskip `/Topology/multiple_selection_errors`
- use `.invalid` domain in test to get reliable error
This PR proposes use of the TLD `.invalid` intended to reliably return a DNS error. [RFC 2606](https://www.rfc-editor.org/rfc/rfc2606.html#section-2) notes:
> ".invalid" is intended for use in online construction of domain names that are sure to be invalid and which it is obvious at a glance are invalid.
Similar use of the `.invalid` TLD was similarly done in https://github.com/mongodb/specifications/pull/1136
> CDRIVER-4342 unskip `/Topology/multiple_selection_errors`

- .evergreen/config_generator/components/cse/openssl.py
- .evergreen/config_generator/components/sanitizers/asan_cse.py
- .evergreen/config_generator/components/sanitizers/asan_sasl.py
- .evergreen/config_generator/components/sanitizers/tsan_sasl.py
- .evergreen/config_generator/components/sasl/nossl.py
- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
Migrate MongoDB 7.0+ Evergreen tasks from Ubuntu 18.04 to 20.04
Tasks matching `.*7.0.*` were run in this patch build to verify: https://spruce.mongodb.com/version/651d7291c9ec44a912961b62. The failing tasks are expected and fail on the master branch.
MongoDB 7.0 does not officially support Ubuntu 18.04. Ubuntu 18.04 binaries were removed in 7.0.2 in SERVER-77233. This has resulted [task failures](https://spruce.mongodb.com/version/mongo_c_driver_eec9249e392082be8aacbe4f96275d948018f065/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=7.0) for server 7.0 tasks on Ubuntu 18.04.
This PR intends to make the minimal change to reduce test failures by upgrading selected variants to Ubuntu 20.04.
> CDRIVER-4739 Migrate MongoDB 7.0+ Evergreen tasks from Ubuntu 18.04 to 20.04

- .evergreen/etc/skip-tests.txt
Unskip `/change_stream/resumable_error`
Test was unskipped and run in a patch build: https://spruce.mongodb.com/version/651d622e0ae606899566e382
Result of three runs was success.
As of https://github.com/mongodb/mongo-c-driver/pull/1277, mock server tests are only run on ubuntu2204-small distro. The flaky test failure may no longer be applicable.
> CDRIVER-4345 unskip `/change_stream/resumable_error`

- tools/poetry.ps1
- tools/poetry.sh
A minor improvement to the `poetry.sh` script that works around unintuitive Poetry Python binary selection behavior post-install. The venv created by Poetry doesn't always use the correct Python binary post-install, even if a specific Python binary was used to run the install script. See the linked PR in the comment for further details.
The separate call to `with-lock` makes me frown, but I could not find a straightforward solution to combine both the Poetry `install` and `run` commands, as `with-lock` [does not support](https://github.com/mongodb/mongo-c-driver/blob/23e375f44249907a44ab043957b722f5d997fd23/tools/with_lock.sh#L6) using shell functions as the executed command, and Poetry itself doesn't support specifying the Python binary in the install command (user requests for `--python …
> Ensure Python binary used by Poetry is consistent post-install

- .evergreen/etc/skip-tests.txt
- src/libmongoc/tests/test-mongoc-primary-stepdown.c
- unskip `/Stepdown/not_primary_keep`
- separate `/Stepdown` tests into `/pooled` and `/single`
`/Stepdown/not_primary_keep` was unskipped and run in a patch build with all variants and tasks with names matching `".*replica-noauth.*`: https://spruce.mongodb.com/version/651c0c8957e85a9882f5109e. Restarting the tasks five times resulted in success (excluding a [System Failure downloading 7.0 server](https://spruce.mongodb.com/task/mongo_c_driver_sasl_matrix_nossl_sasl_off_nossl_ubuntu1804_gcc_test_7.0_replica_noauth_patch_f710a87f9405badfbc652d22ed083ac051820ab3_651c0c8957e85a9882f5109e_23_10_03_12_43_56/logs?execution=3)).
I am not sure what caused the reported failure and if anything has changed to resolve. To help diagnose possible future failures, the `/Stepdown` tests are split into …
> CDRIVER-4341 unskip `/Stepdown/not_primary_keep`

- .evergreen/etc/skip-tests.txt
Unskip `/Topology/slow_server/pooled`
Unskipping test and running five times in Evergreen resulted in success: https://spruce.mongodb.com/version/6515985ea4cf4765a33fb138
As of https://github.com/mongodb/mongo-c-driver/pull/1277, mock server tests are only run on ubuntu2204-small distro. The flaky test failure may no longer be applicable (ran on Windows 2015).
> CDRIVER-4257 unskip `/Topology/slow_server/pooled`

- .evergreen/etc/skip-tests.txt
- src/libmongoc/tests/unified/runner.c
This PR partially resolves CDRIVER-4350.
Unskip the following mock server tests:
- `/inheritance/find/readPrefs`
- `/BulkOperation/error/unordered`
- `/command_monitoring/get_error`
- `/Collection/find_with_opts/newoption`
- `/inheritance/replace_one/writeConcern`
- `/Collection/find_with_opts/newoption`
Unskip the following live test:
- `/unified/entity-client-storeEventsAsEntities`
Remove unnecessary skips for the following tests:
- `/unified/assertNumberConnectionsCheckedOut`
- `/unified/entity-client-cmap-events`
CDRIVER-4350 references both live and mock tests. The following are mock tests:
- `/inheritance/find/readPrefs`
- `/BulkOperation/error/unordered`
- `/command_monitoring/get_error`
- `/Collection/find_with_opts/newoption`
- `/inheritance/replace_one/writeConcern`
- …
> CDRIVER-4350 unskip mock tests and remove unnecessary skips

- .evergreen/etc/skip-tests.txt
- src/libmongoc/tests/test-mongoc-bulk.c
- Unskip `/BulkOperation/split`.
- Use "read-your-own-writes" semantics in test to prevent undercounting.
Three repeated runs of the `/BulkOperation/split` test on all variants and tasks with names matching `".*test.*` did not result in the test failing: https://spruce.mongodb.com/version/651eaee656234357657a0c22
Changes in this PR intend to address a possible cause of the original reported error. The original error reported an undercount after inserting: `Assert Failure: count of split_1512376901_50824 is 97759, not 100010`.
This PR proposes using "read-your-own-writes" semantics to read the count. This is done by using a session with causal consistency, and performing operations with majority read and write concerns described in [Client Sessions and Causal Consistency …
> CDRIVER-4346 unskip `/BulkOperation/split`

- .evergreen/etc/skip-tests.txt
Unskip `/load_balancers/non-lb-connection-establishment`
Test was unskipped and run in a patch build with all variants and tasks with names matching `".*test.*`: https://spruce.mongodb.com/version/65269c41e3c331ec7fe9e579
Results of three runs were successful with unrelated task failures.
> CDRIVER-4356 unskip `/load_balancers/non-lb-connection-establishment`

- .tsan-suppressions
- src/libmongoc/src/mongoc/mongoc-cluster-private.h
- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/src/mongoc/mongoc-scram-private.h
- src/libmongoc/src/mongoc/mongoc-scram.c
- src/libmongoc/src/mongoc/mongoc-topology-scanner-private.h
- src/libmongoc/src/mongoc/mongoc-topology-scanner.c
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-mongoc-client.c
- src/libmongoc/tests/test-mongoc-scram.c
CDRIVER-3514
This fixes an issue that Genny encountered where performance was degraded due to clients not sharing a SCRAM cache within a pool.
This change makes the scram cache global so that way all clients share the SCRAM cache.
I measured the time it took to execute the program below and recorded the runtime in milliseconds. I first did a "warmup" run of 100 iterations to literally warm up my CPU so that there would be less variability in boost clock speed, thus ensuring the system would be at a steady state by the time I start collecting data points. The data from these first 100 iterations was thrown away. I then immediately ran 1000 iterations of this program and collected the timing measurements to produce the median results below.
On master (8a0e9c28b), the median runtime is …
> Share SCRAM cache via a global lookup table

- .evergreen/etc/skip-tests.txt
Unskip `/sessions/unified/snapshot-sessions`
Test was unskipped and run in a patch build with all variants and tasks with names matching `".*test.*`: https://spruce.mongodb.com/version/65269a2657e85a612dd2f043
Results of three runs were successful with unrelated task failures.
I am unsure what caused the original reported error `error: checking expectResult:  { "$numberInt" : "2" }`. https://github.com/mongodb/mongo-c-driver/commit/904db5300d7c90349ef96c2dcfb203bf6609ab6c#diff-1f83e54d27ecd8d43c2fd4d5835485a87bc4882cf6d3d9602d4abf7208cfedffR366 improves the error message to include the actual value. If a later test failure is observed, this may help to diagnose the cause if a future error is observed.
> CDRIVER-4355 unskip `/sessions/unified/snapshot-sessions`

- .evergreen/etc/skip-tests.txt
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-libmongoc.h
- src/libmongoc/tests/test-mongoc-sdam-monitoring.c
Unskip `/server_discovery_and_monitoring/monitoring/heartbeat/pooled/dns`.
Additional related changes are described in commits.
Changes were tested on [this patch](https://spruce.mongodb.com/version/6525acdee3c331ec7fe7e9f5) with all tasks with names matching `".*test.*`. Three repeated runs passed excluding unrelated task failures.
Similar to changes in https://github.com/mongodb/mongo-c-driver/pull/1426, this PR proposes use of the TLD `.invalid` intended to reliably return a DNS error. [RFC 2606](https://www.rfc-editor.org/rfc/rfc2606.html#section-2) notes:
> ".invalid" is intended for use in online construction of domain names that are sure to be invalid and which it is obvious at a glance are invalid.
> CDRIVER-4353 unskip `/server_discovery_and_monitoring/monitoring/heartbeat/pooled/dns`

- src/libmongoc/src/mongoc/mongoc-scram.c
Unlike a POSIX read/write lock, in which both a read lock and a write lock are unlocked by the same function, Windows requires that a read lock is unlocked by a different function than a write lock.
> CDRIVER-3514 Fix Windows shared mutex unlocking

- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/tests/test-mongoc-loadbalanced.c
- Store `recoveryToken` for Load Balanced topology
Bug was discovered running proposed specification test changes with the PHP driver: https://github.com/mongodb/specifications/pull/1459#discussion_r1313559280
> Additionally, several other pinning tests fail due to [`recoveryToken` fields](https://github.com/mongodb/specifications/blob/master/source/transactions/transactions.rst#recoverytoken-field) not being found in outgoing `commitTransaction` and `abortTransaction` commands
The [Load Balancer specification](https://github.com/mongodb/specifications/blob/master/source/load-balancers/load-balancers.rst#behaviour-with-transactions) notes:
> When executing a transaction in load balancing mode, drivers MUST follow the rules outlined in [Sharded …
> CDRIVER-4718 store `recoveryToken` for Load Balanced topology

- src/libmongoc/doc/mongoc_client_session_t.rst
Follow-up for 6fee88bbd68c31ff0741cc1941ea6ba0e1b71823
Patch build on the affected task: https://spruce.mongodb.com/version/652f06eed1fe071ba70d8dc2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> fix symbol ref in mongoc_client_session_t doc

- .evergreen/config_generator/components/funcs/fetch_build.py
A fix to a bug that has not yet been encountered in the C Driver.
If a custom `vars={...}` argument is given to `FetchBuild.call(build_name="abc", vars={...})`, e.g. to define additional environment variables, the config generator will fail due to the `vars` argument being specified multiple times:
```
TypeError: config_generator.etc.function.Function.default_call() got multiple values for keyword argument 'vars'
```
This PR uses `.update()` to ensure if `vars` is given, that the `build_name` will correctly be merged into `vars` instead of triggering a conflict.
> Fix merge of FunctionCall vars argument in FetchBuild

- NEWS
- src/libbson/NEWS
Update NEWS for upcoming 1.25.0 release
Commits planned for the 1.25.0 release were inspected by viewing the following commits:
```
MERGE_BASE=$(git merge-base origin/r1.24 master)
git log $MERGE_BASE..master
```
This PR includes NEWS entries for the following commits:
0dc1a4e833a9339096009ec26e7197e87842f6f7 CDRIVER-4637 Remove ENABLE_SRV=AUTO, clean up SRV URI support (#1301)
9affd70760c66ed9bb85652d014802841ed3378e CDRIVER-504 add `bson_array_builder_t` (#1344)
1c8da0ee199661a4276c87fb9ec2fbb375a2a4ad CDRIVER-4244 use OP_MSG for exhaust cursors (#1399)
84d9d8f5da9ded04d8d2ef9836373679bf8119fb Share SCRAM cache via a global lookup table (#1406)
c7fa88c0bb54bdce42ed9880bcb14ee0580d02af CDRIVER-4615 use polling monitoring in FaaS environments (#1362) …
> Update NEWS for upcoming 1.25.0 release

- .evergreen/scripts/link-sample-program-mingw-bson.cmd
- .evergreen/scripts/link-sample-program-mingw.cmd
Add `git` to `PATH` in `link-sample-program-mingw*` scripts.
Verified with this patch build: https://spruce.mongodb.com/version/65395baf1e2d1738a950cc24
The `link-with-bson-mingw` and `link-with-cmake-mingw` tasks fail to build due to not finding `git`. Here is an [example task](https://spruce.mongodb.com/task/mongo_c_driver_smoke_link_with_bson_mingw_1b0a49ae1dd2a5fff380dd06873437444cb069af_23_10_24_17_28_23/logs?execution=0) logging:
```
RuntimeError: Failed to execute subprocess ['git', 'rev-parse', '--revs-only', '--short=10', 'HEAD^{commit}']: [WinError 2] The system cannot find the file specified [Does the executable ôgitö not exist?]
```
> Add `git` to `PATH` in `link-sample-program-mingw*` scripts

- build/sphinx/homepage-config/conf.py
Use `furo` theme for homepage.
https://github.com/mongodb/mongo-c-driver/pull/1354 switched the libmongoc and libbson to the `furo` theme. This PR also switches the homepage to the `furo` theme.
Using [release.py](https://github.com/10gen/mongo-c-driver-tools/blob/1bbff82ce822f9e6384a35edacf0e0b5546b8e33/release.py#L960) to build docs locally resulted in an error locating the `readable` theme:
```sh
$ poetry run $HOME/code/mongo-c-driver-tools/release.py docs_build \
$(pwd)/KEVINALBS/mongo-c-driver_master \
$(pwd)/KEVINALBS/mongo-c-driver_ghpages \
1.25.0
```
Resulted in the following error:
```sh
Building home page
Theme error:
no theme named 'readable' found (missing theme.conf?)
Traceback (most recent call last):
File "/Users/kevin.albertson/code/mongo-c-driver-tools/release.py", line …
```
> use `furo` theme in homepage

- src/libbson/CMakeLists.txt
- src/libbson/src/bson/bson-macros.h
- src/libmongoc/src/mongoc/mongoc-macros.h
- Remove `bson_obj` library.
- Define `BSON_STATIC` for `bson_static` build to suppress `__declspec (dllexport)`.
Verified with this patch: https://spruce.mongodb.com/version/65380a299ccd4ece69a2b84d
This PR is intended to fix CI builds linking to libmongocrypt that began failing after https://github.com/mongodb/mongo-c-driver/commit/4592ca54f76019905b32995c8bcf032c54d34be7. Windows tasks linking to libmongocrypt fail to build with an "already defined" error. Here is an example from [cse-sasl-cyrus-winssl-windows-2019-vs2017-x64-compile](https://spruce.mongodb.com/task/mongo*c_driver_cse_matrix_winssl_cse_sasl_cyrus_winssl_windows_2019_vs2017_x64_compile_960760fcc19f48328c2cef1e9cf9cad3698e068d_23_10_12_20_02*57/logs?execution=0):
```
bson-static-1.0.lib(bson-error.obj) : error LNK2005: …
```
> CDRIVER-4743 Define `BSON_STATIC` for `bson_static` build

- NEWS
- build/sphinx/homepage-config/conf.py
- src/libbson/NEWS
- src/libmongoc/doc/installing.rst
- Update NEWS for 1.25.0.
- Link to GitHub release page, not tarball.
- Move `:man_page:` directive.
The tarball link is broken for 1.25.0. The tarball is removed in 1.25.0 as part of CDRIVER-4640.
The `:man_page:` directive shows on the current https://mongoc.org/libmongoc/current/installing.html page:
Moving the `:man_page:` directive to the start appears to fix the rendering. I am not sure what the root cause is, but this was not investigated further.
> Update NEWS and docs for 1.25.0

- src/libmongoc/doc/learn/get/installing.rst
Lintian found a typo for the word 'respective' during Debian packaging.
> Respective typo

- NEWS
- build/cmake/BuildVersion.cmake
~~Document removal of `BUILD_VERSION` CMake option.~~
Apply `BUILD_VERSION` CMake option
https://github.com/mongodb/mongo-c-driver/pull/1382 removes the ability to specify a custom `BUILD_VERSION`.
This may result in an error when if attempting to build a source archive with steps that previously worked on 1.24.4:
```bash
wget "https://github.com/mongodb/mongo-c-driver/archive/refs/tags/1.25.0.tar.gz"
tar xf 1.25.0.tar.gz
cd mongo-c-driver-1.25.0
cmake -DBUILD_VERSION=1.25.0 -S. -Bcmake-build
```
Results in this error due to `BUILD_VERSION` being ignored:
```bash
Traceback (most recent call last):
File "/Users/kevin.albertson/Desktop/mongo-c-driver-1.25.0/build/cmake/../calc_release_version.py", line 400, in <module>
RELEASE_VER = previous(main()) if PREVIOUS else main()
^^^^^^
File …
```
> CDRIVER-4763 reapply `BUILD_VERSION` CMake option

- src/libmongoc/doc/mongoc_stream_read.rst
- src/libmongoc/doc/mongoc_stream_readv.rst
- src/libmongoc/doc/mongoc_stream_write.rst
- src/libmongoc/doc/mongoc_stream_writev.rst
- src/libmongoc/doc/mongoc_uri_t.rst
- src/libmongoc/doc/mongoc_write_concern_set_wtimeout.rst
- src/libmongoc/src/mongoc/mongoc-buffer.c
- src/libmongoc/src/mongoc/mongoc-cluster-private.h
- src/libmongoc/src/mongoc/mongoc-crypt.c
- src/libmongoc/src/mongoc/mongoc-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-bio.c
- src/libmongoc/src/mongoc/mongoc-stream.c
- src/libmongoc/tests/test-mongoc-cluster.c
- src/libmongoc/tests/test-mongoc-stream.c
Resolves CDRIVER-4781. Verified by [this patch](https://spruce.mongodb.com/version/65525bff0305b9e2e2b97975).
https://github.com/mongodb/mongo-c-driver/pull/1229 introduced range representability checks for conversion from `int64_t` -> `int32_t` timeout parameters in internal read/write utility functions, where due to historical reasons, `int64_t` timeout parameters for several read/write operations are forwarded to underlying `int32_t` timeout parameters (narrowing conversion). The new range checks are (correctly but unexpectedly) triggered by `mongoc_cluster_t::sockettimeoutms` when the URI option is set to `-1`, which has also been (implicitly) supported for historical reasons. The negative value was being implicitly converted to a large unsigned value before being passed as an …
> CDRIVER-4781 Avoid intermediate uint32_t for socketTimeoutMS

- src/libmongoc/tests/test-mongoc-stream.c
This PR is a follow-up to #1475 intended to fix MinGW builds expecting `char` for the `iov_base` field of `struct iovec`.
Verified changes fix MinGW tasks with this patch: https://spruce.mongodb.com/version/6553ec620ae6067d73912916
> CDRIVER-4781 add `void*` cast in test

- src/libbson/src/bson/bson-error.c
The AIX strerror_r doesn't have the same semantics as glibc's (diff type signature), but it does provide one under a different name. This name is used if you use -D_LINUX_SOURCE_COMPAT, but it's a big hammer. We can just use it directly.
> CDRIVER-4790 AIX has a glibc-compatible strerror_r w/ diff name

- src/libbson/src/bson/bson-memory.c
...so add it to the list of platforms.
This should probably be checked in CMake/autotools instead.
> CDRIVER-4791 AIX doesn't have aligned_alloc

- CMakeLists.txt
- build/cmake/GeneratePkgConfig.cmake
Add thread library to pkg-config `Libs`
Attempting to compile and link in separate steps with static libbson results in a linker error related to pthread with gcc 7.5.0:
```bash
export PKG_CONFIG_PATH=$(pwd)/.install-baseline/lib/pkgconfig
gcc -c ./src/libbson/examples/hello_bson.c -o hello_bson.o $(pkg-config --cflags libbson-static-1.0)
gcc -o hello_bson hello_bson.o $(pkg-config --libs libbson-static-1.0)
```
Results in an error at the Link step:
```bash
/usr/bin/ld: /home/ubuntu/code/tasks/mongo-c-driver-C4776/.install/lib/libbson-static-1.0.a(common-b64.c.o): undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
`man gcc` notes for `-pthread`: …
> CDRIVER-4776 add thread library to pkg-config `Libs`

- src/libmongoc/CMakeLists.txt
Disable shared libmongoc targets if the CMake option `ENABLE_SHARED` is `OFF`
Changes verified with this patch build: https://spruce.mongodb.com/version/656df3c99ccd4e411f5bb551
Using `Hide whitespace` in GitHub is recommended when reviewing.
CDRIVER-4705 adds the `ENABLE_SHARED` option. If `OFF`, building shared libbson targets is disabled. This PR proposes applying this option to libmongoc.
This may help to simplify the vcpkg port. The port currently includes a patch ([disable-dynamic-when-static.patch](https://github.com/microsoft/vcpkg/blob/16ee2ecb31788c336ace8bb14c21801efb6836e4/ports/mongo-c-driver/disable-dynamic-when-static.patch)) to disable the shared library build when the static library is built.
vcpkg documents: ["Choose either static or shared …
> CDRIVER-4784 Disable shared libmongoc targets if `ENABLE_SHARED=OFF`

- build/sphinx/mongoc_common.py
Use `typing.Union` instead of `X | Y` to fix documentation build with Python 3.9.
CDRIVER-4767 reports builds for EPEL are failing to build documentation:
```
Traceback (most recent call last):
File "/Users/kevin.albertson/code/tasks/mongo-c-driver-CDRIVER-4767/.venv/lib/python3.9/site-packages/sphinx/config.py", line 358, in eval_config_file
exec(code, namespace)  # NoQA: S102
File "/Users/kevin.albertson/code/tasks/mongo-c-driver-CDRIVER-4767/src/libmongoc/doc/conf.py", line 30, in <module>
from mongoc_common import *
File "/Users/kevin.albertson/code/tasks/mongo-c-driver-CDRIVER-4767/build/sphinx/mongoc_common.py", line 29, in <module>
def _file_man_page_name(fpath: Path) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
Writing union types as `X | …
> CDRIVER-4767 use `typing.Union` to support Python 3.9

- src/libmongoc/tests/json/index-management/createSearchIndex.json
- src/libmongoc/tests/json/index-management/createSearchIndexes.json
- src/libmongoc/tests/json/index-management/dropSearchIndex.json
- src/libmongoc/tests/json/index-management/listSearchIndexes.json
- src/libmongoc/tests/json/index-management/updateSearchIndex.json
Sync tests from https://github.com/mongodb/specifications/pull/1485
SERVER-83290 changed an error message causing test assertions to fail latest server builds. For example [asan-sasl-cyrus-openssl-ubuntu2004-clang-test-latest-replica-auth](https://spruce.mongodb.com/task/mongo_c_driver_sanitizers_matrix_asan_asan_sasl_cyrus_openssl_ubuntu2004_clang_test_latest_replica_auth_patch_3a624d53dfed8820019a8fb0e436f6151588f0f5_658071a13627e050878a2577_23_12_18_16_21_55/logs?execution=0) failed with:
> error: expected error to contain "Search index commands are only supported with Atlas", but got: "Using Atlas Search Database Commands and the $listSearchIndexes aggregation stage requires additional configuration. Please connect to Atlas or an AtlasCLI local deployment to enable. For more …
> CDRIVER-4799 sync Index Management tests

- src/libmongoc/doc/learn/get/installing.rst
- src/libmongoc/doc/ref/packages.rst
- Restore documentation describing dev packages.
- Document steps to check version of Fedora / Debian packages.
Documentation was previously added in https://github.com/mongodb/mongo-c-driver/pull/1270 but removed after a documentation rewrite.
Documentation is intended to help users choose the type of package to install.
Rendered HTML can be viewed from the `make-docs` task here: https://mciuploads.s3.amazonaws.com/mongo-c-driver/docs/libmongoc/-65831b3e2a60ed7f998135b9/index.html
> CDRIVER-4797 Restore documentation describing dev packages

- NEWS
- build/cmake/SphinxBuild.cmake
- build/sphinx/mongoc_common.py
- src/libbson/NEWS
- src/libmongoc/doc/conf.py
- src/libmongoc/doc/learn/get/docs.rst
- src/libmongoc/doc/learn/get/installing.rst
- src/libmongoc/doc/mongoc_client_encryption_opts_set_kms_credential_provider_callback.rst
This PR includes several workarounds to support building the man page targets with Sphinx 1.7.6.
Commit messages describe the change, and (if applicable) the later version of Sphinx that introduced a feature.
CDRIVER-4767 reports builds for EPEL are failing to build documentation due to use of older Sphinx versions:
```
This project needs at least Sphinx v5.0 and therefore cannot be built with this version.
```
CDRIVER-4767 reports Sphinx versions used are "1.7.6 on EL-8 and 3.4.3 on EL-9"
This PR was tested by building the `mongoc-man` and `bson-man` targets locally with Sphinx 1.7.6, 3.4.3, and 7.1.2. Testing in CI is planned in to CDRIVER-4794.
> CDRIVER-4767 support Sphinx 1.7.6

- src/libbson/src/bson/bson-string.c
Hello,
Minor change, I just noticed a redundant assignment in bson-string.c.
Have a nice day.
> Bson-string: Removed redundant assignement

- src/libmongoc/tests/json/retryable_writes/unified/bulkWrite-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/unified/insertOne-serverErrors.json
- src/libmongoc/tests/json/unified/poc-retryable-writes.json
https://jira.mongodb.org/browse/CDRIVER-4798
Synced with https://github.com/mongodb/specifications/commit/4c73bb13daa0241a3956a30b451edda10f79dde6
This pulls in some changes for [CDRIVER-4639](https://jira.mongodb.org/browse/CDRIVER-4639) for poc-retryable-writes.json, but other files pertinent to [CDRIVER-4639](https://jira.mongodb.org/browse/CDRIVER-4639) have not been synced.
----
This is based on https://github.com/mongodb/mongo-c-driver/pull/1499
> CDRIVER-4798 sync tests for revised runOnRequirements

- build/sphinx/mongoc_common.py
- src/libmongoc/doc/cmakerefdomain.py
- src/libmongoc/doc/conf.py
This PR is intended to support building man pages with Python 3.6.
Commit messages describe the change, and the version of Python that introduced a feature.
CDRIVER-4767 reports builds for EPEL 8 are failing to build man pages:
```
Configuration error:
There is a syntax error in your configuration file: future feature annotations is not defined (mongoc_common.py, line 1)
Did you change the syntax from 2.x to 3.x?
gmake[2]: *** [src/libbson/doc/CMakeFiles/bson-man.dir/build.make:566: src/libbson/doc/man/bson_aligned_alloc.3] Error 2
gmake[2]: Leaving directory '/builddir/build/BUILD/mongo-c-driver-1.25.4'
gmake[1]: *** [CMakeFiles/Makefile2:1034: src/libbson/doc/CMakeFiles/bson-man.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....Configuration error:
There is a syntax error in …
```
> CDRIVER-4767 Support Python 3.6 in man page build

- src/libmongoc/src/mongoc/mongoc-error.c
https://jira.mongodb.org/browse/CDRIVER-4808
Server responses do not return errorLabels within writeConcernError. It is only a top-level field.
> CDRIVER-4808 do not check writeConcernError in mongoc_error_has_label()

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/debian_package_build.sh
Once this is merged, the `debian-package-build` task in the C++ driver should start working again.
> don't clobber 64-bit .debs with 32-bit .debs

- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/src/mongoc/mongoc-error-private.h
- src/libmongoc/src/mongoc/mongoc-error.c
- src/libmongoc/src/mongoc/mongoc-write-command.c
- src/libmongoc/tests/json/retryable_writes/unified/insertOne-serverErrors.json
https://jira.mongodb.org/browse/CDRIVER-4754
POC for https://github.com/mongodb/specifications/pull/1486
> CDRIVER-4754 pre-4.4 mongos writeConcernError does not determine retryability

- .evergreen/config_generator/components/funcs/fetch_det.py
- .evergreen/generated_configs/functions.yml
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/functions.py
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
- .evergreen/scripts/run-aws-tests.sh
- .evergreen/scripts/run-mongodb-aws-ecs-test.sh
- .gitignore
- src/libmongoc/doc/tutorial.rst
- src/libmongoc/tests/test-awsauth.c
This PR migrates AWS tests to use scripts from drivers-evergreen-tools added in DRIVERS-2328.
This removes use of the legacy `mongo` shell and resulted in passing the `.*aws.*` tasks. Verified by this patch build: https://spruce.mongodb.com/version/65a6e2ad0ae60677917cf830
I suggest reviewing individual commits.
https://github.com/mongodb/mongo-c-driver/pull/1514/commits/072eace3a1d00a69d3c61158fbd38bd04125e114 migrates AWS tests using MongoDB 6.0+ to Ubuntu 22.04. This is intended to better follow [Guidelines around Evergreen distros](https://wiki.corp.mongodb.com/display/DBDEVPROD/Guidelines+around+Evergreen+distros):
> Prefer 22.04 when possible
https://github.com/mongodb/mongo-c-driver/pull/1514/commits/6840e85fae72a884cfbbd720ca8d0834765b172b enables tracing in `test-awsauth` …
> CDRIVER-4512 remove legacy shell from AWS test scripts

- .evergreen/config_generator/components/funcs/fetch_det.py
- .evergreen/generated_configs/functions.yml
This is a follow-up to https://github.com/mongodb/mongo-c-driver/pull/1514 intended to resolve errors on some tasks running `find` with `-execdir`. [Example](https://spruce.mongodb.com/task/mongo_c_driver_cse_matrix_openssl_cse_sasl_cyrus_openssl_ubuntu2004_arm64_gcc_test_latest_server_auth_7f1a88b42a311e6db8edd4adafcce55aa3b8a094_24_01_17_13_28_12/logs?execution=0):
> [2024/01/17 08:36:31.247] find: The relative path '.local/bin' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH
Verified with this patch build: https://spruce.mongodb.com/version/65a80624a4cf47738e04ec81
> CDRIVER-4512 do not use `execdir`

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/functions.py
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
Use mongohouse Docker image added in DRIVERS-2543 to fix `test-mongohouse` task.
Verified with this patch build: https://spruce.mongodb.com/version/65aa7f650ae6066158bd3dc1
DRIVERS-2543 adds scripts to use the Docker image maintained by the Atlas Data Lake team.
The `run-mongohouse-local.sh` script currently fails to run. https://github.com/mongodb-labs/drivers-evergreen-tools/pull/392 proposes removing `run-mongohouse-local.sh` from drivers-evergreen-tools.
> CDRIVER-4771 use Docker image to run `mongohouse`

- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/compile-openssl-static.sh
- .evergreen/scripts/compile-scan-build.sh
- .evergreen/scripts/compile-std.sh
- .evergreen/scripts/compile-test-azurekms.sh
- .evergreen/scripts/compile-test-gcpkms.sh
- .evergreen/scripts/compile-unix.sh
- .evergreen/scripts/install-uninstall-check.sh
- .evergreen/scripts/link-sample-program-bson.sh
- .evergreen/scripts/link-sample-program.sh
This PR proposes adding environment variables instructing ccache to allow reuse of compilation results across different build directories. Verified by [this patch](https://spruce.mongodb.com/version/65b15576850e6198196c6533) (the unexpected task failures seem unrelated to this PR).
This is motivated by the realization that Evergreen tasks are typically executed under a working directory of the form `/data/mci/<hash>`, where `<hash>` is used to avoid conflicts between tasks running on the given host. Unfortunately this is also preventing ccache from reusing compilation results as intended.
Per [ccache documentation](https://ccache.dev/manual/4.9.html) under "Compiling in different directories":
> ... if you compile the same code in different locations, you can’t share compilation results …
> Allow ccache to reuse results across build directories

- .evergreen/generated_configs/legacy-config.yml
Followup to https://github.com/mongodb/mongo-c-driver/pull/1522. Missed config generation step.
> Update EVG config with ccache updates

- src/libmongoc/src/mongoc/mongoc-host-list.c
- src/libmongoc/tests/test-mongoc-uri.c
Error parsing IPv6 literals exceeding `BSON_HOST_NAME_MAX - 2` bytes.
Tested with this patch build: https://spruce.mongodb.com/version/65b91a525623434922184fa6. Test failures appear to be unrelated.
See CDRIVER-4816.
Assertions are added to the return values of `bson_snprintf` in `_mongoc_host_list_from_hostport_with_err` to ensure the destination has enough capacity. CDRIVER-4820 was filed to check other calls to `bson_snprintf` in the codebase.
Increasing the size of `mongoc_host_list_t::host_and_port` was briefly considered, but decided against due to `mongoc_host_list_t` being included in the [public API](https://mongoc.org/libmongoc/current/mongoc_host_list_t.html). Changing the size is an ABI breaking change.
> CDRIVER-4816 Error parsing large IPv6 literal

- src/libmongoc/tests/test-mongoc-sample-commands.c
A handful of the code examples we import into the documentation have the `done:` line in the example, while others don't. This cleans up that discrepancy and makes the code examples consistent.
> Reorder start point for doc examples for consistency

- src/libmongoc/CMakeLists.txt
- src/libmongoc/src/mongoc/mongoc-bulk-operation.c
- src/libmongoc/src/mongoc/mongoc-change-stream.c
- src/libmongoc/src/mongoc/mongoc-client-session.c
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-cluster-private.h
- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/src/mongoc/mongoc-cursor.c
- src/libmongoc/src/mongoc/mongoc-database.c
- src/libmongoc/src/mongoc/mongoc-deprioritized-servers-private.h
- src/libmongoc/src/mongoc/mongoc-deprioritized-servers.c
- src/libmongoc/src/mongoc/mongoc-topology-description-private.h
- src/libmongoc/src/mongoc/mongoc-topology-description.c
- src/libmongoc/src/mongoc/mongoc-topology-private.h
- src/libmongoc/src/mongoc/mongoc-topology.c
- src/libmongoc/src/mongoc/mongoc-write-command.c
- src/libmongoc/tests/json-test.c
- src/libmongoc/tests/mock_server/mock-server.c
- src/libmongoc/tests/test-mongoc-client-session.c
- src/libmongoc/tests/test-mongoc-cluster.c
- src/libmongoc/tests/test-mongoc-cyrus.c
- src/libmongoc/tests/test-mongoc-primary-stepdown.c
- src/libmongoc/tests/test-mongoc-retryability-helpers.c
- src/libmongoc/tests/test-mongoc-retryability-helpers.h
- src/libmongoc/tests/test-mongoc-retryable-reads.c
- src/libmongoc/tests/test-mongoc-retryable-writes.c
- src/libmongoc/tests/test-mongoc-topology.c
- src/libmongoc/tests/test-mongoc-transactions.c
- src/libmongoc/tests/test-mongoc-write-commands.c
Resolves CDRIVER-4099. Verified by [this patch](https://spruce.mongodb.com/version/65c2a91d32f41714fea620ce/tasks?taskName=-cyrus-.%2A-sharded-) (filtered to relevant tasks; CSE tasks are failing atm due to an unrelated issue).
This PR also implements the proposed prose test spec changes in https://github.com/mongodb/specifications/pull/1504.
There are five internal functions in libmongoc that each individually (re)implement retryable reads/writes:
- `_mongoc_client_retryable_write_command_with_stream`
- `_mongoc_client_retryable_read_command_with_stream`
- `mongoc_collection_find_and_modify_with_opts`
- `_mongoc_cursor_run_command`
- `_mongoc_write_opmsg`
This PR refrains from refactoring these instances to use a comment implementation due to the complexity required. Instead, the new …
> CDRIVER-4099 Support mongos redirection during retryable operations

- src/libmongoc/doc/ref/packages.rst
To match name and Sub Packages listed here: https://pkgs.alpinelinux.org/package/edge/community/armhf/mongo-c-driver
Can be tested with:
```bash
docker run --rm -it alpine:3.19 
/ # apk add mongo-c-driver
```
Discovered when auditing dependencies as part of CDRIVER-4818.
> fix name of Alpine package

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
Part of CDRIVER-4823. Changes in this PR will be cherry-picked onto the r1.26 branch.
The `toolchain_aws_*` EVG project variables are redundant, fulfilling the same function as the plain `aws_*` EVG project variables. This PR removes their use in the EVG config so the variables can be deleted in EVG project settings.
> CDRIVER-4823 Avoid use of redundant EVG project variables

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_generator/variants.py
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
Applies [display_task](https://docs.devprod.prod.corp.mongodb.com/evergreen/Project-Configuration/Project-Configuration-Files/#display-tasks) to OCSP tasks, grouped by SSL library, to significantly simplify the task list of C Driver EVG builds.
See [this patch](https://spruce.mongodb.com/version/65d5237e0305b9759fba61cb) for example of results.
Proper migration of the OCSP task matrix to the modern config generator is deferred in favor of immediate benefits. Other task matrices may be given display tasks on a case-by-case basis going forward to further simplify the EVG task list.
> Group OCSP tasks into display tasks by SSL library

- .evergreen/config_generator/etc/distros.py
Updates the distros list to remove (soon-to-be-)obsoleted distros. None appear to be in use by the C Driver.
> Remove obsoleted distros from distro list

- src/libbson/src/bson/bson.c
Catched with UBSAN:
runtime error: member access within misaligned address 0x51100000a040 for type 'bson_array_builder_t' (aka 'struct _bson_array_builder_t'), which requires 128 byte alignment
0x51100000a040: note: pointer points here
01 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
^
#0 0x5bb2a5c5b759 in bson_array_builder_new [...]/mongo-c-driver/src/src/libbson/src/bson/bson.c:3662:21
#1 0x5bb2a5c65a43 in bson_append_array_builder_begin [...]/mongo-c-driver/src/src/libbson/src/bson/bson.c:3983:13
> CDRIVER-5487 use aligned alloc for bson_array_builder_t

- .git-blame-ignore-revs
Followup to https://github.com/mongodb/mongo-c-driver/pull/1545.
> CDRIVER-4385 Add .git-blame-ignore-revs entry for ColumnLimit: 80 -> 120

- src/libmongoc/src/mongoc/mongoc-log.c
This was tested by executing a manual build on a Debian armhf porterbox (since the failure was revealed by a failed build on that architecture in Debian and we don't directly test 32-bit ARM architectures in our own CI).
> allow for 64-bit time_t on 32-bit architectures

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/check_rpm_spec.sh
This change implements a check whereby if the RPM spec file we are shipping in the C driver repository differs from the downstream RPM spec file (e.g., because downstream has updated and we have not yet synced it to obtain that update), then the `rpm-package-build` task will fail. This is implemented so that it will only run on waterfall builds (so that patch builds are not unnecessarily cluttered by a most likely unrelated failure of this task).
Patch build: https://spruce.mongodb.com/task/mongo_c_driver_packaging_rpm_package_build_patch_bef6e2d37436fd465f165d7062af9fe2262d6738_65e76bd77742aeab743dd2c9_24_03_05_19_00_42/logs?execution=0
```
[2024/03/05 14:02:04.386] Running command 'shell.exec' (step 1 of 4).
[2024/03/05 14:02:04.391] This is a patch build...skipping RPM spec check …
```
> CDRIVER-5497 implement downstream RPM spec check

- .evergreen/scripts/debian_package_build.sh
The Debian build process has been updated such that the `debian/` directory is now only in the `debian/unstable` branch. This change fetches that directory for Evergreen builds to enable building Debian packages in CI.
> Fix Evergreen task failure

- src/libbson/libbson.rc.in
- src/libmongoc/libmongoc.rc.in
Resolves CDRIVER-5510. Followup to https://github.com/mongodb/mongo-c-driver/pull/1457.
Addresses the preprocessor macro redefinition warning when compiling `libbson.rc`:
```
warning RC4005: 'BSON_COMPILATION' : redefinition
```
> CDRIVER-5510 Remove redundant redefinition of BSON_COMPILATION

- CMakeLists.txt
- NEWS
- src/libmongoc/CMakeLists.txt
- src/libmongoc/doc/authentication.rst
- src/libmongoc/src/mongoc/mongoc-cyrus-private.h
- src/libmongoc/src/mongoc/mongoc-cyrus.c
- src/libmongoc/src/mongoc/mongoc-init.c
This PR proposes disabling loading Cyrus-SASL plug-ins by default on Windows.
Users of Cyrus-SASL on Windows can set the new CMake option `CYRUS_PLUGIN_PATH_PREFIX` to enable Cyrus plug-in loading on Windows.
This is intended to address concerns described in CDRIVER-5511.
I expect this PR is backwards breaking behavior. Loading the GSSAPI plug-in is needed for GSSAPI auth on Windows. GSSAPI is not a [default static plug-in](https://github.com/cyrusimap/cyrus-sasl/blob/master/win32/README.md#msbuild):
> Some of them will be statically linked into sasl2.dll [...] gssapi builds gssapi dynamic plugin
By default, SSPI is used for GSSAPI auth on Windows. I expect there are few users using the C driver with Cyrus-SASL instead of the default SSPI. CDRIVER-5514 was filed to propose dropping …
> CDRIVER-5511 disable loading Cyrus plugins on Windows by default

- NEWS
- src/libmongoc/src/mongoc/mongoc-gridfs-file.c
- src/libmongoc/tests/test-mongoc-gridfs.c
Address a hang observed in `mongoc_gridfs_file_readv` when reading a corrupt incomplete chunk. If an incomplete chunk is detected, an error is now returned.
Though the `mongoc_gridfs_t` API notably [does not conform](https://mongoc.org/libmongoc/current/mongoc_gridfs_t.html) to the GridFS spec, the [GridFS spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.md) requires returning an error for an unexpected length:
> As drivers stream the stored file they MUST check that each chunk received is the next expected chunk (i.e. it has the expected "n" value) and that the data field is of the expected length
The cause of the hang is an assumption that chunks (excluding the last) contain data of length chunk size. `_mongoc_gridfs_file_refresh_page` calculates the …
> CDRIVER-5506 error if `mongoc_gridfs_file_readv` reads an incomplete chunk

- .evergreen/scripts/find-cmake-latest.sh
Build tests with CMake 3.29.0 to resolve Windows OpenSSL task failures.
This PR is intended to address Windows OpenSSL tasks failing to locate OpenSSL. For example, [sasl-cyrus-openssl-windows-2019-vs2017-x64-compile](https://spruce.mongodb.com/task/mongo_c_driver_sasl_matrix_openssl_sasl_cyrus_openssl_windows_2019_vs2017_x64_compile_a2dedb3ff2875a5ac75e3e0a8ded72bf838be1ec_24_03_25_18_00_50/logs?execution=0) fails with:
```
[2024/03/25 15:11:45.958] CMake Error at C:/Users/mci-exec/AppData/Local/mongo-c-driver/tmp.mwlWImHNJh/cmake-3.25.3-windows-x86_64/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[2024/03/25 15:11:45.958]   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
[2024/03/25 15:11:45.958]   system variable OPENSSL_ROOT_DIR …
```
> use CMake 3.29.0 in tests

- src/libmongoc/src/mongoc/mongoc-cursor-legacy.c
- src/libmongoc/tests/test-mongoc-exhaust.c
Fixes a failed assert when an exhaust cursor receives no documents:
```
src/libbson/src/bson/bson-reader.c:534 bson_reader_new_from_data(): precondition failed: data
```
Changes verified with a [patch build](https://spruce.mongodb.com/version/66018d4b86edac00076b6b3d) testing all server 3.6 tasks. 3.6 uses legacy exhaust cursors.
Regression was introduced in 6f58b9d7f32d5ea83b32c162a59d1f97e958657b.
On the prior commit, the call to `bson_reader_new_from_data` was the following:
```c
response->reader =
bson_reader_new_from_data (response->rpc.reply.documents,
(size_t) response->rpc.reply.documents_len);
```
`response->rpc.reply.documents` was always non-NULL. When no documents are received, the pointer [is assigned](https://github.com/mongodb/mongo-c-driver/blob/daf8cce548f316540bc6ce556f87 …
> CDRIVER-5515 fix assert when legacy exhaust cursor receives no documents

- .evergreen/scripts/link-sample-program-mingw.cmd
This PR intends to fix the failing `link-with-cmake-mingw` task ([example](https://spruce.mongodb.com/task/mongo_c_driver_smoke_link_with_cmake_mingw_378eebdc545caedeb4e6df4f43dadd47a29dd588_24_04_02_19_09_02/logs?execution=0)):
```
[2024/04/02 15:34:08.441] CMake Error at C:/Users/mci-exec/AppData/Local/mongo-c-driver/tmp.qA7z0pyqSC/cmake-3.29.0-windows-x86_64/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[2024/04/02 15:34:08.441]   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
[2024/04/02 15:34:08.441]   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
[2024/04/02 15:34:08.441]   OPENSSL_INCLUDE_DIR)
[2024/04/02 15:34:08.441] Call Stack (most recent call first):
[2024/04/02 15:34:08.441] …
```
> do not link to OpenSSL in MinGW task

- src/libmongoc/src/mongoc/mongoc-apm.c
- src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/src/mongoc/mongoc-cmd-private.h
- src/libmongoc/src/mongoc/mongoc-cmd.c
- src/libmongoc/src/mongoc/mongoc-util-private.h
- src/libmongoc/src/mongoc/mongoc-util.c
- src/libmongoc/src/mongoc/mongoc-write-command.c
- src/libmongoc/tests/test-mongoc-cmd.c
This PR introduces private support for sending an OP_MSG with multiple document sequences (OP_MSG [Section with payloadType=1](https://github.com/mongodb/specifications/blob/fe860823426a7ab1d6e492e00e08439c8839ed71/source/message/OP_MSG.rst#op_msg-1))
The C driver currently assumes outgoing commands include one OP_MSG document sequence. https://github.com/mongodb/specifications/pull/1534 is expected to require sending two document sequences:
> Drivers MUST use document sequences ([`OP_MSG`](../message/OP_MSG.rst) payload type 1) for the `ops` and `nsInfo` fields.
This PR tests sending two document sequences using `bulkWrite` with private API. No behavior changes are expected to public API.
> CDRIVER-4363 Support multiple OP_MSG doc sequences

- .evergreen/benchmark.yml
- .evergreen/config_generator/components/funcs/fetch_det.py
- .evergreen/generated_configs/functions.yml
- .evergreen/scripts/integration-tests.sh
Consistently replaces all instances of SSH git clone commands in scripts (not in documentation) with HTTPS equivalents as a proactive measure concerning upcoming updates to EVG. Verified by [this patch](https://spruce.mongodb.com/version/66296fc56a1f920007224b85).
> Replace SSH git clone commands with HTTPS equivalents

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/build_snapshot_rpm.sh
The patch build for this PR (specifically for the `rpm-package-build task`) is in a failed state. This is because the `master` branch of the C driver relies on newly introduced features in libmongocrypt which are not present in the libmongocrypt package which can be installed from the Fedora repo. The PR for `r1.26` (#1580) branch has a patch build demonstrating that this is a working change.
> CDRIVER-4794 build RPM in EPEL environments

- src/libmongoc/doc/mongoc_client_set_sockettimeoutms.rst
- src/libmongoc/doc/mongoc_client_t.rst
- src/libmongoc/doc/mongoc_uri_t.rst
- src/libmongoc/src/mongoc/mongoc-client-pool.c
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-client.h
- src/libmongoc/src/mongoc/mongoc-cluster-private.h
- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/tests/test-mongoc-client-pool.c
so multiple pools are not necessary to accomodate different timeouts
> CDRIVER-5548 new mongoc_client_update_sockettimeoutms()

- src/libmongoc/src/mongoc/mongoc-scram.c
- src/libmongoc/tests/test-mongoc-scram.c
Fix crash when a URI includes an empty password string.
Issue was originally reported in: https://github.com/mongodb/mongo-c-driver/pull/1585
The failing Earthly tasks attached to this PR appear to be failing from unrelated reasons (environment change?). Here is a [patch build](https://spruce.mongodb.com/version/662fd37bd5216d0007283216) verifying these changes with the `*auth*` tasks.
> CDRIVER-5550 fix crash when password is empty

- src/libbson/src/bson/bson-iter.c
Zero-initialize `bson_iter_t::value`.
This PR is related to, but does not resolve CDRIVER-5536.
There are many Coverity issues in the libmongocrypt project referencing uninitialized access of the `bson_iter_t::value` field:
```c
bson_iter_t iter1;
BSON_ASSERT (bson_iter_init (&iter1, &bson)); // Does not initialize `iter1.value`
bson_iter_t iter2 = iter1; // Assigns uninitialized `value`.
```
I expect this is OK in practice. I do not expect `bson_iter_t::value` is meant to be directly accessed. The `bson_iter_t::value` is initialized and returned in `bson_iter_value`. Regardless, this PR errs towards safety. A caller may reasonably expect `bson_iter_init` to initialize all struct fields.
> CDRIVER-5536 zero-init `bson_iter_t::value`

- Earthfile
- etc/cyclonedx.sbom.json
- etc/purls.txt
This is part of the changes required for CDRIVER-5535. Additional changes will be needed for posting the information into Silk, a process which is still WIP.
This gets a head-start on the SBOM-Lite aspect of the work.
Alternative: Do we want to automate this aspect, rather than committing the generated JSON results directly? If so, it will require having and managing service credentials with Artifactory in order to pull the SilkBomb container during the CI process.
> [CDRIVER-5535] Add files and an Earthly target for an SBOM-lite

- .evergreen/config_generator/components/cse/darwinssl.py
- .evergreen/config_generator/components/cse/openssl.py
- .evergreen/config_generator/components/cse/winssl.py
- .evergreen/config_generator/components/loadbalanced.py
- .evergreen/config_generator/components/sanitizers/asan_cse.py
- .evergreen/config_generator/components/sanitizers/asan_sasl.py
- .evergreen/config_generator/components/sanitizers/tsan_sasl.py
- .evergreen/config_generator/components/sasl/darwinssl.py
- .evergreen/config_generator/components/sasl/nossl.py
- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/config_generator/components/sasl/winssl.py
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
- src/libmongoc/tests/test-mongoc-bulkwrite.c
- src/libmongoc/tests/test-mongoc-crud.c
- Add server 8.0 test tasks.
- Fix two tests added in https://github.com/mongodb/mongo-c-driver/pull/1590.
New tasks were verified in this [patch build](https://spruce.mongodb.com/version/66476a5ab1c51f000781e5a6).
Tasks with 7.0 server were copied to test 8.0.
The first commit regenerates the Evergreen config. This removes `-x` from `sh` invocation in `rpm-package-build`. I assume this was leftover from debugging.
Test fixes are intended to address observed task failures:
- `/bulkwrite/server_id/on_retry` in a [`nossl` task](https://spruce.mongodb.com/task/mongo_c_driver_sasl_matrix_nossl_sasl_off_nossl_ubuntu2004_gcc_test_8.0_sharded_noauth_patch_a8513a2119b57f0378ccdb7cbd11110368016fe0_66474fbb732469000773ee5d_24_05_17_12_38_21/logs?execution=0). Retryable writes require crypto (for …
> CDRIVER-5560 add server 8.0 tasks

- .evergreen/scripts/debian_package_build.sh
Patch build: https://spruce.mongodb.com/version/664cdf899105d00007ed761f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> don't (re-)generate VERSION_CURRENT in debian-package-build

- src/libmongoc/doc/mongoc_client_pool_pop.rst
- src/libmongoc/doc/mongoc_client_pool_try_pop.rst
- src/libmongoc/src/mongoc/mongoc-client-pool.c
- src/libmongoc/tests/TestSuite.c
- src/libmongoc/tests/TestSuite.h
- src/libmongoc/tests/test-mongoc-client-pool.c
- src/libmongoc/tests/test-mongoc-dns.c
Close operation connections to removed servers.
Verified with this patch build: https://spruce.mongodb.com/version/665489593f686b000739adf0
Motivated by an issue reported in [HELP-59749](https://jira.mongodb.org/browse/HELP-59749). Tests observed an unexpected increasing connection count. This may have been triggered by (misconfigured?) DNS records resulting in servers being frequently added/removed from the topology during SRV polling.
I considered adding a callback to `_mongoc_topology_description_remove_server` to more immediately signal to close connections. This was rejected to reduce risk of an AB-BA deadlock.
`_mongoc_topology_description_remove_server` expects the caller to hold `mongoc_topology_t::tpld_modification_mtx`. Modifying pooled client requires holding …
> CDRIVER-3645 Close operation connections to removed servers

- .evergreen/scripts/kms-divergence-check.sh
- src/kms-message/src/kms_gcp_request.c
- src/kms-message/src/kms_kmip_reader_writer.c
- src/kms-message/src/kms_kmip_reader_writer_private.h
- src/kms-message/src/kms_kmip_request.c
- src/kms-message/src/kms_kmip_response.c
- src/kms-message/src/kms_kmip_tag_type_private.h
- src/kms-message/src/kms_message/kms_kmip_request.h
- src/kms-message/src/kms_message/kms_kmip_response.h
- src/kms-message/src/kms_request_str.c
- src/kms-message/test/test_kmip_reader_writer.c
This syncs the kms-message sources vendored in the C driver with those from libmongocrypt, as of version 1.10.0 of the latter.
Evergreen patch build: https://spruce.mongodb.com/version/6658daf31dc3d50007132161/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-5583 sync KMS sources with libmongocrypt

- src/libmongoc/src/mongoc/mongoc-scram.c
Prevent integer overflow
Coverity CID: 138996
Evergreen patch build: https://spruce.mongodb.com/version/6658c7c7f2b873000746e815/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-5582 address Coverity issues

- src/libbson/src/bson/bson-endian.h
- src/libbson/tests/test-json.c
- src/libmongoc/src/mongoc/mongoc-counters-private.h
- src/libmongoc/src/mongoc/mongoc-errno-private.h
- src/libmongoc/tests/test-mongoc-stream-tls-error.c
[evergreen](https://spruce.mongodb.com/version/6659f980b0f8570007c19bdf/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
This pr removes preprocessor checks for __sun since solaris is not longer supported.
> CDRIVER-4162 remove remaining solaris workarounds

- src/libmongoc/doc/mongoc_uri_t.rst
- src/libmongoc/src/mongoc/mongoc-client-private.h
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-topology-private.h
- src/libmongoc/src/mongoc/mongoc-topology.c
- src/libmongoc/tests/test-mongoc-dns.c
Add option to prefer TCP for SRV lookup.
Checks for the environment variable `MONGOC_SRV_PREFER_TCP=ON`.
Verified with this [patch build](https://spruce.mongodb.com/version/665dcc280dd80b00072d4d37).
See DRIVERS-2919 for a description of the problem this is intended to solve. DRIVERS-2919 proposes a solution for all drivers. This PR is intended as a libmongoc-only solution for the problem impacting [HELP-59749](https://jira.mongodb.org/browse/HELP-59749).
Initially considered was adding an option setter:
```c
MONGOC_EXPORT (void)
mongoc_client_pool_set_srv_prefer_tcp (mongoc_client_pool_t *pool, bool value);
```
SRV lookup first occurs in `mongoc_client_pool_new_with_error`. An option setter like `mongoc_client_pool_set_ssl_opts` requires a client pool to already be constructed.
Also …
> CDRIVER-5589 add option to prefer TCP for SRV lookup

- Earthfile
This changeset progresses along CDRIVER-5535 by adding automation to obtain an augmented SBOM for a particular branch. This is a follow-up to #1594 and #1619.
This defines an Earthly target `+sbom-download` that downloads the latest augmented SBOM file from Silk baesd on the specified Git branch. This artifact is not currently used, but will be part of upcoming changes related to a new signed release archive artifact for CDRIVER-5537.
> [CDRIVER-5535] Add an +sbom-download target for getting the augmented SBOM

- src/common/common-macros-private.h
- src/libmongoc/src/mongoc/mongoc-opts-private.h
- src/libmongoc/src/mongoc/mongoc-ts-pool-private.h
Added this header:
`/*
* Copyright 2018-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/`
To the files:
- mongoc-ts-pool-private.h
- mongoc-opts-private.h
- common/common-macros-private.h
> CDRIVER-5581: Add missing license attributions

- src/libmongoc/tests/test-mongoc-sample-commands.c
In with_transaction_example:
- Removed explicit setting of read concern options
- Removed explicit setting of read preferences
- Noted that Atlas connection strings include w=majority by default
- Removed timeout (of 1000ms) from write concern
Made same Atlas default note on line 3642
> CDRIVER-4618: updated transaction examples

- src/libmongoc/tests/json/command-logging-and-monitoring/monitoring/unacknowledged-client-bulkWrite.json
Syncs changes from https://github.com/mongodb/specifications/pull/1598. C is the only driver that currently runs this test, so no language-specific tickets were generated for this change.
full patch: https://spruce.mongodb.com/version/666219ab935800000809786e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync w:0 client bulk write command monitoring test

- src/libmongoc/src/mongoc/mongoc-log.c
- src/libmongoc/src/mongoc/mongoc-trace-private.h
Updated:
`if (MONGOC_TRACE_ENABLED)`
to
`if (MONGOC_TRACE_ENABLED && gLogTrace)`
via [_mongoc_log_trace_is_enabled](https://github.com/vector-of-bool/mongo-c-driver/blob/master/src/libmongoc/src/mongoc/mongoc-log.c#L64) which has the same logic.
> CDRIVER-4697: More efficient trace toggle

- Earthfile
- docs/dev/conf.py
- docs/dev/earthly.rst
- docs/dev/index.rst
- docs/dev/releasing.rst
This changeset re-introduces a release archive process as part of the release process. This is significantly simplified from the old `makedist` archive, and is mostly just an archive produced by Git with some additional goodies, with more to be added in later changes.
- New Earthly targets are added to automate aspects of the release process, including generation of the source archive and signing thereof. Currently, this creates an unfortunate split of the release tools between the c-driver-tools repo and this repository, but it is anticipated that future changes will progressively migrate additional components from the c-driver-tools repo back into the main source repository.
- More documentation has been added on using Earthly and the Earthfile targets, hopefully to accelerate future …
> [CDRIVER-5537] A Signed Release Archive + Augmented SBOM Publication

- src/libmongoc/tests/test-mongoc-sample-commands.c
[evergreen](https://spruce.mongodb.com/version/66632552bb4b4200076838fd/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Evergreen test failures don't seem related. The test_sample_txn_commands in the /Samples test suite is erring locally, but the newly added test test_sample_projection_with_aggregation_expressions runs fine.
> CDRIVER-5303 Docs example request: Projection with aggregation expressions

- docs/dev/releasing.rst
This PR adopts the same process/documents that are used by libmongocrypt to generate and address a static analysis report for the C driver.
> [CDRIVER-4786] [CDRIVER-5536] Release process for static analysis checks

- src/libmongoc/src/mongoc/mongoc-topology-background-monitoring.c
- src/libmongoc/src/mongoc/mongoc-topology-private.h
- src/libmongoc/src/mongoc/mongoc-topology.c
Because the topology's rescan interval can be updated in parallel with other threads reading its value, the value needs to be atomic to prevent data races. This does not necessarily fix race conditions, but does avoid the UB of data races.
Coverity CID: 139003 - Was marked as "Intentional", but a data race is always UB, so a fix is warranted.
> CDRIVER-5604 Change updates to SRV rescan interval to be atomic

- src/libmongoc/src/mongoc/mongoc-client-pool.c
- src/libmongoc/src/mongoc/mongoc-topology-private.h
- src/libmongoc/src/mongoc/mongoc-topology.c
This is a very minor and unlikely race on settings the APM callbacks on a client pool. This change wraps the check+update in the topology description guard. This change also does some minor drive-by improvements in style.
Coverity CID 139002
> CDRIVER-5605 Guard against a race on setting APM callbacks

- src/libmongoc/src/mongoc/mongoc-cluster-private.h
- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/src/mongoc/mongoc-cmd-private.h
- src/libmongoc/src/mongoc/mongoc-cmd.c
- src/libmongoc/src/mongoc/mongoc-host-list.c
These changes address minor UB surrounding use of mongoc_host_list_t, which is detected by Coverity at three different locations (f2ae74250c01ee221ea31a24103cfcd2801e3c8e).
This also includes some drive-by cleanup of `_stream_run_hello` to reduce the scope of declared variables and enforce more `const` uses (03d19b0e897c5d4846a3220eeec71492a565e60a).
Coverity: CID 120342, 121139, and 118903
> [CDRIVER-5606] Fix unitiailized padding in mongoc_host_list_t

- src/libbson/src/bson/bson-oid.c
Instead of doing a clever memcpy of a BE-encoded uint32_t bunch-of-bits, explicitly perform the encoding inline. Avoids a suspicious truncation of time_t to uint32_t, and explains why we are doing it.
This does not directly fix any behavioral issue, but makes the implementation less clever and more explicit for static analysis.
Coverity CID 123525 & CID 123519
> CDRIVER-5607 Clean up OID init to avoid a suspicious time_t trunc

- src/libbson/src/bson/bson-decimal128.c
- src/libbson/src/bson/bson-keys.c
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-cluster-aws.c
- src/libmongoc/src/mongoc/mongoc-counters.c
- src/libmongoc/src/mongoc/mongoc-crypt.c
- src/libmongoc/src/mongoc/mongoc-gridfs-bucket.c
- src/libmongoc/src/mongoc/mongoc-gridfs.c
- src/libmongoc/src/mongoc/mongoc-handshake.c
- src/libmongoc/src/mongoc/mongoc-host-list-private.h
- src/libmongoc/src/mongoc/mongoc-host-list.c
- src/libmongoc/src/mongoc/mongoc-read-prefs.c
- src/libmongoc/src/mongoc/mongoc-sasl.c
- src/libmongoc/src/mongoc/mongoc-socket.c
- src/libmongoc/src/mongoc/mongoc-topology-scanner.c
- src/libmongoc/src/mongoc/mongoc-util.c
- src/libmongoc/tests/test-mongoc-dns.c
- src/libmongoc/tests/test-mongoc-gridfs-bucket.c
[ticket](https://jira.mongodb.org/browse/CDRIVER-4820)
[evergreen](https://spruce.mongodb.com/version/6669e4353d2b3f0007b8a217/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Evergreen test failures look unrelated, but could be double checked.
See https://github.com/mongodb/mongo-c-driver/compare/master...kevinAlbs:mongo-c-driver:bson_snprintf-hints.CDRIVER-4820?expand=1 for more details.
> CDRIVER-4820 check return values of `bson_snprintf`

- tools/create-silk-asset-group.py
Followup to https://github.com/mongodb/mongo-c-driver/pull/1619 that ensures the `"file_paths"` field (which tells Silk how vulnerabilities should be directed when multiple distinct asset groups are in the same repo) is set to `["*"]` (current recommended default, details pending further review).
Additionally ensures the `silk_id` of the new asset group is emitted in output on successful creation for asset group tracking and maintenance purposes, as it is currently swallowed by the `json.loads()` call.
> CDRIVER-5535 Minor improvements to create-silk-asset-group.py

- Earthfile
- docs/dev/earthly.rst
- docs/dev/releasing.rst
- etc/ssdlc.md
Refer: CDRIVER-5540. This simple change adds the `ssdlc_compliance_report.md` file to the repository and to the release archive. It is stored in `etc/ssdlc.md` for editing, but is copied as a top-level file `ssdlc_compliance_report.md` within the generate release archive.
The file itself is based on the similar file present in the C++ driver and libmongocrypt repositories.
> [CDRIVER-5540] Introduce an `ssdlc_compliance_report.md` to the release archive

- src/libmongoc/tests/test-mongoc-handshake.c
[evergreen](https://spruce.mongodb.com/version/6675c1fb33395a00075e6435/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) [ticket](https://jira.mongodb.org/browse/CDRIVER-4832)
Added test for the case where the driver does not raise an error if saslSupportedMechs attribute
of the initial handshake reply contains an unknown mechanism.
> CDRIVER-4832 Rearchitect User Acquisition in Authentication and Authorization Workflow

- src/libmongoc/src/mongoc/mongoc-cluster.c
Addresses CDRIVER-5584.
https://github.com/mongodb/mongo-c-driver/commit/1c8da0ee199661a4276c87fb9ec2fbb375a2a4ad introduced a [call](https://github.com/mongodb/mongo-c-driver/commit/1c8da0ee199661a4276c87fb9ec2fbb375a2a4ad#diff-7723202fa2b19410a0b6dd42b6dda8d3708c52f85e7b553977c0bbe324031b41R3709) to `mcd_rpc_op_msg_get_flag_bits`, which has a [precondition](https://github.com/mongodb/mongo-c-driver/blob/1c8da0ee199661a4276c87fb9ec2fbb375a2a4ad/src/libmongoc/src/mongoc/mcd-rpc.c#L2156) that the RPC message's opCode is `OP_MSG` (2013).
Prior to https://github.com/mongodb/mongo-c-driver/commit/1c8da0ee199661a4276c87fb9ec2fbb375a2a4ad, the opCode was validated by a [call](https://github.com/mongodb/mongo-c-driver/blob/6f58b9d7f32d5ea83b32c162a59d1f97e958657b/src/libmongoc/src/mongoc/mongoc-c …
> CDRIVER-5584 delay OP_MSG flag bit access until after opCode check

- src/libbson/src/bson/bson-oid.c
- src/libmongoc/src/mongoc/mongoc-topology-private.h
To fix build on VS 2013. Replaces `inline` added in CDRIVER-5604 and CDRIVER-5607.
Patch with a VS 2013 task: https://spruce.mongodb.com/version/6683efce978b630007f6b801
I also added the `release-compile` task on the `windows-2013` variant as part of the [GitHub Patch Definitions](https://spruce.mongodb.com/project/mongo-c-driver/settings/github-commitqueue) to include a VS 2013 task in the Evergreen patches created in GitHub PRs.
> [CDRIVER-5604 + CDRIVER-5607] replace `inline` with `BSON_INLINE`

- etc/cyclonedx.sbom.json
- etc/purls.txt
PR includes an update to the SBOM file by running the `+sbom-generate` Earthly target. This update accounts for the ZLib update done in https://github.com/mongodb/mongo-c-driver/pull/1651.
> CDRIVER-5610 update SBOM

- Earthfile
- docs/dev/releasing.rst
This PR includes two changes to the release process:
- Do not save report in the `dist` directory. The report is already included in the release tarball.
- Fix typo in report name: `ssldc` => `ssdlc`.
> remove extra artifact from `release-archive`

- src/common/bson-dsl.h
- src/common/bson-dsl.md
- src/libmongoc/src/mongoc/mongoc-uri.c
- src/libmongoc/tests/test-mongoc-client-session.c
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
- src/libmongoc/tests/unified/entity-map.c
- src/libmongoc/tests/unified/operation.c
Replace `bool` in BSON DSL with `boolean`.
Evergreen patch: https://spruce.mongodb.com/version/668c26d644a2bb0007db5a0f
Intended to avoid possible build errors when `bool` is defined as a macro. This [forum post](https://www.mongodb.com/community/forums/t/error-when-build-mongo-c-driver-with-visual-studio-2019/287062/4) suggests the user's build environment defines `bool` (or `_Bool`) as `int`, resulting in a build error due to BSON DSL macros evaluating to an undeclared identifier:
```
mongoc-uri.c:1635:4: error: use of undeclared identifier '_bsonDSL_Type_int'
1635 |    bsonParse (uri->options,
|    ^
```
To reproduce the reported issue, a `stdbool.h` was added locally to define `bool` as `int`:
```c
#ifndef __STDBOOL_CUSTOM_H
#define __STDBOOL_CUSTOM_H
#define bool int
#define true 1 …
```
> CDRIVER-5629 do not use `bool` in BSON DSL

- src/libmongoc/src/mongoc/mongoc-counters-private.h
This PR address the wall of nearly 1K `-Wunused-parameter` warnings emitted by the C Driver when being built-from-source by the CXX Driver in certain EVG tasks ([example](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_macos_1100_latest_compile_and_test_with_static_libs_735cb4d5a668c2068dfe9afa1acc50c4ee9afad7_24_07_01_16_16_07/0/task?bookmarks=0,14099&shareLine=456)).
Most other warnings were already addressed by https://github.com/mongodb/mongo-c-driver/pull/1543.
> Address -Wunused-parameter warnings for SHM counter functions

- NEWS
Announce plan to drop VS 2013.
Dropping VS 2013 is [tentatively planned](https://docs.google.com/spreadsheets/d/1V8N9L9m2SZewWEvAoaKIOlKdZUUF12E7dEl_hTW3Wv0/edit?gid=1420163819#gid=1420163819) in FY25Q3. [Visual Studio Product Lifecycle and Servicing](https://learn.microsoft.com/en-us/visualstudio/productinfo/vs-servicing) documents that "Visual Studio 2013" was in the "Lifecycle Stage" of "Extended" until April 2024.
[Server, language or runtime version compatibility changes](https://docs.google.com/document/d/1Y3aNiHP_g7uqgLLdRnEDQRLl6yz45PVRDoUDsjMkRD0/edit#heading=h.pzmp88gu5q0e) notes:
> Version compatibility changes will be communicated at least one minor version (Y) before compatibility with a version is removed.
> CDRIVER-4479 announce plan to drop VS 2013

- src/libmongoc/examples/example-bulkwrite.c
- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
- src/libmongoc/src/mongoc/mongoc-cyrus.c
- src/libmongoc/tests/unified/operation.c
- src/libmongoc/tests/unified/result.c
- src/libmongoc/tests/unified/result.h
Identifies and addresses some `-Wunused-parameter` warnings following https://github.com/mongodb/mongo-c-driver/pull/1590.
> Address -Wunused-parameter warnings

- .evergreen/config_generator/components/sanitizers/asan_sasl.py
- .evergreen/config_generator/components/sasl/darwinssl.py
- .evergreen/config_generator/components/sasl/nossl.py
- .evergreen/config_generator/components/sasl/winssl.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/scripts/integration-tests.sh
- NEWS
- src/libmongoc/src/mongoc/mongoc-client-private.h
- src/libmongoc/tests/json/server_discovery_and_monitoring/rs/compatible.json
- src/libmongoc/tests/json/server_discovery_and_monitoring/rs/compatible_unknown.json
- src/libmongoc/tests/json/server_discovery_and_monitoring/sharded/compatible.json
- src/libmongoc/tests/json/server_discovery_and_monitoring/single/compatible.json
- src/libmongoc/tests/json/server_discovery_and_monitoring/single/too_old_then_upgraded.json
[ticket](https://jira.mongodb.org/browse/CDRIVER-4815)
Updated minWireVersion to 7. removed server version 3.6 from evergreen config files (asan_sasl, darwinssl, nossl, winssl) then generated evergreen config files, removed 3.6 from documentation in integration-tests.sh,and bumped up maxWireVersion in [specified](https://github.com/mongodb/specifications/commit/959a5de6c3e4cb84033f1505d66a0b109f38918f) sdam tests.
> CDRIVER-4815 Mark Server version 3.6 as EOL from driver's PoV (Min server version as 4.0, minWireVersion as 7.0)

- src/libmongoc/src/mongoc/mongoc-client-private.h
- src/libmongoc/src/mongoc/mongoc-util.c
- Increase `WIRE_VERSION_MAX` to `WIRE_VERSION_8_0`.
> CDRIVER-5612 Bump maxWireVersion for MongoDB 8.0

- src/libmongoc/tests/json/index-management/createSearchIndex.json
- src/libmongoc/tests/json/index-management/createSearchIndexes.json
This PR implements necessary driver changes requested by the spec change [DRIVERS-2768](https://jira.mongodb.org/browse/DRIVERS-2768): "Drivers must support use of the type field when creating search indexes. Creating a vector search index requires specifying type=vectorSearch."
Since the C driver doesn't have a dedicated API for managing search indexes, the only changes made were to the JSON specification tests:
- Copied updated JSON test files from https://github.com/mongodb/specifications/commit/b746fcc71ad7c1b376482852c3c9cbba4eed7d26 into index-management 
- No updates were necessary to the unified test runner as`operation_createSearchIndex` and  `operation_createSearchIndexes` just pass along the search index model without examining its contents.
> CDRIVER-4831 [Vector Search GA] Add support for the new type field when creating search indexes

- src/libbson/src/bson/bson.c
This PR makes the BSON append operation more robust. Specifically, it now checks that the lengths of the key and the value being appended will not cause overflows. Rather than using assertions, I have done as suggested by @eramongodb and used `return` instead. I defaulted to returning `false` or `NULL` (the expected behavior for a wide variety of failure modes of public functions) and in one instance used a return of `bson_append_null (...)` (which follows another available patter in `bson_append_utf8 ()`.
As far as documentation goes, it seems to me that the existing documentation still describes the behavior even following these changes. `src/libbson/doc/bson_append_utf8.rst` contains the following:
```
Returns
-------
Returns ``true`` if the operation was applied successfully. The …
```
> CDRIVER-5601 CDRIVER-5602 more robust bson append

- .evergreen/scripts/compile-unix.sh
- .evergreen/scripts/compile-windows.sh
- CMakeLists.txt
- NEWS
- src/CMakeLists.txt
- src/libbson/CMakeLists.txt
- src/libmongoc/CMakeLists.txt
Resolves CDRIVER-5635. Verified by [this patch](https://spruce.mongodb.com/version/669a9f647a1e2e0007b0e750).
Although tests and examples are correctly _disabled_ via `ENABLE_TESTS` and `ENABLE_EXAMPLES`, they are not being correctly _excluded_ from the `ALL` target when enabled. The `ALL` target should only build targets which are required by the `install` target (that is, targets which produce artifacts intended to be installed, with the exception of excluded components, which does not apply to our project. This is the same in spirit to the `make && make install` pattern).
Grepping the CMake build output for "Linking" is an approximate means of identifying the list of executable/library targets being built. The base commit currently emits the following list of artifacts for a simple …
> CDRIVER-5635 Exclude tests and examples from ALL target

- .evergreen/scripts/compile-libmongocrypt.sh
- src/libmongoc/doc/mongoc_client_encryption_encrypt_range_opts_set_sparsity.rst
- src/libmongoc/doc/mongoc_client_encryption_encrypt_range_opts_set_trim_factor.rst
- src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
- src/libmongoc/tests/json/client_side_encryption/legacy/fle2v2-Rangev2-Defaults.json
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
- Document `sparsity` and `trimFactor` as optional.
- Add tests from DRIVERS-2927.
- Always pass `sparsity` and `trimFactor` to libmongocrypt if set.
Evergreen patch: https://spruce.mongodb.com/version/669eb9a3c96e7f000700497c
MONGOCRYPT-698 changes libmongocrypt to make `trimFactor` and `sparsity` optional. If not set, they default to values matching the server.
This PR includes tests proposed in DRIVERS-2927.
Prior to this PR, `trimFactor` and `sparsity` were only passed to libmongocrypt if set to a non-zero value. However, a `trimFactor` of 0 is a accepted value by libmongocrypt. `sparsity` of 0 results in an error in libmongocrypt.
> CDRIVER-5636 make `trimFactor` and `sparsity` optional

- .evergreen/scripts/run-auth-tests.sh
Skip authentication tests running against 3.6 servers.
Verified by [this patch](https://spruce.mongodb.com/version/66a29f2adf4e6a00076a62fa)
CDRIVER-4815 dropped support for 3.6 servers. Some test servers are running 3.6, resulting in task failures. [Example](https://spruce.mongodb.com/task/mongo_c_driver_gcc48rhel_authentication_tests_openssl_75ec9c31cd974e9bfab0fecd8aa2eca92399543f_24_07_23_19_57_35/logs?execution=0):
```
Ping failure: Server at <REDACTED:auth_host>:27017 reports wire version 6, but this version of libmongoc requires at least 7 (MongoDB 4.0)
```
[DEVPROD-9029](https://jira.mongodb.org/browse/DEVPROD-9029) tracks upgrading test servers. This PR proposes skipping tests in the short-term as they are expected to fail.
> CDRIVER-5645 skip auth tests running against MongoDB 3.6.

- docs/dev/debian.rst
This represents the current procedure for creating and releasing Debian packages, tested on the libmongocrypt 1.11.0 release.
> Update Debian package release steps

- docs/dev/debian.rst
Compare before: https://github.com/mongodb/mongo-c-driver/blob/f2d97fb41dfc50c87911a7b6396093c38b92ac6e/docs/dev/debian.rst
And after: https://github.com/mongodb/mongo-c-driver/blob/88ac67eff92b62ade2fd4cf9a26999ab825d741c/docs/dev/debian.rst
> Fix RST formatting for monospace

- Earthfile
- NEWS
- docs/dev/releasing.rst
- src/libbson/NEWS
- Update the NEWS following the 1.27.5 release.
- Specify `amd64` platform for `snyk-monitor-snapshot` target to ensure downloaded `snyk` binary matches container architecture.
- Remove Homebrew steps from release.
Specifying the `amd64` platform on the `snyk-monitor-snapshot` target is intended to address an error observed during the release:
```
================================== ❌ FAILURE ===================================
+snyk-monitor-snapshot *failed* | Repeating the failure error...
+snyk-monitor-snapshot *failed* | branch=r1.27 name=release-1.27.5
+snyk-monitor-snapshot *failed* | --> RUN --no-cache snyk monitor --org=$SNYK_ORGANIZATION --target-reference=$name --unmanaged --print-deps --project-name=mongo-c-driver --remote-repo-url=https://github.com/mongodb/mongo-c-driver …
```
> Update NEWS and release process

- .tsan-suppressions
- src/libmongoc/src/mongoc/mongoc-handshake.c
Resolves CDRIVER-3685. Verified by [this patch](https://spruce.mongodb.com/version/66ba44e25db9c000071f03c9).
Encountered while investigating [ongoing task failures due to /scram/cache_invalidation](https://spruce.mongodb.com/version/mongo_c_driver_7b2ed297c5c546d520e7ae878ba23338f826bcfa/) following https://github.com/mongodb/mongo-c-driver/pull/1684.
Access of `_mongoc_handshake_get ()` following initialization must be guarded by `gHandshakeLock` (even for single-threaded clients).
> CDRIVER-3685 address TSAN warning for mongoc_handshake_t::frozen

- src/libmongoc/src/mongoc/mongoc-crypto-cng.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1697. Verified by [this patch](https://spruce.mongodb.com/version/66ba490819a1390007d95802/tasks?baseStatuses=failed&page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&statuses=success).
Addresses compilation warnings (treated as error when compiling with MinGW) due to conditionally-used `_crypto_hash_size` and an implicit `const uint8_t*` -> `const char*` conversion in a call to `bson_strndup`.
> CDRIVER-5634 Address MinGW compilation warnings for PBKDF2 related functions

- src/libmongoc/src/mongoc/mongoc-handshake.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1698. Fixes recursive lock in `mongoc_handshake_data_append`. Verified by [this patch](https://spruce.mongodb.com/version/66ba65f505efc400074ad3d7).
> CDRIVER-3638 add non-locking variant of `_mongoc_handshake_freeze`

- CONTRIBUTING.md
- src/libbson/doc/bson_string_append.rst
- src/libbson/doc/bson_string_append_c.rst
- src/libbson/doc/bson_string_append_printf.rst
- src/libbson/doc/bson_string_append_unichar.rst
- src/libbson/doc/bson_string_new.rst
- src/libbson/src/bson/bson-string.c
- src/libbson/tests/test-string.c
See CDRIVER-5669 for a detailed description of the issue. Verified by this [patch build](https://spruce.mongodb.com/version/66b9f9b5d1d9640007f41431/).
Additional improvements:
- Document expected max length for `bson_string_t` functions.
- Add tests to help with local verification. Tests are not run in Evergreen due to observed [25s runtime on ASan](https://parsley.mongodb.com/evergreen/mongo_c_driver_sanitizers_matrix_asan_asan_sasl_cyrus_openssl_ubuntu1804_clang_test_6.0_sharded_auth_patch_7b2ed297c5c546d520e7ae878ba23338f826bcfa_66b8df1bb8a5b300078fe085_24_08_11_15_56_12/0/task?bookmarks=0,21688&shareLine=2151) and [failure to allocate on TSan](https://spruce.mongodb.com/task/mongo_c_driver_sanitizers_matrix_tsan_tsan_sasl_cyrus_openssl_ubuntu1804_clang_test_4.0_replica_auth_patch_7b2e …
> CDRIVER-5669 improve string function handling of large strings

- src/libbson/src/bson/bson-json.c
- src/libbson/tests/test-json.c
Resolves CDRIVER-5667. Verified by [this patch](https://spruce.mongodb.com/version/66b53769e4b2620007435635).
Traced the issue to a code pattern discrepancy in `_bson_json_read_map_key` when handling special keys in the `BSON_JSON_IN_BSON_TYPE` read state. The BSON type field is reset to `BSON_TYPE_EOD` (value: `0`) when transitioning from `BSON_JSON_IN_START_MAP` -> `BSON_JSON_IN_BSON_TYPE`. This PR identified that when subsequently identifying the special key value on re-entry into this function (such as when parsing the key of a subdocument), only some branches performed a check for a pre-existing non-EOD BSON type. Simplified:
```c
if (bson->read_state == BSON_JSON_IN_BSON_TYPE) {
// Via HANDLE_OPTION expansion.
if (len == strlen ("$regex") && strncmp ((const char *) val, ("$regex"), …
```
> CDRIVER-5667 Add missing BSON type checks in special key handlers

- .evergreen/config_generator/components/earthly.py
- .evergreen/generated_configs/tasks.yml
Remove reference to distro `ubuntu1804` (without `-small` or `-large` suffix). Fixes warnings produced by `evergreen validate`:
```bash
$ evergreen validate ./.evergreen/config.yml --project mongo-c-driver
NOTICE: task 'create-silk-asset-group' in buildvariant 'misc' references distro 'ubuntu1804' with the following admin-defined warning(s): This distro was created for ops-manager testing: DEVPROD-7666.  It should be deleted in about 3 weeks from June 3, 2024
[... many more ...]
```
> Remove reference to `ubuntu1804` distro

- src/libmongoc/src/mongoc/mongoc-crypto-cng.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1684. Fixes test failures on Windows with SCRAM auth. [Example failure](https://spruce.mongodb.com/task/mongo_c_driver_sasl_matrix_winssl_sasl_sspi_winssl_windows_2019_vs2017_x86_test_latest_server_auth_b4bf5a1bdc47236450e1ae365e87123a3029ef2b_24_08_12_18_01_53/logs?execution=0):
```
Begin /scram/cache_invalidation, seed 1723487056
{ "status": "fail", "test_file": "/scram/cache_invalidation", "seed": "1723487056", "start": 965.718000, "end": 974.359000, "elapsed": 8.641000  },
FAIL:C:\data\mci\26ca9ede4b9bb4808634a41a0bd207c0\mongoc\src\libmongoc\tests\test-mongoc-scram.c:457  _try_auth_from_uri()
res
Authentication failed.
```
Verified with this [patch build](https://spruce.mongodb.com/version/66ba56cdeb143c00071e6b38/).
Running …
> CDRIVER-5634 account for embedded NULL when copying `salt`

- .evergreen/etc/skip-tests.txt
- src/libmongoc/tests/test-mongoc-sample-commands.c
Resolves CDRIVER-4352. Unskips the `/Samples*` tests and applies fixes.
To verify changes, the `/Samples*` tests were run 100 times in [this patch build](https://spruce.mongodb.com/version/66b41bb6f1658d0007fc2a18).
Several test errors were addressed. See commits for details. Notably:
- An informational `MONGOC_INFO` log was replaced with `MONGOC_DEBUG`. This was to fix a failing `ASSERT_NO_CAPTURED_LOGS`. CDRIVER-4282 changed test log capture to [include `MONGOC_LOG_LEVEL_INFO`](https://github.com/mongodb/mongo-c-driver/pull/1374/files#diff-b71f20ac0b55a16f43592d6bc46791721a0a075febda9e508f3c66d555fae9e9L209). 
- Snapshot query examples added in CDRIVER-4295 were updated to skip on server <= 5.0. Drivers [error](https://jira.mongodb.org/browse/DRIVERS-1820) if using snapshot sessions …
> CDRIVER-4352 unskip `/Samples` tests

- src/libbson/src/bson/bson-atomic.h
When investigating CXX-3088, building the C++ driver resulted in warnings building the C driver:
```
../../../mongo-c-driver-src/src/libbson/src/bson/bson-atomic.h: In function 'bson_atomic_int8_fetch':
../../../mongo-c-driver-src/src/libbson/src/bson/bson-atomic.h:203:54: warning: unused parameter 'order' [-Wunused-parameter]
Type volatile const *a, enum bson_memory_order order)                   \
^
../../../mongo-c-driver-src/src/libbson/src/bson/bson-atomic.h:364:1: note: in expansion of macro 'DECL_ATOMIC_INTEGRAL'
DECL_ATOMIC_INTEGRAL (int8, DECL_ATOMIC_INTEGRAL_INT8, 8)
```
This PR adds `BSON_UNUSED` to fix the warning. Fix was verified with [this patch build](https://spruce.mongodb.com/version/66bbb3d2d10acd0007b8896e) of the C++ driver referring to this branch of the C driver.
> CDRIVER-5673 Fix unused warnings for legacy atomic impls

- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-libmongoc.h
- src/libmongoc/tests/test-mongoc-client.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1673. Fixes failing `retry-true-latest-server` task. [Example failure](https://spruce.mongodb.com/task/mongo_c_driver_gcc75_retry_true_latest_server_f6971f8c49ccca3c840f65233ae514ccf1df8709_24_08_12_18_29_56/logs?execution=0):
```
FAIL:tests/test-mongoc-client.c:2240  test_mongoc_client_change_openssl_ctx_before_ops()
ret
No suitable servers found: `serverSelectionTimeoutMS` expired: [TLS handshake failed: Connection timed out calling hello on 'localhost:27017']. Topology type: Single
```
Tests require the server to be running with TLS enabled. The `retry-true-latest-server` uses a C driver built with OpenSSL, but does not run against a server with TLS enabled.
Verified with [this …
> CDRIVER-4656 check if server is running with TLS in tests

- build/cmake/Sanitizers.cmake
- src/libbson/fuzz/CMakeLists.txt
- src/libbson/fuzz/fuzz_test_validate.c
This patch implements a fuzzer for bson_validate. It works be performing the following steps:
1. Implement a new entrypoint
2. Adding the entrypoint to CMakeLists
3. Adding '-fno-sanitize-recover=all' to sanitizer flags, so that UBSan faults become unrecoverable.
> CDRIVER-5676 implement bson_validate libfuzzer entrypoint

- src/libbson/fuzz/CMakeLists.txt
Followup to https://github.com/mongodb/mongo-c-driver/pull/1705.
A small refactor that extracts common target properties of fuzz test executables into an interface library for reusability as more fuzz test executables are expected to be introduced.
> Add fuzz_test_properties for common target options for fuzz executables

- .evergreen/config_generator/components/cse/darwinssl.py
- .evergreen/config_generator/components/cse/openssl.py
- .evergreen/config_generator/components/cse/winssl.py
- .evergreen/config_generator/components/sasl/darwinssl.py
- .evergreen/config_generator/components/sasl/nossl.py
- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/config_generator/components/sasl/winssl.py
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/variants.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/functions.py
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/compile-libmongocrypt.sh
- .evergreen/scripts/compile-unix.sh
- .evergreen/scripts/compile-windows.sh
- .evergreen/scripts/debug-core-evergreen.sh
- .evergreen/scripts/find-ccache.sh
- .evergreen/scripts/run-mock-server-tests.sh
- .evergreen/scripts/run-tests-mingw.bat
- .evergreen/scripts/run-tests.sh
Followup to https://github.com/mongodb/mongo-c-driver/pull/1524. Verified by [this patch](https://spruce.mongodb.com/version/66ce1342e0dea500075ee87d).
Addresses the following error on some Windows distros when used with the old `CCache.cmake` module (discovered while testing the C++ Driver; this does not break builds but does impact ccache efficiency):
```
ccache: error: CCACHE_BASEDIR: not an absolute path: "/cygdrive/c/data/mci/.../mongo-cxx-driver"
```
Applies a proper transformation to Windows path form on Windows distros to avoid Windows-side cmake or ccache confusion of file paths.
Additional improvements include:
- removing a pre-1.11.0 libmongocrypt workaround now that 1.11.0 is released.
- simplifying DEBUG vs. RELEASE variable checks in compile scripts (mutually exclusive …
> Miscellaneous EVG compilation script improvements

- src/libmongoc/doc/mongoc_client_session_start_transaction.rst
- src/libmongoc/doc/mongoc_client_session_with_transaction.rst
This ticket updates the documentation for `mongoc_client_session_with_transaction` with more information regarding error handling as to avoid infinite loops.
> CDRIVER-4755 document error handing in transactions

- src/libmongoc/src/mongoc/mongoc-log-private.h
- src/libmongoc/src/mongoc/mongoc-log.c
This ticket adds a macro to return early from `mongoc_log_trace_bytes()` and `mongoc_log_trace_iovec()` if no log handler is registered.
> CDRIVER-4800 return from trace functions if no logger

- .evergreen/config_generator/components/c_std_compile.py
- .evergreen/config_generator/components/funcs/find_cmake_latest.py
- .evergreen/config_generator/components/loadbalanced.py
- .evergreen/config_generator/components/make_docs.py
- .evergreen/config_generator/components/mock_server.py
- .evergreen/config_generator/components/openssl_static_compile.py
- .evergreen/config_generator/components/scan_build.py
- .evergreen/config_generator/etc/compile.py
- .evergreen/config_generator/etc/sasl/compile.py
- .evergreen/config_generator/etc/utils.py
- .evergreen/generated_configs/functions.yml
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/legacy_config_generator/evergreen_config_lib/testazurekms.py
- .evergreen/legacy_config_generator/evergreen_config_lib/testgcpkms.py
- .evergreen/scripts/find-cmake-latest.sh
- .evergreen/scripts/find-cmake-version.sh
- poetry.lock
- pyproject.toml
Verified by [this patch](https://spruce.mongodb.com/version/66d0a3ea10a09d0007ad3b6c). (Note: this patch includes `BYPASS_CMAKE_CACHE=ON`.)
Applies some miscellaneous improvements and updates to the EVG config:
- Raise CMake latest version from 3.29.0 to 3.30.2.
- Raise shrub.py version from 3.0.4 to 3.1.3.
- Address potential nounset error due to obsolete `curl_args` variable expansion when requiring building CMake from source.
- Add a standalone `find-cmake-latest` EVG function with `retry_on_failure: true` before (most) commands that use CMake in an attempt to improve the quality (report CMake download-or-build failures as a "Setup" task failure) and robustness (automatically retry on spurious network failures) of obtaining CMake (e.g. as observed in [this …
> Miscellaneous maintenance of EVG config

- src/libmongoc/src/mongoc/mongoc-uri.c
- src/libmongoc/tests/json/connection_uri/invalid-uris.json
- src/libmongoc/tests/json/connection_uri/valid-options.json
- src/libmongoc/tests/test-mongoc-uri.c
This ticket removes the requirement for URIs to have a delimiting slash in between the hosts and options (e.g. `mongodb://example.com?w=1` is equivalent to `mongodb://example.com/?w=1`).
Relevant spec tests were updated according to [this](https://github.com/mongodb/specifications/pull/1447) PR.
> CDRIVER-4726 make delimiting slash in URI optional

- Earthfile
- NEWS
- docs/dev/earthly.rst
- docs/dev/releasing.rst
- src/libbson/NEWS
Add NEWS from 1.27.6 release. Update release instructions to help locate credentials. Update `+release-archive` target to install `bash` to fix error observed error:
```
+release-archive | branch=r1.27 prefix=mongo-c-driver-1.27.6 ref=refs/tags/1.27.6 sbom_branch=r1.27 version=1.27.6
+release-archive | --> IF __str test "$version" -matches ".*\.0\$"
+release-archive | env: can't execute 'bash': No such file or directory
```
> update NEWS and release instructions post 1.27.6 release

- src/libbson/src/bson/bson-iter.c
Addresses CDRIVER-5680. See ticket for details.
> CDRIVER-5680 Address potential integer overflow when validating old binary data length

- .evergreen/scripts/integration-tests.sh
This PR is intended to address recently occurring `Setup Failure` task failures. Verified by this [patch build](https://spruce.mongodb.com/version/66df39cf6495c60007e3e822).
https://github.com/mongodb-labs/drivers-evergreen-tools/commit/57cadda5a5ea4ee272daa20cf402bdb58c5280e7 appeared to result in downloading MongoDB binaries to a location that differed from C driver expectations. This resulted in `Setup Failure` on test tasks: [example](https://spruce.mongodb.com/version/66df1aafc5b87d0007d692e8/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Esanitizers-matrix-asan%24). The attached orchestration.log (under Files) includes error logs:
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/mci/b15d555f806324a511e4c66f6c01ff29/mongoc/mongodb/bin/mongod'
```
I …
> set `MONGODB_BINARIES`

- src/libbson/src/bson/bson-decimal128.c
- src/libbson/tests/test-decimal128.c
Resolves CDRIVER-5681. See ticket for details.
> CDRIVER-5681 Address potential buffer overflow when writing null terminator after decimal128 significand digits

- src/libbson/doc/bson_utf8_escape_for_json.rst
- src/libbson/doc/bson_utf8_get_char.rst
- src/libbson/fuzz/CMakeLists.txt
- src/libbson/fuzz/fuzz_test_bson_utf8_escape_for_json.c
- src/libbson/src/bson/bson-utf8.c
- src/libbson/tests/test-utf8.c
This ticket patches an issue in `bson_utf8_escape_for_json` that causes a crash for some invalid inputs. 
See [CDRIVER-5713](https://jira.mongodb.org/browse/CDRIVER-5713)
> CDRIVER-5713 fix bson_utf8_escape_for_json crash

- src/libmongoc/src/mongoc/mongoc-log.c
`pthread_threadid_np` is not present prior to 10.6 and it is also missing on `ppc` (including 10.6.8 Rosetta), because it is made x86-only in Apple libc.
This is the only issue to be fixed in order for the build to succeed.
> CDRIVER-5719 fix build for macOS without pthread_threadid_np

- CMakeLists.txt
- NEWS
- src/libmongoc/CMakeLists.txt
- src/libmongoc/src/mongoc/mongoc-stream-tls-libressl.h
- src/libmongoc/src/mongoc/mongoc-stream-tls.c
**Summary**
Deprecate the CMake configuration `ENABLE_SSL=LIBRESSL` and function `mongoc_stream_tls_libressl_new`.
Verified by this [patch build](https://spruce.mongodb.com/version/66df176a75c93d00079e20d3).
**Motivation**
Removal of `ENABLE_SSL=LIBRESSL` is proposed for [C driver 2.0](https://docs.google.com/document/d/121Oc5VQdHZ63PS62gDWozt8FbCKrK_MRe-iJUNmoCfM/edit)
> CDRIVER-5694 deprecate use of `ENABLE_SSL=LIBRESSL`

- CMakeLists.txt
- NEWS
Deprecates `ENABLE_SASL=CYRUS` on Windows and the Windows-only option `CYRUS_PLUGIN_PATH_PREFIX`.
See CDRIVER-5696 for rationale.
> CDRIVER-5696 deprecate `ENABLE_SASL=CYRUS` on Windows

- src/libmongoc/src/mongoc/mongoc-cmd.c
To silence Coverity warning of uninitialized variable. See issue with CID 118911.
I expect the reported issue is a false positive. The report notes a possible uninitialized read of [cmd->payloads[i]](https://github.com/mongodb/mongo-c-driver/blob/a2ecf927d6e2a8709621b2b6be7158ca3ce9a265/src/libmongoc/src/mongoc/mongoc-cluster.c#L3251).  `mongoc_cmd_parts_init` sets `cmd->payloads_count` to 0. All assignments of `cmd->payloads_count` appear to initialize the associated `cmd->payloads`. Regardless, this change zeros the payloads struct to silence the warning.
This is cherry-picked from the commit e45fd98b0884342881991d568ba291d8025b88a6. e45fd98b0884342881991d568ba291d8025b88a6 appears to have been unexpectedly committed to `r1.27` without being applied to `master`.
> CDRIVER-5727 zero `parts->assembled.payload`

- .evergreen/config_generator/components/sasl/winssl.py
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
- NEWS
Resolves CDRIVER-4479. Drop Evergreen tasks for VS 2013. Document dropping support.
This PR does not drop workarounds to support VS 2013 (e.g. https://github.com/mongodb/mongo-c-driver/commit/77bbfee6a927af39a8040f18a6a2c37624b5791c and https://github.com/mongodb/mongo-c-driver/pull/1229/commits/61a4a8d80c254791b190aafdcd39ffefe5229d53).
> CDRIVER-4479 drop VS 2013

- src/libmongoc/src/mongoc/mongoc-topology-description.c
- src/libmongoc/tests/test-mongoc-aggregate.c
Ignore unknown servers when checking to override read preferences for an aggregate-with-write.
Verified by this patch build: https://spruce.mongodb.com/version/66e0ad1ebdf6d3000745d0ba
See CDRIVER-5707.
> CDRIVER-5707 ignore unknown servers in aggregate-with-write check

- src/libmongoc/tests/json/crud/unified/aggregate-write-readPreference.json
- src/libmongoc/tests/json/crud/unified/db-aggregate-write-readPreference.json
This PR will sync two spec tests to match the changes made in https://github.com/mongodb/specifications/commit/30b3a75291794794152c377854df9fee1ccc6875.
See DRIVERS-2914. Server 8.0 requires aggregation tests with `$out` to not pre-create the output collection.
> CDRIVER-5579 sync $out aggregation spec tests

- src/libbson/doc/bson_string_append.rst
- src/libbson/doc/bson_string_append_c.rst
- src/libbson/doc/bson_string_append_printf.rst
- src/libbson/doc/bson_string_append_unichar.rst
- src/libbson/doc/bson_string_new.rst
- src/libbson/doc/bson_string_truncate.rst
- src/libbson/src/bson/bson-string.c
- src/libbson/tests/test-string.c
Fixes behavior of `bson_string_truncate` with large lengths. Verified with [this patch build](https://spruce.mongodb.com/version/66f186c226f05a00072fb0a4). See CDRIVER-5733 for details.
Also adds tests for behavior of `bson_string_truncate`. In the process of this fix, other unexpected behavior was observed: `bson_string_truncate` [documents](https://mongoc.org/libbson/1.28.0/bson_string_truncate.html) the truncated length "must be smaller or equal to the current length of the string.". However, `bson_string_truncate` does not reject greater lengths.
```c
bson_string_t *str = bson_string_new ("a");
bson_string_truncate (str, 2u); // Is not rejected.
ASSERT_CMPUINT32 (str->len, ==, 2u);
ASSERT_CMPUINT32 (str->alloc, ==, 4u);
bson_string_free (str, true);
```
This behavior is preserved (and …
> CDRIVER-5733 fix behavior of `bson_string_truncate`

- NEWS
- src/libbson/src/bson/bson.c
Deprecate defining `BSON_MEMCHECK` when building libbson. See CDRIVER-5715 for rationale.
When building with the C flag `-DBSON_MEMCHECK=1`, a warning is now produced:
```
/Users/kevin.albertson/code/tasks/mongo-c-driver-2.0/src/libbson/src/bson/bson.c:31:9: warning: Do not define BSON_MEMCHECK. BSON_MEMCHECK changes the data layout of bson_t. BSON_MEMCHECK is deprecated may be removed in a future major release [-W#pragma-messages]
31 | #pragma message( \
|         ^
1 warning generated.
```
> CDRIVER-5715 deprecate defining `BSON_MEMCHECK`

- src/libmongoc/tests/TestSuite.c
Minor follow-up to https://github.com/mongodb/mongo-c-driver/pull/1742 to address:
```
../../../src/libmongoc/tests/TestSuite.c: In function 'TestSuite_PrintJsonHeader':
../../../src/libmongoc/tests/TestSuite.c:862:13: error: format '%s' expects a matching 'char *' argument [-Werror=format=]
getenv_or ("MONGODB_API_VERSION", "null"));
^
```
> CDRIVER-5740 fix fprintf call

- .evergreen/scripts/run-tests.sh
- CONTRIBUTING.md
Followup to https://github.com/mongodb/mongo-c-driver/pull/1742 which missed removal of some references to `MONGOC_CHECK_IPV6`.
> CDRIVER-5740 Remove stray references to MONGOC_CHECK_IPV6

- src/libmongoc/src/mongoc/mongoc-cluster.c
- src/libmongoc/src/mongoc/mongoc-compression.c
Resolves CDRIVER-5735. Verified by [this patch](https://spruce.mongodb.com/version/66fda3bdea5e9d00077abc3e). See ticket for details.
> CDRIVER-5735 Improve validation of uncompressedSize for OP_COMPRESSED

- NEWS
- src/libmongoc/doc/mongoc_bulkwritereturn_t.rst
- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
- src/libmongoc/src/mongoc/mongoc-bulkwrite.h
- src/libmongoc/tests/json/crud/unified/client-bulkWrite-partialResults.json
Do not return `mongoc_bulkwriteresult_t` if no known successful writes.
Verified by this patch build: https://spruce.mongodb.com/version/66fd6c9083cb7e000745405a
The C driver models `BulkWriteException.partialResult` as a top-level field `res` within `mongoc_bulkwritereturn_t`.
The specification requires only setting `partialResult` if there were known successful writes:
> Drivers MUST NOT populate the `partialResult` field in `BulkWriteException` if no operations were successful.
This was missed in CDRIVER-4363. The C driver incorrectly always set `res` for acknowledged writes. This PR changes to conditionally set `res`.
The specification was updated in DRIVERS-2975 to fix the check. This PR includes the updated spec change and test.
> CDRIVER-5718 fix logic for returning bulk write result on error

- .evergreen/scripts/kms-divergence-check.sh
- src/kms-message/src/kms_kmip_request.c
- src/kms-message/src/kms_message/kms_response_parser.h
- src/kms-message/src/kms_response_parser.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1746 and https://github.com/mongodb/libmongocrypt/pull/888. Verified by [this patch](https://spruce.mongodb.com/version/6704369750c69f00078a9cb7).
Overlooked a required update to `LIBMONGOCRYPT_GITREF` to point to https://github.com/mongodb/libmongocrypt/commit/a650d171ed3b552446095817ae2c5c4f7cec43a2 which contains the kms-message sources with updated spec links. Synced the kms-message sources accordingly.
> CDRIVER-5742 Update ref to kms-message with spec link fixes

- src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.c
- src/libmongoc/tests/test-mongoc-ssl.c
Changes in [CDRIVER-4656](https://github.com/mongodb/mongo-c-driver/pull/1673) resulted in a regression. Failure to create an OpenSSL context resulted in an abort, rather than an expected failure.
This PR updates `mongoc_stream_tls_openssl_new_with_context` to return NULL if the passed context is NULL to signal failure.
The context is created in `mongoc_client_pool_set_ssl_opts` and `mongoc_client_set_ssl_opts`. Neither have a way to return an error.
> CDRIVER-5736 do not assert on failure to create OpenSSL context

- .evergreen/config_generator/generate.py
- .evergreen/config_generator/requirements.txt
- .evergreen/legacy_config_generator/evergreen_config_generator/__init__.py
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- poetry.lock
- pyproject.toml
- Python 3.12 removed the deprecated `pkg_resources` package:
```
ModuleNotFoundError: No module named 'pkg_resources'
```
We were only using it for `parse_version`, so it has been replaced with `package.version.Version` instead (changes to tasks.py).
- The `typing-extensions` package has compatibility issues with Python 3.12 prior to version 4.6.0:
```
TypeError: type 'typing.TypeVar' is not an acceptable base type
```
It has been upgraded alongside other dependencies of required packages with `poetry update` (changes to poetry.lock).
- The pydantic package makes breaking changes in version 2.0 which appears to be incompatible with the shrub-py package:
```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for EvgProject
```
Downgraded and pinned the pydantic package …
> Support Python 3.12 in EVG config scripts

- src/libmongoc/tests/test-mongoc-ssl.c
Follow-up to https://github.com/mongodb/mongo-c-driver/pull/1750 to fix failing Windows tasks.
The Windows hosts appear to have the expected CA file installed:
```
PS C:\Users\Administrator> Get-ChildItem -Recurse Cert:
(...)
Subject      : C=US, S=New York, L=New York City, O=MongoDB, OU=Drivers, CN=Drivers Testing CA
```
So no error is returned for the test.
Verified with this [patch build](https://spruce.mongodb.com/version/670586e5dac49200074a5795).
> CDRIVER-5736 do not assert

- .evergreen/config_generator/components/cse/openssl.py
- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/config_generator/etc/utils.py
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/legacy_config_generator/evergreen_config_generator/variants.py
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
[EVG Distro Guidelines](https://wiki.corp.mongodb.com/pages/viewpage.action?pageId=116563465) states:
> zseries and ppc (power8) hosts are very resource constrained [...] use a very long batch time on mainline commits, and avoid patch building on them.
Applies a batchtime of 1 day already used by the legacy config generator to new config generator components running tasks on Power8 and zSeries distros (overlooked by https://github.com/mongodb/mongo-c-driver/issues/1201). Additionally sets `patchable: false` to avoid their execution in patch builds.
> evg: set patchable and batchtime for Power8 and zSeries tasks

- .evergreen/config_generator/components/cse/openssl.py
- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/config_generator/etc/utils.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
Followup to https://github.com/mongodb/mongo-c-driver/pull/1761.
Evergreen validation errors initially thought to be [false-positives](https://jira.mongodb.org/browse/DEVPROD-11988) turns out to have been accurate: batchtime is [not yet supported](https://jira.mongodb.org/browse/DEVPROD-12032) in standalone task definitions.
Moves the `batchtime` field for Power8 and zSeries tasks to the build variant definition as required until DEVPROD-12032 is resolved. To avoid task definition conflict errors (due to multiple references to a task in a build variant), the convenient component tag in the build variant definition is replaced with an explicit, full list of task references.
> Move batchtime from task definitions to task refs

- src/libbson/src/bson/bson.c
- src/libbson/tests/test-bson.c
This fixes an edge case in `bson_validate_with_error_and_offset` that would cause unexpectedly uninitialized output parameters when a failure occurs at offset zero.
Includes the test case from CDRIVER-5754, now passing.
> CDRIVER-5754 always write output on error in bson_validate_with_error_and_offset

- .evergreen/config_generator/components/abi_compliance_check.py
- .evergreen/config_generator/components/c_std_compile.py
- .evergreen/config_generator/components/cse/openssl.py
- .evergreen/config_generator/components/earthly.py
- .evergreen/config_generator/components/loadbalanced.py
- .evergreen/config_generator/components/sanitizers/asan_cse.py
- .evergreen/config_generator/components/sanitizers/asan_sasl.py
- .evergreen/config_generator/components/sanitizers/tsan_sasl.py
- .evergreen/config_generator/components/sasl/nossl.py
- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/config_generator/components/scan_build.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/generated_configs/functions.yml
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
- .evergreen/scripts/abi-compliance-check-setup.sh
- .evergreen/scripts/abi-compliance-check.sh
- Earthfile
This PR removes unsupported Evergreen platforms and adds two new environments to build on in Earthly.
See [CDRIVER-4602](https://jira.mongodb.org/browse/CDRIVER-4602). Along with the two platforms explicitly mentioned in the ticket, other unsupported variants were also removed/upgraded from our CI according to [this](https://wiki.corp.mongodb.com/pages/viewpage.action?pageId=116563465) wiki page.
Ubuntu <= 18.04 and RHEL <= 7.2 were both removed from our CI pipeline in this PR. However, these are both platforms [supported](https://www.mongodb.com/docs/languages/c/c-driver/current/libmongoc/ref/platforms/) by the C driver, so it was necessary to continue to check that the driver can be built successfully. To achieve this, Earthly was used to spawn the older versions of these OSes (CentOS …
> CDRIVER-4602 switch to supported build hosts

- src/libbson/src/bson/bson-atomic.h
- src/libbson/src/bson/bson-compat.h
Previously, change 71475dfc58d0a35fe9e3a4941a2c997a50eab4ef redefined bson_sync_synchronize in terms of __sync_synchronize, avoiding obsolete conditionals and inline asm. This change fails on the "public-header-warnings" build target when CC=clang, because all warnings are enabled including -Watomic-implicit-seq-cst.
This change uses bson_atomic_thread_fence instead, which is both the simpler solution and it already includes an exception for the compiler warning. The previous patch was written in an attempt to avoid moving the public bson_sync_synchronize entry point from bson-compat to bson-atomic, but now I know the BSON_INSIDE include guard makes this distinction unnecessary.
> CDRIVER-4220 redefine bson_sync_synchronize using bson_atomic_thread_fence

- .evergreen/generated_configs/variants.yml
Followup to https://github.com/mongodb/mongo-c-driver/pull/1760. Addresses the warnings observed in EVG build pages:
Regenerates build variants config YAML file, which appears to have only been partially updated in https://github.com/mongodb/mongo-c-driver/pull/1760.
> CDRIVER-4602 regenerate build variants config

- src/libbson/src/bson/bson.c
- src/libbson/tests/json/bson_corpus/datetime.json
Fix encoding of date after year 9999 to agree with the Extended JSON specification.
Verified with [this patch build](https://spruce.mongodb.com/version/67117b1eb138970007cc034b).
The extended JSON spec notes:
> | **BSON 1.1 Type or Convention**                                                            | **Canonical Extended JSON Format**                                                                                                                                                                                                                                                                                                                                                                                         | **Relaxed Extended JSON Format** …
> CDRIVER-5759 fix relaxed encoding of date after year 9999

- build/cmake/MongoC-Warnings.cmake
This fixes the CentOS 7 build on Earthly that uses Clang 3.4.2.
We still require at least clang 3.1, due to "format-non-iso".
"format-pedantic" was added in 3.7, but since the sequence of compatibility tests here uses major versions only I'm testing against version 4.0.
CentOS 7 normally does not ship with clang (the test gets clang from EPEL).
It also normally has a cmake too old to build mongo-c-driver; our CI builds bring their own cmake.
> CDRIVER-4602 build fix for clang >= 3.1 and < 3.7

- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
- src/libmongoc/tests/json/command-logging-and-monitoring/monitoring/unacknowledged-client-bulkWrite.json
- src/libmongoc/tests/json/crud/unified/client-bulkWrite-errors.json
- src/libmongoc/tests/test-mongoc-bulkwrite.c
- src/libmongoc/tests/test-mongoc-crud.c
- src/libmongoc/tests/unified/runner.c
- Return error if a bulk write is requested with ordered writes or verbose results.
- Implement CRUD prose test 15.
Verified with this [patch build](https://spruce.mongodb.com/version/67042ec092a2b700075f8688)
See DRIVERS-2993.
> CDRIVER-5741 ban `w:0` with verbose or ordered `bulkWrite`

- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
Follow-up to https://github.com/mongodb/mongo-c-driver/pull/1752. Changes were not rebased on https://github.com/mongodb/mongo-c-driver/pull/1749 and resulted in duplicate declaration of `is_ordered`.
> CDRIVER-5741 remove duplicate declaration

- NEWS
- src/libmongoc/CMakeLists.txt
- src/libmongoc/doc/mongoc_client_command.rst
- src/libmongoc/doc/mongoc_collection_command.rst
- src/libmongoc/doc/mongoc_database_command.rst
- src/libmongoc/examples/basic_aggregation/map-reduce-advanced.c
- src/libmongoc/examples/migrating.c
- src/libmongoc/src/mongoc/mongoc-client.h
- src/libmongoc/src/mongoc/mongoc-collection.h
- src/libmongoc/src/mongoc/mongoc-database.h
Deprecate `mongoc_<obj>_command`.
Document migrating to corresponding `mongoc_<obj>_command_simple`.
Verified by [this patch build](https://spruce.mongodb.com/version/671951525bedf30007bc2545).
See CDRIVER-5708 for motivation for deprecating.
Previous documentation [noted]((https://mongoc.org/libmongoc/1.28.0/mongoc_client_command.html)) the `mongoc_<obj>_command` functions were "superseded" by `mongoc_<obj>_command_with_opts`, `mongoc_<obj>_read_command_with_opts`, `mongoc_<obj>_write_command_with_opts`, and `mongoc_client_read_write_<obj>_with_opts`.
Documentation has been updated to recommend migrating to `mongoc_<obj>_command_simple` for simplicity. Though the underlying call to `_mongoc_cursor_run_command` [indicates a read command](https://github.com/mongodb/mongo-c-driver/blob/9e42a …
> CDRIVER-5708 deprecate `mongoc_<obj>_command`

- src/libmongoc/doc/mongoc_collection_delete.rst
- src/libmongoc/doc/mongoc_collection_insert.rst
- src/libmongoc/doc/mongoc_collection_remove.rst
- src/libmongoc/doc/mongoc_collection_update.rst
- src/libmongoc/examples/example-update.c
- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/tests/test-mongoc-collection.c
This PR intends to resolve CDRIVER-3054 with documentation, rather than deprecation.
- Remove "superseded by" in docs of `mongoc_collection_(remove|insert|update)`
- Document `mongoc_collection_remove` as an alternative to `mongoc_collection_delete`.
- Document and test `mongoc_collection_update` accepts a replacement document.
- Add missing `mongoc_init` and `mongoc_cleanup` to `example-update.c`.
Verified by [this patch build](https://spruce.mongodb.com/version/6728d2a45a7cbe000758099d).
CDRIVER-3054 originally proposed deprecating `mongoc_collection_(remove|insert|update)`. Choosing not to deprecate was motivated by a non-trivial migration to the alternatives. Migrating calls with a write concern requires creating a new options BSON. Example:
Before:
```c
return …
```
> CDRIVER-3054 Revise docs from `mongoc_collection_(remove|insert|update)`

- src/libmongoc/doc/mongoc_collection_get_last_error.rst
- src/libmongoc/tests/test-mongoc-collection.c
Fix documentation and add tests for `mongoc_collection_get_last_error`.
This PR is related to, but does not resolve CDRIVER-3054.
Verified by this [patch build](https://spruce.mongodb.com/version/6724e5487840f40007eec0d0).
`mongoc_collection_get_last_error` may be used to obtain results from `mongoc_collection_(remove|insert|update)`. 
`mongoc_collection_get_last_error` has been marked deprecated with `BSON_GNUC_DEPRECATED` since 1.9.0 (CDRIVER-2243) but public docs were not updated.
> CDRIVER-3054 fix docs and test `mongoc_collection_get_last_error`

- src/libmongoc/doc/conf.py
- src/libmongoc/doc/mongoc_client_pool_set_ssl_opts.rst
- src/libmongoc/doc/mongoc_client_set_ssl_opts.rst
- src/libmongoc/doc/mongoc_ssl_opt_get_default.rst
- src/libmongoc/doc/mongoc_ssl_opt_t.rst
Document "ssl" APIs use TLS protocols
CDRIVER-3436 originally proposed deprecating `mongoc_ssl_opt_t`. This PR does not deprecate to avoid unnecessary extra migration effort for users.
The motivation for deprecating `mongoc_ssl_opt_t` refers to the MongoDB URI options [preferring "tls" over "ssl" as a prefix](https://github.com/mongodb/specifications/blob/fc7996db26d0ea92091a5034c6acb287ef7282fe/source/uri-options/uri-options.md#why-use-tls-as-the-prefix-instead-of-ssl-for-related-options).
Deprecating "ssl" termed API was done on [this branch](https://github.com/mongodb/mongo-c-driver/compare/master...kevinAlbs:mongo-c-driver:deprecate-ssl.C3436?expand=1) but was abandoned. Though the migration is simple (find+replace), I think it is an unnecessary effort for users with little value …
> CDRIVER-3436 Document "ssl" APIs use TLS protocols

- .evergreen/config_generator/components/earthly.py
- .evergreen/generated_configs/tasks.yml
- Earthfile
- tools/earthly.sh
Verified by [this patch](https://spruce.mongodb.com/version/673b77880014770007fff149).
Appends a `docker login` command prior to Earthly/Docker commands and uses the custom Earthly buildkit image in `tools/earthly.sh` as done in https://github.com/mongodb/libmongocrypt/pull/911.
The Ubuntu 20.04 distro is dropped from the list due to the following obtuse error:
```
Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`
```
> Use Artifactory to obtain Docker images

- docs/dev/releasing.rst
Applies similar changes from https://github.com/mongodb/mongo-cxx-driver/pull/1282: Add release process step to update the GitHub Webhook.
**Background**
Updating the `debian/unstable` branch may result in Jira ticket comments for commits added to the branch ([example](https://jira.mongodb.org/browse/CDRIVER-4618?focusedCommentId=6703357&focusedId=6703357&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6703357)). I expect this is not helpful, and results in unnecessary emails.
The [webhook](https://github.com/mongodb/mongo-c-driver/settings/hooks) is now updated to limit updates to `master` and `r1.29`:
```
https://githook.mongodb.com?branches=master..r1.29
```
Consequently, the webhook must be updated when new release branches are created.
> add release instruction to update webhook

- .evergreen/config_generator/components/scan_build.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/scripts/compile-scan-build.sh
Followup to https://github.com/mongodb/mongo-c-driver/pull/1791. Moves the MacOS scan-build task from `macos-14` to `macos-14-arm64` per distro recommendations following resolution of [DEVPROD-12817](https://jira.mongodb.org/browse/DEVPROD-12817).
> Move scan-build task from macos-14 to macos-14-arm64

- src/libmongoc/tests/json/retryable_writes/unified/aggregate-out-merge.json
- src/libmongoc/tests/json/retryable_writes/unified/bulkWrite.json
- src/libmongoc/tests/json/retryable_writes/unified/client-bulkWrite-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/unified/deleteMany.json
- src/libmongoc/tests/json/retryable_writes/unified/deleteOne.json
- src/libmongoc/tests/json/retryable_writes/unified/findOneAndDelete.json
- src/libmongoc/tests/json/retryable_writes/unified/findOneAndReplace.json
- src/libmongoc/tests/json/retryable_writes/unified/findOneAndUpdate.json
- src/libmongoc/tests/json/retryable_writes/unified/insertMany.json
- src/libmongoc/tests/json/retryable_writes/unified/insertOne.json
- src/libmongoc/tests/json/retryable_writes/unified/replaceOne.json
- src/libmongoc/tests/json/retryable_writes/unified/unacknowledged-write-concern.json
- src/libmongoc/tests/json/retryable_writes/unified/updateMany.json
- src/libmongoc/tests/json/retryable_writes/unified/updateOne.json
- src/libmongoc/tests/unified/runner.c
Resolves CDRIVER-5770. Adds new retryable writes spec tests. Includes fixes to the unified test runner needed to pass tests.
DRIVERS-943 converts "Command Construction" tests into unified spec tests. The original "Command Construction" tests added in SPEC-969 were not implemented in the C driver.
Fixes an observed [test failure](https://spruce.mongodb.com/version/67290841e49f09000715b984):
```
test file: snapshot-sessions
Result mismatch:
Expected:  [ { "_id" : { "$numberInt" : "1" }, "x" : { "$numberInt" : "11" } } ]
Actual:    [  ]
```
This matches [spec recommendation](https://github.com/mongodb/specifications/blob/f321471ecfc08680a10b8ca29bc826ecb1da5e3b/source/unified-test-format/unified-test-format.md#executing-a-test):
> If the topology is sharded, the test runner SHOULD use a …
> CDRIVER-5770 Convert retryable write command construction prose tests to spec tests

- src/libmongoc/doc/mongoc_auto_encryption_opts_set_key_expiration.rst
- src/libmongoc/doc/mongoc_client_encryption_opts_set_key_expiration.rst
- src/libmongoc/tests/json/client_side_encryption/legacy/keyCache.json
- src/libmongoc/tests/json/client_side_encryption/unified/keyCache.json
Follow-up to https://github.com/mongodb/mongo-c-driver/pull/1779:
- Increase the `wait` time to fix DEK cache tests on Windows.
- Document expiration time of 0 means "never expire".
Verified with this [patch build](https://spruce.mongodb.com/version/675066dec4dc3c0006a3e9b3).
Tests failures were observed on Windows ([example](https://spruce.mongodb.com/task/mongo_c_driver_cse_matrix_winssl_cse_sasl_cyrus_winssl_windows_2019_vs2017_x64_test_latest_server_auth_8eba3f6f52bff67389124eef36fe120dc6fef15f_24_12_03_21_36_43/logs?execution=0)):
```
running test: decrypt, wait, and decrypt again
[...]
error: expected: 2 events but got 1
```
The test configures a 1ms expiration time. The failure suggests the DEK was not considered expired after the 2ms wait. This appears to be due to the coarse …
> CDRIVER-5644 increase `wait` time

- src/libmongoc/src/mongoc/mongoc-bulk-operation.c
- src/libmongoc/tests/test-mongoc-bulk.c
https://jira.mongodb.org/browse/CDRIVER-5819
> CDRIVER-5819 always assign operation_id when bulk client changes

- src/common/src/common-atomic-private.h
- src/libbson/src/bson/bson-atomic.h
- src/libbson/src/bson/bson-compat.h
https://github.com/mongodb/mongo-c-driver/pull/1096 added a conditional `#define BSON_IF_MSVC(...)` to `bson-atomic.h` without later undefining.
This PR assumes the `#define BSON_IF_MSVC(...)` was motivated by `BSON_IF_MSVC` not being defined on xlC.
`BSON_IF_MSVC` is conditionally defined in [in bson-compat.h](https://github.com/mongodb/mongo-c-driver/blob/4ccd9db9c48be5755af83d7a62b61bd141cc9644/src/libbson/src/bson/bson-compat.h#L182-L192). xlC (not xlclang) appears [not to define `__clang__`, `__GNUC__`, or `_MSC_VER`](https://www.ibm.com/docs/en/xl-c-and-cpp-aix/16.1?topic=macros-identify-xl-cc-compiler). I expect this caused `BSON_IF_MSVC` to not be defined.
This PR changes bson-compat.h to define `BSON_IF_MSVC` (and `BSON_IF_GNU_LIKE`) to be empty on unsupported compilers. Though …
> CDRIVER-5813 remove misplaced define `BSON_IF_MSVC`

- .evergreen/scripts/run-tests.sh
When investigating a reported Windows crash unloading crypt shared ([JAVA-5648](https://jira.mongodb.org/browse/JAVA-5648)), I rediscovered that testing with the crypt shared library was skipped on Windows. The skip was added in https://github.com/mongodb/mongo-c-driver/pull/968. I am not sure what motivated the skip. Removing the skips appears to pass. The logs of the [patch build](https://spruce.mongodb.com/version/6733524718af6a0007318507/) include:
```
crypt_shared library will be loaded with cryptSharedLibPath: [C:/data/mci/5c60da88b4d482d9f4943604b2d9b92a/mongoc/mongo_crypt_v1.dll]
```
> Remove skip for loading crypt_shared on Windows

- src/libbson/src/bson/bson-error.c
- src/libbson/tests/test-bson-error.c
Follow-up to https://github.com/mongodb/mongo-c-driver/pull/1370/files. On macOS `bson_strerror_r` always returned NULL and set the output buffer to "Unknown error message". This PR adds a missing `ret = buf;` assignment to fix.
Verified with [this patch build](https://spruce.mongodb.com/version/675320d2c9816e0007e9dca3).
> CDRIVER-5826 Fix result of `bson_strerror_r` on macOS

- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
- src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
https://jira.mongodb.org/browse/CDRIVER-5824
@kevinAlbs: This dates back to the initial release in 1.28.0, but I'm not sure whether it warrants a patch release. I figured it easier to fix in master and then you can backport as desired.
> CDRIVER-5824 remove EXPORT macros from source files

- src/libmongoc/doc/mongoc_bulkwrite_new.rst
- src/libmongoc/doc/mongoc_bulkwrite_set_client.rst
- src/libmongoc/doc/mongoc_bulkwrite_t.rst
- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
- src/libmongoc/src/mongoc/mongoc-bulkwrite.h
- src/libmongoc/tests/test-mongoc-bulkwrite.c
https://jira.mongodb.org/browse/CDRIVER-5816
https://jira.mongodb.org/browse/CDRIVER-5817
Using this to POC the PHPC implementation in [PHPC-2478](https://jira.mongodb.org/browse/PHPC-2478), so there is no rush to review/merge.
> CDRIVER-5816: mongoc_bulkwrite_new and mongoc_bulkwrite_set_client

- build/cmake/TestFixtures.cmake
While building mongo-c-driver 1.29.0 on Arch Linux on TH1520, the test `mongoc/fixtures/fake_imds/start` fails.
TH1520 is a low performance chip. The 0.2s waiting time in proc-ctl.py to wait for spawn is not enough: https://github.com/mongodb/mongo-c-driver/blob/028b987d77c92d879cd844c2fb7b20e09ab1d66f/build/cmake/TestFixtures.cmake#L44
Increase it to 1s make the build to success.
Reported-by: https://archriscv.felixc.at/.status/log.htm?url=logs/mongo-c-driver/mongo-c-driver-1.29.0-1.log
Link: https://github.com/felixonmars/archriscv-packages/pull/4329
> CDRIVER-5829 Increase spawn wait time in TestFixtures

- .evergreen/scripts/kms-divergence-check.sh
- src/kms-message/src/kms_message.c
- src/kms-message/src/kms_message_private.h
set_error is an awful generic name for a global function.
Sadly this easily conflicts with other libraries if you statically link this into an application.
please have us rename set_error to kms_set_error to avoid link errors with libraries/applications that also have set_error as function.
> CDRIVER-5835 Rename `set_error` to `kms_set_error`

- src/libmongoc/src/mongoc/mongoc-server-description.c
In `mongoc_cluster_check_interval` function the `bson_error_t error;` is constructed on the stack, its error message is **not** zero initialised https://github.com/mongodb/mongo-c-driver/blob/db54ccf2fe10f6577cf17feae46f9448cd21f3a4/src/libmongoc/src/mongoc/mongoc-cluster.c#L2771. In case of an error in `mongoc_cluster_run_command_parts` function, a short error message is written to `error`, leaving some of the bytes uninitialized. That `error` is then passed to `mongoc_topology_description_invalidate_server` https://github.com/mongodb/mongo-c-driver/blob/db54ccf2fe10f6577cf17feae46f9448cd21f3a4/src/libmongoc/src/mongoc/mongoc-cluster.c#L2840 , which in turn copies the whole error message buffer into `sd` in `mongoc_server_description_handle_hello` …
> CDRIVER-5834 Do not compare uninitialized bytes in _mongoc_server_description_equal

- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
Follow-up to https://github.com/mongodb/mongo-c-driver/pull/1590. Removes an unnecessary include of `mongoc-error-private.h`.
> CDRIVER-5840 remove unnecessary include

- src/libmongoc/src/mongoc/mongoc-secure-transport.c
Fixes a build error observed after upgrading from macOS 12 to macOS 13.7.2:
```
mongoc-secure-transport.c:335:81: error: format specifies type 'int' but the argument has type 'SecExternalItemType' (aka 'unsigned int') [-Werror,-Wformat]
335 |       MONGOC_ERROR ("Cannot work with keys of type \"%d\". Please file a JIRA", type);
|                                                      ~~                         ^~~~
|                                                      %u
```
`SecExternalItemType` is [represented as `uint32_t`](https://github.com/apple-oss-distributions/Security/blob/3dab46a11f45f2ffdbd70e2127cc5a8ce4a1f222/keychain/headers/SecImportExport.h#L98). I expect the error is triggered by a local upgrade to clang.
Added improvements:
- A string representation of the enum value is …
> CDRIVER-5844 fix macOS format specifier

- NEWS
- docs/dev/releasing.rst
- src/libbson/NEWS
- update NEWS for 1.29.2
- fix release docs rendering of "Create a New Clone [...]" to prevent rendering as a sub-step.
- fix release docs checklist ordering.
> update NEWS for 1.29.2

- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
Follow-up to https://github.com/mongodb/mongo-c-driver/pull/1590. Add a missing return failure to parse `writeConcernError.errInfo` in a `bulkWrite` reply. Fixes a possible ignored error.
> CDRIVER-5841 add missing return on failure to parse `errInfo`

- src/libmongoc/src/mongoc/mongoc-init.c
- src/libmongoc/src/mongoc/utlist.h
This fixes two complication errors:
```
clang -arch arm64 -DNDEBUG -I. -Icommon -Ikms -Iutf8proc -DBSON_COMPILATION -DBSON_EXTRA_ALIGN -DMONGOC_COMPILATION -DMONGOC_HAVE_SASL_CLIENT_DONE -DMONGOC_ENABLE_SSL_SECURE_TRANSPORT -DMONGOC_ENABLE_CRYPTO_COMMON_CRYPTO -DKMS_MESSAGE_ENABLE_CRYPTO -DKMS_MESSAGE_ENABLE_CRYPTO_COMMON_CRYPTO -D_DARWIN_C_SOURCE  -I/opt/R/arm64/include   -mmacosx-version-min=10.8 -fPIC  -falign-functions=64 -Wall -g -O2  -c mongoc/mongoc-cluster.c -o mongoc/mongoc-cluster.o
In file included from mongoc/mongoc-cluster.c:55:
mongoc/utlist.h:20:10: error: 'mongoc-prelude.h' file not found with <angled> include; use "quotes" instead
20 | #include <mongoc-prelude.h>
|          ^~~~~~~~~~~~~~~~~~
|          "mongoc-prelude.h"
1 error generated.
```
and 
```
clang -arch arm64 …
```
> CDRIVER-5866 Fix 2 includes

- .evergreen/config_generator/components/cse/openssl.py
- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
- NEWS
- src/libbson/NEWS
Addresses task failures on Evergreen due to the following error thrown by DET's mongodl.py script on Debian 9.2 distros:
```
ValueError: No download was found for version="latest" target="debian92" arch="x86_64" edition="enterprise" component="crypt_shared"
```
Debian 9 is EOL and should probably have been removed from the EVG matrix as part of CDRIVER-4602.
All removed tasks either already have a Debian 10 or Debian 11 equivalent, or were extended accordingly (i.e. Clang coverage), with the sole exception of the `clang38` build variant which ran the `release-compile`, `debug-compile-nosasl-nossl`, and `test-latest-server-*` tasks (there are no equivalent for Clang on Debian 10+, only GCC equivalents).
> CDRIVER-5873 reduce Debian 9 task coverage to compile-only

- NEWS
Minor follow-up to https://github.com/mongodb/mongo-c-driver/pull/1839.
Relocate deprecation notice to upcoming 1.30.0 release.
> fix NEWS entry

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
Followup to https://github.com/mongodb/mongo-c-driver/pull/1839 which failed to correctly remove Debian 9 tasks from the legacy config despite claiming "tasks in the legacy config remain removed" as the intended changes were inadvertently reverted [by a mistaken rebase](https://github.com/mongodb/mongo-c-driver/compare/99fd5105eea4487e2f1fab2cb5c37ba795dad333..468b6066ac5d67a89bc3e40998a174d377b11b8f).
> CDRIVER-5873 remove Debian 9 tasks from legacy config

- src/libmongoc/src/mongoc/mongoc-bulkwrite.c
- src/libmongoc/tests/test-mongoc-bulkwrite.c
Uses integral offsets, rather than a `bson_iter_t`, to refer to "_id" fields in the `bulkWrite` payload.
Verified with this patch build: https://spruce.mongodb.com/version/6798e244aed6b800073ef361
See CDRIVER-5869 for background.
> CDRIVER-5869 fix bulk write crash with verbose results

- .evergreen/scripts/install-ssl.sh
- .evergreen/scripts/run-auth-tests.sh
Resolves CDRIVER-5645. Verified by [this patch](https://spruce.mongodb.com/version/679cfab28738040007b3b867/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
---
The `build-and-run-authentication-tests-openssl-1.0.1-fips` task has been failing since around [2024-09-30](https://spruce.mongodb.com/task/mongo_c_driver_openssl_build_and_run_authentication_tests_openssl_1.0.1_fips_c5c960a98a8e2d81a3ec9e6f92b4c8b576ba8b10_24_09_24_14_39_27/logs?execution=0). This is presumably due to the old link that was being used to download the OpenSSL FIPS module (at `https://www.openssl.org/source/*`) no longer being supported. The [OpenSSL Downloads page](https://openssl-library.org/source/old/index.html) redirects users to the [/source/old](https://openssl-library.org/source/old/index.html) downlaod …
> CDRIVER-5645 fix and update build-and-run-authentication-tests-* tasks

- src/libmongoc/src/mongoc/mongoc-server-description.c
- src/libmongoc/tests/test-mongoc-server-description.c
This PR is intended to improve performance of `mongoc_server_description_new_copy`. Rather than re-parse the BSON document of the `hello` reply each time, fields are copied over individually. Internal references into the BSON document are copied by calculating the offset into the BSON document.
Atomic modification to `round_trip_time_msec` is removed. `round_trip_time_msec` appears to only be modified with exclusive access to the `mongoc_server_description_t` (when applying [in mongoc_server_description_handle_hello](https://github.com/mongodb/mongo-c-driver/blob/69d04ae70cca48f2035f6b40ae3347057edd43e4/src/libmongoc/src/mongoc/mongoc-server-description.c#L741), or [modifying the topology description](https://github.com/mongodb/mongo-c-driver/blob/69d04ae70cca48f2035f6b40ae3347057edd43e4/s …
> CDRIVER-5864 Do not parse BSON in `mongoc_server_description_new_copy`

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
The usual: https://spruce.mongodb.com/version/67a4f7d4cf2da900075c7d83/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file from downstream (r1.30)

- .evergreen/scripts/compile-libmongocrypt.sh
- .evergreen/scripts/compile-std.sh
- .evergreen/scripts/compile-windows.sh
- .evergreen/scripts/link-sample-program.sh
Attempt to improve support for building with ccache on Windows distros.
CMake uses `/Zi` in `CMAKE_<LANG>_FLAGS_DEBUG` by default. Unfortunately, ccache [does not support](/ccache/ccache/issues/1040) `/Zi`. This means building C projects with CMake and Visual Studio is incompatible with ccache by default when using debug configurations.
CMake 3.25 introduces [CMP0141](https://cmake.org/cmake/help/v3.25/policy/CMP0141.html) which moves the `/Zi` flag out of `CMAKE_<LANG>_FLAGS_DEBUG` into a new, dedicated [`MSVC_DEBUG_INFORMATION_FORMAT`](https://cmake.org/cmake/help/v3.25/prop_tgt/MSVC_DEBUG_INFORMATION_FORMAT.html) target property instead. This property is initialized by the new [`CMAKE_MSVC_DEBUG_INFORMATION_FORMAT`](https://cmake.org/cmake/help/v3.25/variable/CMAKE_MSVC_DEBUG_INFORMATIO …
> ccache: support MSVC by using /Z7 via MSVC_DEBUG_INFORMATION_FORMAT

- .evergreen/scripts/run-ocsp-cache-test.sh
Resolve OCSP task failures due to the following error caused by https://github.com/mongodb/mongo-c-driver/pull/1710:
```
.evergreen/scripts/run-ocsp-cache-test.sh: line 71: [...]/mongoc/src/libmongoc/test-mongoc-cache: No such file or directory
```
> Fix path to test-mongoc-cache under cmake-build

- src/libbson/doc/bson_writer_t.rst
1. `i` is not defined in the example program.
2. Invalid usage of pointers will lead to segmentation fault.
> Fix example code for `bson_writer_t` in docs

- src/libbson/src/bson/bson-decimal128.c
`first_digit` is already cleared out on line 601.
> CDRIVER-5897 Remove duplicated variable assignment in bson-decimal128.c

- src/libbson/doc/bson_value_copy.rst
`dst` should be uninitialized to prevent memory leak.
> Add description for `dst` parameter of `bson_value_copy`

- etc/cyclonedx.sbom.json
- etc/purls.txt
Resolves CDRIVER-5898 for the master branch. Similar changes to https://github.com/mongodb/libmongocrypt/pull/960, but applied to the C Driver.
> CDRIVER-5898 Regenerate SBOM Lite for silkbomb:2.0 forward compatibility

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
note: back out gcc-15 patch, since it wouldn't apply in any event
Evergreen patch build: https://spruce.mongodb.com/task/mongo_c_driver_packaging_rpm_package_build_patch_8422cadd2e9e7734503fa0e675417eea872c4a71_67b51309b6c0f70007349303_25_02_18_23_09_03/logs?execution=0
> sync RPM spec w/ upstream

- src/libmongoc/tests/json/load_balancers/non-lb-connection-establishment.json
Sync `non-lb-connection-establishment` test to https://github.com/mongodb/specifications/commit/d05c33e0a6124ee7d1a9de665084d540b2ff06c5
Verified with [this patch build](https://spruce.mongodb.com/version/67b4ad051cd3dc00077ea2ab/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (macOS failure is separately related to SERVER-101020)
This is intended to proactively avoid tests failure once drivers start testing 8.1 builds.
> CDRIVER-5900 sync `non-lb-connection-establishment`

- etc/cyclonedx.sbom.json
First post-release update of the SBOM Lite following https://github.com/mongodb/mongo-c-driver/pull/1882. Executed the new Earthly `+sbom-generate-new-serial-number` target to generate a new SBOM serial number for the next release version (1.30.2). (The SBOM serial number for 1.30.1 was generated by https://github.com/mongodb/mongo-c-driver/pull/1876.)
> Generate a new SBOM serial number for 1.30.2

- src/libmongoc/src/mongoc/mongoc-secure-channel.c
Fixes an error with gcc in c23 mode:
```
gcc  -DNDEBUG -I. -Icommon -Ikms -Iutf8proc -DBSON_COMPILATION -DMONGOC_COMPILATION -DMONGOC_ENABLE_SSL_SECURE_CHANNEL -DMONGOC_ENABLE_CRYPTO_CNG -DKMS_MESSAGE_ENABLE_CRYPTO -DKMS_MESSAGE_ENABLE_CRYPTO_CNG -DMONGOC_HAVE_SASL_CLIENT_DONE -D__USE_MINGW_ANSI_STDIO -DKMS_MESSAGE_LITTLE_ENDIAN -DUTF8PROC_STATIC -DMONGOC_HAVE_BCRYPT_PBKDF2    -I"C:/rtools44/x86_64-w64-mingw32.static.posix/include"      -O2 -Wall -std=gnu2x  -mfpmath=sse -msse2 -mstackrealign   -c mongoc/mongoc-secure-channel.c -o mongoc/mongoc-secure-channel.o
mongoc/mongoc-secure-channel.c: In function 'mongoc_secure_channel_setup_certificate_from_file':
mongoc/mongoc-secure-channel.c:67:14: error: incompatible types when returning type '_Bool' but 'PCCERT_CONTEXT' {aka 'const …
```
> CDRIVER-5913 Fix Windows compilation under C23

- src/libmongoc/examples/client-side-encryption-helpers.c
- src/libmongoc/tests/test-mongoc-topology.c
Related to CDRIVER-5891 (C23 forward compatibility). Similar issues and fixes as in https://github.com/mongodb/mongo-c-driver/pull/1886.
> CDRIVER-5891 Address implicit bool-to-null conversion in return statements

- src/libbson/src/jsonsl/jsonsl.c
- src/libbson/src/jsonsl/jsonsl.h
Fixes a reported error when building with `-fsanitize=bounds-strict`.
`jsonsl_st::stack` appears to be treated as a flexible array member, but is declared with size 1. This PR removes the size declaration and updates the allocation.
> CDRIVER-5912 fix `bounds-strict` sanitizer

- .evergreen/scripts/compile-libmongocrypt.sh
- CONTRIBUTING.md
- src/libmongoc/src/mongoc/mongoc-crypt.c
- src/libmongoc/tests/client_side_encryption_prose/lookup/key-doc.json
- src/libmongoc/tests/client_side_encryption_prose/lookup/schema-csfle.json
- src/libmongoc/tests/client_side_encryption_prose/lookup/schema-csfle2.json
- src/libmongoc/tests/client_side_encryption_prose/lookup/schema-qe.json
- src/libmongoc/tests/client_side_encryption_prose/lookup/schema-qe2.json
- src/libmongoc/tests/json-test.c
- src/libmongoc/tests/test-conveniences.h
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-libmongoc.h
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
- Update protocol to `libmongocrypt` to support `$lookup`
- Pass all `listCollections` results to libmongocrypt.
- Opt-in to supporting multi-collection commands by calling `mongocrypt_setopt_enable_multiple_collinfo`.
- Implement prose tests from DRIVERS-3082.
Verified by this patch build: https://spruce.mongodb.com/version/67b7337b99718b000730e99c
- Print the version of the server in `integration-tests.sh`. This was helpful to verify that the `latest` server version was the expected 8.1 "latest build" version. https://github.com/mongodb-labs/drivers-evergreen-tools/pull/607 fixed the download version of `latest`.
- Fix description of mock KMS server set-up in CONTRIBUTING.md.
- Abort in `get_bson_from_json_file` on failure (rather than return NULL) to surface error sooner.
> CDRIVER-5861 support `$lookup` in CSFLE and QE

- .evergreen/config_generator/components/c_std_compile.py
- .evergreen/config_generator/components/openssl_static_compile.py
- .evergreen/config_generator/components/scan_build.py
- .evergreen/config_generator/etc/compile.py
- .evergreen/config_generator/etc/cse/test.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/config_generator/etc/sanitizers/test.py
- .evergreen/config_generator/etc/sasl/test.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/scripts/compile-openssl-static.sh
- .evergreen/scripts/compile-std.sh
- .evergreen/scripts/compile-unix.sh
- .evergreen/scripts/compile-windows.sh
- .evergreen/scripts/link-sample-program-msvc-bson.cmd
- .evergreen/scripts/link-sample-program-msvc.cmd
- src/CMakeLists.txt
- src/common/src/bson-dsl.md
- src/common/src/common-bson-dsl-private.h
- src/libbson/tests/test-bson.c
- src/libmongoc/src/mongoc/mongoc-aggregate.c
- src/libmongoc/src/mongoc/mongoc-uri.c
Resolves CDRIVER-5891.
Extends `std-matrix` Evergreen tasks to support compilation with C99 through C23 using GCC, Clang, and MSVC.
To facilitate the expansion of compilation coverage to newer versions of Visual Studio, compile scripts (beyond `std-matrix` tasks) are updated to utilize the CMake `CMAKE_GENERATOR` and `CMAKE_GENERATOR_PLATFORM` environment variables to specify the Visual Studio version and target architecture (equivalent to `-G` + `-A`; similar changes to https://github.com/mongodb/mongo-cxx-driver/pull/1082). The definition of `CC` and `CXX` variables are also moved into the config generator to ensure copmiler consistency (no need for `if [[ "$CC" == "gcc" ]]`-esque logic in scripts), including specific compiler version requests (e.g. `clang-12`). The list of distros in …
> CDRIVER-5891 extend C standard coverage up to C23

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/67c2338323a40400075ec53d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Note that the task fails because the `master` branch requires the latest (not yet packaged) libmongocrypt. It will eventually turn green once the new libmongocrypt packages land.
> sync RPM spec from downstream

- src/libmongoc/tests/json/load_balancers/non-lb-connection-establishment.json
This reverts commit e5bc5a84bdfa511fdaa38ad4df3513dea57ab880.
The fix of [SERVER-101078](https://jira.mongodb.org/browse/SERVER-101078) enables this test to be run on latest servers again.
> CDRIVER-5919 Revert skip to `non-lb-connection-establishment`

- .evergreen/config_generator/components/earthly.py
- .evergreen/generated_configs/tasks.yml
A recent change in task definitions caused the `sasl=off` tasks to be fully excluded from the Earthly task matrix. This was also caught by pylance/pyright in the `earthly.py` file when it detects unreachable branches. This small changeset re-enables those tasks and makes `earthly.py` warning-free.
> Clean up Earthly task generation, add missing tasks

- .evergreen/config_generator/components/sasl/openssl.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
Test on Graviton with latest server
Testing Graviton is requested in DRIVERS-2436. MongoDB servers on Graviton is expected to be [more common](https://docs.google.com/document/d/117jiFR_JH6tgNBC5QeoXRpTxJoV308M1Q-JxImN30mM/edit?tab=t.0). Additional testing appears motivated by server issues encountered on Graviton. [HELP-37322](https://jira.mongodb.org/browse/HELP-37322) references two behavior differences:
1. SERVER-69612: [`char` is unsigned](https://github.com/aws/aws-graviton-getting-started/blob/main/c-c%2B%2B.md#signed-vs-unsigned-char) on ARM.
2. SERVER-69611: gcc may enable a default for `-ffp-contract` (which differs from clang).
Neither appear specific to Graviton. (1) applies to other ARM CPUs. The C driver already tests on arm (via `ubuntu2004-arm64`). (2) appears …
> CDRIVER-5924 test on Graviton

- .evergreen/config_generator/components/earthly.py
- .evergreen/generated_configs/tasks.yml
- src/libbson/doc/includes/seealso/bson-as-json.txt
Follow-up to https://github.com/mongodb/mongo-c-driver/pull/1920:
- Remove references to removed symbols in documentation to fix `make-docs` task.
- Update C++ driver reference from r3.9.0 to r4.0.0. This includes CXX-2995 to removes use of `bson_as_json`. Fixes Earthly tasks.
> CDRIVER-5701 remove references to removed symbols

- .evergreen/config_generator/components/abi_compliance_check.py
- .evergreen/generated_configs/functions.yml
- .evergreen/scripts/abi-compliance-check.sh
The `compat_report.html` file is not being uploaded properly to AWS on task failure. This PR fixes the upload routine such that the task will have a "failed" status (via the curl command) while proceeding with subsequent `s3.put` operations. However, this curl command is temporarily disabled given the deliberate breaking changes targeting the 2.0.0 release. CDRIVER-5930 tracks re-enabling task failure after the 2.0.0 release.
> Fix upload of ABI Compatibility Report HTML on failure

- Earthfile
- tools/earthly.sh
Follow-up to #1794
Use of Artifactory is likely the cause of frequently encountered HTTP errors ([example](https://spruce.mongodb.com/task/mongo_c_driver_alpine3.17_clang_check:sasl=Cyrus%C2%A0%E2%80%A2%C2%A0tls=OpenSSL%C2%A0%E2%80%A2%C2%A0test_mongocxx_ref=r3.9.0_patch_c186295845d80a6047fd7ba6b7fde56567080ab9_67d03ad1274f720007fd9433_25_03_11_13_29_55/logs?execution=0)). Quoting [slack](https://mongodb.slack.com/archives/C0V7VEU15/p1741630372464459):
> Our Artifactory cluster is just three hosts, and they run really hot.
Using Artifactory is not needed. Quoting [DEVPROD-12970](https://jira.mongodb.org/browse/DEVPROD-12970):
> We're unblocked for now after Docker agreed to add our IPv6 block to their allowlist
Unqualified images names (e.g. `ubuntu:22.04`) are used rather than a qualified …
> CDRIVER-5814 Use less Artifactory for Earthly images

- src/common/src/mlib/cmp.h
- src/libbson/examples/extended-json.c
- src/libmongoc/examples/example-structured-log.c
- src/libmongoc/tests/test-mongoc-change-stream.c
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
- src/libmongoc/tests/test-mongoc-counters.c
- src/libmongoc/tests/unified/runner.c
- src/tools/mongoc-stat.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1930. Address other instances of `-Wunused-parameter` warnings throughout the codebase (including tests, examples, and utils) as locally observed with Clang 21 on Linux.
> Reduce Warnings - address -Wunused-parameter warnings

- NEWS
- src/libmongoc/src/mongoc/mongoc-uri.c
- src/libmongoc/tests/test-mongoc-uri.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1896. Enforces that even optional usernames are non-empty when specified (there are no cases where an empty username is desirable).
>  CDRIVER-4489 promote empty username to client error 

- .evergreen/config_generator/components/loadbalanced.py
- .evergreen/config_generator/components/mock_server.py
- .evergreen/config_generator/components/sanitizers/asan.py
- .evergreen/config_generator/components/sanitizers/tsan.py
- .evergreen/generated_configs/legacy-config.yml
- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
- CMakeLists.txt
- Earthfile
- src/libbson/NEWS
- src/libbson/doc/bson_t.rst
- src/libbson/src/bson/bson-config.h.in
- src/libbson/src/bson/bson-macros.h
- src/libbson/src/bson/bson-private.h
- src/libbson/src/bson/bson-types.h
- Remove CMake option `ENABLE_EXTRA_ALIGNMENT`.
- Align `bson_t` and `bson_iter_t` to the size of a pointer.
Verified with this patch build: https://spruce.mongodb.com/version/67dc0db1caab950007b0f764
Addresses long-standing ask to remove default over-alignment: CDRIVER-2813.
Removing alignment specifiers entirely was considered. However, removing the alignment specifier on `bson_t` resulted in a runtime error in calls to `BSON_ALIGNED_ALLOC (bson_t)`:
> Failure to allocate memory in bson_aligned_alloc()
I expect this is due to `bson_t` having alignment of 4. `bson_t` does not contain a pointer.
From `man aligned_alloc` (emphasis mine):
> In addition, aligned_alloc() returns a NULL pointer and sets errno to EINVAL if size is not an integral multiple of alignment, or if alignment is not a …
> CDRIVER-2813 remove `BSON_EXTRA_ALIGNMENT` option

- NEWS
- src/libbson/src/bson/bson-json.h
- src/libbson/src/bson/bson-memory.h
- src/libbson/src/bson/bson-reader.h
- src/libbson/src/bson/bson-types.h
- src/libmongoc/src/mongoc/mongoc-apm.h
- src/libmongoc/src/mongoc/mongoc-client-session.h
- src/libmongoc/src/mongoc/mongoc-client-side-encryption.h
- src/libmongoc/src/mongoc/mongoc-client.h
- src/libmongoc/src/mongoc/mongoc-log.h
- src/libmongoc/src/mongoc/mongoc-sleep.h
- src/libmongoc/src/mongoc/mongoc-stream.h
- src/libmongoc/src/mongoc/mongoc-structured-log.h
Apply missing `BSON_CALL` to all exported callbacks to ensure `__cdecl` is applied when building with MSVC.
Resolves CDRIVER-2737 and CDRIVER-5678.
Verified with this [patch build](https://spruce.mongodb.com/version/67ea8bcf3bab8700076d6888).
This PR assumes libbson and libmongoc do not support building with a non-cdecl calling convention. Attempting to build libbson with [/Gv](https://learn.microsoft.com/en-us/cpp/build/reference/gd-gr-gv-gz-calling-convention) to specify the `__vectorcall` calling convention results in errors:
```
src\libbson\src\bson\bson-clock.c(45): error C2373: 'bson_gettimeofday': redefinition; different type modifier
(... and many more ...)
```
This PR intends to ensure consumers building with MSVC see `__cdecl` in the function declaration when building headers to …
> Apply `__cdecl` to all exported callbacks

- src/libmongoc/tests/json/change_streams/unified/change-streams-disambiguatedPaths.json
- src/libmongoc/tests/json/change_streams/unified/change-streams-pre_and_post_images.json
- src/libmongoc/tests/json/change_streams/unified/change-streams.json
Preemptive changes mirroring those in https://github.com/mongodb/mongo-cxx-driver/pull/1365 until a proper solution is implemented for [DRIVERS-3151](https://jira.mongodb.org/browse/DRIVERS-3151).
> CDRIVER-5959 temporarily restrict updateDescription tests to 8.1 or older

- src/libmongoc/src/mongoc/mongoc-openssl.c
Fixes
```
mongoc/mongoc-openssl.c:150:21: warning: format '%X' expects argument of type 'unsigned int', but argument 4 has type 'DWORD' {aka 'long unsigned int'} [-Wformat=]
```
> CDRIVER-5968 Fix compiler warning on Windows

- .evergreen/config_generator/components/abi_compliance_check.py
- .evergreen/config_generator/components/funcs/set_cache_dir.py
- .evergreen/generated_configs/functions.yml
- .evergreen/scripts/abi-compliance-check-setup.sh
- .evergreen/scripts/abi-compliance-check.sh
Resolves CDRIVER-5930 for the master branch (`mongo-c-driver` EVG project).
Applies some minor drive-by optimizations and improvements:
- Adopt the `SetCacheDir` -> `MONGO_C_DRIVER_CACHE_DIR` pattern from the [C++ Driver](https://github.com/mongodb/mongo-cxx-driver/blob/cb7afd1b886b0e1be3c4dec8bbc075258b8c070c/.evergreen/config_generator/components/funcs/set_cache_dir.py).
- Full migration to consistently using `$MONGO_C_DRIVER_CACHE_DIR` is deferred to a separate PR.
- Move abi-compliance-check and ctags binaries into the C Driver cache directory for reusability.
- `abi-compliance-check.sh` is updated to be more consistent with its [C++ Driver counterpart](https://github.com/mongodb/mongo-cxx-driver/blob/cb7afd1b886b0e1be3c4dec8bbc075258b8c070c/.evergreen/scripts/abi-compliance-check-test …
> CDRIVER-5930 re-enable ABI compliance checks

- .evergreen/config_generator/components/abi_compliance_check.py
- .evergreen/config_generator/components/funcs/set_cache_dir.py
- .evergreen/generated_configs/functions.yml
- .evergreen/scripts/abi-compliance-check-setup.sh
- .evergreen/scripts/abi-compliance-check.sh
Followup to https://github.com/mongodb/mongo-c-driver/pull/1976.
There are no notable differences between the changes committed in https://github.com/mongodb/mongo-c-driver/pull/1976 and this PR.
>  CDRIVER-5930 re-enable ABI compliance checks for r2.0 

- .evergreen/config_generator/components/abi_compliance_check.py
- .evergreen/config_generator/components/funcs/set_cache_dir.py
- .evergreen/generated_configs/functions.yml
- .evergreen/scripts/abi-compliance-check-setup.sh
- .evergreen/scripts/abi-compliance-check.sh
Followup to https://github.com/mongodb/mongo-c-driver/pull/1976.
Notable differences between the changes committed in https://github.com/mongodb/mongo-c-driver/pull/1976 and this PR include:
- replacing `${project}` with `mongo-c-driver` for AWS S3 put commands to avoid the permissions issues described in https://github.com/mongodb/mongo-c-driver/pull/1975.
- using `libbson-1.0` and `libmongoc-1.0` include directories for v1.30 compatibility instead of `bson-<api-version>` and `mongoc-<api-version>`.
- checking for API major version `1` instead of `2`.
>  CDRIVER-5930 re-enable ABI compliance checks for r1.30

- .evergreen/scripts/abi-compliance-check.sh
Followup to https://github.com/mongodb/mongo-c-driver/pull/1978. Fixes a stray reference to the `$base_verdir` variable which does not exist for r1.30 in the API major version compatibility check.
> Fix variable expansion in r1.30 abi-compliance-check.sh

- src/libmongoc/tests/test-mongoc-change-stream.c
- Use majority write concern to insert documents in test `/change_stream/batchSize0`.
- Remove faulty assert in `/change_stream/live/track_resume_token`.
Using majority write concern is intended to address this [observed test failure](https://parsley.mongodb.com/evergreen/mongo_c_driver_latest_release_sasl_matrix_nossl_sasl_off_nossl_debian10_gcc_test_4.2_replica_noauth_d79a0bd931e7de88af7e4eeb877421f853ca5bf1_25_04_02_19_28_33/0/task?bookmarks=0,3082&selectedLineRange=L2098), which receives only one of two expected events.
The faulty assert removal follows https://github.com/mongodb/mongo-cxx-driver/pull/1367, which made a similar change in the C++ driver test runner. I suspect the C++ tests were based off of the C driver tests.
> Use majority write concern and remove assert in change stream tests

- src/libbson/CMakeLists.txt
- src/libbson/examples/cmake/find_package/CMakeLists.txt
- src/libbson/examples/cmake/find_package_static/CMakeLists.txt
- src/libmongoc/examples/cmake/find_package/CMakeLists.txt
- src/libmongoc/examples/cmake/find_package_static/CMakeLists.txt
Remove unnecessary `cmake_policy (SET CMP0042 OLD)` statements that error in CMake 4.
Verified with this [patch build](https://spruce.mongodb.com/version/67ec4d31f11d6b00072d232a/).
Fixes an error on macOS with the recently released CMake 4:
```
% cmake -S. -Bcmake-build
...
CMake Error at src/libbson/CMakeLists.txt:33 (cmake_policy):
Policy CMP0042 may not be set to OLD behavior because this version of CMake
no longer supports it.  The policy was introduced in CMake version 3.0.0,
and use of NEW behavior is now required.
```
[CMP0042 documents](https://cmake.org/cmake/help/latest/policy/CMP0042.html):
> MACOSX_RPATH is enabled by default.
MACOSX_RPATH is already enabled by the [`set (CMAKE_MACOSX_RPATH ON)`](https://github.com/mongodb/mongo-c-driver/blob/8e65858ad870a3379a731f233ab919e515 …
> CDRIVER-5967 do not set CMP0042 to "OLD"

- .evergreen/config_generator/components/sbom.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/generated_configs/tasks.yml
The issues motivating https://github.com/mongodb/mongo-c-driver/pull/1981 have been addressed by [DEVPROD-16404](https://jira.mongodb.org/browse/DEVPROD-16404). Verified by [this patch](https://spruce.mongodb.com/version/67eec1ffedd634000745ceb2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
> Revert "Temporarily relocate sbom task from rhel80 to rhel8.8 (#1981)"

- src/libmongoc/tests/test-mongoc-change-stream.c
Addresses ongoing lint task failure on the r1.30 branch following https://github.com/mongodb/mongo-c-driver/pull/1980.
> Format test-mongoc-change-stream.c

- CMakeLists.txt
- Earthfile
- NEWS
- build/cmake/GeneratePkgConfig.cmake
- build/cmake/GenerateUninstaller.cmake
- build/cmake/LoadTests.cmake
- build/cmake/TestFixtures.cmake
- build/cmake/TestProject.cmake
- build/cmake/packageConfigVersion.cmake.in
- src/libbson/CMakeLists.txt
- src/libbson/NEWS
- src/libbson/etc/bsonConfig.cmake
- src/libbson/examples/cmake/find_package/CMakeLists.txt
- src/libbson/examples/cmake/find_package_static/CMakeLists.txt
- src/libmongoc/CMakeLists.txt
- src/libmongoc/etc/mongocConfig.cmake
- src/libmongoc/examples/cmake/find_package/CMakeLists.txt
- src/libmongoc/examples/cmake/find_package_static/CMakeLists.txt
- src/libmongoc/examples/cmake/vcpkg/CMakeLists.txt
- src/libmongoc/tests/cmake-import/CMakeLists.txt
- src/libmongoc/tests/cmake-import/use-bson.c
- src/libmongoc/tests/cmake-import/use-mongoc.c
- src/libmongoc/tests/import-tests.cmake
This changeset cherry-picks #1955 onto the 1.30.x release branch. Refer to that PR for details. The following tweaks are made in addition:
1. The CMake cache variable `MONGOC_INSTALL_CMAKEDIR` is renamed `MONGO_C_DRIVER_INSTALL_CMAKEDIR` to match the name used in 2.x. `MONGOC_INSTALL_CMAKEDIR` was never published in a release, so this change does not affect users.
2. The Earthfile's root directive was changed from `LOCALLY` to `FROM alpine:3.21`. This allows the repository to be used with Earthfile `IMPORT`.
> [CDRIVER-5391] Backport 2.x CMake Package Names

- build/calc_release_version.py
To avoid breaking PHP driver builds upgrading to the latest 1.30.x release.
See [slack](https://mongodb.slack.com/archives/GMY98JS86/p1744118665322989). https://github.com/mongodb/mongo-c-driver/pull/1975 backported removal of `calc_release_version.py`. PHP driver builds invoke `calc_release_version.py` directly ([example](https://github.com/mongodb/mongo-php-driver/blob/e0440f04ae00564fe4d94ddbe1ec3b5bf124b601/Makefile.frag#L66-L67)).
Though the C driver no longer uses `calc_release_version.py`, this PR restores the script to avoid needing build system changes for the PHP driver to upgrade to the latest 1.30.x release.
> CDRIVER-5976 restore `calc_release_version.py`

- src/common/tests/test-mlib.c
- src/libbson/src/jsonsl/jsonsl.c
- src/libmongoc/tests/unified/operation.c
- src/libmongoc/tests/unified/runner.c
Addresses 171 `-Wextra-semi-stmt` warnings (81 unique) with Clang 21.
> Reduce Warnings: address -Wextra-semi-stmt warnings

- .evergreen/config_generator/components/c_std_compile.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/scripts/compile-std.sh
Resolves CDRIVER-3253 following resolution of [DEVPROD-16074](https://jira.mongodb.org/browse/DEVPROD-16074). The providing distro is now `windows-vsCurrent` rather than the initially proposed `windows64-vsMulti` distro.
Updated `compile-std.sh` to take advantage of CMake 3.30's [CMAKE_\<LANG\>_STANDARD_LATEST](https://cmake.org/cmake/help/v3.30/variable/CMAKE_LANG_STANDARD_LATEST.html) variable to sanity-check that the requested C standard version is supported by the requested compiler (according to CMake). This exposed VS 2015 does not support C17:
```
CMake Error at CMakeLists.txt:15 (message):
Latest C standard 11 is less than 17
```
Additionally added a C compiler flag check to ensure the `/std:clatest` flag is actually supported by the compilers rather than an easily-missed warning …
> CDRIVER-3253 reintroduce VS 2015 task coverage

- .github/CODEOWNERS
To meet requirement of DRIVERS-3098. Follows pattern from other drivers: [PHP](https://github.com/mongodb/mongo-php-library/blob/a4ccccd9011bad978e6f0d52efd1a512ef64d35a/.github/CODEOWNERS), [C#](https://github.com/mongodb/mongo-csharp-driver/blob/main/CODEOWNERS).
> CDRIVER-5978 add CODEOWNERS

- .evergreen/config_generator/components/funcs/prepare_kerberos.py
- .evergreen/generated_configs/functions.yml
Fix base64 decoding of keytab on macOS. Fixes failing task: [authentication-tests-darwinssl](https://spruce.mongodb.com/task/mongo_c_driver_darwin_authentication_tests_darwinssl_3c2161fe78abccbd02c5b5115213eb2096dc9847_25_04_17_23_28_05/logs?execution=0). Tested with this [patch build](https://spruce.mongodb.com/version/68019808d1283200071d51bc).
Running on my local macOS, the previous command errored:
```
% base64 --decode /tmp/drivers.keytab.base64 > /tmp/drivers.keytab
base64: invalid argument /tmp/drivers.keytab.base64
```
> fix base64 decoding command in keytab

- .evergreen/scripts/run-auth-tests.sh
Skip auth tests on zSeries depending on DEVPROD-16954. Tested in this [patch build](https://spruce.mongodb.com/version/6802a216fa9a8e00073cc6b0).
The C driver tests on zSeries (rhel8-zseries-large) fails to connect to the test host referenced in DEVPROD-16954. From a [patch](https://spruce.mongodb.com/task/mongo_c_driver_zseries_rhel8_survey_patch_8c0a2446ae44350066becfa908c83499b6cca96c_6802918b57ad790007f5f618_25_04_18_17_53_16/logs?execution=0):
```
nc: connect to [REDACTED:auth_host] (54.225.237.121) port 27017 (tcp) failed: Connection timed out
```
I expect this is related to the migration of zSeries hosts in DEVPROD-5083. (Tests did not fail at the time since auth tests were [temporarily skipped](https://github.com/mongodb/mongo-c-driver/blob/ae9fcb388480351800c39485447d9f76b9ecea75/ …
> CDRIVER-5990 skip auth tests on zSeries

- src/libmongoc/tests/json/command-logging-and-monitoring/monitoring/unacknowledged-client-bulkWrite.json
Sync from https://github.com/mongodb/specifications/commit/78916887729bf0d3088541bd9a7390770fae5f77
No test runner changes were needed.The C driver test runner [represents an unacknowledged result as an empty BSON document `{}`](https://github.com/mongodb/mongo-c-driver/blob/1ca2bfabba1fcd0a4c578377ff8b88521f987c3e/src/libmongoc/tests/unified/result.c#L667-L687). Before: matching `{}` against `{ "insertedCount": { "$$unsetOrMatches": 0 } , ... }` succeeded. After: matching `{}` to `{ "$$unsetOrMatches": { "insertedCount": { "$$unsetOrMatches": 0 } , ... }}` also succeeds.
> CDRIVER-5934 sync spec test

- docs/dev/releasing.rst
Resolves CDRIVER-5529. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1385.
The rulesets for the C Driver repository are nearly identical to those implemented [for the C++ Driver](https://github.com/mongodb/mongo-cxx-driver/pull/1385#issuecomment-2822366466), re-summarized here:
- Joining the @mongodb/dbx-c-cxx-releases team during a release allows one to bypass to the following rulesets:
- "Restrict Creations" (branches and tags) to create new release branches and tags.
- "Require a Pull Request" (new and active branches) to directly push to (new) release branches.
- "Restrict Deletions" apply to all branches and tags without exception.
- "Restrict Updates" applies to all tags without exception and to an _inclusive_ target list of stale branches which may be "locked" from …
> CDRIVER-5529 update release instructions to account for new rulesets

- .evergreen/config_generator/components/sasl/darwinssl.py
- .evergreen/config_generator/components/sasl/winssl.py
- .evergreen/generated_configs/tasks.yml
- .evergreen/scripts/run-auth-tests.sh
- NEWS
- src/libmongoc/src/mongoc/mongoc-change-stream.c
- src/libmongoc/src/mongoc/mongoc-client-private.h
- src/libmongoc/src/mongoc/mongoc-client-session.c
- src/libmongoc/src/mongoc/mongoc-topology.c
- src/libmongoc/src/mongoc/mongoc-util.c
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-libmongoc.h
- src/libmongoc/tests/test-mongoc-bulk.c
- src/libmongoc/tests/test-mongoc-change-stream.c
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
- src/libmongoc/tests/test-mongoc-collection-find-with-opts.c
- src/libmongoc/tests/test-mongoc-collection.c
- src/libmongoc/tests/test-mongoc-crud.c
- src/libmongoc/tests/test-mongoc-exhaust.c
- src/libmongoc/tests/test-mongoc-mongos-pinning.c
- src/libmongoc/tests/test-mongoc-primary-stepdown.c
- src/libmongoc/tests/test-mongoc-read-prefs.c
- src/libmongoc/tests/test-mongoc-retryable-reads.c
- src/libmongoc/tests/test-mongoc-sdam.c
- src/libmongoc/tests/test-mongoc-transactions.c
- Raise minimum supported wire version from 7 (server 4.0) to 8 (server 4.2).
- Remove behavior and tests specific to maxWireVersion < 8.
Verified with this [patch build](https://spruce.mongodb.com/version/68090d0103e0920007b5cec5).
Removing no-longer-needed cursor implementations is not done in this PR and planned for CDRIVER-4722.
Auth tests using the test server are temporarily skipped until the test server is upgraded. Upgrading is tracked in DEVPROD-9029.
Some tests that destroy cursors (`test_change_stream_resumable_error`) are updated to reflect behavior for server > 4.0. Quoting [SDAM](https://github.com/mongodb/specifications/blob/43d2c7bacd62249de8d2173bf8ee39e6fd7a686e/source/server-discovery-and-monitoring/server-discovery-and-monitoring.md#L939):
> If the old primary server …
> CDRIVER-5956 raise min wire version from 7 to 8 (server 4.2)

- .evergreen/benchmark.yml
We replace the perf.send command with new shell scripts that submit the performance data to the new performance data end point available in signal processing service.
Successful patch with changes here, data can be viewed on the Trend Charts tab as before:
https://spruce.mongodb.com/version/681271b6fead0f0007f143bf/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> DEVPROD-17323 - Replace perf.send with new data submission end point

- src/libmongoc/tests/test-mongoc-client-side-encryption.c
Update invalid endpoints to speed up Client Side Encryption test 7.
Verified with this [patch build](https://spruce.mongodb.com/version/680fd22a2f809900074b249c).
Some drivers observed recent timeout test failures connecting to intentionally invalid URIs. Drivers do not use a consistent timeout for KMS requests (DRIVERS-1049). C driver tests were not failing, but logs indicate the test was very slow. On a prior [commit](https://spruce.mongodb.com/task/mongo_c_driver_sanitizers_matrix_asan_asan_cse_sasl_cyrus_openssl_ubuntu2004_clang_test_5.0_server_auth_970589376bba991ce1a3a8336ca1410022349f67_25_04_23_18_21_36/logs?execution=0):
```
[...] "/client_side_encryption/custom_endpoint" [...] "elapsed": 143.074858
```
With [this PR](https://spruce.mongodb.com/task/mongo_c_driver_sanitizers_matri …
> CDRIVER-5997 speed up CSE endpoint tests

- src/libmongoc/tests/unified/entity-map.c
- src/libmongoc/tests/unified/entity-map.h
- src/libmongoc/tests/unified/operation.c
- src/libmongoc/tests/unified/runner.c
- src/libmongoc/tests/unified/runner.h
Implement test changes described in DRIVERS-2816 to fix test failures:
> Modify the unified test runner to collect the cluster time from the internal MongoClient following initialData operations, and use it to advance cluster times of all session entities created during the subsequent test
This change appears to fix ongoing failures for the `client bulkWrite in a transaction` test ([example](https://spruce.mongodb.com/task/mongo_c_driver_loadbalanced_loadbalanced_rhel8.9_gcc_test_latest_auth_openssl_27a824ccb23f321a2e8a28b34d81c5addabc4104_25_05_07_19_18_06/logs?execution=0)):
```
test file: client bulkWrite transactions
[...]
running test: client bulkWrite in a transaction
[...]
error: expected result, but got error: Transaction 39dbb2a4-d1db-4913-bdbe-dec0b3056a91 - …
```
> CDRIVER-5304 set cluster time in test sessions

- src/libbson/src/bson/bson-error.c
- src/libbson/tests/test-bson-error.c
Backport of https://github.com/mongodb/mongo-c-driver/pull/2011 to r2.0.
> CDRIVER-6011 fix message of `bson_strerror_r` on Windows (#2011)

- src/libmongoc/src/mongoc/mongoc-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel.c
- src/libmongoc/tests/test-mongoc-x509.c
This PR addresses several memory-related found in certificate loading for Secure Channel:
- Fix several memory leaks.
- NUL-terminate the PEM file for the client certificate.
Reading the PEM file is refactored with more error checks logs including the system error.
Leaks were discovered when implementing PKCS#8 certificate support for (CDRIVER-4269). This may help motivate future addition of leak detection on Windows (CDRIVER-2529).
NUL-terminating the PEM file was similarly done in https://github.com/mongodb/mongo-c-driver/pull/1903. NUL-terminating is intended to avoid reading past beyond the string in later calls to `strstr`.
The Secure Channel implementation would likely benefit from a larger rewrite, and may be done as part of CDRIVER-4463. This PR intends to address the more severe …
> CDRIVER-3228 fix memory leaks in SChannel cert loading

- src/libmongoc/src/mongoc/mongoc-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel.c
- src/libmongoc/tests/test-mongoc-x509.c
Backport of https://github.com/mongodb/mongo-c-driver/pull/2009 to r2.0 branch. No changes were needed to cherry-pick. Tested with this [patch](https://spruce.mongodb.com/version/682760cc6c21ed00077a1165).
> [r2.0] CDRIVER-3228 fix memory leaks in SChannel cert loading (#2009)

- src/libmongoc/src/mongoc/mongoc-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel.c
- src/libmongoc/tests/test-mongoc-x509.c
Backport of https://github.com/mongodb/mongo-c-driver/pull/2009 to r1.30 branch. Commits in CDRIVER-5743 are also backported to avoid a merge conflict. Tested with this [patch](https://spruce.mongodb.com/version/682760cc6c21ed00077a1165).
> [r1.30] CDRIVER-3228 fix memory leaks in SChannel cert loading (#2009)

- src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-error-private.h
- src/libmongoc/src/mongoc/mongoc-error.c
- src/libmongoc/src/mongoc/mongoc-handshake.c
- src/libmongoc/src/mongoc/mongoc-openssl.c
- src/libmongoc/src/mongoc/mongoc-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-sspi.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel.c
- src/libmongoc/tests/TestSuite.c
- src/libmongoc/tests/test-mongoc-error.c
Cherry-pick of https://github.com/mongodb/mongo-c-driver/commit/1b0e008d3aab07431827433c783f92680cb0cffe to r2.0.
Only bug fixes are expected to be backported. This change is less of a bug fix, but is expected to be needed for CDRIVER-4269 (which is intended to be backported too).
Tested with this patch build: https://spruce.mongodb.com/version/6837729e811623000746ea1b
> [2.0] CDRIVER-6019 Improve error messages from Windows APIs (#2020)

- .evergreen/config_generator/components/c_std_compile.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/generated_configs/tasks.yml
Per DevProd guidance. RHEL 7.9 is the latest RHEL 7 minor release and the one which is currently recommended for use by DevProd. This distro does not significantly change the available toolchain used for compilation test coverage (still GCC 4.8.5).
> Migrate EVG tasks from RHEL 7.6 to RHEL 7.9

- .evergreen/scripts/check-preludes.py
- src/libbson/NEWS
- src/libbson/doc/bson_validate_flags_t.rst
- src/libbson/src/bson/bson-types.h
- src/libbson/src/bson/bson.c
- src/libbson/src/bson/validate-private.h
- src/libbson/src/bson/validate.c
- src/libbson/tests/test-bson.c
- src/libbson/tests/test-validate.generated.c
- src/libbson/tests/validate-tests.py
- src/libmongoc/CMakeLists.txt
- src/libmongoc/src/mongoc/mongoc-util.c
- src/libmongoc/tests/test-libmongoc-main.c
- src/libmongoc/tests/test-mongoc-bulk.c
- src/libmongoc/tests/test-mongoc-collection.c
- src/libmongoc/tests/test-mongoc-cursor.c
This changeset is a large refactor of the `bson_validate` implementation.
Existing validation test cases were rewritten to use a uniform code generation mechanism that notes the purpose of each case. Many more validation scenarios were added.
The `BSON_VALIDATE_UTF8` flags have been removed from the default flags used by the CRUD API. Because of a bug, UTF-8 validation wasn't being applied to the CRUD API, so removing the flag is necessary since it would otherwise be a breaking change.
The new validation is written as a straightforward recursive algorithm, and doesn't use the error-prone `bson_visit` API.
The following changes are of note:
1. The error code `BSON_VALIDATE_CORRUPT` is now set on corruption. Previously, this was set to `BSON_VALIDATE_NONE`, which had a value of zero. This …
> [CDRIVER-6017] BSON Validation Refactor

- .evergreen/scripts/check-preludes.py
- src/libbson/NEWS
- src/libbson/doc/bson_validate_flags_t.rst
- src/libbson/src/bson/bson-types.h
- src/libbson/src/bson/bson.c
- src/libbson/src/bson/validate-private.h
- src/libbson/src/bson/validate.c
- src/libbson/tests/test-bson.c
- src/libbson/tests/test-validate.generated.c
- src/libbson/tests/validate-tests.py
- src/libmongoc/CMakeLists.txt
- src/libmongoc/src/mongoc/mongoc-util.c
- src/libmongoc/tests/test-libmongoc-main.c
- src/libmongoc/tests/test-mongoc-bulk.c
- src/libmongoc/tests/test-mongoc-collection.c
- src/libmongoc/tests/test-mongoc-cursor.c
This is a cherry-pick of changes from #2026 for the 2.0.x release.
The original merge commit message is retained below and should be included in the final merge. 
---
* New BSON validation routine rewrite
The new `bson_validate` implementation does not
make use of the error-prone `bson_visit` APIs. Instead, it is written as a simple recursive validator. The new validator respects requests for UTF-8 validation properly.
* Stop validating at 1000 depth, preventing stack overflow
* Replace most BSON validation tests with generated ones
The existing test cases used BSON files, and didn't have any commentary on what they were actually testing. New test cases are generated from a Python shorthand and contain the tested bytes inline, with a distinct test case for each actual validation scenario. …
> [CDRIVER-6017] BSON Validation Refactor (#2026) (Cherry-pick for 2.0.x)

- src/libbson/src/bson/validate-private.h
Cherry-pick of https://github.com/mongodb/mongo-c-driver/pull/2034 to r1.30.
> [CDRIVER-6017] Reduce `BSON_VALIDATION_MAX_NESTING_DEPTH` to 500 [r1.30]

- src/libbson/doc/bson_validate_flags_t.rst
Clarify `BSON_VALIDATE_UTF8_ALLOW_NULL` applies only when `BSON_VALIDATE_UTF8` is set. This is [documented in the public header](https://github.com/mongodb/mongo-c-driver/blob/1afa0998882dad4f2a424af32260ca0f95f603b9/src/libbson/src/bson/bson-types.h#L221), but not in the RST docs.
> clarify `BSON_VALIDATE_UTF8_ALLOW_NULL` behavior in RST

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/functions.py
See DRIVERS-3188. Use `ec2.assume_role` to fix failing [test-mongohouse](https://spruce.mongodb.com/task/mongo_c_driver_mongohouse_test_mongohouse_1b0e008d3aab07431827433c783f92680cb0cffe_25_05_28_19_40_43/logs?execution=0) task:
```
An error occurred (AccessDenied) when calling the AssumeRole operation
```
Tested with this [patch build](https://spruce.mongodb.com/version/6837acc2e5c4bc000761874d).
> CDRIVER-6010 use `ec2.assume_role` for mongohouse task

- src/common/tests/test-mlib.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1999. Addresses ongoing VS 2017 test task failures due to what seems to be a VS 2017 compiler bug. Narrowed the issue down to what seems to be a poor interaction between the conditional operator and compound literals, which manifests in the expansion of the `mlib_upsize_integer` macro:
```c
#include <assert.h>
#include <stdio.h>
#include <stdbool.h>
typedef struct S { int v; } S;
int main(void) {
int x = 0;
int y = true ? (S){++x}.v : (S){++x}.v;
assert(y == 1); // OK
assert(x == 1); // failure (!?!?)
}
```
I am unable to reproduce this behavior on any other currently tested or supported compiler (GCC, Clang, MSVC). I could not find any Visual Studio bug reports relating to this behavior. This behavior does not seem to be present …
> CDRIVER-5996 Address EVG task failure due to possible VS 2017 compiler bug

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
A minor drive-by fix to the EVG configuration following removal of the `link-with-cmake-mac-deprecated` task in https://github.com/mongodb/mongo-c-driver/pull/1956.
```
WARNING: buildvariant 'smoke' has unmatched selector: 'link-with-cmake-mac-deprecated'
WARNING: buildvariant 'smoke' has unmatched criteria: 'link-with-cmake-mac-deprecated'
.evergreen/config.yml is valid with warnings/notices
```
> Address Evergreen validation warnings for link-with-cmake-mac-deprecated

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/testazurekms.py
Apply fix from https://github.com/mongodb/mongo-c-driver/pull/2025 to `testazurekms-task`. Intended to fix [on-going failure](https://spruce.mongodb.com/task/mongo_c_driver_testazurekms_variant_testazurekms_task_30ac9bf0d8b2677a1a1e92a4fe5a13584845f30e_25_06_26_17_37_40/logs?execution=2) logging:
```
An error occurred (AccessDenied) when calling the AssumeRole operation
```
Verified with this patch build: https://spruce.mongodb.com/version/6862e5f5778aa400072b85d3
> CDRIVER-6010 use `ec2.assume_role` for Azure KMS task

- src/libmongoc/CMakeLists.txt
- src/libmongoc/src/mongoc/mongoc-client-pool.c
- src/libmongoc/src/mongoc/mongoc-client-private.h
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-server-monitor.c
- src/libmongoc/src/mongoc/mongoc-stream-tls-private.h
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel-private.h
- src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel.c
- src/libmongoc/src/mongoc/mongoc-stream-tls.c
- src/libmongoc/src/mongoc/mongoc-topology-scanner-private.h
- src/libmongoc/src/mongoc/mongoc-topology-scanner.c
- src/libmongoc/tests/test-libmongoc-main.c
- src/libmongoc/tests/test-mongoc-secure-channel.c
- src/libmongoc/tests/test-mongoc-x509.c
Share `SCHANNEL_CRED` across connections.
Verified with this patch: https://spruce.mongodb.com/version/686298d51b4881000729652b/
Sharing the `SCHANNEL_CRED` is motivated by an upcoming fix for CDRIVER-5998. The private key for a client certificate is currently imported as an ephemeral key stored in-process (via [call to CryptImportKey](https://github.com/mongodb/mongo-c-driver/blob/31c13b6080a8a153be9c849b7c4138bfa1cbc6d8/src/libmongoc/src/mongoc/mongoc-secure-channel.c#L320)). Supporting SHA2 signatures appears to require importing a persisted private key stored on the file-system (with a unique name). This will be described further in a follow-up PR. But to avoid importing many duplicate keys, I want to change the current behavior from "import key per connection" to "import key per …
> CDRIVER-5998 share `SCHANNEL_CRED`

- src/common/src/mlib/ckdint.h
- src/common/src/mlib/ckdint.test.cpp
- src/common/src/mlib/cmp.h
- src/common/src/mlib/intutil.h
- src/common/src/mlib/str.h
- src/common/src/mlib/test.h
- src/common/tests/test-mlib.c
The following changes are made:
- We avoid compound literals expanded from macros. This is to avoid buggy compound-literal support in VS 2017 (See CDRIVER-6043).
Instead, we pass the relevant argument to a function that initializes the new aggregate object.
This has the downside that we cannot use the macros in constant expressions, but that was a minor feature that wasn't really used anywhere.
- Add a new macro to define bit masks. This simplifies the expressions that build bit patterns used for two's complement arithmetic.
- Rename the members of `mlib_upsized_integer` to give them meaningful names.
This doesn't fully fix CDRIVER-6043, but will avoid future subtle issues with VS 2017.
> [CDRIVER-6043] Modify definitions in `intutil` to avoid compound-literals

- src/libmongoc/tests/json/client_side_encryption/unified/localSchema.json
Applies test change proposed in DRIVERS-3106. The entire test is not copied, since the test runner does not support the `sessionToken` placeholder (pending CDRIVER-5779).
Tested with this [patch build](https://spruce.mongodb.com/version/6876971272e2810007950140)
> CDRIVER-5901 update error assert in localSchema.json

- src/libmongoc/tests/unified/entity-map.c
Apply a `cryptSharedLibPath` to the unified test runner.
Tested by this [patch build](https://spruce.mongodb.com/version/68767a60298c3d0007a683f0).
This applies a consistent search path for crypt_shared. Using a consistent path may avoid triggering an [error from libmongocrypt](https://github.com/mongodb/libmongocrypt/blob/9ed7c48c7034a93a743c149bfe0f3b4ecea206bb/src/mongocrypt.c#L681-L690). I expect this did not trigger an error from libmongocrypt since tests were not run concurrently (only one crypt_shared was loaded in process at a time).
A [previous task](https://parsley.mongodb.com/evergreen/mongo_c_driver_sanitizers_matrix_asan_asan_cse_sasl_cyrus_openssl_rhel8_latest_clang_test_8.0_server_auth_afb406d5069306b07379caa7af40c11f691e931b_25_07_11_15_09_57/0/task?bookmarks=0,2498&shareLi …
> CDRIVER-5901 set `cryptSharedLibPath` if not present

- src/libmongoc/doc/mongoc_stream_buffered_new.rst
- src/libmongoc/src/mongoc/mongoc-client-private.h
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-server-monitor.c
Remove buffered stream on pooled connections
See CDRIVER-6053 for a description of the problem. In short: long-lived buffered streams can significantly increase memory usage.
I initially thought buffering was intended to reduce allocations. But it actually increases allocations. When using a buffered stream to read, the caller still [allocates](https://github.com/mongodb/mongo-c-driver/blob/017cf329d7c9bf705cfa1d88eca15e884d13f7dc/src/libmongoc/src/mongoc/mongoc-buffer.c#L185) for the result, then [copies from the buffered stream](https://github.com/mongodb/mongo-c-driver/blob/017cf329d7c9bf705cfa1d88eca15e884d13f7dc/src/libmongoc/src/mongoc/mongoc-stream-buffered.c#L251).
[Comments](https://github.com/mongodb/mongo-c-driver/blob/017cf329d7c9bf705cfa1d88eca15e884d13f7dc/src/libmongoc/src/m …
> CDRIVER-6053 do not buffer pooled streams

- .evergreen/config_generator/components/earthly.py
- .evergreen/generated_configs/tasks.yml
Followup to https://github.com/mongodb/mongo-c-driver/pull/2071, which overlooked that in addition to the EVG generated config being out-of-date, it was also missing the required call to `DockerLoginAmazonECR` to authenticate with Amazon ECR prior to running the `verify-headers` Earthly command.
> Add DockerLoginAmazonECR to verify-headers task

- tools/earthly.sh
To fix `no such host` error logs observed after the Earthly cloud shutdown. [Example](https://parsley.mongodb.com/evergreen/mongo_c_driver_alpine3.16_gcc_check:sasl=Cyrus%C2%A0%E2%80%A2%C2%A0tls=OpenSSL%C2%A0%E2%80%A2%C2%A0test_mongocxx_ref=master_a3ba342a03df26f59b0427c921b8b727264b4f64_25_07_24_17_48_47/0/task?bookmarks=0,1419&shareLine=354):
```
retrying http request due to unexpected error Get "https://api.earthly.dev/api/v0/account/auth-challenge": dial tcp: lookup api.earthly.dev on 10.122.0.2:53: no such host {reqID: 6ebdff5e-e702-4953-b775-88ed20c8c031}
```
https://github.com/earthly/earthly/releases/tag/v0.8.16 notes:
> v0.8.16 does not emit log messages after the cloud shutdown
> update Earthly version from 0.8.3 to 0.8.16

- .evergreen/scripts/debian_package_build.sh
Evergreen patch build: https://spruce.mongodb.com/version/688bbbe50de93a0007007c04/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Use tag debian/1.30.4-1 for building Debian packages in Evergreen

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
Followup to https://github.com/mongodb/mongo-c-driver/pull/2070 which overlooked the `mingw-windows2016` variant in the legacy config generator.
> The `CC` env var is also updated to correctly indicate the compiler to use (`gcc`, not `mingw`), since we are only really interested in testing compilation of our libraries with the mingw-w64 compiler on Windows, not the particulars of the build system of choice.
> Update mingw-windows2016 to use "CC=gcc" for mingw-w64

- .evergreen/scripts/run-tests.sh
- src/libmongoc/CMakeLists.txt
- src/libmongoc/src/mongoc/mongoc-client-pool.c
- src/libmongoc/tests/TestSuite.c
- src/libmongoc/tests/TestSuite.h
- src/libmongoc/tests/stream-tracker.c
- src/libmongoc/tests/stream-tracker.h
- src/libmongoc/tests/test-libmongoc-main.c
- src/libmongoc/tests/test-mongoc-client-pool.c
- src/libmongoc/tests/test-mongoc-dns.c
- src/libmongoc/tests/test-mongoc-exhaust.c
- src/libmongoc/tests/test-mongoc-primary-stepdown.c
This PR adds a test utility to count client-side streams: `stream_tracker_t`.
Tests in CDRIVER-6080 are unskipped and updated to replace server-side connection tracking with the client-side stream tracking.
As a drive-by fix, the `llvm-symbolizer` path is updated to prefer `/opt/mongodbtoolchain/v4` if available.
Running only `/client_pool/disconnects_removed_servers/on_push` on 100x-repeat reproduced failures: https://spruce.mongodb.com/version/689f2acc28a3590007ece216:
```
test error in: ../../../src/libmongoc/tests/test-mongoc-client-pool.c 445:disconnects_removed_servers_on_push()
Got unexpected connection count to localhost:27017:
Expected 6, got 4
```
With fixes from this PR, the test consistently appears to pass: https://spruce.mongodb.com/version/68a1fc25c3e9fc00072bbb70.
The test …
> CDRIVER-6080 track client streams in connection counting tests

- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/tests/test-mongoc-collection.c
`mongoc_collection_create_indexes_with_opts` uses `mongoc_client_command_with_opts` rather than `mongoc_collection_write_command_with_opts`. As a result, write command behavior is not applied:
- Write concern is not inherited from the parent mongoc_collection_t (contrary to [documentation](https://mongoc.org/libmongoc/1.30.2/mongoc_collection_create_indexes_with_opts.html))
- A server reply with a "writeConcernError" does not result in a failing return.
These changes now call `mongoc_collection_write_command_with_opts`. 
A test was added to reproduce the errors in the original code and confirm that write command behavior is fixed with the correct call.
> CDRIVER-5945 mongoc_collection_create_indexes_with_opts does not apply write command behavior

- src/libmongoc/tests/test-mongoc-client-side-encryption.c
Intended to fix failing [C driver tasks](https://spruce.mongodb.com/task/mongo_c_driver_sanitizers_matrix_asan_asan_cse_sasl_cyrus_openssl_rhel8_latest_clang_test_latest_replica_auth_patch_d77a79e4b83bbcc4bc48a02cf443e4879fb36161_68b70664262fa0000703c44d_25_09_02_14_59_52/logs?execution=0) on latest servers:
```
test-mongoc-client-side-encryption.c:489 test_bson_size_limits_and_batch_splitting(): error code 10334 doesn't match expected 2
```
Changes from SERVER-104405 resulted in a different error code returned for a too-large document.
> check for new "too-large" error code

- docs/dev/releasing.rst
Motivated by a [slack conversation](https://mongodb.slack.com/archives/GMY98JS86/p1756493343064969) about CDRIVER-4153. The ticket originally had commits in 2.1.0 but was left open. Prefer closing tickets with commits in a release to simplify consistency with Jira.
> add step to check tickets in commit messages

- src/libmongoc/src/mongoc/mongoc-oidc-callback-private.h
- src/libmongoc/src/mongoc/mongoc-oidc-callback.c
- src/libmongoc/tests/test-mongoc-oidc-callback.c
Add a private `mongoc_oidc_callback_copy`.
This is a start towards resolving CDRIVER-4689. The copy function is expected to be used in soon-to-be-added setter functions:
```c
// Configure OIDC callback:
mongoc_oidc_callback_t *oidc_callback = mongoc_oidc_callback_new (oidc_callback_fn);
mongoc_client_set_oidc_callback (client, oidc_callback); // Copies callback.
```
Following patterns of other setters (e.g. `mongoc_client_set_write_concern`) a copy of the argument is stored.
> CDRIVER-4689 add a private `mongoc_oidc_callback_copy`

- src/libmongoc/src/mongoc/mongoc-topology-scanner.c
See [CDRIVER-4812](https://jira.mongodb.org/browse/CDRIVER-4812) for full details. In summary, the flag `negotiated_sasl_supported_mechs` stored by topology scanner nodes is never set to true after parsing saslSupportedMechs from the server's hello_response, causing saslSupportedMechs to be continuously appended to all outgoing hellos. This seems to have caused extraneous log output for customers.
This PR adds a wrapper to `_mongoc_handshake_parse_sasl_supported_mechs` which allows for `node->negotiated_sasl_supported_mechs` to be set to true upon successful parsing. This ensures saslSupportedMechs are not appended to outgoing hellos after the initial hello response from the server. 
To replicate the issue found in [mongodb/mongo-php-driver#1506](https://github.com/mongodb/mongo-php-driver …
> CDRIVER-4812 Single-threaded monitoring commands may include saslSupportedMechs beyond initial handshake

- .evergreen/scripts/run-tests.sh
- src/libmongoc/tests/test-mongoc-exhaust.c
Follow-up to #2095 intended to fix observed test failures on macOS replica sets. [Example](https://spruce.mongodb.com/task/mongo_c_driver_sasl_matrix_darwinssl_sasl_cyrus_darwinssl_macos_14_arm64_clang_test_6.0_replica_auth_patch_bd58f9df2029955cb1564557ab5403198b1ce650_68bb4bca9fc72c00079c4923_25_09_05_20_45_01/logs?execution=0):
```
test error in: /Users/ec2-user/data/mci/c4f6b76328d456c45e1a0f91c797f34d/mongoc/src/libmongoc/tests/test-mongoc-exhaust.c 202:test_exhaust_cursor()
Got unexpected total stream count to localhost:27018:
Expected 3, got 4
```
I reproduced the error by running test in repeat 100x: https://spruce.mongodb.com/version/68bb4bca9fc72c00079c4923
Tests pass with this fix applied: https://spruce.mongodb.com/version/68bb4f4fe5543500071df4fc
I expect the extra observed …
> CDRIVER-6080 fix stream tracking in `/Client/exhaust_cursor/pool`

- src/libmongoc/src/mongoc/mongoc-change-stream.c
- src/libmongoc/tests/test-mongoc-change-stream.c
- Attempting to iterate a closed change stream with `mongoc_change_stream_next` will now return the error "Cannot advance a closed change stream."
- Added a [test](https://github.com/mongodb/mongo-c-driver/compare/master...kevinAlbs:mongo-c-driver:changestream) that reproduced the issue.
> CDRIVER-4738 Do not resume after change stream cursor is closed

- src/libmongoc/examples/client-side-encryption-server-schema.c
- src/libmongoc/src/mongoc/mongoc-write-concern.c
- src/libmongoc/tests/test-conveniences.c
- src/libmongoc/tests/test-mongoc-change-stream.c
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
- src/libmongoc/tests/test-mongoc-primary-stepdown.c
- src/libmongoc/tests/test-mongoc-sample-commands.c
Do not set write concern timeout in most tests executing server operations.
Intended to fix recent observed failures in Evergreen. [Example](https://spruce.mongodb.com/task/mongo_c_driver_cse_matrix_darwinssl_cse_sasl_cyrus_darwinssl_macos_14_clang_test_4.4_sharded_auth_0540e9929d6af9cb32086292db61fda78247ec1a_25_09_26_16_54_36/logs?execution=0):
```
FAIL:/Users/ec2-user/data/mci/ffb7ebf283ddea39b3d6257ed6eff9b4/mongoc/src/libmongoc/tests/test-mongoc-client-side-encryption.c:76  _before_test()
ret
waiting for replication timed out; Error details: { wtimeout: true, writeConcern: { w: "majority", wtimeout: 1000, provenance: "clientSupplied" } } at sh01
```
I expect the 1 second timeout is sometimes too short (IIRC servers on macOS Evergreen hosts generally run slower).
Removing `wTimeout` …
> Reduce use of write concern timeout in tests

- src/libmongoc/src/mongoc/mongoc-array-private.h
- src/libmongoc/src/mongoc/mongoc-write-command-private.h
- src/libmongoc/src/mongoc/mongoc-write-command.c
- src/libmongoc/tests/test-mongoc-bulk.c
Change `mongoc_write_command_t::cmd_opts` from `bson_t` to `bson_t*`.
Tested with this patch: https://spruce.mongodb.com/version/68dd762c5eafa20007be24b2
Intended to fix behavior when `mongoc_write_command_t` is copied into a `mongoc_array_t`. See [comment](https://jira.mongodb.org/browse/CDRIVER-6112?focusedCommentId=7734413&focusedId=7734413&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-7734413) in CDRIVER-6112 for a more detailed description. This PR proposes a simple fix: change `bson_t` to `bson_t *` to simplify ownership transfer.
Other instances of `_mongoc_array_init` were checked. No others appear to use an array of a type embedding `bson_t`. A comment is added to warn against storing `bson_t` in `mongoc_array_t`.
> CDRIVER-6112 fix ownership transfer of `mongoc_write_command_t`

- NEWS
- src/libbson/NEWS
Add NEWS entries for 2.1.1 following release.
> add NEWS for 2.1.1

- src/libbson/tests/test-json.c
This PR fixes the signbit symbol missing issue.
Below is the issue URL.
https://jira.mongodb.org/browse/CDRIVER-6103
> CDRIVER-6103 AIX build failure fix
