src/mongoc/mongoc-stream-tls.c, tests/ssl-test.c
Rather than calling BIO_write multiple times for each iovec_t in a call
to mongoc_stream_tls_writev(), buffer them and send them all at once.
Attempt to "do the right thing"tm, when buffering provides no
performance benefit.
=> CDRIVER-532 - Coalesce small vecrotized TLS writes

src/mongoc/Makefile.am, src/mongoc/mongoc-uri-private.h, src/mongoc/mongoc-uri.c, tests/test-mongoc-uri.c
@hanumantmk and @ajdavis if you get a minute today, would you please review?  Note that this only canonicalizes hostnames within URIs.  Once it's merged in the SDAM branch will need a bit more work to complete the task.
=> CDRIVER-536 hostnames are normalized to lowercase

src/mongoc/mongoc-bulk-operation.c
https://jira.mongodb.org/browse/CDRIVER-570
When using mongoc_bulk_operation_new() to construct a bulk operation (not through a collection), one would expect the client's write concern to be used at execution time if an explicit write concern is not set on the bulk operation. That functionality is already handled by _mongoc_write_command_execute(), but it requires we not initialize a new write concern on the bulk operation.
=> CDRIVER-570: Executing bulk without write concern should inherit from client

src/mongoc/mongoc-cluster.c, src/mongoc/mongoc-socket.c, src/mongoc/mongoc-stream.c
otherwise data from other handlers won't be dumped
=> fix dumping io - it should always be done in the stream wrapper

src/mongoc/mongoc-client.c
Avoid the use of cluster_try_sendv for healthy and unhealthy clusters.
It just needlessly avoids reconnects and persists the same errors.
=> CDRIVER-588 avoid cluster_try_sendv

src/mongoc/mongoc-client-pool.c, src/mongoc/mongoc-client.c, src/mongoc/mongoc-cluster-private.h, src/mongoc/mongoc-cluster.c, src/mongoc/mongoc-thread-private.h, src/mongoc/mongoc-topology-description.c, src/mongoc/mongoc-topology-private.h, src/mongoc/mongoc-topology-scanner-private.h, src/mongoc/mongoc-topology-scanner.c, src/mongoc/mongoc-topology.c, src/mongoc/mongoc-uri.c, tests/test-mongoc-topology.c
There's a bunch in here.
@ajdavis, mind taking a look to see if the logic is correct?
=> CDRIVER-594 fix all the SS/SDAM timers

build/autotools/versions.ldscript, build/cmake/libmongoc-ssl.def, build/cmake/libmongoc.def, src/libmongoc.symbols, src/mongoc/mongoc-client.c, src/mongoc/mongoc-cluster.c, src/mongoc/mongoc-gridfs.c, src/mongoc/mongoc-stream-buffered.c, src/mongoc/mongoc-stream-file.c, src/mongoc/mongoc-stream-gridfs.c, src/mongoc/mongoc-stream-socket.c, src/mongoc/mongoc-stream-tls.c, src/mongoc/mongoc-stream.c, src/mongoc/mongoc-stream.h, src/mongoc/mongoc-topology-scanner-private.h, src/mongoc/mongoc-topology-scanner.c
This adds a new `failed` handler to the mongoc_stream_t, along with
mongoc_stream_failed().
The failed handler shall be called when the stream truely needs to be
destroyed (due to errors, removal from topology, etc etc).
The destroy handler shall be called during normal _destroy() routines,
like mongoc_destroy().
By default, for BC, if no failed handler is provided we will fallback
and call the `destroy` handler.
=> CDRIVER-609: Differenciate between a failed stream, and cleanup/destroy

src/mongoc/mongoc-topology.c
Cancel after first blocking scan's timeout, not the second's.
In @bjori's example code for CDRIVER-610, the fix in this PR reduces the total runtime from 90 seconds to the expected 60 seconds on my system.
=> CDRIVER-594 Fix timeout in single-thread selection

src/mongoc/mongoc-stream-tls.c
See issue [CDRIVER-613](https://jira.mongodb.org/browse/CDRIVER-613).
=> ANSI C warnings

src/mongoc/mongoc-cursor-cursorid-private.h, src/mongoc/mongoc-cursor-cursorid.c
The PHP driver needs access to this structure, since it reimplements some of the logic within `_mongoc_cursor_cursorid_prime()`.
=> Move mongoc_cursor_cursorid_t typedef into private header

src/mongoc/mongoc-async.c, src/mongoc/mongoc-stream.c, tests/test-bulk.c
./autogen.sh --enable-tracing --enable-debug-symbols=full --enable-maintainer-flags=yes --enable-debug
src/mongoc/mongoc-async.c:68:26: warning: declaration of 'poll' shadows a global declaration [-Wshadow]
src/mongoc/mongoc-stream.c:310:27: warning: declaration of 'poll' shadows a global declaration [-Wshadow]
tests/test-bulk.c:301:34: warning: declaration of ‘index’ shadows a global declaration [-Wshadow]
=> Fix compiler warnings

CMakeLists.txt, CONTRIBUTING.md, build/autotools/CheckSasl.m4, build/cmake/FindSASL2.cmake, src/mongoc/mongoc-config.h.in, src/mongoc/mongoc-init.c, src/mongoc/mongoc-sasl.c, tests/Makefile.am, tests/test-libmongoc.c, tests/test-libmongoc.h, tests/test-sasl.c
https://jira.mongodb.org/browse/CDRIVER-530: SASL version check is wrong
https://jira.mongodb.org/browse/CDRIVER-547: properly use sasl_set_mutex, sasl_client_init, and sasl_client_done
Also, experimental support for building with SASL in CMake.
=> C Driver SASL fixes

src/mongoc/mongoc-client.c, src/mongoc/mongoc-log.c
Plus: ISO C90 forbids mixed declarations and code
=> Fix build on MSVC

src/mongoc/mongoc-init.c
https://jira.mongodb.org/browse/CDRIVER-731
=> CDRIVER-731: Do not trace SASL mutex callbacks

src/mongoc/mongoc-matcher-op.c
https://jira.mongodb.org/browse/CDRIVER-757
If the enum is compiled as an unsigned integer, this could trigger a type-limits warning (which might disrupt a -Werror build).
I only saw this when building on GCC, so I'm not sure if there's an equivalent clang warning we'd like to suppress.
=> CDRIVER-757: Suppress GCC warning for enum range check

tests/test-mongoc-collection.c
https://jira.mongodb.org/browse/CDRIVER-768
=> CDRIVER-768: Fix build warning for uninitialized value

src/mongoc/mongoc-log-private.h
the mongo-php-driver-prototype (pecl ext mongodb 1.0.0alpha2) needs this.
=> allow driver to use mongoc-log-private

src/mongoc/mongoc-cluster.c, src/mongoc/mongoc-cursor.c, src/mongoc/mongoc-host-list.c, src/mongoc/mongoc-sasl.c, src/mongoc/mongoc-server-description.c, src/mongoc/mongoc-ssl.c, src/mongoc/mongoc-topology-description.c, src/mongoc/mongoc-uri.c, src/mongoc/mongoc-util-private.h
This consolidates all of the Windows `strcasecmp` and `strncasecmp` checks into `mongoc-util-private.h`.
=> CDRIVER-593 strcasecmp

.gitmodules
was getting socket error timeouts on `git submodule update --init` within `autogen.sh`, this change makes it work as intended.
=> edits .gitmodules, fixes libbson url

src/mongoc/mongoc-gridfs-file.c
One should freely be able to seek in a file, even past `EOF`, as long as it isn't before the beginning of a file.
=> CDRIVER-849 allow seek past end-of-file

src/mongoc/mongoc-gridfs-file-private.h, src/mongoc/mongoc-gridfs-file.c, tests/test-mongoc-gridfs.c
Fixes an incorrect sign comparison when flushing.
Fixes an incorrect flush when the file's position pointer ends on a chunk boundary when writing to the database.
Added some tests to check the behavior of the driver on chunk boundaries and the like.
=> CDRIVER-765 fix gridfs flush

Makefile.am
Second attempt, now with correct names.
The correct flag is `--enable-html-docs`.
=> CDRIVER-886: fix wrong HTML docs configure flag

src/mongoc/mongoc-collection.c, tests/test-mongoc-collection.c
`mongoc_collection_aggregate()` will no longer destroy a failed cursor under certain circumstances. The error can be detected by the user on the next cursor operation.
This also tests an example of a failed aggregation with an incorrect pipeline.
=> CDRIVER-880: aggregation may return destroyed cursor

doc/mongoc_gridfs_file_seek.page, src/mongoc/mongoc-gridfs-file.c
`mongoc_gridfs_file_seek()` detects a few more errors. Importantly, it now prohibits seeks to a negative offset (before the start of a file).
=> CDRIVER-867: Errors for GridFS seek

src/mongoc/mongoc-gridfs-file.c
Callers of `_mongoc_grifs_file_refresh_page()` now check its value and fail appropriately. Failures during a query to the database set `file->failed` to true and place the error in `file->error`.
=> CDRIVER-871: check value of GridFS page refresh

src/mongoc/mongoc-gridfs-file-page.c, tests/test-mongoc-gridfs.c
We now properly manage a GridFS file's underlying buffers in a way that allows for interleaved reads and writes *without* requiring a save.
=> CDRIVER-511: Allow interleaving GridFS reads/writes

doc/Makefile.am
Running `make clean` now also cleans the generated HTML documentation and man pages. Yelp HTML files have been added to `CLEANFILES` as well.
There are also new rules for cleaning just the documentation: "html-clean" and "man-clean".
Thanks @bjori for the help and suggestions!
=> CDRIVER-822: clean generated documentation

build/generate-future-functions.py, tests/TestSuite.h, tests/mock_server/future-functions.c, tests/mock_server/future-functions.h, tests/mock_server/future-value.c, tests/mock_server/future-value.h, tests/mock_server/future.c, tests/mock_server/future.h, tests/test-mongoc-gridfs.c
This will make testing on GridFS feature branches much easier. Thanks @ajdavis !
Nitpick: In a future commit I want to investigate why `generate-future-functions.py` generates files with trailing whitespace.
=> [WIP] GridFS test improvements

README.rst, doc/installing.page
Both the README and the installation page have been updated, though in the future the README should simply point to the online docs for the best and most-detailed explanations.
=> CDRIVER-802: Mac OS X installation documentation

src/mongoc/mongoc-gridfs.c
Failure to create the GridFS indexes no longer leaks a pointer to a `mongoc_gridfs_t`.
=> CDRIVER-920: fix leak in `_mongoc_gridfs_new()`

src/mongoc/mongoc-gridfs-file-page-private.h, src/mongoc/mongoc-gridfs-file-page.c, src/mongoc/mongoc-gridfs-file.c, tests/test-mongoc-gridfs-file-page.c, tests/test-mongoc-gridfs.c
There are two big fixes in this pull request:
- Attempting to read after calling a seek past the end of file results in an error.
- Performing a write after seeking past the end of a file extends the file, filling in the "gap space" between the old end-of-file and the new write with zeros.
=> CDRIVER-870: sane GridFS behavior past end-of-file

README.rst
Stumbled across this while installing.
Came in from [CDRIVER-882](https://jira.mongodb.org/browse/CDRIVER-882) and its respective [commit](https://github.com/mongodb/mongo-c-driver/commit/c725c7e44e95c0d3762539caaffd715c66a1d42e).
[http://api.mongodb.org/mongo-c-driver/current/installing.html](http://api.mongodb.org/mongo-c-driver/current/installing.html) will 404; in documentation section for current readme you link to [http://api.mongodb.org/c/current/](http://api.mongodb.org/c/current/).
Feel free to not merge and fix it yourself :).
=> CDRIVER-882 update link to c driver manual

build/autotools/versions.ldscript, build/cmake/libmongoc-ssl.def, build/cmake/libmongoc.def, src/libmongoc.symbols, src/mongoc/mongoc-collection.c, src/mongoc/mongoc-collection.h, src/mongoc/mongoc-database.c, src/mongoc/mongoc-database.h, tests/test-mongoc-collection.c, tests/test-mongoc-database.c
This adds methods for copying `mongoc_database_t`'s and `mongoc_collection_t`'s.
These would be nice to add into the C++11 driver :) Happy to make changes if you have feedback!
=> CDRIVER-942 add copy methods for db and collection

build/rpm/mongo-c-driver.spec
rpmbuild (at least on CentOS 6) doesn't understand
the following date format in %changelog: Thu October 29 2015 ...
It requires short month names: Thu Oct 29 2015 ...
=> Fix date specfile date format

src/mongoc/mongoc-database.c
If an invalid namespace is supplied to mongoc_database_has_collection the cursor that is used in this function is not freed causing a memory leak every time the function is called. This leads to a drastic increase in memory consumption if the function is called frequently.
=> Removed memory leak in function mongoc_database_has_collection

src/mongoc/mongoc-log.c
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.
=> Refactoring conditional directives that break statements.

src/mongoc/mongoc-cursor.c
See also [[CDRIVER-1041]](https://jira.mongodb.org/browse/CDRIVER-1041).
=> use bson_strnlen when strnlen is not available

src/mongoc/mongoc-cursor-private.h, src/mongoc/mongoc-cursor.c, tests/test-mongoc-collection-find.c
https://jira.mongodb.org/browse/CDRIVER-1054
This adds internal support for specifying a negative cursor limit (i.e. single-batch mode) for both OP_QUERY and find command code paths. Note that this does not change the public API, which will be handled for 2.0 by CDRIVER-1053.
=> CDRIVER-1054: Support negative cursor limit

tests/test-libmongoc.c, tests/test-libmongoc.h, tests/test-mongoc-topology.c
In Fedora infrastructure, builder don't have internet access.
So test suite fails, see https://kojipkgs.fedoraproject.org//work/tasks/7900/13177900/build.log
FAIL
Assert Failure: "No suitable servers found (`serverselectiontryonce` set): [Failed to resolve 'doesntexist'] [Failed to resolve 'example.com']" does not contain "[connection error calling ismaster on 'example.com:2']"
This small enhancement allow to define SKIP_INLINE env. var. before running to skip such test (for now there is only 1)
=> allow to skip online tests

doc/mongoc_client_select_server.page, src/mongoc/mongoc-client.c, src/mongoc/mongoc-client.h
Noticed while implementing [PHPC-607](https://jira.mongodb.org/browse/PHPC-607). This seemed like an oversight compared to the private `mongoc_topology_select()` function and other client functions that accept a read preference.
Related to: https://github.com/mongodb/mongo-c-driver/commit/929e8590a0ff49979ff83cc8175844d8aa992890
=> CDRIVER-1096: Use const for mongoc_client_select_server() read prefs

src/mongoc/mongoc-secure-transport.c
Fixes a compiler warning for "/* within comment"
Feel free to take or leave this, but it seemed trivial to fix without sacrificing the readability of the comment (more so than disabling -Wcomment for the build on PHPC's end).
=> Rewrite comment to avoid -Wcomment warning

src/mongoc/mongoc-server-description.c, src/mongoc/mongoc-topology-description.c
https://jira.mongodb.org/browse/CDRIVER-1198
This PR is split off from https://github.com/mongodb/mongo-c-driver/pull/322 to remove publication of the server description's type enum.
=> CDRIVER-1198: Use strings for server and topology types in SDAM transition logs

src/mongoc/mongoc-cursor-private.h
Realized this while researching [PHPC-688](https://jira.mongodb.org/browse/PHPC-688). I'm not sure when libmongoc stopped using the `stamp` field, but I found no reference to it within the project.
Let me know if you'd like a JIRA ticket for this; I found no reference to a "stamp" among CDRIVER tickets. The concept of a cursor stamp dates back to https://github.com/mongodb/mongo-c-driver/commit/d6e191612c84e33bf06ee85b242a115542e7bed3 but that method has been removed for some time. This is likely just cleaning up dead code.
=> Remove unused stamp field on _mongoc_cursor_t struct

CMakeLists.txt, build/autotools/CheckSSL.m4, src/mongoc/mongoc-config.h.in, src/mongoc/mongoc-openssl.c
See : https://jira.mongodb.org/browse/CDRIVER-1231
* for autotools, add the --enable-system-crypto-profile build option
* for cmake, add the -DENABLE_SYSTEM_CRYPTO_PROFILE:BOOL=ON build option
In both case, default to off, so no change for standard build.
=> CDRIVER-1231 Allow to use system crypto policies

src/mongoc/mongoc-cluster.c
This fixes calls introduced in e8f031a6deb7d0fdea10ba2161d9fb5b56fa6e8e.
I noticed this when compiling a recently bumped libmongoc submodule with PHPC, where we utilize stricter build checks. Original error was:
```
In file included from /home/jmikola/workspace/mongodb/phpc/src/libmongoc/src/mongoc/mongoc-cluster.c:50:0:
/home/jmikola/workspace/mongodb/phpc/src/libmongoc/src/mongoc/mongoc-cluster.c: In function ‘_mongoc_cluster_auth_node_x509’:
/home/jmikola/workspace/mongodb/phpc/src/libmongoc/src/mongoc/mongoc-trace.h:34:135: error: expected expression before ‘)’ token
do { mongoc_log(MONGOC_LOG_LEVEL_TRACE, MONGOC_LOG_DOMAIN, "TRACE: %s():%d " msg, BSON_FUNC, __LINE__, __VA_ARGS__); } while (0)
^
/home/jmikola/workspace/mongodb/phpc/src/libmongoc/src/mongoc/mongoc-cluster.c:1037:7: …
```
=> TRACE() macro requires var args

tests/abicheck.sh
We encounter recent failure because of this script.
See: https://bugzilla.redhat.com/1345868
And : https://apps.fedoraproject.org/koschei/package/mongo-c-driver
Build is back to "green" thanks to this minor fix.
=> avoid abicheck failure

doc/mongoc_collection_validate.page, src/mongoc/mongoc-collection.c, tests/test-mongoc-collection.c
I guess I forgot to make a pull request for this. Here's the CR link:
https://mongodbcr.appspot.com/79000001/
=> CDRIVER-1328 reply is always initialized in mongoc_collection_validate

CMakeLists.txt, build/autotools/ReadCommandLineArguments.m4, build/cmake/libmongoc-experimental.def, build/cmake/libmongoc-ssl-experimental.def, build/cmake/libmongoc-ssl.def, build/cmake/libmongoc.def, src/mongoc/Makefile.am, src/mongoc/mongoc-client-pool.c, src/mongoc/mongoc-client-pool.h, src/mongoc/mongoc-client.c, src/mongoc/mongoc-client.h, src/mongoc/mongoc-config.h.in, src/mongoc/mongoc-init.c, src/mongoc/mongoc-read-prefs.c, src/mongoc/mongoc-read-prefs.h, src/mongoc/mongoc-server-description.c, src/mongoc/mongoc-topology-scanner.c, src/mongoc/mongoc-topology.c, src/mongoc/mongoc-uri.c, src/mongoc/mongoc.h, tests/Makefile.am, tests/json-test.c, tests/test-conveniences.c, tests/test-libmongoc.c, tests/test-mongoc-client-pool.c, tests/test-mongoc-client.c, tests/test-mongoc-collection.c
Only change I made from the CR was to remove metadata_append, client_set_appname and client_pool_set_appname from libmongoc.def and libmongoc-ssl.def (so now it's only in the "-experimental" files)
=> CDRIVER-1393 put metadata and max_staleness behind MONGOC_EXPERIMENTAL_FEATURE

build/autotools/versions.ldscript, build/cmake/libmongoc-ssl.def, build/cmake/libmongoc.def, src/libmongoc.symbols, src/mongoc/mongoc-write-concern.c, src/mongoc/mongoc-write-concern.h, tests/test-mongoc-write-concern.c
Function that helps users append writeConcerns to commands before passing them into generic functions.
=> CDRIVER-1384: added mongoc_write_concern_append

build/cmake/libmongoc-experimental.def, build/cmake/libmongoc-ssl-experimental.def, doc/mongoc_write_concern_append.page
Added mongoc_write_concern_append symbol to build/cmake/*-experimental.def files, and added symbol page to documentation.
=> CDRIVER-1384: add symbol to doc, *experimental.def

tests/test-mongoc-collection.c
$out pipeline stage is not supported in other versions
=> CDRIVER-1415: enable test for wire version 2+ only

src/mongoc/mongoc-collection.c, src/mongoc/mongoc-cursor-private.h, src/mongoc/mongoc-cursor.c
added writeConcern to cursor, and appended writeConcern to command inside _mongoc_cursor_run_command instead of inside mongoc_collection_aggregate_with_write_concern.
=> CDRIVER-1414: add mongoc_write_concern_t to mongoc_cursor_t

src/mongoc/mongoc-cursor.c, src/mongoc/mongoc-write-concern.c, tests/test-mongoc-collection.c
add is_default in mongoc_write_concern_copy. if there is a writeConcernError parse it out and return false
=> CDRIVER-1414: parse writeConcernErrors in command helper

src/mongoc/mongoc-client-private.h, src/mongoc/mongoc-client.c, tests/test-mongoc-client.c
implemented private client command function that takes writeConcern parameter. append valid writeConcern to command if writeConcern has been modified since creation, and server is the correct version.
=> CDRIVER-1448: _mongoc_client_command_with_write_concern

src/mongoc/mongoc-client.c, src/mongoc/mongoc-collection.c, tests/test-mongoc-collection.c
mongoc_collection_drop_with_write_concern: on writeConcernError, parse writeConcernError and return false.
=> CDRIVER-1460: collection_drop, parse wc err and return false

src/mongoc/mongoc-log.h
Patch signed off by @bjori in Rietveld; merge at will.  Thanks!
=> CDRIVER-1347 Add missing BSON_API specifier to mongoc_log_set_handler

tests/test-mongoc-handshake.c
platform can be truncated in _append_platform_field (according to doc length, HANDSHAKE_MAX_SIZE...)
=> CDRIVER-1702 don't fail when returned platform is truncated

tests/Makefile.am
Minimal fix.
Probably more needed (for installation)
=> CDRIVER-1703 missing files in archive

debian/libmongoc-dev.install
Resolves lintian warning brace-expansion-in-debhelper-config-file, "This
debhelper config file appears to use shell brace expansion. This happens
to work due to an accident of implementation but is not a supported
feature."
=> no braces in debian install script

README.rst
I should probably bookmark the c docs, but I always come to the README to get to them. 
`http://api.mongodb.org/c/current/` redirects to `http://mongoc.org/` so I updated that as well.
=> Update README links to mongoc host

src/mongoc/mongoc-handshake.c
See https://jira.mongodb.org/browse/CDRIVER-1935
=> DWORD is unsigned long, fixes CDRIVER-1935

src/mongoc/mongoc-set.c
If `items_len == 0` then `malloc(items_len) == NULL` which results in `memcpy(NULL, ...)` which is undefined behaviour.
=> fix UBSAN problem

src/mongoc/mongoc-counters-private.h
When using the `RDTSCP` instruction, the register `rcx` contains the value of the low-order 32-bits of `IA32_TSC_AUX MSR`, which is loaded for each processor by the Linux kernel to contain the processor number in the `11:0` bits and the node number in the `31:12` bits. So for machines with only one node, or when the process is running on the 0th node, the previous implementation of the code worked. However, when the node ID is not 0, the code would return the entire result of register `rcx`, which could be an invalid number because it would be a combination of the core number plus and number. E.g., on a machine with 2 nodes, if the thread is running on CPU core 61 located on node 1, the previous implementation would return a value of 4157 (61 + 4096), where 4096 comes from the 12th bit of …
=> CDRIVER-1946 SEGFAULT with fast performance counters on NUMA

src/mongoc/mongoc-gridfs-file.h
When using clang to export modules, functions set of
mongo_gridfs_file_set_xxx couldn’t export to destination simply because
only the getting methods were marked with BSON_API. Typical scenario is
a third party exporting, such as c library exporting for Swift
language.
Script test-libmongoc, which includes GridFS, passed.
This issue was found by Kyle Jessup and Rockford Wei,
perfect.org
=> Fixing gridfs_file_set_xxx wouldn’t export to module map.

tests/test-mongoc-collection.c
From test_create_index_fail, requires internet connectivity (DNS):
client = mongoc_client_new ("mongodb://example.com/?connectTimeoutMS=10");
trivial fix
=> CDRIVER-2042 skip test_create_index_fail when offline

src/mongoc/mongoc-cursor.c, tests/test-mongoc-cursor.c
https://jira.mongodb.org/browse/CDRIVER-2072
`mongoc_cursor_destroy()` always attempts to destroy these documents, which would previously crash if they were left uninitialized when an error was reported by `_mongoc_cursor_new_with_opts()`.
=> CDRIVER-2072: Always initialize cursor filter and opts

build/autotools/m4/ax_prototype.m4
This avoids a possible autoheader warning when calling AC_DEFINE with less than three arguments.
See: https://lists.gnu.org/archive/html/autoconf/2009-04/msg00087.html
This resolves an issue when including this m4 file in the PHP driver:
```
$ phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
autoheader: warning: missing template: ACCEPT_ARG2
autoheader: Use AC_DEFINE([ACCEPT_ARG2], [], [Description])
autoheader: warning: missing template: ACCEPT_ARG3
```
If it's relevant, my environment was using autoheader 2.6.9.
Related to: https://github.com/mongodb/mongo-c-driver/commit/63757304e5e97a8beb4f6d1bac18c7723a6f421d
=> Supply description argument to AC_DEFINE

src/mongoc/mongoc-stream-tls-openssl.c
LibreSSL forked from 1.0.1f, this 1.0.2 method is unavailable
In the tree I also see separate sources for LibreSSL but apparently these aren't used. Detection of LibreSSL not going well in configure?
=> Fix LibreSSL build issue

src/mongoc/mongoc-uri.c
The default return was changed to false in 16d03dc58f598c1671d20d658681c0d871f96514, which means we need only check for known options.
=> Remove unnecessary string comparisons in mongoc_uri_option_is_utf8()

src/mongoc/mongoc-uri.c
https://jira.mongodb.org/browse/CDRIVER-2142
=> CDRIVER-2141: Set error if authSource is invalid GSSAPI and X509

build/autotools/Versions.m4
https://jira.mongodb.org/browse/CDRIVER-2297
=> CDRIVER-2297: Space out parents to avoid unterminated string error

CMakeLists.txt
Unable to configure against `LibreSSL` on Alpine.
```sh
cmake -DENABLE_SSL=LIBRESSL
```
```sh
CMake Error at CMakeLists.txt:9 (_message):   
ENABLE_SSL option must be DARWIN, WINDOWS, OPENSSL, AUTO, or OFF
```
[1.8.0/CMakeLists.txt#L113-L115](https://github.com/mongodb/mongo-c-driver/blob/1.8.0/CMakeLists.txt#L113-L115):
```cmake
if (ENABLE_SSL STREQUAL LIBRESSL)
set (LIBRESSL 1)
endif ()
```
This condition will never be executed.
=> Add the missing CMake LIBRESSL option

src/mongoc/mongoc-uri.c
This suddenly started creating "double dots" in the the PHP driver:
```
006+ Failed to parse MongoDB URI: 'mongodb://127.0.0.1/?w=-1&journal=true'. Journal conflicts with w value [w=-1]..
006- Failed to parse MongoDB URI: 'mongodb://127.0.0.1/?w=-1&journal=true'. Invalid writeConcern.
008+ Failed to parse MongoDB URI: 'mongodb://127.0.0.1/?w=0&journal=true'. Journal conflicts with w value [w=0]..
008- Failed to parse MongoDB URI: 'mongodb://127.0.0.1/?w=0&journal=true'. Invalid writeConcern.
```
=> remove dot at end of sentence in new error message

src/mongoc/mongoc-bulk-operation.c
Fixed monogc_bulk_operation_execute() so that it behaves as documented
and always initializes the reply bson_t before returning.
=> CDRIVER-2384 Fixed reply not being initialized

build/autotools/CheckSnappy.m4, build/autotools/CheckZlib.m4
*_LIBS often contains library paths (-L) if returned by pkg-config.
Stripping them out causes the snappy and zlib libraries to not be found if they are not installed in a system library path.
This happens with (at least) the libmongoc package in Spack (https://github.com/spack/spack).
=> Do not overwrite {SNAPPY,ZLIB}_LIBS for system versions

examples/example-gridfs.c
Fixes issue : 
mongoc: A '/' is required between the host list and any options.
mongoc: Error parsing URI: 'Invalid host string in URI'
mongoc_uri_parse_hosts in mongoc/mongoc-uri.c  expects '/' between host list and options.
=> Fix :Error parsing URI: Invalid host string in URI

src/mongoc/mongoc-client-session.c
I assume anything with `EXIT` should also have an `ENTRY`. Noticed this was imbalanced while looking at some trace logs.
=> Missing ENTRY in advance_operation_time

src/mongoc/mongoc-util.c
`_mongoc_validate_update()` validates the `newObj` parameter. The selector (i.e. first argument for update and replace) is not validated by these util functions.
This fixes the change introduced in [this commit](https://github.com/mongodb/mongo-c-driver/commit/0c9cc9d26728d3cf4dd84e1fe91e75ca40e9a7fd#diff-305c362b208afd140b9f4230bf871ad4R347).
=> CDRIVER-2256 fix _mongoc_validate_update errmsg

NEWS, doc/includes/crud-opts.txt, src/mongoc/mongoc-bulk-operation.c, src/mongoc/mongoc-collection.c, src/mongoc/mongoc-util-private.h, src/mongoc/mongoc-util.c, tests/test-mongoc-collection.c
User can now pass bson_validate_flags_t to update/insert functions via "validate" field in the opt.
=> CDRIVER-2296 pass bson_validate_flags_t to update/insert functions

CMakeLists.txt, src/mongoc/mongoc-cluster-sspi.c, src/mongoc/mongoc-socket.c, src/mongoc/mongoc-sspi-private.h, src/mongoc/mongoc-util.c
This fixes two compiler warnings on mingw-w64:
```c
mongoc/mongoc-socket.c: In function 'mongoc_socket_close':
mongoc/mongoc-socket.c:774:4: warning: implicit declaration of function 'getpid' [-Wimplicit-function-declaration]
owned = (sock->pid == (int) getpid ());
^
```
This PR switched to `_getpid()` on Windows (which is already used elsewhere in the code).
```c
mongoc/mongoc-util.c -o mongoc/mongoc-util.o
mongoc/mongoc-util.c: In function '_mongoc_rand_simple':
mongoc/mongoc-util.c:33:4: warning: implicit declaration of function 'rand_s' [-Wimplicit-function-declaration]
err = rand_s (&ret);
^
```
The [windows documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand-s) says:
> The `rand_s` function requires that constant `_CRT_RAND_S` be defined prior to the …
=> Windows: fixes for implicit declaration of functions

src/mongoc/mongoc-cluster-sspi.c, src/mongoc/mongoc-socket.c
Ran into a few more warnings on mingw-w64. These are (hopefully) the final windows fixes I need.
Fixed two `-Wunused` warnings:
```c
mongoc/mongoc-socket.c:354:9: warning: unused variable 'optval'
mongoc/mongoc-cluster-sspi.c:152:18: warning: variable 'options' set but not used
```
Fixed missing `#include process.h` for `_getpid()`:
```c
mongoc/mongoc-socket.c:775:4: warning: implicit declaration of function '_getpid'
```
And a `-pedantic` warning about variadic args:
```c
mongoc/mongoc-socket.c:419:46: warning: ISO C99 requires rest arguments to be used
mongoc/mongoc-socket.c:421:40: warning: ISO C99 requires rest arguments to be used
```
Thank you for reviewing!
=> Windows: fix compiler warnings

src/mongoc/mongoc-client.c, src/mongoc/mongoc-cmd.c, tests/test-mongoc-client.c
https://jira.mongodb.org/browse/CDRIVER-2431
`clang-format` picked up bad formatting in `mongoc-client.c`, which I split off into a separate commit.
=>  CDRIVER-2431 check for empty command before comparing name

src/mongoc/mongoc-cluster.c
https://jira.mongodb.org/browse/CDRIVER-2449
Per [exceptions to sending the session ID to the server on all commands](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#exceptions-to-sending-the-session-id-to-the-server-on-all-commands), we should omit `lsid` from authentication commands and may also do so for monitoring commands. The spec only mentions `isMaster` for monitoring, but libmongoc uses `ping` for that purpose as well.
=> CDRIVER-2449 omit lsid from auth and monitoring commands

.gdbinit, CONTRIBUTING.md
This PR implements the 'printbson' function in a ``.gdbinit`` file to print ``bson_t*`` values.
An example of an output is:
```
(gdb) printbson bson
ALLOC [0x555556cd7310 + 0] (len=475)
{
'bool' : true,
'int32' : NumberInt("42"),
'int64' : NumberLong("3000000042"),
'string' : "Stŕìñg",
'objectId' : ObjectID("5A1442F3122D331C3C6757E1"),
'utcDateTime' : UTCDateTime(1511277299031),
'arrayOfInts' : [
'0' : NumberInt("1"),
'1' : NumberInt("2"),
'2' : NumberInt("3"),
'3' : NumberInt("5"),
'4' : NumberInt("8"),
'5' : NumberInt("13"),
'6' : NumberInt("21"),
'7' : NumberInt("34")
],
'embeddedDocument' : {
'arrayOfStrings' : [
'0' : "one",
'1' : "two",
'2' : "three"
],
'double' : 2.718280,
'notherDoc' : {
'true' : NumberInt("1"),
'false' : false
}
},
'binary' : Binary("02", "3031343532333637"), …
```
=> Add .gdbinit file that exposes a 'printbson' function to dump a bson_t*

.gitignore
This likely should have been removed as part of [CDRIVER-2369](https://jira.mongodb.org/browse/CDRIVER-2369).
=> CDRIVER-2369 remove bundled snappy from .gitignore

src/mongoc/mongoc-topology.c, tests/test-mongoc-sdam-monitoring.c
While most callbacks were correctly disabled when passing in `NULL`, this was not the case for topology events. This adds a fix for that, and a test - just a slight modification of `_test_topology_events` - confirming that the last event is *not* topology closed. 
Also, I guess clang-format caught a lingering error in `mongoc-topology.c`... if you'd rather I remove that from this PR let me know.
=> Disable topology event callbacks when NULL is passed in

doc/mongoc_apm_callbacks_t.rst, doc/mongoc_apm_set_server_changed_cb.rst, doc/mongoc_apm_set_server_closed_cb.rst, doc/mongoc_apm_set_server_heartbeat_failed_cb.rst, doc/mongoc_apm_set_server_heartbeat_started_cb.rst, doc/mongoc_apm_set_server_heartbeat_succeeded_cb.rst, doc/mongoc_apm_set_server_opening_cb.rst, doc/mongoc_apm_set_topology_changed_cb.rst, doc/mongoc_apm_set_topology_closed_cb.rst, doc/mongoc_apm_set_topology_opening_cb.rst
sphinx generated all the HTML files and man pages without complaining. the HTML pages look correct to me in the browser, and I just used `groff -man -Tascii [filename]` to check that the man pages as plaintext looked reasonable/matched the existing ones - is there is some other way I should check those, let me know.
=> CDRIVER-2577 add missing docs for setting SDAM monitoring callbacks

tests/mock_server/mock-rs.c
This makes isMaster consistent with `mock_mongos_new()`.
I originally developed this while investigating a fix for https://github.com/mongodb/mongo-c-driver/pull/494, but ended up not needing it. I still think there's value in the changes, and they didn't appear to break any existing mock tests across the driver.
=>  Add additional 3.6 fields in mock replica set isMaster

src/mongoc/mongoc-cmd.c, tests/test-mongoc-cluster.c
https://jira.mongodb.org/browse/CDRIVER-2439
This addresses an edge case where an explicit session's cluster time may have been manually advanced. Under normal usage, sessions used with a standalone will always have an empty cluster time.
=> CDRIVER-2439 don't gossip cluster time to standalones

.evergreen/config.yml
This was already reviewed by @kevinAlbs but I do not have push permission I needed to open a pull request. 
Description from earlier CR:
There is a rare crash on Windows SSL with MongoDB that I would like to get a dump for. As such, I have migrated the Server's evergreen support for collecting crash dumps to the C Driver.
MDMP
Mongo Orchestration is running mongodb from c:\mongodb. Example is from the log in SERVER-35125
2018-05-21T16:23:22.131+0000 I CONTROL [conn9] writing minidump diagnostic file c:\mongodb\bin\mongod.2018-05-21T16-23-22.mdmp
Linux
MongoDB Evergreen hosts generate crashdumps with .core
=> CDRIVER-2658 Save minidump files if mongodb crashes during test

src/libmongoc/src/mongoc/mongoc-async-cmd.c
Arithmetic on a pointer to void is a GNU extension [-Wpointer-arith]
=> Fix warning: arithmetic on a pointer to void

src/libbson/src/bson/bson-compat.h, src/libmongoc/src/mongoc/mongoc-iovec.h
Fix macro redefinition warning when including <inttypes.h> after mongoc.h using Visual Studio 2013 or newer.
Fix iov_len in mongoc_iovec_t on Windows to be size_t like on Linux
=> Fix two warnings when using mongoc.h with the Visual Studio compiler

src/libmongoc/doc/mongoc_collection_insert_many.rst, src/libmongoc/doc/mongoc_collection_update_many.rst, src/libmongoc/doc/mongoc_collection_update_one.rst
`update_one` and `update_many` were inconsistent with other methods.
Since `insert_many` is technically a bulk write, its reply may include multiple `writeErrors` alongside `writeConcernErrors` (with one subdocument). Revise that language and reference the bulk write examples to avoid repetition.
=> Improve documentation for CRUD replies

src/libbson/src/bson/bson-iso8601.c
See issue https://github.com/jeroen/mongolite/issues/163
This ensures that leading zero's get included in the ms part of a datetime. Currently dates get printed like this: `1998-11-07T00:00:00. 23Z` (note the blank instead of 0).
=> Print leading zeros in datetime ms

src/libbson/CMakeLists.txt, src/libmongoc/CMakeLists.txt
Internally we rename the libraries we integrate as to avoid interference with the library versions already available on the target systems by giving them a prefix.
This PR allows users to specify, for example:
```
-DBSON_OUTPUT_BASENAME:STRING=MYORG_bson
-DMONGOC_OUTPUT_BASENAME:STRING=MYORG_mongoc
```
I used `BASENAME` as the flavor and/or version are appended later.
Alternatively, it would be also fine for us to add a prefix variable like `OUTPUT_NAME_PREFIX` or so but I was unable to find a good name that cannot be confused the target `PREFIX` property (e.g. `lib`)
=> Allow libbson and libmongoc library names to be changed externally

src/libmongoc/CMakeLists.txt, src/libmongoc/src/mongoc/mongoc-config.h.in, src/libmongoc/src/mongoc/mongoc-socket.h
See issue https://github.com/mongodb/mongo-c-driver/pull/562.
Correct way to find ``ss_family`` on AIX 5+.
Tested on AIX 6.1. It compiles and the whole test suite is OK.
=> Fix __ss_family build issue on AIX6.1

src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
I encountered the following build warning when compiling PHPC with bundled libmongoc and FLE: 
```
/home/jmikola/workspace/mongodb/phpc/src/libmongoc/src/libmongoc/src/mongoc/mongoc-client-side-encryption.c: In function ‘_log_callback’:
/home/jmikola/workspace/mongodb/phpc/src/libmongoc/src/libmongoc/src/mongoc/mongoc-client-side-encryption.c:978:46: warning: too many arguments for format [-Wformat-extra-args]
mongoc_log (log_level, MONGOC_LOG_DOMAIN, "%s", message, NULL);
```
=> Remove extra arg in mongoc_log call

src/libbson/src/bson/bson-macros.h
I am not sure why Windows is special cased here, but mingw-w64 / gcc needs the same logic as other systems, otherwise we get compiler warnings about non-standard c99.
=> Fix for mingw-w64 Windows build

src/libbson/src/bson/bson-macros.h, src/libmongoc/src/mongoc/mongoc-buffer.c, src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/src/mongoc/mongoc-database.c, src/libmongoc/src/mongoc/mongoc-stream.c
This pull request makes a change to the way the mongoc driver reports encountering `NULL` in function parameters where a non `NULL` pointer is expected. Currently, a confusing error message is given:
```
mongoc_collection_count_documents(): precondition failed: coll
```
This arises from the  `BSON_ASSERT` macro, defined as:
```c
#define BSON_ASSERT(test)                                  \
do {                                                    \
if (!(BSON_LIKELY (test))) {                         \
fprintf (stderr,                                  \
"%s:%d %s(): precondition failed: %s\n", \
__FILE__,                                \
__LINE__,                                \
BSON_FUNC,                               \
#test);                                  \
abort (); …
```
=> Improve error messaging when a NULL parameter is encountered.

src/libmongoc/src/mongoc/mongoc-topology-description.c, src/libmongoc/src/mongoc/mongoc-trace-private.h, src/libmongoc/tests/json/server_discovery_and_monitoring/single/direct_connection_wrong_set_name.json
For a topology type single, if the user specified a setName in the URI, the server should be marked Unknown if it reports a different setName.
=> CDRIVER-3619 reject bad setname for single topology

src/libmongoc/tests/test-mongoc-long-namespace.c, src/libmongoc/tests/test-mongoc-primary-stepdown.c, src/libmongoc/tests/test-mongoc-retryable-reads.c, src/libmongoc/tests/test-mongoc-retryable-writes.c
The "ns not found" error has changed on the server to include more info. This changes our exact match checks to substring checks. Fixes failing "latest" tests on master.
=>  CDRIVER-3655 handle new 'ns not found' err format

.evergreen/config.yml, build/evergreen_config_lib/functions.py
Not all evergreen variants have a new enough version of git to run calc_release_version.py on a non-master branch. This fixes patch builds made through GitHub PRs
=> CDRIVER-3573 hard code version on patches

src/libmongoc/tests/test-mongoc-cmd.c
I apparently neglected to run clang-format on my previous change that created `test-mongoc-cmd.c`.
=> clang-format fixes

src/libmongoc/tests/test-mongoc-cluster.c
Full Evergreen patch build: https://evergreen.mongodb.com/version/5ec30e00d1fe073c378f2bc7
=> CDRIVER-3596 tweak cluster_time tests for valgrind environment

.evergreen/config.yml, build/evergreen_config_lib/tasks.py
From a patch build, it appears they take 3.5 hours to fully execute.
https://evergreen.mongodb.com/version/5ec3d728d1fe073c379213e9
=> CDRIVER-3680 bump valgrind timeout

src/libmongoc/tests/test-mongoc-topology.c
CDRIVER-3615 changed an exotic edge case for parsing errors.
An error with a NotMaster error code, but a "node is recovering" message
is considered a "node is recovering" error for multi-threaded error
handling. So requested scan is expected.
A "node is recovering" error should request scan for multi-threaded, not
single-threaded scanning. The test was making a wrong assertion, but the
check of the assertion was very racy.
This fixes the test and increases the wait to make the test less racy.
=> CDRIVER-3678 fix /Topology/request_scan_on_error

src/libmongoc/tests/mock_server/mock-server.c, src/libmongoc/tests/test-libmongoc.c
This is not urgent. This, and some other test fixes from https://github.com/mongodb/mongo-c-driver/pull/607 are prerequisites for adding a thread-sanitizer task to evergreen to automatically check for thread related bugs.
mock_server_hangs_up and mock_server_resets were closing a request stream directly from the main thread. But a request stream should only be accessed by the worker thread. This now adds a special reply to the worker thread's queue to signal a hangup or reset.
=> CDRIVER-748 fix mock server for TSAN

src/libmongoc/doc/mongoc_apm_server_heartbeat_failed_get_awaited.rst, src/libmongoc/doc/mongoc_apm_server_heartbeat_failed_t.rst, src/libmongoc/doc/mongoc_apm_server_heartbeat_started_get_awaited.rst, src/libmongoc/doc/mongoc_apm_server_heartbeat_started_t.rst, src/libmongoc/doc/mongoc_apm_server_heartbeat_succeeded_get_awaited.rst, src/libmongoc/doc/mongoc_apm_server_heartbeat_succeeded_t.rst, src/libmongoc/src/mongoc/mongoc-apm-private.h, src/libmongoc/src/mongoc/mongoc-apm.c, src/libmongoc/src/mongoc/mongoc-apm.h, src/libmongoc/src/mongoc/mongoc-topology-scanner.c, src/libmongoc/tests/test-mongoc-sdam-monitoring.c
A small isolated chunk of streamable ismaster to add an `awaited` field to heartbeat started/succeeded/failed events. It was added as part of this spec change: https://github.com/mongodb/specifications/commit/a813663112d2ec67b71925f62b2363c79ce4478a
Currently `awaited` is always false, but after streamable ismaster, it will be true for awaitable isMaster commands.
=> CDRIVER-3535 add awaited to heartbeat events

.evergreen/config.yml, build/evergreen_config_lib/tasks.py, src/libmongoc/src/mongoc/mongoc-crypt.c, src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel.c, src/libmongoc/src/mongoc/mongoc-topology-description.c, src/libmongoc/src/mongoc/mongoc-topology.c, src/libmongoc/tests/test-mongoc-topology.c
Fix gcc warnings for `TRACE` macros with a single string argument (and trailing NULL).
clang doesn't warn for this, but I saw the same warnings with gcc 5.4 in a VM.
Also fixes a couple other warnings I observed, and adds `-Werror` to the evergreen task that builds with tracing. That builds with gcc 5.4. It was already logging warnings:
https://evergreen.mongodb.com/task_log_raw/mongo_c_driver_releng_compile_tracing_e0be759b857bbafb7cdfa9b543c927e94ff27871_20_06_03_18_22_13/0?type=T#L505 but was not treating them as build failures.
=> CDRIVER-3701 fix TRACE macro warnings

.gitignore
These sometimes show up after compiling the libmongoc submodule for PHPC (often after a failed build). I don't believe they have any permanence, so it should be reasonable to ignore them.
=> Ignore libtool object files

.evergreen/config.yml, build/evergreen_config_lib/tasks.py, build/evergreen_config_lib/variants.py, src/libmongoc/CMakeLists.txt, src/libmongoc/doc/configuring_tls.rst, src/libmongoc/src/mongoc/mongoc-ocsp-cache.c, src/libmongoc/src/mongoc/mongoc-openssl-private.h, src/libmongoc/src/mongoc/mongoc-openssl.c, src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-private.h, src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.c, src/libmongoc/src/mongoc/mongoc-uri.c, src/libmongoc/tests/test-libmongoc.c, src/libmongoc/tests/test-mongoc-ocsp-cache.c, src/libmongoc/tests/test-mongoc-uri.c, src/libmongoc/tests/test-mongoc-x509.c
Adds polyfills and makes a few tweaks to support OpenSSL back to 1.0.1.
Summary of changes:
- change SSL_CTX_set_tlsext_status_type to SSL_set_tlsext_status_type.
- polyfill SSL_get0_verified_chain, NID_tlsfeature, and hostname check.
- check for status_request from the tlsfeature extension when inspecting peer certificate.
- skip time check for older OpenSSL when updating cache entries.
- perform the OCSP check after the handshake, since sometimes the peer certificate is not available in the callback in OpenSSL <= 1.0.2.
- check tlsDisableOCSPEndpointCheck before reaching out to a responder.
- make tlsDisableOCSPEndpointCheck and tlsDisableCertificateRevocationCheck URI options implicitly enable TLS.
- enable OCSP tests on OpenSSL and macOS that were skipped.
- add OCSP tests for OpenSSL …
=> CDRIVER-3668 support OCSP back to OpenSSL 1.0.1

.evergreen/debian_package_build.sh, debian/rules
The two commits in this PR:
* address the bug identified in CDRIVER-3704
* fix the persistent failure in the `debian-package-build` task by installing build dependencies from within the chroot environment
Evergreen patch build: https://evergreen.mongodb.com/version/5edc5eb0306615560ebd3eff
=> Cdriver 3704

.evergreen/config.yml, build/evergreen_config_lib/tasks.py, build/evergreen_config_lib/variants.py, src/libmongoc/tests/test-libmongoc.c, src/libmongoc/tests/test-libmongoc.h, src/libmongoc/tests/test-mongoc-client.c
Until SERVER-48715 is resolved, skip tests with auth against a >4.4 replica set that rely on arbiters being discovered.
Also skips the test failure described in CDRIVER-3709.
[CDRIVER-3708](https://jira.mongodb.org/browse/CDRIVER-3708) has more context.
=> CDRIVER-3708 skip two tests on latest auth replset

src/libmongoc/src/mongoc/mongoc-buffer.c
Removed memmove calls that are a logical no-op.
=> removed superfluous memmove calls in mongoc-buffer.c

src/libmongoc/src/mongoc/mongoc-cluster-cyrus.c, src/libmongoc/src/mongoc/mongoc-cluster.c
Adds null checks after all calls to _mongoc_cluster_create_server_stream
=> CDRIVER-3539 null checks after calls to _mongoc_cluster_create_server_stream

src/libmongoc/doc/connection-pooling.rst
Multi-threaded monitoring now creates separate threads per server (up
to two per server after CDRIVER-3535).
=> CDRIVER-3722 update docs for bg scanning

src/libmongoc/src/mongoc/mongoc-buffer.c, src/libmongoc/src/mongoc/mongoc-client-session-private.h, src/libmongoc/src/mongoc/mongoc-client-session.c, src/libmongoc/src/mongoc/mongoc-topology.c, src/libmongoc/tests/test-mongoc-client-pool.c, src/libmongoc/tests/test-mongoc-client-session.c
When in pooling mode, destroying a session that had never been used produced a warning log.  Fixed by not pushing unused sessions to session_pool for being reused because server is unaware of the existence of the session.
=> CDRIVER-3322 warning log with destroying unused session in pooled mode

src/libmongoc/src/mongoc/mongoc-cluster-sspi.c
A fix to a bug I introduced in CDRIVER-3486.
There are no tests. AFAICT the uninitialized reads would be happening in the current SSPI authentication tests on evergreen. The uninitialized read shows up in Dr. Memory for me locally, but still succeeds at authenticating with Kerberos.
=> CDRIVER-3725 fix uninitialized read

src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/tests/test-mongoc-client-session.c, src/libmongoc/tests/test-mongoc-collection.c, src/libmongoc/tests/test-mongoc-retryable-reads.c
Full patch build: https://spruce.mongodb.com/version/5ef65493d1fe072a882ec1cf/tasks
=> CDRIVER-3612 do not accept explicit session for collection count

.evergreen/config.yml, build/evergreen_config_lib/functions.py
https://github.com/mongodb/mongo-c-driver/commit/529a2be72907aeb6823e9ebbf830f9dbe7baa91c had a typo, comparing `mongoc-c-driver` instead of `mongo-c-driver`. This meant that the Evergreen project tracking the master branch was not uploading to the expected location. I noticed this in the C++ driver project, which was fetching the version of libmongoc just before 529a2be72907aeb6823e9ebbf830f9dbe7baa91c.
=> CDRIVER-3573 fix hardcode

.evergreen/config.yml, .evergreen/run-ocsp-test.sh, build/evergreen_config_lib/tasks.py, src/libmongoc/doc/configuring_tls.rst, src/libmongoc/src/mongoc/mongoc-secure-channel.c, src/libmongoc/src/mongoc/mongoc-stream-tls-secure-channel.c
Change the default certificate validation with Secure Channel to ignore errors due to an OCSP responder / CRL distribution point being offline and due to a peer certificate not listing any revocation information. [CDRIVER-3580](https://jira.mongodb.org/browse/CDRIVER-3580) has more background.
Patch build with just the OCSP tests:
https://evergreen.mongodb.com/version/5efaada3d1fe072a883a5c2f
=> CDRIVER-3580 / CDRIVER-3719 soft-fail with Secure Channel + regenerate OCSP tests

.evergreen/compile-unix.sh, .evergreen/config.yml, .evergreen/run-tests.sh, .tsan-suppressions, build/evergreen_config_lib/tasks.py, build/evergreen_config_lib/variants.py, src/libmongoc/tests/mock_server/mock-server.c, src/libmongoc/tests/test-mongoc-topology-description.c
Adds thread sanitizer tasks to Evergreen to catch thread races.
[Here's an example failure](https://spruce.mongodb.com/task/mongo_c_driver_tsan_ubuntu_test_tsan_3.4_replica_set_noauth_nosasl_openssl_patch_1763427bff432aca8abf01e753969343095cb496_5efd072b32f41770fe1d220c_20_07_01_21_59_33/logs). TSAN produces stack traces to identify the concurrent reader/writer of shared data.
=> CDRIVER-748 add TSAN tasks

.evergreen/benchmark.yml
Fixes the failing tasks in the mongo-c-driver-perf evergreen project, and adds a task to test against the latest 4.4 release.
Patch build: https://evergreen.mongodb.com/version/5f0386f332f41728dadad719
=> CDRIVER-2785 fix benchmark project

src/libmongoc/src/mongoc/mongoc-server-monitor.c, src/libmongoc/tests/TestSuite.c, src/libmongoc/tests/json-test-monitoring.c, src/libmongoc/tests/json-test-monitoring.h, src/libmongoc/tests/json-test-operations.c, src/libmongoc/tests/json-test-operations.h, src/libmongoc/tests/json-test.c, src/libmongoc/tests/json-test.h, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/cancel-server-check.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/find-network-error.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/find-shutdown-error.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/insert-network-error.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/insert-shutdown-error.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/isMaster-command-error.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/isMaster-network-error.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/isMaster-timeout.json, src/libmongoc/tests/json/server_discovery_and_monitoring/integration/rediscover-quickly-after-step-down.json, src/libmongoc/tests/test-mongoc-sdam.c
Adds support for all SDAM integration tests and the prose RTT test.
This does not include the connectTimeoutMS=0 test introduced in [CDRIVER-3721](https://jira.mongodb.org/browse/CDRIVER-3721). libmongoc does not interpret `connectTimeoutMS=0` as an unlimited timeout, and instead interprets `0` as the option being unset (so it defaults to `10,000`). I'll address that as part of CDRIVER-3721 instead of folding it in here.
The JSON files are on the second commit.
=> CDRIVER-3535 integration tests + RTT test

.evergreen/run-ocsp-test.sh, src/libmongoc/src/mongoc/mongoc-ocsp-cache.c, src/libmongoc/src/mongoc/mongoc-openssl.c, src/libmongoc/tests/test-mongoc-ocsp-cache.c
Log messages in Evergreen were indicating soft-failures against Amazon KMS servers. In addition to checking responses locally, I inspected the logs of the `-cse` tasks to validate this is no longer failing.
The HTTP header Host is required by KMS servers (and is required by HTTP in general). Related issue in OpenSSL: https://github.com/openssl/openssl/issues/1986
Fixes a leak of `next_time` / `this_time` fields.
Permits verified chain be used to validate OCSP response signature certificate.
=> CDRIVER-3734 add Host header to OCSP requests

src/libmongoc/CMakeLists.txt, src/libmongoc/src/mongoc/CMakeLists.txt, src/libmongoc/src/mongoc/mongoc-cluster-aws.c, src/libmongoc/src/mongoc/mongoc-http-private.h, src/libmongoc/src/mongoc/mongoc-http.c, src/libmongoc/src/mongoc/mongoc-openssl.c, src/libmongoc/src/mongoc/mongoc-stream-tls-openssl-private.h, src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.c, src/libmongoc/tests/test-libmongoc.c, src/libmongoc/tests/test-mongoc-http.c
- Reuse libmongoc's HTTP function instead of OCSP_sendreq_new
- Support TLS in OCSP endpoint
- Do not log a soft failure if a certificate has no OCSP endpoints
=> CDRIVER-3739 Add 5 second timeout to OCSP

src/libmongoc/doc/mongoc_uri_set_compressors.rst
There is already a test that asserts this behavior:
https://github.com/mongodb/mongo-c-driver/blob/1.16.2/src/libmongoc/tests/test-mongoc-uri.c/#L1039-L1043
=> CDRIVER-3751 document NULL for set_compressors

src/libmongoc/src/mongoc/mongoc-cmd.c, src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/tests/test-mongoc-write-concern.c
The bugs mentioned in CDRIVER-3595 don't seem to be observable, as demonstrated in the test cases that this PR adds to test-mongoc-write-concern.c.  The only real change that this PR makes is in mongoc-collection.c.
=> CDRIVER-3595 adds tests, removes extraneous check

src/libmongoc/src/mongoc/mongoc-client-pool.c, src/libmongoc/tests/test-mongoc-client-pool.c
This PR initializes the `mongoc_client_pool_t` condition variable.  It also adds a test, asserting that the function `mongoc_client_pool_pop` returns when the max pool number of clients have already been allocated.
=> CDRIVER-3757 inits pool cond, adds test

src/libmongoc/tests/test-mongoc-sdam.c
Some SDAM integration tests make assumptions about thread context switching.
Specifically, the [find-shutdown-error.yml](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/tests/integration/find-shutdown-error.yml) test starts two threads. Each threads send a `find` command. The server blocks the response to the find command for 500ms before responding with an error (which increments the connection generation). The intent of the 500ms block is so both threads grab a connection from the same generation (i.e. both find commands send the command before either gets an error response).
But the logs for the test running through Valgrind [/server_discovery_and_monitoring/integration/find-shutdown-error](https://evergreen.mongodb.com/task/mongo_c_driver_va …
=> CDRIVER-3746 skip SDAM int tests on valgrind

src/libmongoc/tests/TestSuite.c, src/libmongoc/tests/test-conveniences.c, src/libmongoc/tests/test-conveniences.h
Not urgent. I had theorized that temporary objects created in tests (via `tmp_bson()`) were causing slowdown in Valgrind tasks. Clearing it after each test run did not speed up Valgrind, but seemed like a reasonable improvement regardless.
=> clear convenience temps after each test

README.rst, src/libbson/doc/bson_oid_t.rst, src/libmongoc/doc/advanced-connections.rst, src/libmongoc/doc/configuring_tls.rst, src/libmongoc/doc/mongoc_client_set_read_prefs.rst, src/libmongoc/doc/mongoc_collection_aggregate.rst, src/libmongoc/doc/mongoc_collection_count.rst, src/libmongoc/doc/mongoc_collection_count_with_opts.rst, src/libmongoc/doc/mongoc_collection_set_read_prefs.rst, src/libmongoc/doc/mongoc_database_aggregate.rst, src/libmongoc/doc/mongoc_database_find_collections_with_opts.rst, src/libmongoc/doc/mongoc_database_get_collection_names_with_opts.rst, src/libmongoc/doc/mongoc_database_set_read_prefs.rst, src/libmongoc/doc/mongoc_read_mode_t.rst, src/libmongoc/doc/mongoc_read_prefs_set_mode.rst, src/libmongoc/doc/mongoc_uri_t.rst, src/libmongoc/doc/mongoc_write_concern_t.rst, src/libmongoc/doc/tutorial.rst
- only note OCSP behavior exceptions
- note that crl_file is unsupported with LibreSSL and Secure Transport
=> CDRIVER-3786 clean up OCSP docs

.evergreen/spec.patch
This updates the spec.patch so that it applies cleanly the latest upstream spec file.
Patch build: https://spruce.mongodb.com/version/5f2880b157e85a6bdd33eea8/tasks
=> fix rpm-package-build task

CMakeLists.txt
After the `message` override was removed in 5ab86d634e24de99bd1f1b2ca27d69871139ee6d, `MESSAGES_ENABLED` is unused.
=> CDRIVER-3756 remove unused MESSAGES_ENABLED

src/libmongoc/tests/json-test.c, src/libmongoc/tests/json/change_streams/change-streams-errors.json, src/libmongoc/tests/json/change_streams/change-streams.json
Note, the `cse` tasks on evergreen are failing due to a compiler warning from libmongocrypt. That is independent of this change.
=> CDRIVER-3779 resync change stream tests

src/libmongoc/CMakeLists.txt
Based on: https://developer.mongodb.com/community/forums/t/mongo-c-driver-error-when-executing-a-build/8852
Full Evergreen patch build: https://spruce.mongodb.com/version/5f57aa9f32f41726dbe5b8f3/tasks
=> make build work with space in source tree path

src/libmongoc/src/mongoc/mongoc-client-private.h, src/libmongoc/src/mongoc/mongoc-client.c, src/libmongoc/src/mongoc/mongoc-topology.c, src/libmongoc/tests/test-mongoc-dns.c
Includes a test with a small initial buffer size. See the ticket for a description of the issue.
=> CDRIVER-3806 fix DNS result size comparison

src/libmongoc/CMakeLists.txt
Full Evergreen patch build: https://spruce.mongodb.com/version/5f75fa79e3c3312424d9b554/tasks
=> CDRIVER-3805 fix build with system zlib in non-standard location

src/libbson/src/bson/bcon.c
There is a small typo in src/libbson/src/bson/bcon.c
Should read manipulate rather than manimpulate.
(libbson PR https://github.com/mongodb/libbson/pull/223 requested application here)
=> docs: fix simple typo, manimpulate -> manipulate

.evergreen/debian_package_build.sh, debian/README.source, debian/control
Evergreen patch build (to ensure `debian-package-build` task is exercised): https://spruce.mongodb.com/version/5f9de1fd30661537f4dc19ba/tasks
Note that once this PR is approved/merged I will cherry-pick the change on to the `r1.17` branch.  Ideally, this will take place before the pending 1.17.2 release.  Additionally, I will include an entry regarding this change in the next `debian/changelog` update when I prepare the 1.17.2 package.
=> (Debian packaging) CDRIVER-3809 build mongo-c-driver with libmongocrypt

src/libmongoc/src/mongoc/mongoc-topology-background-monitoring.c, src/libmongoc/src/mongoc/mongoc-topology-private.h, src/libmongoc/src/mongoc/mongoc-topology.c
If an SRV URI is used to connect to a deployment other than a sharded cluster
the SRV polling thread spins since it bypasses the poll due to the topology
type being ineligible. This change terminates the thread when the topology
type is discovered to be ineligible.
I reran SRV polling tests described in [the spec](https://github.com/mongodb/specifications/tree/master/source/polling-srv-records-for-mongos-discovery/tests) using the steps outlined in https://github.com/kevinAlbs/SRVPollingTesting.
=> CDRIVER-3808 fix srv polling thread from spinning

src/libmongoc/doc/mongoc_collection_rename_with_opts.rst
Note that while this accomplishes the objective of not listing `collation` in an instance where it is not a valid option, it results in duplicating part of the generated `opts` documentation.  If the `opts` change in a way that should be reflected here, then it is not clear how to ensure that change is not overlooked.  That said, this change is probably better than documenting something as valid that is not actually valid.
=> CDRIVER-3819 collation is not an option for collection rename

src/libbson/fuzz/fuzz_test_libbson.c
Hi
I have integrated fuzzing into libbson and was thinking that it would be nice to set up continuous fuzzing by way of OSS-Fuzz. In this PR: https://github.com/google/oss-fuzz/pull/4808 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate. In that PR you also see the fuzzer attached, but it would be nicer to have the fuzzer integrated into the upstream project itself rather than keeping it in OSS-Fuzz - so if this PR gets merged I will remove it from OSS-Fuzz
Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is …
=> libbson fuzzer for OSS-Fuzz integration.

src/libmongoc/src/mongoc/mongoc-cluster.c
I simply removed this assert.  The logic right below should compare for server_id 0 and fail with a nice error.
=> CDRIVER-3825 remove BSON_ASSERT for server_id

src/libmongoc/src/mongoc/mongoc-socket.c
`MSG_NOSIGNAL`, the flag that we currently use to ignore `SIGPIPE` on POSIX systems, is not supported on OSX.  Instead, OSX offers the `SO_NOSIGPIPE` flag that can be set as a socket option before performing writes.
I had asked @kmahar to test a different solution for ignoring `SIGPIPE`:
`signal(SIGPIPE, SIG_IGN);`
Upon further research, this solution isn't ideal, because it ignores `SIGPIPE` for the entire program, including any user code running a level above the C driver.  In the case that a user is interested in `SIGPIPE` for some reason, setting the handler to `SIG_IGN` like this would also capture `SIGPIPE` in user code.  The `SO_NOSIGPIPE` solution is less intrusive for a library like ours.
=> CDRIVER-3823 ignore SIGPIPE on osx

src/libbson/doc/bson_as_json_with_opts.rst, src/libbson/doc/bson_json_mode_t.rst, src/libbson/doc/bson_json_opts_destroy.rst, src/libbson/doc/bson_json_opts_new.rst, src/libbson/doc/bson_json_opts_t.rst, src/libbson/doc/bson_t.rst, src/libbson/doc/includes/seealso/bson-as-json.txt, src/libbson/src/bson/CMakeLists.txt, src/libbson/src/bson/bson-json-private.h, src/libbson/src/bson/bson-json.c, src/libbson/src/bson/bson-json.h, src/libbson/src/bson/bson-types.h, src/libbson/src/bson/bson.c, src/libbson/src/bson/bson.h, src/libbson/tests/test-json.c
This commit was extracted from #684, which is the POC for CDRIVER-3775. Since this logic is not entirely related to logging, I figured it was easier to review this separately.
This introduces a new `bson_as_json_with_opts` method, which is used to pass extra options to the encoding process. For now, the opts struct holds a mode (corresponding to the individual `bson_as_json`, `bson_as_canonical_extended_json`, and `bson_as_relaxed_extended_json` functions) and a maximum length, which is required by the new structured logging component.
The goal behind this function is that not all BSON is read and encoded, but that the process ends when the character limit is reached. For the time being, this works by checking the length limit in a `visit_after` visitor. This means that while we won't …
=> Implement BSON to JSON encoder that limits encoded string length

src/libmongoc/doc/mongoc_client_session_get_dirty.rst, src/libmongoc/doc/mongoc_client_session_t.rst, src/libmongoc/src/mongoc/mongoc-client-session.c, src/libmongoc/src/mongoc/mongoc-client-session.h
Unified test format (and driver sessions tests) make assertions on whether a session has been marked dirty. This adds a getter to `mongoc_client_session_t` so wrapping drivers can easily implement those assertions.
=> CDRIVER-3780 add client_session_get_dirty

src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/tests/test-mongoc-collection.c
If `mongoc_collection_find_and_modify_with_opts` or `mongoc_collection_find_and_modify` succeeds after retrying due to retryable writes being enabled, it correctly returns `true` but leaves the output `bson_error_t` set to the original error.
This clears the error on a successful retry.
Note, this came up during implementation of the unified test runner. I implemented error checking by checking the out `bson_error_t` on operations (not the boolean return value).
=> CDRIVER-3873 clear fam error on retry

src/libbson/tests/test-bson.c
The bug fix is part of https://github.com/mongodb/mongo-c-driver/pull/690/commits/4ed28488442b9013e6f59efc8532e85df132a324#diff-40f2bad12fecbb316a142e83953d727ed35c749b920931a18791f8558654aef2R2582
That line will be backported, along with this test, in 1.17.4.
=> CDRIVER-3877 test BSON string produced

src/libmongoc/doc/mongoc_server_description_t.rst
Adds a note to the docs for `mongoc_server_description_t` to note it is temporary when obtained through APM callbacks.
This is similar to the existing note for `mongoc_topology_description_t`. Though users do need to destroy a `mongoc_server_description_t` when obtained through `mongoc_client_select_server`.
=> clarify lifecycle of sd

src/libmongoc/doc/init-cleanup.rst
Fixes https://jira.mongodb.org/browse/CDRIVER-3903 changing the only reference that I have found using NO to OFF (doing the other way around, changing all OFF to NO would have involved much more changes).
I hope you find it useful. Feedback welcome.
=> CDRIVER 3903 fix doc to ENABLE_AUTOMATIC_INIT_AND_CLEANUP setting homogeneous

src/libmongoc/tests/unified/operation.c, src/libmongoc/tests/unified/result.c, src/libmongoc/tests/unified/runner.c
Not urgent – this is a follow up ticket for unified test format. If an operation in the unified test format does not include `expectResult` or `expectError` it should still check that the operation succeeded.
=> CDRIVER-3902 handle absence of expectResult/expectError

src/libmongoc/doc/logging.rst
This PR moves `mongoc_log_set_handler` above `mongoc_init` in our logging docs example. This clarifies the log handler can be set at any time, even before a call to `mongoc_init`.
=> CDRIVER-3904 move log handler above init in logging example

src/libbson/CMakeLists.txt
Requiring consumers of libbson-static to link against libm on macOS causes an issue for the Go driver's use of libmongocrypt (error encountered originally in MONGOCRYPT-309, but copying details here).
```
$ pkg-config --libs --cflags libmongocrypt-static
-DMONGOCRYPT_STATIC_DEFINE -DKMS_MSG_STATIC -DBSON_STATIC -I/usr/local/Cellar/libmongocrypt/1.2.0/include/mongocrypt -I/usr/local/Cellar/mongo-c-driver/1.17.4/include/libbson-1.0 -L/usr/local/Cellar/mongo-c-driver/1.17.4/lib /usr/local/Cellar/libmongocrypt/1.2.0/lib/libmongocrypt-static.a /usr/local/Cellar/libmongocrypt/1.2.0/lib/libkms_message-static.a -framework CoreFoundation -framework Security -lbson-static-1.0 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libm.tbd
```
The …
=> CDRIVER-3906 do not add libm on macOS

src/libmongoc/doc/includes/init_cleanup.txt, src/libmongoc/doc/logging.rst
PR as discussed at https://github.com/mongodb/mongo-c-driver/pull/736#discussion_r574787760
Any feedback is welcome, including .rst syntax, documentation style in the Mongo C driver repository, or even text wording (English is not my native language ;)
=> CDRIVER-3904 improve documentation regarding when to call mongoc_log_set_handler

src/libmongoc/src/mongoc/mongoc-timeout.c, src/libmongoc/tests/test-mongoc-versioned-api.c
removes redefinition of mongoc_timeout_t.
=> changes assignment to equality check

src/libbson/doc/bson_get_monotonic_time.rst
[CDRIVER-3272](https://jira.mongodb.org/browse/CDRIVER-3272)
Document `bson_gettimeofday()` correctly. The docs previously listed an incorrect, additional `timezone` param that does not actually exist in [bson-clock.h](https://github.com/mongodb/mongo-c-driver/blob/master/src/libbson/src/bson/bson-clock.h#L35).
=> CDRIVER-3272 Correctly document bson gettimeofday

src/libmongoc/tests/unified/operation.c
This commit fixes the issue from the task **test-latest-server-auth-sasl-openssl-cse on GCC 8.3** [here](https://evergreen.mongodb.com/task_log_raw/mongo_c_driver_gcc83_test_latest_server_auth_sasl_openssl_cse_4184f376b51c64dffb7ba1256dbc7c68a0a7c3b3_21_03_09_16_32_01/0?type=T#L2949). Unfortunately, that task now has another unrelated error.
Here's a patch showing the previously failing tasks succeeding ([link](https://evergreen.mongodb.com/task_log_raw/mongo_c_driver_gcc83_test_latest_server_auth_sasl_openssl_cse_patch_4184f376b51c64dffb7ba1256dbc7c68a0a7c3b3_6047ade19ccd4e2acd95d67f_21_03_09_17_18_28/0?type=T#L2950)). I also verified this locally.
=> set distinct.query as document

src/libmongoc/tests/test-mongoc-cursor.c
This commit fixes the failing `cmd_deprecated` tasks on Evergreen ([here](https://evergreen.mongodb.com/task_log_raw/mongo_c_driver_windows_2017_test_latest_replica_set_noauth_nosasl_nossl_26898e57f1de4ba3db54622f11adfa9a8be19b3f_21_03_09_18_26_08/0?type=T#L2904) for example).
=> remove batchSize and limit from isMaster

src/libbson/src/bson/bson-json.c, src/libbson/tests/test-json.c
[CDRIVER-3773](https://jira.mongodb.org/browse/CDRIVER-3773)
python-bsonjs, which relies on libbson, requested the ability to load regexes without the "options" field through JSON into BSON. I see no language in the extended JSON [spec](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#regularexpression) forbidding this behavior, and it's unlikely an existing user would actively expect a "missing options" error, so it seems ok to add.
Removes the "missing options" errors in `_bson_json_read_append_regex` and adds two new tests to verify correct parsing and absence of error for legacy and canonical regexes without options.
=> CDRIVER-3773 Support regular expressions with no options

src/libbson/src/bson/bson-json.c, src/libbson/tests/test-json.c
Reverts mongodb/mongo-c-driver#751.
We cannot support regular expressions with no options without a spec change because of an existing spec [test](https://github.com/mongodb/specifications/blob/master/source/bson-corpus/tests/top.json#L74..L77) that checks for a parse error on a regex with no options.
[CDRIVER-3773](https://jira.mongodb.org/browse/CDRIVER-3773) would require a larger spec change, which I will look into.
=> CDRIVER-3773 Remove support for canonical regular expressions with no options

src/libmongoc/tests/test-mongoc-async.c, src/libmongoc/tests/test-mongoc-topology.c
This commit fixes the failing [/Async/ismaster](https://evergreen.mongodb.com/task_log_raw/mongo_c_driver_clang38_i386_test_latest_server_ipv4_client_ipv4_noauth_nosasl_nossl_27f1d6e1be7eb85545ef1ebb14920434ea98d031_21_03_11_22_58_44/0?type=T#L2343) tests in evergreen.
Because of [SERVER-53150](https://jira.mongodb.org/browse/SERVER-53150), the latest server versions fail on isMaster commands with unknown fields. Previously this test inflatted the isMaster to >1MB to address the issue in [CDRIVER-2483](https://jira.mongodb.org/browse/CDRIVER-2483) by adding random-ish fields. Rather than sending an unknown field, this fix adds a >1MB comment.
=> Remove unknown fields in isMaster cmd

src/libmongoc/tests/bsonutil/bson-parser.c
[CDRIVER-3931](https://jira.mongodb.org/browse/CDRIVER-3931)
The bson test util `bson_parser_parse` can run BSON_FOREACH on a NULL document causing an error in BSON_ASSERT. Adds a check to verify the document isn't NULL.
=> CDRIVER-3931 Check for null document in bson parser parse

src/libmongoc/CMakeLists.txt, src/libmongoc/src/mongoc/CMakeLists.txt, src/libmongoc/src/mongoc/mongoc-cmd.c, src/libmongoc/src/mongoc/mongoc-optional.c, src/libmongoc/src/mongoc/mongoc-optional.h, src/libmongoc/src/mongoc/mongoc-server-api-private.h, src/libmongoc/src/mongoc/mongoc-server-api.c, src/libmongoc/src/mongoc/mongoc-server-api.h, src/libmongoc/tests/test-mongoc-versioned-api.c
This PR adds a new `mongoc_optional_t` type (which represents an optional bool) and returns that type for boolean options for versioned API.  I thought through a couple of questions when implementing this:
- What about other optional types?  Is it odd that `mongoc_optional_t` is only for bools?
The only other type I could see us wanting to represent this way is an integer.  Everything else can be pointer-based to indicate NULL-ness.  I think we could implement a `mongoc_optional_int_t` later on if we wanted to, and we actually may need specifically named types for int32, int64, etc.  Given that, I decided using `mongoc_optional_t` here would be nicer than `mongoc_optional_bool_t`.
- Is this over-engineered?
Maybe!  We do represent optional booleans in a fair number of places, and I think …
=> CDRIVER-3918 expose server api options as mongoc_optional_t

src/libmongoc/tests/json-test-operations.c, src/libmongoc/tests/json/transactions/errors-client.json
[CDRIVER-3215](https://jira.mongodb.org/browse/CDRIVER-3215)
Adds new spec test to assert that transaction state does not move from both "starting" or "in progress" when a client-side error is encountered.
Updates test runner to support "assertSessionTransactionState" described [here](https://github.com/mongodb/specifications/blob/master/source/transactions/tests/README.rst#assertsessiontransactionstate).
=> CDRIVER-3215 Assert transaction state does not change on client-side error

src/libbson/src/bson/bson-json.c, src/libbson/tests/json/bson_corpus/binary.json, src/libbson/tests/test-bson-corpus.c
CDRIVER-3792
This adds support for parsing UUIDs from extended JSON into BSON. To avoid using a UUID library, this uses sscanf to first validate the UUID and extract the data skipping hyphens, then decodes the hex values into the format understood by the BSON binary type. Any malformed UUID (e.g. wrong length, wrong position of hyphens, etc.) is rejected.
=> CDRIVER-3792 Support parsing $uuid as extended JSON

src/libmongoc/src/mongoc/mongoc-client-pool.c, src/libmongoc/src/mongoc/mongoc-client-private.h, src/libmongoc/src/mongoc/mongoc-client.c, src/libmongoc/src/mongoc/mongoc-cmd-private.h, src/libmongoc/src/mongoc/mongoc-cmd.c, src/libmongoc/src/mongoc/mongoc-error.h, src/libmongoc/src/mongoc/mongoc-topology-scanner-private.h, src/libmongoc/src/mongoc/mongoc-topology-scanner.c, src/libmongoc/tests/test-mongoc-topology.c, src/libmongoc/tests/test-mongoc-versioned-api.c
CDRIVER-3929
This fixes an oversight in the versioned API implementation where the handshake did not send API Version information to the server. This required exposing the API Version to the topology scanner as that's where the actual commands are handled. I've decided to allow changing the API Version multiple times as this part of libmongoc is very much internal.
During testing I discovered a couple of edge cases around setting API Version on a pooled client:
* When no API Version has been set, a user can set it after clients have been popped. This causes an inconsistent state in the pool. Solution is to prevent changing the API Version when the pool size is greater than 0. I understand this can cause an inconsistency when the last client is destroyed where one could once again set the …
=> CDRIVER-3929 Include apiVersion in handshake commands

src/libmongoc/doc/api.rst, src/libmongoc/doc/mongoc_optional_copy.rst, src/libmongoc/doc/mongoc_optional_init.rst, src/libmongoc/doc/mongoc_optional_is_set.rst, src/libmongoc/doc/mongoc_optional_set_value.rst, src/libmongoc/doc/mongoc_optional_t.rst, src/libmongoc/doc/mongoc_optional_value.rst, src/libmongoc/doc/mongoc_server_api_get_deprecation_errors.rst, src/libmongoc/doc/mongoc_server_api_get_strict.rst, src/libmongoc/doc/mongoc_server_api_get_version.rst, src/libmongoc/doc/mongoc_server_api_t.rst, src/libmongoc/src/mongoc/mongoc-optional.c, src/libmongoc/src/mongoc/mongoc-optional.h, src/libmongoc/src/mongoc/mongoc-server-api.c, src/libmongoc/src/mongoc/mongoc-server-api.h
This PR collects a few fixes that were necessary to get the PHP changes running after the introduction of `mongoc_optional_t`:
* Arguments for `mongoc_optional_t` getters were not marked as `const`
* Arguments for `mongoc_server_api_t` getters were not marked as `const`
* `mongoc_server_api_get_strict` had a wrong name
* Added `mongoc_server_api_get_version` to retrieve the `mongoc_server_api_version_t`
* Added documentation for `mongoc_server_api_get_*`
* Added documentation for `mongoc_optional_t`.
=> Update versioned API getters

src/libmongoc/tests/json/versioned_api/crud-api-version-1-strict.json, src/libmongoc/tests/json/versioned_api/crud-api-version-1.json, src/libmongoc/tests/json/versioned_api/runcommand-helper-no-api-version-declared.json, src/libmongoc/tests/json/versioned_api/test-commands-deprecation-errors.json, src/libmongoc/tests/json/versioned_api/test-commands-strict-mode.json, src/libmongoc/tests/json/versioned_api/transaction-handling.json
[CDRIVER-3919](https://jira.mongodb.org/browse/CDRIVER-3919)
[CDRIVER-3920](https://jira.mongodb.org/browse/CDRIVER-3920)
[CDRIVER-3932](https://jira.mongodb.org/browse/CDRIVER-3932)
Syncs versioned API spec tests to add a new test for abortTransaction and only run tests on 4.9+. Also removes skipReason on estimatedDocumentCount test.
I will not merge this until PR #753 to include apiVersion in handshakes and heartbeats is merged, and the "latest" server version on Evergreen includes [this commit](https://evergreen.mongodb.com/version/mongodb_mongo_master_075e51fefecc54e219c56e75c3ba08c993b5c187).
=> Sync Versioned API Tests

src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/tests/unified/operation.c
[CDRIVER-3933](https://jira.mongodb.org/browse/CDRIVER-3933)
Destroys and re-initializes `reply` in `mongoc_collection_estimated_document_count` in the case of a NamespaceNotFound error caused by an aggregate on a non-existent collection. Also removes the workaround for 3933 in `operation.c`.
Per the spec, drivers are required to swallow a NamespaceNotFound error and return a count of 0. While the `bson_error_t` was being unset, and a count of 0 was being returned, `reply` still housed the error, which is arguably unexpected behavior for the user.
=> CDRIVER-3933 Reinit reply in edc for NamespaceNotFound

src/libmongoc/src/mongoc/mongoc-collection.c
This PR fixes a conditional jump warning in valgrind if an uninitialized `bson_error_t` is passed as the output argument for `mongoc_collection_estimated_document_count`.
This appeared on a C++ [patch build](https://evergreen.mongodb.com/lobster/evergreen/task/cxx_driver_ubuntu1604_debug_valgrind_compile_and_test_with_shared_libs_patch_33416f88f1d59e19eb103fedab59d73399332a7c_6061e9b2d6d80a5ce526e478_21_03_29_14_52_40/0/task#bookmarks=0%2C6962%2C6967%2C7647&l=1) while implementing Azure/GCP support.
There is a test coverage of running `mongoc_collection_estimated_document_count` against a live server and passing an uninitialized `bson_error_t` in [test_estimated_document_count_live](https://github.com/mongodb/mongo-c-driver/blob/a9afdeb0d58dfb5ac60be699442f17fde6f78dd9/src/libmongoc/tests/ …
=> Fix valgrind

src/libmongoc/src/mongoc/mongoc-client-pool.c, src/libmongoc/src/mongoc/mongoc-client.c, src/libmongoc/src/mongoc/mongoc-topology-scanner.c
Calling `_mongoc_topology_scanner_set_server_api` resets `ismaster_cmd_with_handshake`, which requires obtaining a lock on the topology.
=> Lock topology mutex before setting server API

src/libmongoc/src/mongoc/mongoc-cluster.c, src/libmongoc/src/mongoc/mongoc-server-monitor.c, src/libmongoc/src/mongoc/mongoc-topology-private.h, src/libmongoc/src/mongoc/mongoc-topology-scanner-private.h, src/libmongoc/src/mongoc/mongoc-topology-scanner.c, src/libmongoc/src/mongoc/mongoc-topology.c
CDRIVER-3940
The server monitor assembles its own `isMaster` command without using the topology scanner. This logic was missing the Versioned API fields, causing errors in background monitoring when connected to servers with `requireApiVersion` enabled.
This PR changes the logic to always fetch the hello command from the topology scanner. To make the distinction easier, I renamed `_mongoc_topology_scanner_get_ismaster` to `_mongoc_topology_scanner_get_handshake_cmd` and added a new `_mongoc_topology_scanner_get_hello_cmd` to return the base command without additional handshake data. This contains Versioned API fields, and we append the necessary fields for awaitable hello.
Note that this logic will likely have to change again in the near future, as the server monitor needs to know whether …
=> CDRIVER-3940 Fix missing versioned API options in server monitor

.evergreen/config.yml, .evergreen/integration-tests.sh, .evergreen/require-api-version.js, build/evergreen_config_lib/functions.py, build/evergreen_config_lib/tasks.py, build/evergreen_config_lib/variants.py, orchestration_configs/servers/versioned-api-testing.json, src/libmongoc/tests/test-libmongoc.c
[CDRIVER-3917](https://jira.mongodb.org/browse/CDRIVER-3917)
Adds a new Evergreen build variant for versioned API with three tasks. The first is `debug-compile-nosasl-openssl` to compile a `test-libmongoc`. The second is `test-versioned-api` to run versioned API tests against a 4.9.0 server with `requireApiVersion=1`. The third is `test-versioned-api-accept-version-two` to run versioned API tests against a 4.9.0 server with `enableTestCommands=1`, `acceptApiVersion2=1` and `requireApiVersion=0`.
These new tests (see example patch [here](https://spruce.mongodb.com/version/6064b0123066156f51b72d99/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)), will continue to fail until [CDRIVER-3940](https://github.com/mongodb/mongo-c-driver/pull/770) is merged.
We might want to update the C driver …
=> CDRIVER-3917 Run versioned API tests in Evergreen

src/libmongoc/tests/test-libmongoc.c
[CDRIVER-3924](https://jira.mongodb.org/browse/CDRIVER-3924)
Ignores the fourth field of version strings in `_parse_server_version` and `test_framework_str_to_version`. Updates `test_version_cmp` to test this behavior.
According to the unified test format [spec](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst#version-string), we should only consider `major`, `minor` and `patch` when comparing server version strings for testing. Release candidates like `"3.4.0.-49"` should not be distinct from non-rcs like `"3.4.0"`.
I _think_ the changes in this PR will also affect tests outside of the unified test format, so let me know if that seems like a problem.
=> CDRIVER-3924 Ignore RCs when comparing test version strings

orchestration_configs/servers/versioned-api-testing.json, src/libmongoc/tests/json/versioned_api/test-commands-deprecation-errors.json
[CDRIVER-3953](https://jira.mongodb.org/browse/CDRIVER-3953)
The server changed the parameter `acceptAPIVersion2` to `acceptApiVersion2`. Updates spec test runOnRequirement of `test-commands-deprecation-errors` and our local copy of the `verioned-api-testing.json` server configuration to reflect this.
Note that the server commit renaming `acceptAPIVersion2` will not be available until we upgrade to Ubuntu 18.04. Until then, there might be a setup failure in versioned API tests (setting `acceptApiVersion2=1` when only `acceptAPIVersion2=1` is accepted).
=> CDRIVER-3953 Replace acceptAPIVersion2 with acceptApiVersion2

src/libmongoc/tests/json/transactions/unified/mongos-unpin.json
Syncs transaction spec tests with mongodb/specifications@ec326862be443d11f0233cee2de32a95751144df. One change was missed in 2d7938aa068a1df70929a161c94642707cb4bd3e (#783).
Will merge once CI is green (ignoring ASAN failures).
=> CDRIVER-3966 Sync transaction spec tests

src/libmongoc/doc/mongoc_collection_find_and_modify_with_opts.rst
If an unacknowledged write concern is used as an option for a
mongoc_find_and_modify_with_opts, the output reply document is
always empty.
=> document fam reply is empty for w0

src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
CDRIVER-3942
Bumps the mongocryptd server selection timeout in client side encryption from 5 seconds to 10 seconds.
=> CDRIVER-3942 Bump mongocryptd server selection t/o to 10 seconds

src/libmongoc/src/mongoc/mongoc-cluster.c, src/libmongoc/tests/test-mongoc-change-stream.c, src/libmongoc/tests/test-mongoc-client.c
CDRIVER-3934
Also adds an assertion to avoid memory access failure that appeared once with VS15
=> CDRIVER-3934 Correctly handle network errors during speculative authentication

src/libmongoc/src/mongoc/mongoc-cursor.c, src/libmongoc/tests/json/command_monitoring/find.json, src/libmongoc/tests/json/unified/poc-command-monitoring.json, src/libmongoc/tests/test-mongoc-cursor.c
CDRIVER-4001
This PR proposes a fix for a number of tests that are currently failing due to slot-based execution (SBE) in the latest 5.0 builds. With SBE enabled we see the server keep the cursor alive when the end of a cursor is reached at the end of a batch. This usually doesn't occur too often, but the getMore command logic replicates the OP_GET_MORE behaviour of reducing the size of the last batch to fetch exactly `limit` documents. This triggers the unintended server behaviour for every cursor. While neither mandated nor prohibited, this behaviour is somewhat enforced by the command monitoring spec tests.
This PR updates the logic for the getMore command (OP_GET_MORE is unaffected) to always send the intended batch size. These changes can be safely reverted once the server behaviour …
=> CDRIVER-4001 Temporarily fix batchSize behaviour for getMore

src/libmongoc/tests/test-mongoc-collection.c
Follows #793. Versioned API tests are fixed by #792. With all patches applied, tests pass again: https://spruce.mongodb.com/version/60a62eabc9ec443716160e3d/tasks
Note that these tests will be replaced by spec tests after the completion of DRIVERS-1237 (see https://github.com/mongodb/specifications/pull/980)
=> Skip tests with dots and dollars in field names on 5.0+

src/libmongoc/doc/mongoc_database_create_collection.rst, src/libmongoc/tests/json/collection-management/timeseries-collection.json, src/libmongoc/tests/unified/runner.c
Resyncs tests to include the new time-series spec tests and fixes a bug in the unified test runner's outcome matching. No code changes were required.
- `authentication-tests-openssl-nosasl` task failures are due to CDRIVER-3998
- `test-asan-latest-*` task failures will be resolved with the Ubuntu 18.04 upgrade to pull in latest server releases: CDRIVER-3946
=> CDRIVER-3897 add tests for time-series collections

src/libmongoc/doc/includes/returns-cursor.txt, src/libmongoc/doc/mongoc_collection_aggregate.rst, src/libmongoc/doc/mongoc_collection_command.rst, src/libmongoc/doc/mongoc_collection_find.rst, src/libmongoc/doc/mongoc_collection_find_indexes.rst, src/libmongoc/doc/mongoc_collection_find_indexes_with_opts.rst, src/libmongoc/doc/mongoc_collection_find_with_opts.rst, src/libmongoc/doc/mongoc_database_aggregate.rst, src/libmongoc/doc/mongoc_database_command.rst, src/libmongoc/doc/mongoc_database_find_collections.rst, src/libmongoc/doc/mongoc_database_find_collections_with_opts.rst
Comparing the "Returns" section in src/libmongoc/doc/mongoc_collection_aggreage.rst with the one in src/libmongoc/doc/mongoc_collection_find.rst and src/libmongoc/doc/mongoc_collection_find_with_options.rst it seems the later ones are missing important information about how errors are reported (related with https://stackoverflow.com/questions/66027858/how-to-get-errors-when-calling-mongoc-collection-find-function).
I'd like to have feedback on this pull request, please. If it is right, please merge to improve the documentation. In addition, if you know any other document (others operations returning mongo_cursor_t*, probably) that may need a similar improvement, I can include it in this PR before merging.
Thanks!
=> Improve docs of cursor returning functions

src/libmongoc/tests/test-mongoc-sample-commands.c
=> CDRIVER-3991 Add versioned API connection examples

src/libmongoc/tests/json/crud/unified/aggregate-let.json, src/libmongoc/tests/json/crud/unified/insertOne-dots_and_dollars.json
https://jira.mongodb.org/browse/CDRIVER-3895
Synced with mongodb/specifications@fc21cb7330925647e7961c324f1594096025c17e (see https://github.com/mongodb/specifications/pull/1028 for more context).
Note: this also pulls in test changes relevant to aggregate let support (CDRIVER-4010)
@rcsanchez97: The previous PR for CDRIVER-3895 (#801) introduced `aggregate-let.json` and this PR pulls in the latest updates from https://github.com/mongodb/specifications/commit/3a58fc612b3520030a97a1161a5651c451c40f8e. Per @kevinAlbs' comment in [CDRIVER-4010](https://jira.mongodb.org/browse/CDRIVER-4010?focusedCommentId=3881139&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3881139) there may be no other work required for that ticket (perhaps beyond documentation if …
=> CDRIVER-3895: Sync CRUD tests for dots/dollars

src/libmongoc/src/mongoc/mongoc-client.c
CDRIVER-4028
I'll backport the resulting commit to r1.17 after merging.
=> CDRIVER-4028 Print correct error message when DNS resolution fails

build/generate-opts.py, src/libmongoc/doc/includes/aggregate-opts.txt, src/libmongoc/src/mongoc/mongoc-opts-private.h, src/libmongoc/src/mongoc/mongoc-opts.c
Full patch build: https://spruce.mongodb.com/version/60d5ee4be3c33111e05b9faa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
I checked quite a few of the failures in that patch build in every single case (with one exception*) the failure in the patch build was identical to the failure of the same task in the base commit.  *The one exception is a Valgrind test that had a hard failure in the base commit but which timed out in the patch build.
Based on this, it seems like the C driver already has the necessary support, so simply updating the CRUD JSON test is all we need to do.
=> CDRIVER-4010 support 'let' option for aggregate command

src/libmongoc/src/mongoc/mongoc-rand-openssl.c
https://jira.mongodb.org/browse/CDRIVER-3978
I opted not to implement PID-change detection, as https://www.agwa.name/blog/post/libressls_prng_is_unsafe_on_linux described a case where a grandparent and grandchild could theoretically shares the same PID.
Always mixing the current time before calling `RAND_bytes` seemed much simpler. This is the same approach taken in PHP (https://github.com/php/php-src/blob/php-8.0.8/ext/openssl/openssl.c#L936), and another patch to OpenSSL (https://github.com/openssl/openssl/commit/3cd8547a2018ada88a4303067a2aa15eadc17f39) mentioned in https://wiki.openssl.org/index.php/Random_fork-safety.
Will cherry-pick to r1.17 after merging.
=> CDRIVER-3978 mix time to avoid duplicate RAND_bytes for the same PIDs

src/libmongoc/src/mongoc/mongoc-apm.c
Fix backport of CDRIVER-4000 to r1.17 branch.
Merge this only to the r1.17 branch.
Patch in progress: https://spruce.mongodb.com/version/60e47dea3627e06703e137b6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CDRIVER-4000 Remove undefined macro

src/libmongoc/src/mongoc/mongoc-gridfs-bucket.c, src/libmongoc/tests/test-mongoc-gridfs-bucket.c, src/libmongoc/tests/test-mongoc-gridfs.c
GridFSBucket.find must forward the 'opts' to the underlying
collection query.
Also: Permit 'opts' to be NULL for mongoc_gridfs_bucket_find
=> CDRIVER-3164 & CDRIVER-4049: Fix 'opts' usage in mongoc_gridfs_bucket_find

src/libmongoc/doc/mongoc_session_opts_get_snapshot.rst, src/libmongoc/doc/mongoc_session_opts_set_causal_consistency.rst, src/libmongoc/doc/mongoc_session_opts_set_snapshot.rst
CDRIVER-4036
Adds documentation for `mongoc_session_opts_get_snapshot` and `mongoc_session_opts_set_snapshot`. Also mentions a possible error if `snapshot` is enabled when using `mongoc_session_opts_set_causal_consistency`.
=> CDRIVER-4036 document new API added for snapshot reads

src/libmongoc/CMakeLists.txt, src/libmongoc/doc/mongoc_client_get_handshake_description.rst, src/libmongoc/doc/mongoc_client_t.rst, src/libmongoc/doc/mongoc_server_description_type.rst, src/libmongoc/src/mongoc/mongoc-change-stream.c, src/libmongoc/src/mongoc/mongoc-client-session.c, src/libmongoc/src/mongoc/mongoc-client.c, src/libmongoc/src/mongoc/mongoc-client.h, src/libmongoc/src/mongoc/mongoc-cluster-aws.c, src/libmongoc/src/mongoc/mongoc-cluster-cyrus.c, src/libmongoc/src/mongoc/mongoc-cluster-private.h, src/libmongoc/src/mongoc/mongoc-cluster-sspi.c, src/libmongoc/src/mongoc/mongoc-cluster.c, src/libmongoc/src/mongoc/mongoc-server-description.c, src/libmongoc/src/mongoc/mongoc-topology-scanner-private.h, src/libmongoc/src/mongoc/mongoc-topology-scanner.c, src/libmongoc/tests/TestSuite.c, src/libmongoc/tests/TestSuite.h, src/libmongoc/tests/test-libmongoc.c, src/libmongoc/tests/test-mongoc-change-stream.c, src/libmongoc/tests/test-mongoc-client.c, src/libmongoc/tests/test-mongoc-cluster.c, src/libmongoc/tests/test-mongoc-server-stream.c
**Terms**
- **handshake description** is a server description constructed during connection handshake.
- **monitor description** is a server description constructed and updated in server monitoring.
**Motivation**
- libmongoc currently uses monitor descriptions when constructing commands (to check wire version, how to pass read preferences, etc.). This is racy, and the cause of bugs like CDRIVER-3404.
- Supporting load balancer requires setting the monitor description to an empty LoadBalancer description. A load balancer can front many backing servers. Connections must track the handshake description to work correctly with load balancers.
**Summary**
- Store handshake descriptions alongside their corresponding connections.
- Update change stream and transactions wire version checks to …
=> CDRIVER-3653 use handshake metadata for connection checks

src/libmongoc/tests/test-mongoc-mongohouse.c
https://jira.mongodb.org/browse/CDRIVER-4091
gcc 9.3.0 complains that because the strncpy() call uses the source's size as a bound,
the trailing NULL will not be copied.
Replaced with:
updated allocation size of destination to include room for the NULL character
eliminated redundant srlen()
changed strncpy() call to strcpy(), which includes the trailing NULL
Signed-off-by: Jesse Williamson <jesse.williamson@mongodb.com>
=> CDRIVER-4091 - Truncation in strncpy() causes build error

src/libmongoc/tests/test-libmongoc.c, src/libmongoc/tests/test-libmongoc.h, src/libmongoc/tests/test-mongoc-bulk.c, src/libmongoc/tests/test-mongoc-command-monitoring.c, src/libmongoc/tests/test-mongoc-cursor.c, src/libmongoc/tests/test-mongoc-exhaust.c
__Background__
The latest 5.1 pre-release removes support for:
- [legacy wire protocol op codes](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/) in [SERVER-57457](https://jira.mongodb.org/browse/SERVER-57457) and [SERVER-57391](https://jira.mongodb.org/browse/SERVER-57391).
- The deprecated `getLastError` command in [SERVER-57390](https://jira.mongodb.org/browse/SERVER-57390)
- This also addresses CDRIVER-4092 by fixing tests that send OP_GET_MORE and legacy OP_QUERY
__Changes__
- Skip `/command_monitoring/kill_cursors_deprecated` on latest servers since it tests sending OP_KILL_CURSORS.
- Skip `/BulkOperation/write_concern/split` on latest servers since it sends `getLastError`.
- Update `test_kill_cursor_live` to use the [`getMore` command on newer …
=> CDRIVER-4076 skip legacy opcode / getLastError tests on pre 5.1

src/libmongoc/doc/mongoc_apm_command_failed_get_service_id.rst, src/libmongoc/doc/mongoc_apm_command_failed_t.rst, src/libmongoc/doc/mongoc_apm_command_started_get_service_id.rst, src/libmongoc/doc/mongoc_apm_command_started_t.rst, src/libmongoc/doc/mongoc_apm_command_succeeded_get_service_id.rst, src/libmongoc/doc/mongoc_apm_command_succeeded_t.rst, src/libmongoc/src/mongoc/mongoc-apm-private.h, src/libmongoc/src/mongoc/mongoc-apm.c, src/libmongoc/src/mongoc/mongoc-apm.h, src/libmongoc/src/mongoc/mongoc-client.c, src/libmongoc/src/mongoc/mongoc-cluster.c, src/libmongoc/src/mongoc/mongoc-cursor-legacy.c, src/libmongoc/src/mongoc/mongoc-cursor.c, src/libmongoc/src/mongoc/mongoc-server-description-private.h, src/libmongoc/src/mongoc/mongoc-write-command-legacy.c, src/libmongoc/tests/test-mongoc-command-monitoring.c
https://jira.mongodb.org/browse/CDRIVER-4059
It's not often that I add new API methods, so please let me know if I missed anything. AFAICT, the docs don't report the version number when a particular method was introduced.
=> CDRIVER-4059 service_id on command monitoring events

.evergreen/build_snapshot_rpm.sh, .evergreen/config.yml, .evergreen/spec.patch
Patch build: https://spruce.mongodb.com/version/61032dce850e6118fbedda87/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CDRIVER-4112 use arm64 hosts for rpm-package-build

src/libmongoc/src/mongoc/mongoc-client-session-private.h, src/libmongoc/src/mongoc/mongoc-client-session.c, src/libmongoc/tests/test-mongoc-client-session.c, src/libmongoc/tests/test-mongoc-transactions.c, src/libmongoc/tests/unified/entity-map.c
https://jira.mongodb.org/browse/CDRIVER-4110
* Removes a work-around from the unified test runner originally introduced in https://github.com/mongodb/mongo-c-driver/commit/d5f73e18eac7acaa05f31c4ffde68c9cd565704a.
* Relocates the snapshot prose test, since it's part of the session spec (not transactions)
* Use `mongoc_optional_t` in `mongoc_session_opt_t` to track values for `causalConsistency` and `snapshot` options, and enforce the `causalConsistency` logic in the corresponding getter method.
=> CDRIVER-4110: Default for causal_consistency depends on snapshot

.evergreen/config.yml, .evergreen/run-auth-tests.sh, build/evergreen_config_lib/functions.py
Add a connectivity test to ensure we can connect and send a `ping` command to a live serverless instance.
Tests against the latest server are failing due to a recent server change. It is described in CDRIVER-4120 and resolved in #843.
=> CDRIVER-4068 add connectivity tests for serverless

src/libmongoc/tests/test-mongoc-primary-stepdown.c, src/libmongoc/tests/test-mongoc-retryable-reads.c, src/libmongoc/tests/test-mongoc-sample-commands.c
This also includes a fix for tests against latest server builds (CDRIVER-4120).
=> CDRIVER-4093 add versioned API strict examples 5-8

src/libmongoc/tests/test-mongoc-dns.c
Only [prose test 9](https://github.com/mongodb/specifications/blob/df6be82f865e9b72444488fd62ae1eb5fca18569/source/polling-srv-records-for-mongos-discovery/tests/README.rst#9-test-that-srv-polling-is-not-done-for-load-balalanced-clusters) is [currently implemented](https://github.com/mongodb/mongo-c-driver/blob/0d6a8ba27ed5cd94a26e4db879f61b545799193f/src/libmongoc/tests/test-mongoc-dns.c#L646) according to spec. Behavior of [`test_srv_polling_mocked`](https://github.com/mongodb/mongo-c-driver/blob/0d6a8ba27ed5cd94a26e4db879f61b545799193f/src/libmongoc/tests/test-mongoc-dns.c#L500) does not conform to prose tests described by spec. Therefore, only names related to prose test 9 are updated with numbering.
Prose tests 1 through 8 are to be implemented separately; see CDRIVER-4125.
---
This …
=> CDRIVER-4106 Update numbers for existing SRV polling prose tests.

CONTRIBUTING.md
Several tests require use of the [`configureFailPoint` command](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst#configuring-fail-points) to trigger server-side errors. The command must be enabled via configuration file or command line option when starting `mongod`.
The `configureFailPoint` command is not yet documented; see [DOCS-10784](https://jira.mongodb.org/browse/DOCS-10784).
---
This PR is motivated by my experience following written instructions to run the test suite locally. After following instructions, several tests were failing due to the error: `no such command: 'configureFailPoint'`.
Diagnosing this issue was difficult due to the `configureFailPoint` command having little to no documentation. It is however mentioned in …
=> Add instructions to enable fail points for test suite

src/libmongoc/doc/mongoc_server_description_destroy.rst, src/libmongoc/doc/mongoc_server_description_new_copy.rst, src/libmongoc/doc/mongoc_topology_description_destroy.rst, src/libmongoc/doc/mongoc_topology_description_new_copy.rst, src/libmongoc/doc/mongoc_topology_description_t.rst, src/libmongoc/src/mongoc/mongoc-topology-description-apm.c, src/libmongoc/src/mongoc/mongoc-topology-description-private.h, src/libmongoc/src/mongoc/mongoc-topology-description.c, src/libmongoc/src/mongoc/mongoc-topology-description.h, src/libmongoc/src/mongoc/mongoc-topology.c, src/libmongoc/tests/json-test.c, src/libmongoc/tests/test-mongoc-dns.c, src/libmongoc/tests/test-mongoc-topology-description.c
https://jira.mongodb.org/browse/CDRIVER-3909
=> CDRIVER-3909 topology description copy/destroy methods

.evergreen/download-mongodb.sh, src/libmongoc/tests/test-mongoc-sample-commands.c
Addresses test failures introduced in #843 to the versioned API tests and 5.0 sharded tests.
=> CDRIVER-4093 fix versioned API sample tests

src/libmongoc/doc/mongoc_topology_description_type.rst
Noticed the new type was missing from the list 🙂
=> Mention LoadBalanced topology type in docs

src/libmongoc/doc/mongoc_session_opts_clone.rst, src/libmongoc/doc/mongoc_session_opts_get_default_transaction_opts.rst, src/libmongoc/doc/mongoc_session_opts_get_transaction_opts.rst, src/libmongoc/doc/mongoc_session_opts_new.rst, src/libmongoc/doc/mongoc_transaction_opts_clone.rst, src/libmongoc/doc/mongoc_transaction_opts_new.rst
Documentation was updated for all functions that may return an owning pointer to either a `mongoc_transaction_opt` or `mongoc_session_opt` to indicate (no) responsibility to free the pointed-to object. Wording and content organization were made consistent across modified pages.
=> CDRIVER-3361 update documentation for owning return values

src/libmongoc/tests/TestSuite.c, src/libmongoc/tests/TestSuite.h
The solution to CDRIVER-3632 (merged in https://github.com/mongodb/mongo-c-driver/pull/865) introduced a bug in `TestSuite_Add()` and `TestSuite_AddLive()` where the static `TestFnCtx` object generated by the new `TestSuite_AddFullWithTestFn()`, pointed-to by each `Test` object created on invocation of `TestSuite_Add()` or `TestSuite_AddLive()`, is modified by a subsequent call to `TestSuite_Add()` or `TestSuite_AddLive()`. This has the effect of incorrectly (effectively) modifying `_Test::ctx->func` to point the _last_ (and _only_ the last) `test_fn` given to `TestSuite_Add()` or `TestSuite_AddLive()` respectively (each has their own static local variable):
```c
void
TestSuite_Add (TestSuite *suite, /* IN */
const char *name, /* IN */
TestFunc func)    /* IN */
{
/* Expanded: …
```
=> CDRIVER-4151 Replace static TestFnCtx with allocated object

src/libbson/doc/bson_subtype_t.rst, src/libbson/src/bson/bson-types.h, src/libbson/tests/json/bson_corpus/binary.json
Validating changes relating to DRIVERS-1875.
=> CDRIVER-4122 Add BSON corpus test for binary subtype 7

src/libmongoc/doc/mongoc_client_session_get_client.rst, src/libmongoc/doc/mongoc_client_session_get_cluster_time.rst, src/libmongoc/doc/mongoc_client_session_get_lsid.rst, src/libmongoc/doc/mongoc_client_session_get_opts.rst, src/libmongoc/doc/mongoc_session_opts_get_default_transaction_opts.rst, src/libmongoc/doc/mongoc_transaction_opts_get_read_concern.rst, src/libmongoc/doc/mongoc_transaction_opts_get_read_prefs.rst, src/libmongoc/doc/mongoc_transaction_opts_get_write_concern.rst
Lifetime of return values for client session, session option, and transaction option accessors has been added to documentation using the common phrase, "valid only for the lifetime of" to denote dependent lifetime, a phrase already being used in some pages such as [mongoc_change_stream_get_resume_token()](https://github.com/eramongodb/mongo-c-driver/blob/2b2a37400857fbc1c9fbc639b906aca4c5a99e7f/src/libmongoc/doc/mongoc_change_stream_get_resume_token.rst).
=> CDRIVER-3362 update documentation for non-owning return values

src/libmongoc/src/mongoc/mongoc-topology-description.c, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/MaxStalenessTooSmall.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/Unavailable.json
Do not check PossiblePrimary servers in the maxWireVersion check
for topology support of maxStalenessSeconds
=> CDRIVER-3636 exclude PossiblePrimary from MSS check

.evergreen/integration-tests.sh
Evergreen patch build: https://evergreen.mongodb.com/version/613fe728c9ec444561e48f6b?redirect_spruce_users=true
c.f. discussion in #867
=> CDRIVER-4156 use Python from toolchain on Ubuntu 14.04 Evergreen hosts

CMakeLists.txt, src/CMakeLists.txt, src/cpp-check.cpp, src/libbson/src/bson/bson-atomic.h
Fixes CDRIVER-4158. There was some implicit cross-casting going on in the headers that is not valid C++ code.
This also adds a C++ utility target that is only compiled to check that the public headers are valid C++ code.
=> CDRIVER-4158: Fix bson-atomic.h for compatibility with C++

CMakeLists.txt
Evergreen patch build: https://spruce.mongodb.com/version/6143d8c7d6d80a70550288d1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The BSON Atomics API fix broke the `rpm-package-build` task because the build environment does not include a C++ compiler by default.
Apparently, the CMake documentation contains this note regarding the `enable_language` command:
```
The OPTIONAL keyword is a placeholder for future implementation and does not currently work. Instead you can
use the CheckLanguage module to verify support before enabling.
```
So, the originally implemented change depends on a dummy feature.  The change in this PR instead takes the approach the suggested in the CMake documentation.
=> CDRIVER-4158 make CXX enablement optional

.evergreen/integration-tests.sh
This specifically addresses the situation on Ubuntu 16.04 Evergreen
hosts, which have the virtualenv module installed only for Python 3.
Currently, tasks on Ubuntu 16.04 that execute the `.evergreen/integration-tests.sh` land in the `system-failed` state on Evergreen.  This change allows the tasks to run to completion.
Evergreen patch build: https://spruce.mongodb.com/version/6144dc983627e00c42d46fa5/tasks
=> CDRIVER-4160 more robust Python selection for integration tests

.evergreen/build_snapshot_rpm.sh
Evergreen patch build: https://spruce.mongodb.com/version/6144edef3627e00c42d4e86b/tasks
A failure on the C++ driver waterfall (which uses the same script for building RPMs) is what prompted me to make this change.
=> dump mock logs if RPM build fails in Evergreen

src/libmongoc/tests/json-test-operations.c
Fixes the test failure associated with the [rediscover-quickly-after-stepdown](https://github.com/mongodb/specifications/blob/c48d7f416e51dce8fd4c8d05bdb05790508ca3bb/source/server-discovery-and-monitoring/tests/integration/rediscover-quickly-after-step-down.yml#L34-L42) SDAM specification test.
The test runner was not passing a read preference. No read preference defaults to a primary read preference. The test operation requires sending to a secondary.
=> CDRIVER-4035 use runAdminCommand.arguments.readPreference

src/libmongoc/src/mongoc/mongoc-handshake.c, src/libmongoc/tests/test-mongoc-handshake.c
`mongoc_handshake_data_append()` [special-cases](https://github.com/mongodb/mongo-c-driver/blob/130938ad44a6516e6c399b9d25e5fe1b0464f14f/src/libmongoc/src/mongoc/mongoc-handshake.c#L638) the first write to `mongoc_handshake_t::platform` to avoid inserting a leading delimiter. This special-case branch does not protect against a `NULL` value for the `platform` parameter; other branches use the [`NULL` check](https://github.com/mongodb/mongo-c-driver/blob/130938ad44a6516e6c399b9d25e5fe1b0464f14f/src/libmongoc/src/mongoc/mongoc-handshake.c#L590) within the `_append_and_truncate()` helper function. However, this bug was likely not detected due to both `vsnprintf()` (Unix/macOS) and `_vsnprintf_s()` (Windows), [used internally](https://github.com/mongodb/mongo-c-driver/blob/130938ad44a6516e6c399 …
=> CDRIVER-4166 permit NULL platform argument to mongoc_handshake_data_append()

src/libmongoc/src/mongoc/mongoc-topology-background-monitoring.c, src/libmongoc/src/mongoc/mongoc-topology-private.h, src/libmongoc/src/mongoc/mongoc-topology.c, src/libmongoc/tests/test-libmongoc.c
**Background**
Configuring a client with multiple hosts and the `loadBalanced=true` option, like `mongodb://host1,host2/?loadBalanced=true`, is an error. This comes from the [Load Balanced specification](https://github.com/mongodb/specifications/blob/2b0e9ed07446b2a92ac66216d19da59b7f582e69/source/load-balancers/load-balancers.rst#uri-validation):
> When loadBalanced=true is provided in the connection string, the driver MUST throw an exception in the following cases:
>
> - The connection string contains more than one host/port.
A single-threaded `mongoc_client_t` and multi-threaded `mongoc_client_pool_t` share behavior in a `mongoc_topology_t`. The `mongoc_topology_t` is constructed with a URI in `mongoc_topology_new`. In the invalid case for single-threaded, a `mongoc_client_t` [does not …
=> CDRIVER-4145 do not monitor an invalid topology

src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/DefaultNoMaxStaleness.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/LastUpdateTime.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/Nearest.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/Nearest2.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/OneKnownTwoUnavailable.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/PrimaryPreferred.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/PrimaryPreferred_tags.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/Secondary.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/SecondaryPreferred.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/SecondaryPreferred_tags.json, src/libmongoc/tests/json/max_staleness/ReplicaSetNoPrimary/ZeroMaxStaleness.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/DefaultNoMaxStaleness.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/LastUpdateTime.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/LongHeartbeat.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/LongHeartbeat2.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/MaxStalenessTooSmall.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/MaxStalenessWithModePrimary.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/Nearest.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/Nearest2.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/Nearest_tags.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/PrimaryPreferred.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/SecondaryPreferred.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/SecondaryPreferred_tags.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/SecondaryPreferred_tags2.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/Secondary_tags.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/Secondary_tags2.json, src/libmongoc/tests/json/max_staleness/ReplicaSetWithPrimary/ZeroMaxStaleness.json, src/libmongoc/tests/json/max_staleness/Sharded/SmallMaxStaleness.json, src/libmongoc/tests/json/max_staleness/Single/SmallMaxStaleness.json, src/libmongoc/tests/json/max_staleness/Unknown/SmallMaxStaleness.json
Resyncs the max staleness spec tests to commit e2914e7c88ad8578b78f26706bfa8e0737d0fcc0. This covers CDRIVER-4152 and CDRIVER-4204.
Tests were resynced using the following command from the [mongo-c-driver-tools](https://github.com/10gen/mongo-c-driver-tools) repo:
`ONLY=MAX_STALENESS ../mongo-c-driver-tools/update-c-spec-tests.sh`
=> CDRIVER-4204 / CDRIVER-4152 resync max staleness tests

src/libmongoc/src/mongoc/mongoc-client-private.h
Updates the wire protocol max version to 14.
Added comments to help when searching for maxWireVersion.
See: https://jira.mongodb.org/browse/CDRIVER-4165
Signed-off-by: Jesse Williamson <jesse.williamson@mongodb.com>
=> Bump WIRE_VERSION_MAX to 14

src/common/common-thread-private.h, src/libbson/src/bson/bson-atomic.c, src/libmongoc/src/mongoc/mongoc-cluster-sspi.c, src/libmongoc/src/mongoc/mongoc-shared.c
There are some warnings that appear in code, including one major incompatible-pointer-type that only appears on Windows. This also fixes an incompatible pointer type used in bson-atomic.c appearing in some configuration of MinGW on Windows (CDRIVER-4221).
=> Fix Win32 Warnings

.evergreen/run-tests.sh, src/libbson/src/bson/bson-atomic.h, src/libbson/tests/test-atomic.c
This work is not yet complete.  However, given the scope of the change just in getting the compile to succeed on RHEL 6, it seemed prudent to push my first set of changes as a WIP PR.
Initial patch build: https://spruce.mongodb.com/version/61874ce932f4177a1ad61efb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
@vector-of-bool In the patch build, you will want to focus on the compile task in the `rhel62` variant.  The test tasks are still failing, but for unrelated reasons.  At this point I am specifically interested to know if you find any errors or deficiencies in my initial changes.
After I get the compile working on RHEL 7 I will take a look at all the warnings that are still being produced.
=> CDRIVER-4215 use legacy atomic built-ins on gcc (>= 4.1, < 4.9)

src/libbson/src/bson/bson-atomic.h
So, it turns out that we need to use legacy atomics on all gcc 4.x versions.  The original change in #889 still results in build failures on Debian 8 (gcc 4.9).  It seems that using the new `__atomic` built-ins requires setting `-std=c11`.  It is not clear that we want to require that for legacy platforms, so expanding the check in this way seems like the better way.
Full patch build (filtered down to the Debian 8 variant): https://spruce.mongodb.com/version/618d9bcd0305b93ba3051410/tasks?page=0&variant=%5Egcc49%24
=> use legacy atomics on gcc < 5

NEWS, src/libbson/NEWS
- Copy `NEWS` and `src/libbson/NEWS` changes from 1.19.2.
- Copy `NEWS` and `src/libbson/NEWS` changes from 1.20.0. 
- Note atomics in `src/libbson/NEWS` and add contributors list.
After this is merged the 1.20.0 community announcement and GitHub release notes will be updated with the new release notes.
=> Update NEWS for 1.20.0 and 1.19.2

.evergreen/config.yml, .evergreen/run-aws-tests.sh, build/evergreen_config_lib/functions.py
A straightforward update that substitutes `git://` with `https://`, as [Github is planning to disable support](https://github.blog/2021-09-01-improving-git-protocol-security-github/) for the unencrypted Git protocol. The only instances of this protocol still being used in the C driver appears to be when cloning the [drivers-evergreen-tools](https://github.com/mongodb-labs/drivers-evergreen-tools) repository for Evergreen tasks.
=> CDRIVER-4216 Replace 'git://' with 'https://' for drivers-evergreen-tools repo

.evergreen/run-tests.sh, CONTRIBUTING.md, src/libmongoc/tests/test-mongoc-client-side-encryption.c
Thanks to CDRIVER-4206, the KMS TLS connections can now use user-provided CA and certificate files rather than depending on system certificate registration. This PR removes system cert registration and associated test skip condition checks, replacing them with use of the new `tls_opts` fields whose values are set by the `MONGOC_TEST_CSFLE_TLS_CA_FILE` and `MONGOC_TEST_CSFLE_TLS_CERTIFICATE_KEY_FILE` environment variables.
=> CDRIVER-4225 Explicitly set CA and cert file for use by KMS TLS connections

src/libmongoc/tests/test-mongoc-client-side-encryption.c
The insidious problem of "merge of well-tested-changeset into well-tested-base-branch produces never-before-seen and untested code" has bitten `master` following the merge of #890. The fixes are simple, fortunately.
=> Fix warnings following warnings-as-error merge

CMakeLists.txt, src/libmongoc/CMakeLists.txt
Ensure that the target for the bundled zlib is only built when the
bundled target is needed.  Also ensure that the build always correctly
finds the necessary headers.  For instance, even if there is a zlib
installed on the system and the build specifies the bundled zlib, ensure
that bundled headers are located before the system headers.
=> fix build of bundled zlib

src/libmongoc/doc/mongoc_collection_find_with_opts.rst, src/libmongoc/src/mongoc/mongoc-cmd.c, src/libmongoc/src/mongoc/mongoc-cursor-cmd.c, src/libmongoc/src/mongoc/mongoc-cursor-find.c, src/libmongoc/src/mongoc/mongoc-cursor.c, src/libmongoc/tests/test-mongoc-counters.c, src/libmongoc/tests/test-mongoc-exhaust.c, src/libmongoc/tests/test-mongoc-read-prefs.c
The C driver currently supports [exhaust cursors with OP_QUERY wire protocol messages](https://jira.mongodb.org/browse/CDRIVER-242), but does not support [exhaust cursors with OP_MSG wire protocol messages](https://jira.mongodb.org/browse/CDRIVER-2807). MongoDB Server 5.1 and newer [removes support for OP_QUERY messages](https://jira.mongodb.org/browse/DRIVERS-1857). The [Find, getMore and killCursors commands Spec](https://github.com/mongodb/specifications/blob/8f6f0fd67a479f1a09ca34477823469d0dec0fa9/source/find_getmore_killcursors_commands.rst#exhaust) accordingly requires drivers supporting exhaust cursors to unconditionally use OP_MSG for server versions that support it. However, strict compliance with the spec as currently written would introduce a regression in supported features …
=> CDRIVER-4130 Unconditionally use OP_MSG for server 5.1 and newer

.evergreen/find-cmake.sh
(This change would help facilitate building on platforms with a system CMake that is too old, like Amazon Linux 2, that has CMake version 2.8 at /usr/bin/cmake).
Evergreen patch build: https://spruce.mongodb.com/version/61cba5b63e8e86449da91664/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> add option to ignore system CMake

src/libbson/src/bson/bson-atomic.h
Fixes following compiler warning appearing constantly while building
open5gs project, which uses libbson:
/usr/include/libbson-1.0/bson/bson-atomic.h:725:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
725 | bson_atomic_thread_fence ()
| ^~~~~~~~~~~~~~~~~~~~~~~~
=> bson-atomic.h: Fix compiler warning in bson_atomic_thread_fence()

src/libbson/src/bson/bson-atomic.h
This PR aims to resolve CDRIVER-4237, depended on by [PHP-2013](https://jira.mongodb.org/browse/PHPC-2013).
~Four~ Three types of warnings are addressed by this PR (as described by GCC 4.8.5):
- ISO C does not allow extra `;` outside of a function [-Wpedantic]
- passing argument `{N}` of `{func}` from incompatible pointer type [enabled by default]
- pointer targets in passing argument `{N}` of `{func}` differ in signedness [-Wpointer-sign]
- ~empty macro arguments are undefined in ISO C90 and ISO C++98 [enabled by default]~
Followup changes in addition to the current set may need to be added to fully resolve [PHP-2013](https://jira.mongodb.org/browse/PHPC-2013). These will be added as demanded in response to code review.
=> CDRIVER-4237 - Address incompatible pointer warnings on GCC 4.8.5

src/libbson/src/bson/bson-atomic.c, src/libbson/src/bson/bson-atomic.h, src/libmongoc/tests/TestSuite.c, src/libmongoc/tests/TestSuite.h, src/libmongoc/tests/json-test.c, src/libmongoc/tests/test-mongoc-uri.c
Per CDRIVER-4264, there are three compilation errors preventing successful compilation [on VS 2013 variants](https://evergreen.mongodb.com/version/mongo_c_driver_7a35cf865629122267c3d59cca0f922c5e455f0d). This PR addresses each of these warnings:
- `'_Exit' undefined; assuming extern returning int`
VS 2013 only provides partial support for the C99 standard. This support apparently does not extend to providing the `_Exit` function, which is a C99 feature. Given that its use in the test suite (to report the type of signal triggering failure) is [not strictly necessary](https://github.com/mongodb/mongo-c-driver/pull/870#discussion_r712657428), I have [opted for its removal](https://github.com/mongodb/mongo-c-driver/commit/5b0dbb33a76eb0c1d837de790fc313c963b5bf53).
- `'snprintf' undefined; …
=> CDRIVER-4264 Address build failures on VS 2013 variants on Evergreen

.evergreen/benchmark.yml
CDRIVER-4098 (#926) neglected to remove the [c-driver-benchmark-mongo32](https://evergreen.mongodb.com/task/mongo_c_driver_perf_c_driver_benchmark_mongo32_BenchMarkTests_3d0f609537dd8c120dbbce9ed4a8e29519b1b191_22_01_28_17_09_12) task from the [mongo-c-driver-perf Evergreen matrix](https://evergreen.mongodb.com/waterfall/mongo-c-driver-perf). This PR removes this benchmark with MongoDB server 3.2, which is now below the supported minimum wire version corresponding to server 3.6.
=> Remove c-driver-benchmark-mongo32 from mongo-c-driver-perf

src/libmongoc/tests/test-mongoc-client-side-encryption.c
See https://github.com/mongodb/specifications/pull/1136 for the motivation behind this change. This resolves recent inconsistent test failures seen with Client Side Encryption tests.
=> CDRIVER-4285 remove example.com from tests

src/libmongoc/src/mongoc/mongoc-stream-tls-openssl.c
CDRIVER-4284 reports a scenario where `ERR_get_error` is used to construct failure information despite the possibility that the OpenSSL library may not contain error info to be reported. This PR ensures that there is a meaningful error message is guaranteed to be relayed even if OpenSSL does not provide error info.
=> CDRIVER-4284 Avoid empty OpenSSL error condition on handshake failure

.evergreen/run-tests.sh
Flaky mock KMS server startup failures as reported in CDRIVER-4274 seem to be addressed by raising the wait duration up from 1 minute to 5 minutes per [patch results](https://spruce.mongodb.com/version/6201961761837d0dfe173e88/) (none of the failing tasks are due to mock KMS server startup failure). It seems like the background processes launching the mock KMS servers were not being given enough time (1 minute was too short).
=> CDRIVER-4274 Increase wait time for mock KMS server startup to 5 minutes

.evergreen/abi-compliance-check.sh, .evergreen/config.yml, build/calc_release_version.py, build/evergreen_config_lib/functions.py
- Add a `--next-minor` version flag to calc_release_version.py.
- Remove hard coded version numbers for C driver builds from test scripts.
calc_release_version.py is used to calculate release versions by inspecting git history. When checked out to a non-release non-master branch, calc_release_version.py prints a version based off of the `1.11.0` tag `1.11.1-20220201+gitf6e6a7025d`. The `1.11.0` tag is erroneously on the `master` branch. Evergreen patch builds check out a revision. That necessitated hard coding the version in test scripts.
It results in this [misleading report](https://mciuploads.s3.amazonaws.com/mongo-c-driver/releng/99fe2b528b0e0d869cb0687baeacf23b602ad3c8/mongo_c_driver_99fe2b528b0e0d869cb0687baeacf23b602ad3c8/mongo_c_driver_releng_99fe2b528b0e0d869cb0687baeacf23b602ad3c …
=> CDRIVER-3573 remove hard-coded versions from test scripts

src/libmongoc/src/mongoc/mongoc-crypto-openssl.c
https://jira.mongodb.org/browse/CDRIVER-4297
See https://github.com/mongodb/mongo-php-driver/issues/1302 for discussion why having these symbol public is bad
Notice: others are already hidden
ex: https://github.com/mongodb/mongo-c-driver/blob/master/src/kms-message/src/kms_crypto_libcrypto.c#L25
=> CDRIVER-4297 use static decls for OpenSSL 1.1 polyfills

src/libmongoc/doc/authentication.rst
See CDRIVER-4310 for background and motivation.
=> CDRIVER-4310 clarify that SSPI is used by default

.evergreen/config.yml, build/evergreen_config_lib/variants.py, src/libmongoc/tests/test-libmongoc.c, src/libmongoc/tests/test-libmongoc.h, src/libmongoc/tests/test-mongoc-sdam-monitoring.c
Full patch build: https://spruce.mongodb.com/version/622e50b457e85a4b73b784fd/tasks
A few items to note:
- the new variant is named `zseries-rhel83`, but retains the same display name as before, `*zSeries`
- the `authentication-tests-openssl-nosasl` and `authentication-tests-openssl` tasks in the new variant fail, but they were also failing on the waterfall before this change
- all of the `test-*` tasks in the new variant are failing in the `SYSTEM FAILED` state; this is a result of the server not yet publishing builds for RHEL8 zSeries (the ticket for that is [SERVER-44074](https://jira.mongodb.org/browse/SERVER-44074)) and the tasks should turn green once the server builds are published
- based on the Slack discussion I have added a skip for the …
=> CDRIVER-3923 switch to new RHEL8 s390x Evergreen hosts

.evergreen/config.yml, CMakeLists.txt, build/evergreen_config_lib/tasks.py, src/kms-message/src/kms_request_str.c, src/libmongoc/tests/TestSuite.h
This is the first in a series of PRs intended to reduce the set of warnings currently being observed when building the C driver.
This PR addresses the following warnings:
* LLDLinker on Windows
The LLDLinker module as currently written does not support MSVC, but was being [unconditionally included](https://github.com/mongodb/mongo-c-driver/commit/14a8be487c2189c8716c40d0eeb3d1f518ca472a). Its inclusion has been conditioned on not being compiled with MSVC.
* `-fPIC` on Windows
MSVC does not recognize the `-fPIC` flag, but it was being [unconditionally passed](https://github.com/mongodb/mongo-c-driver/commit/547c93cb29c19b0606d1a674d5c61b960b9b6236) as an compilation argument. Instances of the flag have been replaced by use of the `ENABLE_PIC` CMake configuration option.
* Format specifies …
=> Reducing Warnings - Miscellaneous Warnings

src/libmongoc/src/mongoc/mongoc-cmd.c, src/libmongoc/tests/test-mongoc-topology.c
Evergreen patch build: https://spruce.mongodb.com/version/623cd28b61837d50964ea4e1/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=scan-build (it is a complete patch build, but the link has it filtered down to only scan-build tasks)
@vector-of-bool I requested your review as well since this required tweaking code that was committed by you in the last few months.
=> eliminate dead store operations that caused scan-build failures

src/libbson/CMakeLists.txt, src/libbson/src/bson/CMakeLists.txt, src/libbson/src/bson/bson-cmp.h, src/libbson/src/bson/bson-compat.h, src/libbson/src/bson/bson.h, src/libbson/tests/test-bson-cmp.c, src/libmongoc/CMakeLists.txt, src/libmongoc/tests/test-libmongoc.c
This is part of a series of PRs intended to reduce the set of warnings currently being observed when building the C driver.
This PR introduces [a set of utilities](https://github.com/mongodb/mongo-c-driver/commit/1c007a3bd54328a59b5ec08df58acdcb2cc5d762) modeled after the [Safe Integral Comparisons](https://wg21.link/p0586r2) proposal for the C++ standard library, which was accepted and merged into the C++20 standard. These utilities are extremely useful in addressing warnings involving comparisons or conversions between integers with different signedness and sizes.
The interface proposed in the original paper relies on type deduction to select appropriate behavior according to the signedness and size of the given arguments:
```cpp
A a = ...
B b = ...
// no need for any cast since …
```
=> Reducing Warnings - Safe Integral Comparisons

src/libmongoc/tests/json/client_side_encryption/types.json
Resync the `types` CSFLE test to https://github.com/mongodb/specifications/commit/6a7158d51b4c41f2f4a9c1293c5e1dceb93ab5c2 to resolve test failures on mongocryptd 6.0.0-alpha.
The `badQueries` test is not included in C driver tests due to CDRIVER-3387. Only the `types` test was resynced.
=> CDRIVER-4332 resync types CSFLE test

src/libmongoc/doc/mongoc_apm_command_failed_get_server_connection_id.rst, src/libmongoc/doc/mongoc_apm_command_failed_t.rst, src/libmongoc/doc/mongoc_apm_command_started_get_server_connection_id.rst, src/libmongoc/doc/mongoc_apm_command_started_t.rst, src/libmongoc/doc/mongoc_apm_command_succeeded_get_server_connection_id.rst, src/libmongoc/doc/mongoc_apm_command_succeeded_t.rst, src/libmongoc/src/mongoc/mongoc-apm-private.h, src/libmongoc/src/mongoc/mongoc-apm.c, src/libmongoc/src/mongoc/mongoc-apm.h, src/libmongoc/src/mongoc/mongoc-client.c, src/libmongoc/src/mongoc/mongoc-cluster.c, src/libmongoc/src/mongoc/mongoc-cursor-legacy.c, src/libmongoc/src/mongoc/mongoc-cursor.c, src/libmongoc/src/mongoc/mongoc-server-description-private.h, src/libmongoc/src/mongoc/mongoc-server-description.c, src/libmongoc/src/mongoc/mongoc-write-command-legacy.c, src/libmongoc/tests/json/command_monitoring/unified/pre-42-server-connection-id.json, src/libmongoc/tests/json/command_monitoring/unified/server-connection-id.json, src/libmongoc/tests/unified/entity-map.c, src/libmongoc/tests/unified/entity-map.h, src/libmongoc/tests/unified/runner.c
Evergreen patch build: https://spruce.mongodb.com/version/625f6c3057e85a68b11bea04/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
I've reviewed the tasks that are green on the base commit and red on the patch build.  The few failures are unrelated (e.g., the longstanding ccache bug on Ubuntu, the failure to build with static libssl on RHEL, etc.).
=> CDRIVER-4085 add server connectionId to command monitoring events

src/libmongoc/tests/bsonutil/bson-match.c, src/libmongoc/tests/json/unified/kmsProviders-explicit_kms_credentials.json, src/libmongoc/tests/json/unified/kmsProviders-mixed_kms_credential_fields.json, src/libmongoc/tests/json/unified/kmsProviders-placeholder_kms_credentials.json, src/libmongoc/tests/json/unified/kmsProviders-unconfigured_kms.json, src/libmongoc/tests/unified/entity-map.c, src/libmongoc/tests/unified/entity-map.h, src/libmongoc/tests/unified/result.c, src/libmongoc/tests/unified/runner.c
This PR is a part of CDRIVER-4317. It is being reviewed separately to unblock FLE 2 work.
This PR implements support for the new `clientEncryption` entity in unified tests. The JSON schema version is bumped from 1.5 to 1.8 to support running new unified test format valid-pass test files. This does _not_ indicate that the unified test runner supports JSON schema version 1.8 in its entirety (not all spec tests have been updated).
This PR includes a drive-by improvement to unified test runner error messages to support outputting the actual value of a BSON document when it differs from the expected value.
- Add support for `runOnRequirement.csfle` to avoid test runner errors when built without CSFLE.
=> CDRIVER-4317 Add support for clientEncryption entity in unified test runner

src/libmongoc/doc/mongoc_apm_command_failed_get_server_connection_id.rst, src/libmongoc/doc/mongoc_apm_command_started_get_server_connection_id.rst, src/libmongoc/doc/mongoc_apm_command_succeeded_get_server_connection_id.rst
This removes copypasta that was missed in https://github.com/mongodb/mongo-c-driver/commit/ba73833f18191b34acc990bdca91bb9e68c90dfb (#972)
=> CDRIVER-4085 fix docs for server_connection_id getters

src/libmongoc/tests/json/crud/unified/aggregate-allowdiskuse.json
Full Evergreen patch build: https://spruce.mongodb.com/version/626c8db630661566a405605d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
I synced all the spec tests associated with the `allowDiskUse` option and ran a patch build.  There were no failures present in the patch build that weren't in the base commit (except for one spurious TSAN failure).  I also checked to ensure that we aren't skipping any of the tests associated with `allowDiskUse`.  Apart from the spec tests themselves, there are only two mentions of `allowDiskUse` in the C driver code:
- in `test-mongoc-collection.c`, where it is set as an option as part of a specific test
- in `mongoc_collection_find_with_opts.rst` where its existence and type is documented
Neither of those occurrences appear to require a change as part of …
=> CDRIVER-4358 sync allowDiskUse CRUD spec tests

src/libmongoc/src/mongoc/mongoc-openssl.c
See [SSL_get_tlsext_status_ocsp_resp](https://www.openssl.org/docs/man3.0/man3/SSL_get_tlsext_status_ocsp_resp.html). Previous versions have the same signature also.
The `resp` argument is not `const`, and when `mongoc-openssl.c` is built on Windows this causes a [C4090](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4090) error.
We can work around this by simply passing a pointer to a pointer that is not const, and then assigning its value to the const pointer.
=> fix const mismatch for pointer to data

src/libmongoc/CMakeLists.txt
As it stands, this check does not function as intended on the CMake versions that I tried (3.22 and 3.23).
I suspect it would not work from CMake 3.10 until CMake 3.70 (were such a version ever to exist); the comparison appears to a floating-point comparison instead of a version comparison.
I took the error message
> `requires CMake 3.7 or later`
at face value and assumed that `${CMAKE_VERSION} VERSION_GREATER_EQUAL 3.7` is correct instead of `${CMAKE_VERSION} VERSION_GREATER 3.7` which would be the direct translation from the previous version of the script.
=> fix CMake version check for OpenSSL 1.1+ on Windows

.evergreen/config.yml, build/evergreen_config_lib/tasks.py, src/libmongoc/doc/mongoc_auto_encryption_opts_set_encrypted_fields_map.rst, src/libmongoc/doc/mongoc_auto_encryption_opts_t.rst, src/libmongoc/doc/mongoc_database_create_collection.rst, src/libmongoc/doc/mongoc_database_drop_with_opts.rst, src/libmongoc/src/mongoc/mongoc-client-side-encryption.c, src/libmongoc/src/mongoc/mongoc-client-side-encryption.h, src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/src/mongoc/mongoc-database-private.h, src/libmongoc/src/mongoc/mongoc-database.c, src/libmongoc/src/mongoc/mongoc-topology-private.h, src/libmongoc/src/mongoc/mongoc-topology.c, src/libmongoc/src/mongoc/mongoc-util-private.h, src/libmongoc/src/mongoc/mongoc-util.c, src/libmongoc/tests/json-test.c, src/libmongoc/tests/json/client_side_encryption/fle2-CreateCollection.json, src/libmongoc/tests/test-mongoc-client-side-encryption.c
- Add `mongoc_auto_encryption_opts_set_encrypted_fields_map`
- Add `encryptedFields` required behavior to create and drop collection helpers.
- Run "*-cse" tasks on replica set for server 6.0+.
- Add "majority" write concern to key vault operations in CSFLE tests.
- Add `_mongoc_iter_document_as_bson` utility to convert a `bson_iter_t` to `bson_t`.
Please see https://github.com/mongodb/specifications/pull/1183/ for the specification changes.
FLE 2.0 requires a non-standalone server topology. Tests need to apply write concern majority on key vault operations, as noted in the [specification test README](https://github.com/mongodb/specifications/blob/c5067286cf05f741660c05e1fe5fc66144fef76d/source/client-side-encryption/tests/README.rst#prose-tests)
> Perform all applicable operations on key …
=> CDRIVER-4365 support encryptedFields in collection create and drop

.evergreen/compile-unix.sh, .evergreen/config.yml, CMakeLists.txt, build/cmake/CMakeLists.txt, build/cmake/Sanitizers.cmake, build/evergreen_config_lib/tasks.py
This change adds a CMake sanitizer setting and removes raw compile-flags from the high-level build config.
=> Sanitizer options

src/libbson/src/bson/bson-decimal128.c, src/libbson/src/bson/bson-json.c, src/libbson/src/jsonsl/jsonsl.c, src/libbson/tests/test-json.c
Certain token sequences leave the bson-from-json parser unhappy. This addresses those.
=> [CDRIVER-3380] Fixup JSON specials and decimal128 parsing

CMakeLists.txt
The `Ninja Multi-Config` generator permits building arbitrary configurations without rerunning CMake. This PR enables the special "colon-suffix" cross-config targets in the generated Ninja files. i.e. one can build `all:Debug` to build the project in `Debug`, `all:Release` to build the project in release, and `all:all` to build all enabled configurations simultaneously.
=> (QoL) Enable cross-config if we are the top-level project in a ninja-multiconf build

src/libmongoc/doc/installing.rst
The C driver has not tested on Visual Studio < 2013 or since Visual Studio versions older than 2013 were removed from Evergreen (refer: CDRIVER-3593).
There is an incorrect note in [the public documentation](http://mongoc.org/libmongoc/current/installing.html#build-environment-on-windows-with-visual-studio) claiming to support back to 2010.
=> CDRIVER-4376 note that Visual Studio 2013 is required

src/libmongoc/doc/mongoc_collection_estimated_document_count.rst
https://jira.mongodb.org/browse/CDRIVER-4309
Required documentation per the [CRUD spec](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#estimateddocumentcount), which I missed in the [original PR](https://github.com/mongodb/mongo-c-driver/pull/984).
=> CDRIVER-4309 document behavior for estimated_document_count

.evergreen/config.yml, build/evergreen_config_lib/tasks.py, src/libmongoc/src/mongoc/mongoc-client-private.h, src/libmongoc/src/mongoc/mongoc-util.c
Addresses CDRIVER-4380 
I've added a set of tasks for `6.0` integration testing in this PR. Also we seem to have jumped over wire version 16, which I believe corresponds to server version 5.3 based on digging in the code.
=> CDRIVER-4380 Update maxWireVersion for 6.0

.evergreen/skip-tests.txt
Explain is now supported when using csfle with changes of MONGOCRYPT-427.
=> do not skip explain

src/libmongoc/src/mongoc/mongoc-cursor.c
This was previously discussed in https://github.com/mongodb/mongo-c-driver/pull/982#discussion_r870403589 but I forgot to revise the TODO comment before merging.
=> Replace TODO comment

src/libmongoc/src/mongoc/mongoc-change-stream.c, src/libmongoc/src/mongoc/mongoc-opts.c, src/libmongoc/tests/test-mongoc-change-stream.c
This commit implements CDRIVER-4305, which allows fullDocument to be
NULL equivalent to a literal "default" string. This is permitted in
server 3.6+, and this change makes that the preferred and default
behavior.
This driver already requires 3.6 or newer (as per minWireVersion)
This changeset does not introduce new tests, but it was tested locally against the change_streams unified tests, which rely on `fullDocument` being nullable. Additional changes are required before the change_streams unified tests can be enabled.
=> CDRIVER-4305: 'fullDocument' may be null/omitted

src/libmongoc/src/mongoc/mongoc-change-stream.c
This adds a missing "comment" value to getMore for changestreams. This
fixes test failures in the changestreams tests, which are not yet
enabled in this branch but has been manually validated locally.
=> CDRIVER-4199: Add comment to change stream getMore commands

src/libmongoc/CMakeLists.txt
Current implementation results in the following error message (note the missing location of the candidate):
```
Searching for libmongocrypt
--   libmongocrypt found at
--   libmongocrypt version 1.3.0 found
--   libmongocrypt version 1.5.0 is required to enable Client-Side Field Level Encryption Support.
CMake Error at src/libmongoc/CMakeLists.txt:466 (message):
Required library (libmongocrypt) not found.
```
This PR addresses this issue by using [`${mongocrypt_DIR}`](https://cmake.org/cmake/help/v3.1/command/find_package.html) instead of the not-yet-defined `${LIBMONGOCRYPT_LIBRARY}` on [line 459](https://github.com/eramongodb/mongo-c-driver/blob/62fc65d20ad90b76052775f1b720e36945984f81/src/libmongoc/CMakeLists.txt#L459):
```
Searching for libmongocrypt
--   libmongocrypt found at …
```
=> Fix printing location of libmongocrypt with invalid version

.evergreen/compile-unix.sh, .evergreen/compile-windows.sh
Resolving MONGOCRYPT-434 may put the libmongocrypt master branch in a temporary breaking state until drivers update bindings and [SERVER-66771](https://jira.mongodb.org/browse/SERVER-66771) is released.
=> pin libmongocrypt to 1.5.0-alpha2

src/libmongoc/tests/json/client_side_encryption/legacy/fle2-Delete.json, src/libmongoc/tests/json/client_side_encryption/legacy/fle2-EncryptedFields-vs-jsonSchema.json, src/libmongoc/tests/json/client_side_encryption/legacy/fle2-FindOneAndUpdate.json, src/libmongoc/tests/json/client_side_encryption/legacy/fle2-InsertFind-Indexed.json, src/libmongoc/tests/json/client_side_encryption/legacy/fle2-Update.json
- Resync fle2-* tests for revert in DRIVERS-2343.
MONGOCRYPT-433 was reverted in libmongocrypt 1.5.0-rc1. This required updating FLE 2 tests.
=> CDRIVER-4397 Resync fle2-* tests for revert

build/cmake/CCache.cmake
This PR addresses the "ccache.conf: No such file or directory" spurious failures on Evergreen by conditionally disabling ccache by default given the detected ccache version is older than 3.4.3.
After further investigation, I found [this issue thread](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/35) which documented the same spurious failure being observed on Evergreen. Thread participants deduced the cause to be ccache being invoked in parallel, "which is problematic because ccache creates its configuration in `$HOME/.ccache/ccache.conf` on first run, but in non-atomic way, which breaks with error". This issue was then [reported and subsequently patched](https://github.com/ccache/ccache/issues/260) in ccache version 3.4.3.
As of time of writing, this condition to disable …
=> Disable ccache by default for versions older than 3.4.3

build/cmake/CCache.cmake
Fix overzealous elison of call to ~`find_package()`~ `find_program()` introduced in https://github.com/mongodb/mongo-c-driver/pull/1029 when `MONGO_USE_CCACHE` is set. `CCACHE_EXECUTABLE` still needs to be found and set when `MONGO_USE_CCACHE` is manually set by the user on initial configuration, not just post-configuration.
=> Do not elide find_package() if MONGO_USE_CCACHE is set

.evergreen/mongo-c-driver.spec, .evergreen/spec.patch
Also use version 1.23.0 for the mock build, since that is what will be
calculate as the next version by the build based on the precense of the
1.22.0-beta0 release tag.
Patch build: https://spruce.mongodb.com/version/62a4b55b850e61511437f291/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Note that the patch build fails.  However, the failure is a result of C driver `master` branch requiring libmongocrypt 1.5.0 but Fedora only has 1.4.0 (since 1.5.0 isn't yet released).  The post-1.5.0 work to make sure this task returns to succeeding is captured in CDRIVER-4399.
=> sync RPM spec file for 1.21.2 release

src/libmongoc/doc/conf.py, src/libmongoc/doc/mongoc_auto_encryption_opts_set_bypass_query_analysis.rst, src/libmongoc/doc/mongoc_auto_encryption_opts_set_encrypted_fields_map.rst, src/libmongoc/doc/mongoc_client_encryption_encrypt.rst, src/libmongoc/doc/mongoc_client_encryption_encrypt_opts_set_algorithm.rst, src/libmongoc/doc/mongoc_client_encryption_encrypt_opts_set_contention_factor.rst, src/libmongoc/doc/mongoc_client_encryption_encrypt_opts_set_query_type.rst, src/libmongoc/doc/queryable-encryption.rst
[CDRIVER-4402]
The ticket requests updating the documentation on `indexKeyId`, but that parameter is not exposed in the public API (yet).
=> [CDRIVER-4402] Document Queryable Encryption as an experimental API

src/libmongoc/src/mongoc/mongoc-client-side-encryption.c, src/libmongoc/tests/json/client_side_encryption/unified/removeKeyAltName.json, src/libmongoc/tests/unified/runner.c
This PR implements the necessary changes to satisfy [DRIVERS-2356](https://jira.mongodb.org/browse/DRIVERS-2356).
It also includes a drive-by fix for a potential null pointer dereference of `ignore_extra_events` in the unified test runner given the optional `ignoreExtraEvents` option is not provided.
=> Reduce expected removeKeyAltName operations to a single findOneAndUpdate

build/calc_release_version.py
- Use prerelease marker when computing previous release version in calc_release_version.py
This resolves recent failures of the [abi-compliance-check task](https://evergreen.mongodb.com/task/mongo_c_driver_releng_abi_compliance_check_72ca151532da0eaa7be39aea51b3b9d473612b20_22_06_14_19_21_58). The task compares the C driver from the most recent release tag. The most recent release tag is computed [here](https://github.com/mongodb/mongo-c-driver/blob/72ca151532da0eaa7be39aea51b3b9d473612b20/.evergreen/abi-compliance-check.sh#L14:L14) with:
```sh
echo $(python ./build/calc_release_version.py --next-minor -p) > VERSION_RELEASED
```
Before this change, a non-existent tag is output:
```
% python ./build/calc_release_version.py --next-minor -p
1.22.0
```
After this change, the 1.22.0-beta1 tag …
=> fix abi-compliance-check task

src/libmongoc/tests/test-mongoc-client-side-encryption.c
- Add example use of Queryable Encryption.
This example was requested to assist the documentation team. It is not intended to be in the C driver public documentation.
=> CDRIVER-4379 add example use of Queryable Encryption

src/libmongoc/tests/test-mongoc-client-side-encryption.c
Resolves CDRIVER-4407. Implements the new assertions proposed by DRIVERS-2360.
=> CDRIVER-4407 Add assertions that addKeyAltName() added keyAltName without failure

src/libmongoc/tests/unified/runner.c
This PR validates changes proposed in DRIVERS-2359.
There are no tests on Evergreen with `*-cse` running against servers older than 4.2.
Running locally with a 3.6 server before this change:
```
% ./cmake-build/src/libmongoc/test-libmongoc -l "/client_side_encryption/unified/removeKeyAltName"
...
error: expected result, but got error: The dollar ($) prefixed field '$set' in '0.$set' is not valid for storage.
{ "status": "fail", "test_file": "/client_side_encryption/unified/removeKeyAltName", "seed": "1458558547", "start": 884.901830, "end": 886.010523, "elapsed": 1.108693  }
```
After this change:
```
./cmake-build/src/libmongoc/test-libmongoc -l "/client_side_encryption/unified/removeKeyAltName"
...
Requirement 0 failed because: Server version(3.6.21) is lower than …
```
=> CDRIVER-4408 require 4.2.0 server for csfle tests

src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/src/mongoc/mongoc-write-command.c, src/libmongoc/tests/test-mongoc-find-and-modify.c, src/libmongoc/tests/test-mongoc-server-stream.c
This PR resolves some discrepancies in how the client-side error reporting server incompatibility with the `hint` feature is communicated.
This PR ensure all related errors have:
- Domain: `MONGOC_ERROR_COMMAND`
- Code: `MONGOC_ERROR_PROTOCOL_BAD_WIRE_VERSION`
- Message: "The selected server does not support hint for \<commandName\>"
This PR is also motivated by work being done on [CXX-2347](https://jira.mongodb.org/browse/CXX-2347) in light of [CXX-2377](https://jira.mongodb.org/browse/CXX-2377).
=> Enforce consistency across server support for hint errors

.gitignore
- Add dist to gitignore
The "dist" directory is created as part of the release process [here](https://github.com/10gen/mongo-c-driver-tools/blob/0f61287a1141eacb0d0be06f59c62d77e670c5c5/release.py#L397).
=> ignore dist

src/libmongoc/tests/TestSuite.c
I was scratching my head about LeakSanitizer warnings I was only seeing on my own box, until I realized that I use CTest and Evergreen does not.
=> Fix leak of test context when test registration is skipped

.evergreen/compile-unix.sh
libmongocrypt needs a copy of mongo-c-driver to build a libbson for itself. We are already such a mongo-c-driver, so send that to the libmongocrypt sub-build.
=> Inject our own project as the mongoc source for building libmongocrypt

build/calc_release_version.py
Detail of changes:
* remove --merged option for compatibility with older versions of 'git'
* fix bug that considered pre-release tags as higher than their
succeeding releases (e.g., 1.22.0-beta0 was treated as a higher
version tag than 1.22.0)
* formatting fixes
* refactor to reduce code duplication, increase readability, and
improve maintainability
Patch builds are not a good reflection of whether or not this will work as intended, so here is a console transcript showing the behavior.  This was done on a Debian 8 system (Git version 2.1.4, Python 2.7.9/3.4.2) as well as on a Debian 7 system (Git 1.7.10.4, Python 2.7.3):
```
root@debian:~/mongo-c-driver.git# git checkout master
M	build/calc_release_version.py
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'. …
```
=> CDRIVER-4422 calc_release_version.py: remove --merged, plus improvements

src/libbson/src/bson/bson-json.c
Motivated by the number of times this file has been attempted to be clang-formatted only for the `HANDLE_OPTION` blocks to be rendered utterly unreadable. Hopefully this is preferable to disabling clang-format for such a large block of code. Given how strange the `HANDLE_OPTION` macro is to begin with, I'm willing to accept the strangeness of the `_selection_statement` pattern. This code could use a refactor down the road to avoid these unusual patterns.
=> Improve clang-format friendliness of HANDLE_OPTION macro

orchestration_configs/replica_sets/auth-ssl.json, orchestration_configs/replica_sets/auth-thisDB-ssl.json, orchestration_configs/replica_sets/auth.json, orchestration_configs/replica_sets/basic-ssl.json, orchestration_configs/replica_sets/basic.json, orchestration_configs/servers/auth-aws.json, orchestration_configs/servers/auth-ssl.json, orchestration_configs/servers/auth.json, orchestration_configs/servers/basic-ipv4-only.json, orchestration_configs/servers/basic-ssl.json, orchestration_configs/servers/basic.json, orchestration_configs/servers/ecdsa-basic-tls-ocsp-disableStapling.json, orchestration_configs/servers/ecdsa-basic-tls-ocsp-mustStaple-disableStapling.json, orchestration_configs/servers/ecdsa-basic-tls-ocsp-mustStaple.json, orchestration_configs/servers/mmapv1.json, orchestration_configs/servers/rsa-basic-tls-ocsp-disableStapling.json, orchestration_configs/servers/rsa-basic-tls-ocsp-mustStaple-disableStapling.json, orchestration_configs/servers/rsa-basic-tls-ocsp-mustStaple.json, orchestration_configs/servers/snappy-zlib-zstd.json, orchestration_configs/servers/snappy.json, orchestration_configs/servers/versioned-api-testing.json, orchestration_configs/servers/wiredtiger.json, orchestration_configs/servers/zlib.json, orchestration_configs/servers/zstd.json
- Remove `journal: "true"` from all mongo-orchestration configs
See DRIVERS-2388 for a motivation of the removal.
The C driver has copies of the orchestration config files. The first attempted solution was to copy the contents of `.evergreen/orchestration/configs/` from https://github.com/mongodb-labs/drivers-evergreen-tools/commit/fd8d93e30bfea852245da727851078cfb297dc92 into `mongo-c-driver/orchestration_configs`. The diff included changes additional to the removal of `"journal": true`. Attempting to run a patch build resulted in a [test failure](https://spruce.mongodb.com/version/62d1cd59c9ec4462ba444eae/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
Because this is causing test failures, I prefer proceeding with a simpler fix. This PR proposes a simple fix of applying the same change …
=> Remove journal from all configs

build/cmake/FindSASL2.cmake
The normal variable `MONGOC_HAVE_SASL_CLIENT_DONE` being set to `0` by default in [src/libmongoc/CMakeLists.txt](https://github.com/eramongodb/mongo-c-driver/blob/9c4f49f2e9e69d6ae61070095457fb742a375919/src/libmongoc/CMakeLists.txt#L254) interferes with `check_symbol_exists` which tries to set the result variable [as an internal cache variable](https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html), as noted under [Set Cache Entry](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry):
> The content of the cache variable will not be directly accessible if a normal variable of the same name already exists (see [rules of variable evaluation](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#cmake-language-variables)).
This is demonstrated by this …
=> Fix sasl_client_done detection

.evergreen/config.yml, build/evergreen_config_generator/__init__.py, build/generate-future-functions.py, src/libmongoc/tests/mock_server/future-functions.c, src/libmongoc/tests/mock_server/future-functions.h, src/libmongoc/tests/mock_server/future-value.c, src/libmongoc/tests/mock_server/future-value.h, src/libmongoc/tests/mock_server/future.c, src/libmongoc/tests/mock_server/future.h, src/libmongoc/tests/test-mongoc-topology-reconcile.c, src/libmongoc/tests/test-mongoc-topology-scanner.c, src/libmongoc/tests/test-mongoc-topology.c
~It seems like something has changed with how the Evergreen config file is generated (namely the formatting). This PR commits these updates to the `config.yml` file.~ Patch applied, prior "block style" formatting is now preserved.
This PR also updates `generate-future-functions.py` to account for the new (as of https://github.com/mongodb/mongo-c-driver/pull/904) `must_use_primary` parameter for `mongoc_topology_select`. Call sites for `future_topology_select` were updated with an additional `NULL` argument accordingly.
=> Update generated files for Evergreen config and future functions

src/libmongoc/tests/test-mongoc-client-side-encryption.c
The `cryptSharedLibPath` auto encryption option was not being correctly included in the call to `mongoc_auto_encryption_opts_set_extra`.
=> Fix setting of mongo_crypt_v1 shared library path

src/libmongoc/tests/json/change_streams/unified/change-streams-resume-errorLabels.json
- Sync change-streams-resume-errorLabels test https://github.com/mongodb/specifications/commit/8d897ad01f8c600ddaef139740d5b68fd2950c0e
This resolves test failures on the `*-latest-*` tasks due to the issue described in DRIVERS-2387. Here is a [patch build](https://spruce.mongodb.com/version/62debbe43e8e864fca2721d5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with the previously failing task.
=> CDRIVER-4429 sync change-streams-resume-errorLabels test

.evergreen/config.yml, .evergreen/ecs_hosted_test.js, build/evergreen_config_lib/functions.py
This PR fixes the [AWS ECS test tasks](https://spruce.mongodb.com/version/62d9e3f83627e0054179d630/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=ecs).
- Use a Python virtual environment with upgraded boto3.
- Use separate client in shell auth.
Upgrading boto3 resolves [the error](https://spruce.mongodb.com/task/mongo_c_driver_clang60ubuntu_test_aws_openssl_ecs_4.4_99b55d7f4b3e3ea96152d689e81f6563ec99d664_22_07_20_21_42_37/logs?execution=0) `botocore.exceptions.ParamValidationError: Parameter validation failed`. It is suggested in DRIVERS-1462. A script for creating the virtual environment was added in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/138.
Using a separate client in the shell auth resolves [the …
=> CDRIVER-4150 fix the AWS ECS test tasks

src/libmongoc/src/mongoc/mongoc-uri.c, src/libmongoc/tests/test-mongoc-uri.c
This PR resolves CDRIVER-4437.
In addition to the existing SRV URI parse error message "Invalid service name in URI", additional messages were added for each potential parse failure condition in `mongoc_uri_parse_srv`:
- "Missing service name in SRV URI"
- "Multiple service names are prohibited in an SRV URI"
- "Port numbers are prohibited in an SRV URI" (specifically requested by CDRIVER-4437)
=> CDRIVER-4437 Improve quality of SRV URI parse error messages

src/libbson/src/bson/bson-timegm-private.h
gmtsub in bson-timegm.c tried to assign a static const string to a non
const string tm_zone on bson_tm struct, failing the build because of the
enforced -Wincompatible-pointer-types:
static const char wildabbr[] = WILDABBR;
static const char gmt[] = "GMT";
// [...]
tmp->TM_ZONE = offset ? wildabbr : gmtptr ? gmtptr->chars : gmt;
Fix it by making tm_zone const.
=> Fix discarded const in gmtsub function

.evergreen/build_snapshot_rpm.sh, .evergreen/mongo-c-driver.spec, .evergreen/spec.patch, src/libmongoc/doc/conf.py
Included changes:
* CDRIVER-4399 update to Fedora 37 environment for RPM build
* sync RPM spec file for 1.22.0 release
* CDRIVER-4413 adjust configuration for building docs with Sphinx 5.0+
Evergreen patch build: https://spruce.mongodb.com/version/62e438853627e033781fccc3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CDRIVER-4413, CDRIVER-4399

.evergreen/compile-windows-mingw.bat, .evergreen/install-uninstall-check-windows.cmd, .evergreen/link-sample-program-mingw-bson.cmd, .evergreen/link-sample-program-mingw.cmd
Related to CDRIVER-4136. Followup to https://github.com/mongodb/mongo-c-driver/pull/1067. A recent [patch build](https://evergreen.mongodb.com/lobster/evergreen/task/mongo_c_driver_releng_link_with_bson_mingw_patch_2966c67d69bc22c3f68fc4f2b2d2164b7cf5b665_62e8462430661553e63af154_22_08_01_21_31_17/0/task#bookmarks=0%2C743&l=1&shareLine=683) exposed some scripts that were missed in https://github.com/mongodb/mongo-c-driver/pull/1067. This PR applies the appropriate CMake config vars to consistently opt into strict C99 conformance.
=> CDRIVER-4136 Update cmd scripts to use strict C99 via CMake config vars

src/libmongoc/src/mongoc/mongoc-counters-private.h
get_nprocs is not available on Android below API level 23.
=> Fix _mongoc_get_cpu_count on Android

debian/changelog, debian/rules
Note that after merging this PR I will also cherry-pick and push on the `r1.22` branch.
=> CDRIVER-4456 (Debian packaging) Explicitly link to libatomic on riscv64 (Closes: #1017345)

.evergreen/config.yml, .evergreen/download-mongodb.sh, build/evergreen_config_lib/variants.py
This PR resolves CDRIVER-4361.
Server versions 4.0, 4.2, and 4.4 are not available for zSeries RHEL 8.3, so they have been removed. Server version 6.0 has been added instead.
The `download-mongodb.sh` file was synced with [it's latest state](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/8159c42f559900ca28381b284590756ce3a672c6/.evergreen/download-mongodb.sh) to resolve System Failures on Evergreen due to 5.0.8 no longer being available.
Changes verified by [this patch](https://spruce.mongodb.com/version/6308f5b4850e615766de8ca9).
=> CDRIVER-4361 Update zSeries RHEL 8.3 tasks and server versions

src/libmongoc/src/mongoc/mcd-azure.c, src/libmongoc/src/mongoc/mongoc-http.c, src/libmongoc/tests/test-mcd-azure-imds.c, src/libmongoc/tests/test-mongoc-http.c
While preparing additional tests for CDRIVER-4454, a few issues were found in the internal HTTP API.
=> CDRIVER-4454 Some HTTP Fixes

build/cmake/CCache.cmake
Restores Ccache version checks.
Also apparently "Ccache" is the correct spelling.
=> CDRIVER-4468 Detect old Ccache to prevent spurious failures

src/libmongoc/src/mongoc/mcd-azure.c, src/libmongoc/src/mongoc/mcd-integer.h, src/libmongoc/src/mongoc/mcd-time.h
- Use `BSON_INLINE`, not `inline`.
- Add cast of `size_t` to `int`.
Resolves errors on [VS 2013 build](https://evergreen.mongodb.com/lobster/evergreen/task/mongo_c_driver_windows_2013_debug_compile_nosasl_nossl_686bff81f565f93db83d99902ce1c3a6f89922c7_22_09_09_19_56_55/0/task#bookmarks=0%2C1725&shareLine=1673).
I also added `debug-compile-nosasl-nossl` tasks to the [GitHub Pull Request Testing](https://spruce.mongodb.com/project/mongo-c-driver/settings/github-commitqueue). The required alias defines tasks that are run for GitHub PRs.
=> CDRIVER-4454 fix VS 2013 compile

src/libmongoc/CMakeLists.txt
- Use a stable version of the `crypt_shared` library for downloads.
A user reported an error downloading `crypt_shared` attempting to build all targets: https://www.mongodb.com/community/forums/t/problem-downloading-crypt-shared-when-installing-the-mongodb-c-driver/189370
Until CDRIVER-4427 is fully resolved, it may be a small improvement to use a stable version of the `crypt_shared` library for downloads.
=> CDRIVER-4427 use stable mongo_crypt shared for tests

CMakeLists.txt, build/cmake/CMakeLists.txt, build/cmake/LoadTests.cmake, build/cmake/TestFixtures.cmake, build/fake_azure.py, build/proc-ctl.py, src/libmongoc/tests/test-mcd-azure-imds.c
This is a follow-up to #1104. This changeset introduces automated testing of the IMDS server via CTest test fixtures. CTest will handle spawning and stopping the IMDS server as it is needed for executing tests. The `fake_azure.py` script was cleaned up for older Python compatibility in anticipation of sharing with other driver codebases and other platforms.
=> IMDS Mock Server Testing

src/libbson/src/bson/bson-atomic.h, src/libbson/src/bson/bson-compat.h
These file changes fix the build issues on the IBM AIX platform. 
Since AIX is not taken care of in the existing library, "BSON_USE_LEGACY_GCC_ATOMICS" is not getting defined, and "DEF_ATOMIC_OP" macro which dynamically creates code for atomic functions based on the Operating system, generates incorrect code with multiple return statements (Code expanded using xlC -E ). 
```
static __inline__ signed char bson_atomic_int8_fetch_add(signed char volatile * a, signed char addend, enum bson_memory_order ord) {
do {
switch (ord) {
case bson_memory_order_acq_rel:
BSON_IF_MSVC(
return _InterlockedExchangeAdd8(a, addend);) return __tg_builtin("__sync_fetch_and_add", a, addend);
case bson_memory_order_seq_cst:
BSON_IF_MSVC(
return _InterlockedExchangeAdd8(a, addend);) return …
```
=> AIX platform build fix

build/mongodl.py
Port the build system to Fedora by extending DISTRO_VERSION_MAP by a mapping from Fedora version 32-36 to RHEL version 8 according to official Fedora documentation:
https://docs.fedoraproject.org/en-US/quick-docs/fedora-and-red-hat-enterprise-linux
Signed-off-by: Michał Grzelak <mig@semihalf.com>
=> build/mongodl.py: Port mongo-c-driver to Fedora

build/mongodl.py
During 'cmake --build .' file linked by /etc/os-release is used to obtain operating system's type and its version number. Version is extracted in _infer_target_os_rel() from VERSION_ID field by regular expression r'VERSION_ID=("?)(.*?)\1'. Version is extracted as a second group of the regular expression. This pattern is correct for Debian-based operating systems, where value for this field is followed and ended with quotation marks, e.g. VERSION_ID="20.02". On RHEL-based distributions there are no quotation marks, e.g. VERSION_ID=36. Without quotation marks, ("?) and \1 are matched to null string; lazy operator is not forced to match anything, thus it is also matched to null string. This results in extraction of version number as a null string. In DISTRO_VERSION_MAP there is no entry for …
=> build/mongodl.py: Extract version of RHEL via .*

.evergreen/add-build-dirs-to-paths.sh, .evergreen/config.yml, CONTRIBUTING.md, build/evergreen_config_lib/functions.py, build/evergreen_config_lib/tasks.py, src/libmongoc/tests/json-test.c, src/libmongoc/tests/json/client_side_encryption/legacy/awsTemporary.json
This PR address CDRIVER-3882.
No changes were necessary to the C Driver interfaces to support AWS temp creds, as they are specified via BSON fields. Support for the `aws.sessionToken` field already added by https://github.com/mongodb/mongo-c-driver/pull/1043. This PR only required updating the legacy test runner to support the new corresponding spec tests.
Documentation was updated to describe the new `MONGOC_TEST_AWS_TEMP_*` environment variables by which AWS temp creds are communicated to the legacy test runner. The Evergreen config file and test scripts were updated to set these new environment variables accordingly via the [Drivers Evergreen Tools set-temp-creds.sh script](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/fd450866cbff621b3753ba6101b41454df612781/.evergreen/c …
=> CDRIVER-3882 Support AWS temporary credentials

build/mongodl.py
According to `man os-release', file /etc/os-release isn't mandatory to be present in the system. Fallback to /usr/lib/os-release in absence of /etc/os-release.
Signed-off-by: Michał Grzelak <mig@semihalf.com>
=> build/mongodl.py: Fall back to /usr/lib/os-release

build/mongodl.py
In Linux Mint in /etc/os-release there is ID=linuxmint instead of 'mint' present in DISTRO_ID_MAP. Add a mapping to handle it.
Add 'linuxmint' mapping in DISTRO_VERSION_MAP corresponding to official Mint docs: https://linuxmint.com/download_all.php
Signed-off-by: Michał Grzelak <mig@semihalf.com>
=> build/mongodl.py: Port the build system to Mint

src/libmongoc/src/mongoc/mongoc-apm-private.h, src/libmongoc/src/mongoc/mongoc-apm.c, src/libmongoc/src/mongoc/mongoc-server-description-private.h, src/libmongoc/src/mongoc/mongoc-server-description.c, src/libmongoc/tests/test-mongoc-server-description.c, src/libmongoc/tests/unified/entity-map.h, src/libmongoc/tests/unified/runner.c
CDRIVER-4502
This updates the server description and command monitoring struct to store the connection ID as `int64_t` to reflect the type returned by the server. `mongoc_server_description_handle_hello` was updated to accept any integer for the `connectionId` field in the response and will read the field as int64.
To preserve backward compatibility, `mongoc_apm_command_started_get_server_connection_id` (and the equivalent methods for other command monitoring events) still return the value as `int32_t`. If the connection ID returned from the server exceeds the 32-bit range, `-1` is returned.
=> CDRIVER-4502: Handle int64 connectionId values in hello responses

src/libmongoc/doc/mongoc_database_find_collections_with_opts.rst
The code snippet in the documentation below errored when built using the c driver. The field`.msg` did not exist, there was a missing curly brace, and `cursor` was undefined.
=> [CDRIVER-4478] Fix code snippet in find collection documentation

src/libmongoc/src/mongoc/mongoc-crypt.c, src/libmongoc/src/mongoc/mongoc-http.c
- Allow HTTP/1.1 protocol in response
- Fix error return check in `_try_add_azure_from_env`
Discovered during integration testing for DRIVERS-2411. WIP integration tests pass with these fixes.
HTTP requests from libmongoc use [HTTP/1.0](https://github.com/mongodb/mongo-c-driver/blob/master/src/libmongoc/src/mongoc/mongoc-http.c#L68). The Azure IMDS server responds with HTTP/1.1. https://www.rfc-editor.org/rfc/rfc2145#section-2.3 does not prohibit a server response with a minor version greater than the one received.
> An HTTP server SHOULD send a response version equal to the highest
version for which the server is at least conditionally compliant, and
whose major version is less than or equal to the one received in the
request.  An HTTP server MUST NOT send a version for which it is not …
=> CDRIVER-4454 fix error return and HTTP version check

.evergreen/mongo-c-driver.spec, .evergreen/spec.patch, debian/changelog
Evergreen patch build: https://spruce.mongodb.com/version/63519bbae3c3315fe0191dae/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The `debian-package-build` task omitted from the patch build because the task is currently broken as a result of the ongoing Perl transition in Debian unstable.
=> DEB and RPM Packaging for 1.23.1

build/maintainer-flags.txt
This PR resolves CDRIVER-4504 as followup to CDRIVER-4484.
Changes were verified by [this patch](https://spruce.mongodb.com/version/63485b21850e6128847b27fe).
=> CDRIVER-4504 Add -Wstrict-prototypes to maintainer flags

src/libmongoc/src/mongoc/mongoc-server-description.c, src/libmongoc/tests/test-mongoc-server-description.c
Before when a type error occurred in `mongoc_server_description_handle_hello` the program jumped to the `failure` label and exited without setting an error. Now the `failure` label sets the error message and code as a type error. There are two different types of failures in `mongoc_server_description_handle_hello` with different error codes, so the `failure` label was split into two labels to make it clearer which type of error is occuring.
=> CDRIVER-4499 Set bson_error when hello response is malformed

src/libmongoc/tests/json/change_streams/unified/change-streams-disambiguatedPaths.json
No new changes are required in the C driver to support the new field (`disambiguatedPaths`) in `updateDescription` for change stream update events, since the C driver does not parse change stream documents. The new test file is added.
=> CDRIVER-4440 Add test file for new field in updateDescription

src/libmongoc/src/mongoc/mongoc-counters.c
CDRIVER-4505
It appears that getpagesize has been deprecated on newer MacOS versions. We can see that POSIX version 7 (link below) has removed getpagesize altogether from the standard, so even including unistd.h does not solve this problem on newer MacOS versions.
Please see here at section B.3.2 System Interfaces Removed in the Previous Version:
https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xsh_chap03.html
Relevant stackoverflow:
https://stackoverflow.com/a/37193970
Jira:
https://jira.mongodb.org/browse/CDRIVER-4505
=> CDRIVER-4505 Fix build on MacOS due to undeclared getpagesize

src/libmongoc/tests/unified/entity-map.c
This PR is a followup to https://github.com/mongodb/mongo-c-driver/pull/1094 to address [current task failures on Evergreen](https://spruce.mongodb.com/version/mongo_c_driver_40a64c2ffd6634021741e5435be15089d1f466f3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
I [overlooked](https://github.com/mongodb/mongo-c-driver/pull/1094#discussion_r1004734154) during code review that on top of `aligned_alloc`/`posix_memalign` requirements that the requested alignment to be both a multiple of 2 and a multiple of `sizeof(void*)`, several implementations ([one](https://www.freebsd.org/cgi/man.cgi?query=aligned_alloc), [two](https://man.netbsd.org/aligned_alloc.3)) additionally require that the alignment is _at least as large as_ `sizeof(void*)` , which `bool` does not satisfy.
This is what motivated …
=> CDRIVER-4503 Address aligned_alloc failures due to violating minimum alignment

src/libmongoc/tests/test-mongoc-sample-commands.c
Building on master results in a few unused variable warnings from the example code. Specifically the variable `bson_error_t error` was not being used in some examples, presumably to simplify the example code.
Adding a `BSON_UNUSED (error);` to these locations keeps the example code simple while also suppressing compiler warnings.
=> Supress unused variable warnings

src/libmongoc/tests/json/client_side_encryption/legacy/maxWireVersion.json
Update version on maxWireVersion test to 4.0.99 based on this [specification](https://github.com/mongodb/specifications/commit/e761591616849d9b507287811e77f7a359fb9587)
=> CDRIVER-4473 update maxServerVersion to 4.0.99

src/libmongoc/src/mongoc/mongoc-client-side-encryption.c, src/libmongoc/tests/test-mongoc-client-side-encryption.c
This adds more to the work for CDRIVER-4424, and adds two very basic error-handling tests. This already caught one minor issue in the implementation (a missing check for encryptedFields resulted in a regular collection being created without issue).
=> CDRIVER-4424: Additional error handling tests for CEC

src/libmongoc/tests/test-mongoc-client-side-encryption.c
There is a new prose test (specified [here](https://github.com/mongodb/specifications/commit/33a03f2eae1f479165fbde97993afb18241204af)). The c driver already had a very similar test `test_bypass_spawning_via_cryptSharedLibRequired`, so I just edited this test to match the prose test.
=> CDRIVER-4515 Add prose test to not spawn mongocrypt if shared library is loaded

src/libmongoc/tests/json/retryable_reads/unified/handshakeError.json, src/libmongoc/tests/json/retryable_writes/unified/handshakeError.json, src/libmongoc/tests/unified/runner.c
This PR amends CDRIVER-4517 and is a followup to https://github.com/mongodb/mongo-c-driver/pull/1141 that applies a bugfix that skips createChangeStream and listLocalSessions operations on serverless where they are not supported.
=> CDRIVER-4517 Sync unified retryable read and write test files with 35b17b70

src/libmongoc/src/mongoc/mcd-azure.h
https://jira.mongodb.org/browse/CDRIVER-4454
This include was inconsistent with all others in libmongoc. The path is necessary for compilation in Visual Studio when "src/libmongoc/src/libmongoc/src" is used as an include path.
This was originally introduced in mongodb/mongo-c-driver@686bff81f565f93db83d99902ce1c3a6f89922c7
----
This was responsible for a Windows build failure in PHPC: https://github.com/mongodb/mongo-php-driver/actions/runs/3581633513/jobs/6024994327#step:7:299
```
d:\a\mongo-php-driver\mongo-php-driver\src\libmongoc\src\libmongoc\src\mongoc\./mcd-azure.h(26): fatal error C1083: Cannot open include file: 'mcd-time.h': No such file or directory (compiling source file D:\a\mongo-php-driver\mongo-php-driver\src\libmongoc\src\libmongoc\src\mongoc\mcd-azure.c)
```
See also: …
=> CDRIVER-4454: Use consistent include path for mcd-time.h

.evergreen/config.yml, build/evergreen_config_lib/functions.py
This PR resolves CDRIVER-4519. Verified by [this patch](https://spruce.mongodb.com/version/63892c6e3e8e862a7830fa52/tasks).
The proposed changes are a straightforward substitution of the old `activate_venv.sh` scripts for kmstslvenv and authawsvenv with the exception of Python selection behavior on Windows.
CDRIVER-4530 was created in response to issues with default cipher suite incompatibilities on Windows due to use of Python 3.10. A crude but simple workaround was applied that explicitly uses Python 3.9 (windows-2017) or Python 3.8 (windows-2015) instead, as addressing the root problem (upgrading certificates to use a better signature algorithm) required an unexpectedly significant amount of effort. See CDRIVER-4530 for more info.
=> CDRIVER-4519 Replace activate_venv.sh with new hygienic scripts

.evergreen/config.yml, .evergreen/integration-tests.sh, build/evergreen_config_lib/functions.py, build/evergreen_config_lib/tasks.py, orchestration_configs/sharded_clusters/auth-load-balancer.json, orchestration_configs/sharded_clusters/auth-ssl-load-balancer.json, orchestration_configs/sharded_clusters/basic-load-balancer.json, orchestration_configs/sharded_clusters/basic-ssl-load-balancer.json, src/libmongoc/src/mongoc/mongoc-server-description-private.h, src/libmongoc/src/mongoc/mongoc-server-description.c, src/libmongoc/tests/json/initial_dns_seedlist_discovery/load-balanced/loadBalanced-directConnection.json, src/libmongoc/tests/json/initial_dns_seedlist_discovery/load-balanced/loadBalanced-replicaSet-errors.json, src/libmongoc/tests/json/initial_dns_seedlist_discovery/load-balanced/loadBalanced-true-txt.json, src/libmongoc/tests/json/initial_dns_seedlist_discovery/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.json, src/libmongoc/tests/json/initial_dns_seedlist_discovery/load-balanced/srvMaxHosts-zero-txt.json, src/libmongoc/tests/json/initial_dns_seedlist_discovery/load-balanced/srvMaxHosts-zero.json, src/libmongoc/tests/test-libmongoc.c
- Fix load balancer tasks.
- Remove `mongoc_global_mock_service_id`.
- Update load balancer DNS tests to https://github.com/mongodb/specifications/commit/5d1b42a05017ba27ffdbe6fd068a45e93e5b68c5
Resolves CDRIVER-4275 and CDRIVER-4387.
`integration-tests.sh` and orchestration configs have been updated for load balancer support. The orchestration configs were added in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/183 and later updated in https://github.com/mongodb-labs/drivers-evergreen-tools/pull/186.
The C driver maintains a modified copy of the drivers-evergreen-tools script [`run-orchestration.sh`](https://github.com/mongodb-labs/drivers-evergreen-tools) as `integration-tests.sh`. `integration-tests.sh` may be removed in CDRIVER-4029.
The JSON tests in …
=> CDRIVER-4275 and CDRIVER-4275

src/libmongoc/doc/installing.rst
Accounts for updates in the Evergreen matrix for these variants:
- GCC 9.4 (Ubuntu 20.04)
- GCC 10.2 (Debian 11.0)
- GCC 7.5 (Ubuntu 18.04)
- Power8 (ppc64le) (RHEL 8.1)
- zseries-rhel83
=> CDRIVER-4488 update supported platforms

src/libmongoc/tests/test-mongoc-retryable-writes.c
Resolves CDRIVER-4146. Verified by [this patch](https://spruce.mongodb.com/version/6398a0785623437037b6d485/tasks).
`test_framework_skip_if_max_wire_version_less_than_6` was chosen to comply with the [Retryable Writes Tests spec](https://github.com/mongodb/specifications/blob/3634d568587a776f18885502cde4f26f1c0ac051/source/retryable-writes/tests/README.rst#introduction):
> Tests will require a MongoClient created with options defined in the tests. Integration tests will require a running MongoDB cluster with server versions 3.6.0 or later.
=> CDRIVER-4146 Add live server version 3.6 condition to /retryable_writes/legacy tests

src/libmongoc/tests/test-mongoc-sample-commands.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1156, observed in [this patch](https://parsley.mongodb.com/evergreen/mongo_c_driver_arm_ubuntu1604_debug_compile_scan_build_patch_766a8a3c8c6afe2fa3031520c0fb6fef135d2d8a_6398bf553066157ccb88b3e0_22_12_13_18_07_20/0/task?bookmarks=0,867&selectedLine=667).
=> Address scan-build warning: value stored to ok is never read

src/libmongoc/tests/TestSuite.c, src/libmongoc/tests/TestSuite.h, src/libmongoc/tests/test-mongoc-http.c
Resolves CDRIVER-4538. Verified by [this patch](https://spruce.mongodb.com/version/6398bf553066157ccb88b3e0/tasks).
The `/http` test has been split into `/http/get` and `/http/post` and uses `httpbin.org` instead of `example.org`.
As a drive-by fix, this PR also resolves CDRIVER-4537 by ensure calls to `abort()` in the test suite are preceeded by both `fflush (stdout)` and `fflush (stderr)` to improve the quality of test output on failures.
=> Use httpbin.org instead of example.com for /http tests

.evergreen/config.yml, build/evergreen_config_lib/variants.py
The versions of OpenSSL tested on 2013, 2015, and 2017 are all 1.0.2s. The cause of failure is likely a host configuration issue. It is possibly related to BUILD-10841.
- Move the `authentication-tests-openssl-nosasl` to the `windows-2017` variant.
The `authentication-tests-openssl-nosasl` task on the `windows-2015` variant is failing.
Enabling verbose logs shows the failure occurs on [Connecting to Atlas Replica Set](https://parsley.mongodb.com/evergreen/mongo_c_driver_windows_2015_authentication_tests_openssl_nosasl_patch_d1134294420514f4308507ff5b2a5f4764d93c73_639dd762850e61492e0eff6d_22_12_17_14_51_16/0/task?bookmarks=0,212&selectedLine=164):
> Ping failure: No suitable servers found: `serverselectiontimeoutms` timed out: [TLS handshake failed: certificate verify failed (20): unable …
=> CDRIVER-3998 move Windows OpenSSL auth to 2017

src/libmongoc/tests/test-mongoc-bulk.c
This PR intends to resolve test failures observed in `/BulkOperation/multiple_errors`.
- wait for unacknowledged writes to apply in `test_bulk_reply_w0`
- set `appName` in failpoint for `test_bulk_write_multiple_errors`.
The `/BulkOperation/multiple_errors` test was recently added. It infrequently fails with an error matching the expected `errorReplies`. See CDRIVER-4539 for a sample test output.
`test_bulk_write_multiple_errors` sets a failpoint and expects the `insert` and `delete` commands to fail.
This [patch build with command monitoring enabled](https://spruce.mongodb.com/task/mongo_c_driver_asan_ubuntu_test_asan_latest_replica_set_noauth_nosasl_nossl_patch_218445d89368f5b6b89476b97900f33b071dfd1c_63a223aa2a60ed4a7b7f4db0_22_12_20_21_05_47/logs?execution=0) reproduced the test …
=> CDRIVER-4539 wait for unacknowledged writes to apply in `test_bulk_reply_w0`

.evergreen/config.yml, .evergreen/integration-tests.sh, .evergreen/run-aws-tests.sh, .evergreen/run-ocsp-responder.sh, build/evergreen_config_lib/functions.py, build/evergreen_config_lib/testazurekms.py, build/evergreen_config_lib/testgcpkms.py
This PR resolves CDRIVER-4543. Verified by [this patch](https://spruce.mongodb.com/version/639cded4d6d80a5cc50b8d8e/tasks).
As drive-by fix/improvement, ensures all cloning of the DET repository is consistent in their "already exists" check, use of `--depth 1`, and use of `git@github.com:<owner>/<repo>.git`.
=> CDRIVER-4543 Use find-python3.sh in integration-tests.sh

src/libbson/src/bson/bson-memory.c
@kalibera found that `aligned_alloc` is not in stdlib.h and it is not supported in Windows, despite that it is in C11. See the footnote in: https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance:
> The Universal CRT doesn't implement C11 aligned_alloc, but does provide _aligned_malloc and _aligned_free. Because the Windows operating system doesn't support aligned allocations, this function is unlikely to be implemented."
Actually `aligned_alloc()` is also missing on MacOS 10.13 (which we also need) but I will patch that on my end because you are no longer offically supporting MacOS < 10.14.
Downstream issues here: https://github.com/jeroen/mongolite/issues/247 and https://github.com/jeroen/mongolite/issues/244
=> CDRIVER-4550 Do not use aligned_alloc() on Windows

.evergreen/config.yml, build/evergreen_config_lib/variants.py
GCOV is sometimes [unusually slow](https://spruce.mongodb.com/task/mongo_c_driver_darwin_debug_compile_coverage_fa7d499b8ca53269b008cf7c19747164f98bede2_23_01_04_01_58_39/logs?execution=0) on macos-1014, regularly timing out on Evergreen due to taking over 1 hour to parse `.gcda` files when it should take [under 4 minutes](https://spruce.mongodb.com/task/mongo_c_driver_darwin_debug_compile_coverage_9e37e3e846395eaa3fa814f59bcf813f15692a4d_22_12_20_17_44_54/logs?execution=0). Some `.gcda` files such as `entity-map.c.gcda` [seem to be culprit](https://parsley.mongodb.com/evergreen/mongo_c_driver_darwin_debug_compile_coverage_fa7d499b8ca53269b008cf7c19747164f98bede2_23_01_04_01_58_39/0/task?bookmarks=0,11899&selectedLine=11759), but it is unclear why this behavior seems to only occur on …
=> Remove debug-compile-coverage from Apple LLVM variant

.evergreen/compile-test-azurekms.sh, .evergreen/compile-test-gcpkms.sh, .evergreen/compile-unix.sh, .evergreen/compile-windows.sh
Followup to https://github.com/mongodb/mongo-c-driver/pull/1152. The git clone command for libmongocrypt in `compile-test-gcpkms.sh` appears to have been missed.
As a drive-by improvement, ensured all libmongocrypt git clone commands use `--depth 1` for consistency.
=> CDRIVER-4394 Fix libmongocrypt branch in compile-test-gcpkms.sh

src/libbson/src/bson/bson-timegm.c
Observed a [surprise task failure](https://parsley.mongodb.com/evergreen/mongo_c_driver_darwin_debug_compile_scan_build_patch_21275453cd46253b9d252fdfc319c1880b3dca3a_63c04dcfd6d80a4b2c695915_23_01_12_18_13_36/0/task?bookmarks=0,994&selectedLine=331) during a patch build. I do not expect `tmp->tm_mon < MONSPERYEAR` to ever be violated given the context, but to satisfy scan-build, I elected to add the condition to the loop anyways. Verified by [this patch](https://spruce.mongodb.com/version/63c051db3066157a49372e66/tasks).
=> Assert bounds of tmp->tm_mon to address scan-build warnings

src/libmongoc/tests/test-mongoc-http.c
This PR resolves(?) CDRIVER-4538 and is a followup to https://github.com/mongodb/mongo-c-driver/pull/1161. Verified by [this patch](https://spruce.mongodb.com/version/63c04ebe1e2d175671d92967/tasks).
Spurious test failure due to `502 Bad Gateway` when running `/http` tests is [still occurring](https://parsley.mongodb.com/evergreen/mongo_c_driver_darwin_test_3.6_server_auth_sasl_darwinssl_21275453cd46253b9d252fdfc319c1880b3dca3a_23_01_10_21_07_05/0/task?bookmarks=0,7176&selectedLine=7122). Manually restarting the failed task often resolves the issue, so this PR adds an automatic retry attempt to the test instead.
=> CDRIVER-4538 Automatically retry on 502 Bad Gateway in /http tests

src/libmongoc/tests/json/retryable_writes/unified/insertOne-noWritesPerformedError.json
- Sync `insertOne-noWritesPerformedError` test from https://github.com/mongodb/specifications/commit/2051f3522390dd342f5bdd4703145eeb38cfd36f
DRIVERS-2501 fixed [a bug](https://github.com/mongodb/specifications/commit/2051f3522390dd342f5bdd4703145eeb38cfd36f#diff-01c94ffec48124f66d321265e57d6c892b1355813cf2bce099d0345ff222eabeR482) in the specification pseudo-code for retryable writes. As written, the pseudo-code resulted in reporting a `null` error if both write attempts failed with an error containing the `NoWritesPerformed` label. The intended behavior is to report the first error if both errors contain the `NoWritesPerformed` label.
The intended behavior was implemented in CDRIVER-4449 and is validated by the `insertOne-noWritesPerformedError` test.
=> CDRIVER-4531 sync insertOne-noWritesPerformedError

src/libmongoc/tests/test-mongoc-client-side-encryption.c
- Fix condition variable handling in `test_bypass_mongocryptd_shared_library`.
- Fix expire_at time in `mongoc_socket_accept`.
Fixes a possible race. If the listener thread calls `mongoc_cond_signal` before the test thread calls `mongoc_cond_timedwait`, the call to `mongoc_cond_timedwait` may time out.
The `expire_at` argument in `mongoc_socket_accept` is [documented as an absolute time from `bson_get_monotonic_time`](https://github.com/mongodb/mongo-c-driver/blob/9e18dd1b08591242a4da33be1f55f3a33c629d07/src/libmongoc/src/mongoc/mongoc-socket.c#L129-L132).
zseries fix was verified with this [patch build](https://spruce.mongodb.com/version/63c862c72fbabe4a31f1c4a5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
=> CDRIVER-4515 fix `test_bypass_mongocryptd_shared_library`

src/libmongoc/src/mongoc/mongoc-rand-openssl.c
Observed in [current patches](https://parsley.mongodb.com/evergreen/mongo_c_driver_openssl_build_and_run_authentication_tests_openssl_1.0.1_fips_ce46f36ae21b21dc349e853109da2e4c36832d1d_23_01_26_15_14_56/0/task?bookmarks=0,1183&shareLine=521) compiling against OpenSSL:
```
src/libmongoc/src/mongoc/mongoc-rand-openssl.c:31:5: warning: "OPENSSL_VERSION_NUMBER" is not defined, evaluates to 0 [-Wundef]
31 | #if OPENSSL_VERSION_NUMBER < 0x10101000L
|     ^~~~~~~~~~~~~~~~~~~~~~
```
Ensures `<openssl/opensslv.h>` which defines `OPENSSL_VERSION_NUMBER` is included without depending on transitive inclusion.
=> Address -Wundef of OPENSSL_VERSION_NUMBER in mongoc-rand-openssl.c

src/libbson/src/bson/bson-clock.c
Resolves(?) CDRIVER-4565. Verified by [this patch](https://spruce.mongodb.com/version/63d803720ae60614180f6406/tasks).
Per [Apple documentation](https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time) for `mach_absolute_time`:
> Prefer to use the equivalent `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` in nanoseconds.
Simplifies the implementation of `bson_get_monotonic_time` on MacOS and hopefully addresses the occasional `t2 >= t1` assertion violation observed on MacOS by delegating the required ~intermediate floating-point arithmetic~ unit conversion to the implementation of `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)`.
~To fully avoid the intermediate floating-point arithmetic,~ We may want to consider using `CLOCK_MONOTONIC_RAW` instead of `CLOCK_UPTIME_RAW`. Per [MAN …
=> CDRIVER-4565 Use clock_gettime_nsec_np instead of mach_absolute_time

src/libmongoc/src/mongoc/mongoc-client-side-encryption.c, src/libmongoc/src/mongoc/mongoc-collection.c, src/libmongoc/src/mongoc/mongoc-database-private.h, src/libmongoc/src/mongoc/mongoc-database.c, src/libmongoc/tests/test-mongoc-client-side-encryption.c
- do not check encryptedFieldsMap in CreateEncryptedCollection
Implements https://github.com/mongodb/specifications/pull/1376
=> CDRIVER-4428 do not check encryptedFieldsMap in CreateEncryptedCollection

.evergreen/scripts/compile-unix.sh, .evergreen/scripts/compile-windows.sh, .evergreen/scripts/run-tests.sh, src/libmongoc/src/mongoc/mongoc-crypt.c
- Update `CMAKE_PREFIX_PATH` and `CMAKE_INSTALL_PATH` to use Windows paths to unskip `-cse` tests on Windows.
- Use a relative path for `MONGOC_TEST_CSFLE_TLS_CERTIFICATE_KEY_FILE` and `MONGOC_TEST_CSFLE_TLS_CA_FILE` to fix `-cse` KMIP tests on Windows.
- Return an error on failure to construct a TLS stream for KMS.
Using a relative path for `MONGOC_TEST_CSFLE_TLS_CERTIFICATE_KEY_FILE` and `MONGOC_TEST_CSFLE_TLS_CA_FILE`
Changes in f4a83c084088e3878097b17881458548bc621ea2 result in `-cse` tests being skipped on Windows. Fixing the `CMAKE_PREFIX_PATH` and `CMAKE_INSTALL_PATH` resulted in test failures with with KMIP. [This patch](https://spruce.mongodb.com/version/63da96100ae6068e52b089ec/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) includes additional logs:
```
[2023/02/01 16:59:25.870] …
```
=> CDRIVER-3620 Unskip `-cse` tests on Windows

src/libmongoc/tests/json/sessions/unified/implicit-sessions-default-causal-consistency.json
Full patch build: https://spruce.mongodb.com/version/63dc0d4a9ccd4e093b0e3916/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CDRIVER-4431 sync causal consistency JSON test

.evergreen/scripts/compile-test-azurekms.sh, .evergreen/scripts/compile-test-gcpkms.sh, .evergreen/scripts/compile-unix.sh, .evergreen/scripts/compile-windows.sh
Followup to https://github.com/mongodb/libmongocrypt/pull/563 (CC @vector-of-bool), motivated by https://github.com/mongodb/mongo-c-driver/pull/1201#discussion_r1098078765 (CC @rcsanchez97).
Verified by ~[this patch](https://spruce.mongodb.com/version/63e3f33e2a60ed5eebfd75b2/tasks)~ [this patch](https://spruce.mongodb.com/version/63e3fa801e2d170a35e7cc82/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (includes MinGW fixes).
Avoids redundant compilation of libmongoc by libmongocrypt by setting `ENABLE_ONLINE_TESTS=OFF`, `BUILD_TESTING=OFF`, and `ENABLE_MONGOC=OFF`. Also sets `MONGOCRYPT_MONGOC_DIR` to point to the current C Driver repository to avoid a redundant download of the C Driver repo. I considered also forwarding `configure_flags` and `extra_configure_flags` but decided against it …
=> Avoid compiling libmongoc when compiling libmongocrypt

.evergreen/generated_configs/legacy-config.yml, .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py, .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
Disables inclusion of OCSP tasks in patch builds.
Motivated by the [OCSP Support Test Plan](https://github.com/mongodb/specifications/blob/master/source/ocsp-support/tests/README.rst) instructions which states:
> [...] each Evergreen task SHOULD set a batchtime of 14 days to reduce how often these tests run (this will not affect patch builds).
The OCSP tasks can be re-enabled for patch builds as needed by temporarily setting `task['patchable'] = True` when submitting patch builds.
As a drive-by improvement, also removes redundant specification of the `ubuntu2004-small` distro for tasks in the `ocsp` variant.
=> Set patchable: false for OCSP tasks

.evergreen/scripts/compile-test-azurekms.sh, .evergreen/scripts/compile-test-gcpkms.sh, .evergreen/scripts/compile-unix.sh, .evergreen/scripts/compile-windows.sh
A small followup to https://github.com/mongodb/mongo-c-driver/pull/1198 and https://github.com/mongodb/mongo-c-driver/pull/1202 that reduces the verbosity of output generated by compiling libmongocrypt. Verified by [this patch](https://spruce.mongodb.com/version/63ea5dc232f4174313be458d/tasks).
Invoking `exec 3>/dev/null` and setting `BASH_XTRACEFD="3"` [redirects xtrace output to /dev/null](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-BASH_005fXTRACEFD). This workaround can be removed once the libmongocrypt commit being built contains https://github.com/mongodb/libmongocrypt/pull/571. Note, [macos-1014 still emits xtrace output](https://parsley.mongodb.com/evergreen/mongo_c_driver_darwin_debug_compile_sasl_darwinssl_cse_patch_04d975b2e140e9a40859f4a44e53395 …
=> Silence xtrace and debug output when compiling libmongocrypt

src/libbson/src/bson/bson-timegm.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1178 and https://github.com/mongodb/mongo-c-driver/pull/1201. Upon further inspection, it seems like the analyzer fails to realize the subscripts of `ip` is indexing the array elements of `mon_lengths` (length of `MONSPERYEAR`), mistakening the length of the array pointed to by `ip` to be 2 (length of `mon_lengths` instead of `mon_lengths[n]`). To aid scan-build in its analysis, propose changing the type of `ip` to be explicitly a pointer to arrays of length `MONSPERYEAR`.
=> Address scan-build warning of tmp->tm_mon again

.evergreen/config_generator/etc/distros.py, .evergreen/scripts/find-cmake-version.sh
We currently do not use the windows-64-2016 distro. Discussion in BUILD-16821 suggests we shouldn't/won't be using it in the foreseeable future either.
=> Remove windows-64-2016 from Evergreen config

src/libmongoc/tests/test-mongoc-scram.c
Verified by [this patch](https://spruce.mongodb.com/version/63f8e55657e85a26ee8a71ed/tasks).
Several tasks on Evergreen are [currently failing](https://spruce.mongodb.com/version/mongo_c_driver_8eaac64c6893c717ac6af3bfdb4aac870848ee43/tasks) due to an unexpected error message in `/scram/auth_tests` that does not satisfy the expected substring search:
> src/libmongoc/tests/test-mongoc-scram.c:295 _check_error(): [Unable to use SCRAM-SHA-256 based authentication for user without any SCRAM-SHA-256 credentials registered] does not contain [Authentication failed]
It is unclear why the error message has changed. This PR simply proposes modifying the test to account for new error message in its expected output.
=> Update /scram/auth_tests to handle SCRAM-SHA-256 error messages

src/libmongoc/tests/json/client_side_encryption/legacy/fle2-CreateCollection.json, src/libmongoc/tests/json/client_side_encryption/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json
- Update fle2-CreateCollection and fle2-EncryptedFields-vs-EncryptedFieldsMap with updated state collection names
See https://github.com/mongodb/specifications/pull/1382. These tests are expected to fail against latest server builds until this update is applied.
=> CDRIVER-4587 sync fle2 tests

src/libmongoc/tests/mock_server/mock-rs.c, src/libmongoc/tests/mock_server/mock-server.c, src/libmongoc/tests/test-mongoc-bulk.c, src/libmongoc/tests/test-mongoc-cluster.c, src/libmongoc/tests/test-mongoc-database.c, src/libmongoc/tests/test-mongoc-loadbalanced.c, src/libmongoc/tests/test-mongoc-retryable-reads.c, src/libmongoc/tests/test-mongoc-retryable-writes.c
There have been several mock server tests since https://github.com/mongodb/mongo-c-driver/pull/1141 was merged that required manually disabling retryable handshakes to maintain correct test behavior (i.e. expectations that a single mock server hangup request should trigger progress). This PR removes those workarounds in favor of setting `retryReads=false` and `retryWrites=false` by default in the URI returned by `mock_server_get_uri` and `mock_rs_get_uri`. Mock server tests that actually require retryable handshakes are thus appropriately limited to `test-mongoc-retryable-reads.c` and `test-mongoc-retryable-writes.c` where `retryReads=true` or `retryWrites=true` is explicitly set as needed.
=> Disable retryable handshakes by default for mock server tests

src/libmongoc/tests/test-mongoc-scram.c
If a `/scram` test happens to fail before the test users are dropped, a subsequent run of the `/scram` tests will error on attempt to (re)create the test users because they already exist. This PR adds a `_clear_(saslprep|scram)_users` function that is invoked before required test users are created to prevent test failure due to existing test users.
=> Clear existing users before running /scram tests

.evergreen/generated_configs/legacy-config.yml, .evergreen/legacy_config_generator/evergreen_config_lib/functions.py, .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py, .evergreen/legacy_config_generator/evergreen_config_lib/variants.py, .evergreen/scripts/run-aws-tests.sh, src/libbson/src/bson/bson-string.c, src/libmongoc/src/mongoc/mongoc-cluster-aws.c, src/libmongoc/src/mongoc/mongoc-http.c, src/libmongoc/src/mongoc/mongoc-util-private.h, src/libmongoc/src/mongoc/mongoc-util.c, src/libmongoc/tests/bsonutil/bson-match.c, src/libmongoc/tests/test-mongoc-util.c, src/libmongoc/tests/unified/operation.c, src/libmongoc/tests/unified/util.c, src/libmongoc/tests/unified/util.h
- Add support for `AssumeRoleWithWebIdentity` in AWS Auth
- Fix length in `_mongoc_http_send`.
- Fix size arg in `bin_to_hex` utility.
- Ignore NULL for `bson_string_free`. 
AWS tasks were verified in this [Evergreen patch build](https://spruce.mongodb.com/version/63ff8372850e612de432d042).
The specification change is described in DRIVERS-1746.
`generate_AWS_ROLE_SESSION_NAME` generates a random 32 character hex string to generate `AWS_ROLE_SESSION_NAME` if needed:
> If ``AWS_ROLE_SESSION_NAME`` is set, it MUST be used for the ``RoleSessionName`` parameter, otherwise a suitable random name can be chosen.
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html lists the constraints for RoleSessionName:
> Length Constraints: Minimum length of 2. Maximum length of 64.
> …
=> CDRIVER-4081 Add support for `AssumeRoleWithWebIdentity` in AWS Auth

src/libbson/src/bson/bson-version.h.in, src/libmongoc/src/mongoc/mongoc-version.h.in
- add "or equal to" to `MONGOC_CHECK_VERSION` and `BSON_CHECK_VERSION`
This is a documentation fix to correctly describe the behavior.
`MONGOC_CHECK_VERSION` and `BSON_CHECK_VERSION` are also documented in RST with "greater than or equal to" behavior:
- http://mongoc.org/libmongoc/current/mongoc_version.html
- http://mongoc.org/libbson/current/version.html
=> add "or equal to" to version compare macro

src/libmongoc/src/mongoc/mongoc-openssl.c
https://jira.mongodb.org/browse/CDRIVER-4590
OpenSSL 3.0 loads error strings automatically and deprecated this function.
=> CDRIVER-4590 don't call ERR_load_BIO_strings for OpenSSL 3.0+

src/libbson/CMakeLists.txt, src/libbson/examples/bson-check-depth.c, src/libbson/examples/bson-metrics.c, src/libbson/src/bson/bson-decimal128.c, src/libbson/src/bson/bson-iter.c, src/libbson/src/bson/bson-json.c, src/libbson/src/bson/bson-memory.c, src/libbson/src/bson/bson-timegm.c, src/libbson/src/bson/bson.c, src/libbson/tests/test-b64.c, src/libbson/tests/test-iso8601.c, src/libbson/tests/test-json.c, src/libmongoc/src/mongoc/mongoc-util.c
This PR is a belated followup to https://github.com/mongodb/mongo-c-driver/pull/960 that addresses various warnings emitted by MSVC and MinGW on Windows distros, mostly pertaining to signedness mismatch or implicit narrowing conversions of integral types.
Verified by [this patch](https://spruce.mongodb.com/version/641dc814d6d80ac9bbcb4055/tasks), which adds `/WX` or `-Werror` when compiling `bson_shared` and `bson_static` with MSVC or MinGW respectively (treat all warnings as errors). These flags are _not_ included in this PR.
The scope of this PR is limited to MSVC and MinGW warnings for the libbson library only (+ some libbson test files and misc. drive-by fixes). Followup PRs will address warnings emitted by MSVC and MinGW for the libmongoc library, example executables, and test …
=> CDRIVER-4596 Reducing Warnings - MSVC and MinGW Warnings in libbson

src/libmongoc/CMakeLists.txt, src/libmongoc/tests/TestSuite.c, src/libmongoc/tests/TestSuite.h, src/libmongoc/tests/test-atlas-executor.c, src/libmongoc/tests/test-libmongoc-main.c, src/libmongoc/tests/test-libmongoc.c, src/libmongoc/tests/test-libmongoc.h, src/libmongoc/tests/unified/entity-map.c, src/libmongoc/tests/unified/entity-map.h, src/libmongoc/tests/unified/operation.c, src/libmongoc/tests/unified/operation.h, src/libmongoc/tests/unified/runner.c, src/libmongoc/tests/unified/runner.h, src/libmongoc/tests/unified/test-diagnostics.c, src/libmongoc/tests/unified/util.c, src/libmongoc/tests/unified/util.h
This PR introduces the `test-atlas-executor` binary to be used by the [Drivers Atlas Testing](https://github.com/mongodb-labs/drivers-atlas-testing) integration scripts for the C Driver and implements the `loop` unified test runner operation.
Addresses CDRIVER-2964 and is related to https://github.com/mongodb-labs/drivers-atlas-testing/pull/164.
Verified by [this patch](https://spruce.mongodb.com/version/640f8e347742aee833e8e489/tasks).
The [Atlas Planned Maintenance Test Scenario Format](https://mongodb-labs.github.io/drivers-atlas-testing/spec-test-format.html) reuses the [Unified Test Format](https://github.com/mongodb/specifications/blob/ed45dc95ca174a5832d653adec5a842184b7a82f/source/unified-test-format/unified-test-format.rst) specification but in an environment incompatible with …
=> CDRIVER-2964 Add test-atlas-executor for Atlas Planned Maintenance Tests
