mongodb/mongo-c-driver

- src/mongoc/mongoc-uri.c
- src/mongoc/mongoc-write-command.c
- src/mongoc/mongoc-write-concern-private.h
- src/mongoc/mongoc-write-concern.c
- tests/test-mongoc-uri.c
- tests/test-mongoc-write-concern.c
- tests/test-write-commands.c
https://jira.mongodb.org/browse/CDRIVER-580
> CDRIVER-580: fsync or j in write concern can imply GLE

- build/autotools/versions.ldscript
- build/cmake/libmongoc-ssl.def
- build/cmake/libmongoc.def
- doc/mongoc_uri_get_read_prefs.page
- doc/mongoc_uri_get_read_prefs_t.page
- src/libmongoc.symbols
- src/mongoc/mongoc-client.c
- src/mongoc/mongoc-uri.c
- src/mongoc/mongoc-uri.h
- tests/test-mongoc-uri.c
https://jira.mongodb.org/browse/CDRIVER-590
> CDRIVER-590: Support readPreference connection string option

- src/mongoc/mongoc-buffer.c
> min_bytes is unsigned -- this will never be false

- doc/mongoc_client_get_gridfs.page
- doc/mongoc_gridfs_file_remove.page
- doc/mongoc_gridfs_file_t.page
- doc/mongoc_gridfs_find_one_by_filename.page
- doc/mongoc_gridfs_remove_by_filename.page
- src/mongoc/mongoc-client.c
Rendered:
http://emptysqua.re/cdriver/mongoc_gridfs_file_remove.html
http://emptysqua.re/cdriver/mongoc_gridfs_remove_by_filename.html
> CDRIVER-513 missing docs

- CMakeLists.txt
- src/mongoc/mongoc-client.c
- tests/Makefile.am
- tests/ssl-test.h
- tests/test-libmongoc.c
- tests/test-libmongoc.h
- tests/test-mongoc-client.c
- tests/test-mongoc-stream-tls-error.c
CDRIVER-630 default_stream_initiator can block forever in TLS handshake
> fix hang in TLS handshake

- src/mongoc/mongoc-scram.c
instead use EVP_sha1 so our scram auth is compatible with openssl in FIPS
mode.
> Avoid use of SHA1 for scram for FIPS

- src/mongoc/mongoc-bulk-operation.c
- src/mongoc/mongoc-collection.c
- src/mongoc/mongoc-write-command-private.h
- src/mongoc/mongoc-write-command.c
This is the same optimization done for bulk inserts.
Hopefully it looks good, much of it is only slightly modified from the insert code.
> bulk: send multiple delete commands at once.

- src/mongoc/mongoc-cluster.c
- src/mongoc/mongoc-stream.c
CDRIVER-650 crash after replset reconnect
> CDRIVER-650 crash after replset reconnect

- src/mongoc/mongoc-gridfs-file.c
This should hopefully address issues with several tickets, including CDRIVER-509, CDRIVER-510 and CDRIVER-847.
> CDRIVER-510 don't seek if page is NULL

- tests/test-mongoc-gridfs.c
Test GridFS operations on an empty file.
> CDRIVER-509 and friends: test empty file

- doc/mongoc_write_concern_set_wmajority.page
- doc/mongoc_write_concern_set_wtimeout.page
- src/mongoc/mongoc-write-concern.c
- tests/test-mongoc-write-concern.c
https://jira.mongodb.org/browse/CDRIVER-851
> CDRIVER-851: Negative wtimeout values are invalid

- doc/mongoc_gridfs_t.page
Stay tuned on the GridFS spec for any potential changes to this behavior.
> CDRIVER-512: GridFS ignores read preference

- src/mongoc/mongoc-gridfs-file.c
The ticket remains open in JIRA, pending changes to `file->error` when these kinds of issues are detected.
> CDRIVER-869: check for missing GridFS chunks

- doc/mongoc_cursor_get_hint.page
https://jira.mongodb.org/browse/CDRIVER-1189
> CDRIVER-1189: Document mongoc_cursor_get_hint

- build/autotools/versions.ldscript
- build/cmake/libmongoc-ssl.def
- build/cmake/libmongoc.def
- doc/mongoc_cursor_set_hint.page
- src/mongoc/mongoc-cursor.c
- src/mongoc/mongoc-cursor.h
- tests/test-mongoc-cursor.c
https://jira.mongodb.org/browse/CDRIVER-1188
> CDRIVER-1188: Implement mongoc_cursor_set_hint()

- debian/changelog
- debian/control
These are the changes to clean up for the 1.3.5-1 upload.
> Clean up for the 1.3.5-1 upload

- build/autotools/versions.ldscript
- build/cmake/libmongoc-ssl.def
- build/cmake/libmongoc.def
- doc/mongoc_collection_create_index_2.page
- src/libmongoc.symbols
- src/mongoc/mongoc-collection.c
- src/mongoc/mongoc-collection.h
- tests/test-mongoc-collection.c
I added the memset(error) to 0 thing like you mentioned.
> CDRIVER-725 added mongoc_collection_create_index_2 function

- doc/mongoc_client_command_simple_with_server_id.page
Updated the signature of mongoc_client_command_simple_with_server_id() to reflect the implemented function.
> CDRIVER-1334 fixed function signature in documentation

- doc/mongoc_basic_aggregate.page
- doc/mongoc_collection_copy.page
- doc/mongoc_common_task_examples.page
- doc/mongoc_database_copy.page
- examples/basic_aggregation/basic-aggregation.c
- examples/basic_aggregation/constants.c
- examples/basic_aggregation/distinct.c
- examples/basic_aggregation/map-reduce-advanced.c
- examples/basic_aggregation/map-reduce-basic.c
- examples/common_operations/clone-collection.c
- examples/common_operations/common-operations.c
- examples/common_operations/copydb.c
- examples/common_operations/explain.c
- examples/doc-common-insert.c
Fixed the the link in both databse_copy.page and collection_copy.page
> CDRIVER-1201 added documentation for common operations

- src/mongoc/mongoc-ssl.c
- src/mongoc/mongoc-ssl.h
> re-consted ssl_opts strings

- src/mongoc/mongoc-client.c
- src/mongoc/mongoc-collection.c
- src/mongoc/mongoc-read-prefs-private.h
- src/mongoc/mongoc-read-prefs.c
- tests/test-mongoc-collection.c
Validate read preferences where they are used. If they are invalid, set error where applicable.
> CDRIVER-608 validate mongoc_read_prefs_t's

- doc/mallard2man.py
- doc/mongoc_basic_aggregate.page
- doc/mongoc_common_task_examples.page
> CDRIVER-1201 fix man

- doc/mongoc_advanced_connections.page
- doc/mongoc_authentication.page
Moved SSL instructions from authentication to advanced_connections.
> CDRIVER-1320 move SSL instructions

- tests/test-mongoc-client.c
Ensures a lack of special handling for writeConcerns and writeConcernErrors in generic command functions.
> CDRIVER-1322: test for generic command functions

- src/mongoc/mongoc-client-private.h
- src/mongoc/mongoc-write-concern-private.h
- src/mongoc/mongoc-write-concern.c
Added internal functions and values for implementing writeConcern support for commands that write.
> CDRIVER-1322: internal helper functions and values

- src/mongoc/mongoc-collection.c
By using reply_ptr, removed need for bson_copy_to call in mongoc_collection_find_and_modify_with_opts
> CDRIVER-1381: small optimization in reply_local

- CMakeLists.txt
- src/mongoc/Makefile.am
- src/mongoc/mongoc-metadata-os-private.h
- src/mongoc/mongoc-metadata.c
- tests/test-mongoc-metadata.c
I split this into 2 commits.
1) The os_type field
2) The cmake build was broken with the experimental=off flag.
These were both part of the same CR, I just split it into 2 commits.
> Cdriver 1394

- tests/test-mongoc-collection.c
rename test and assert error does not exist more descriptively
> CDRIVER-1322: improve test for aggregate_w_write_concern

- doc/mongoc_collection_aggregate.page
- doc/mongoc_collection_aggregate_with_write_concern.page
Updated doc for mongoc_collection_aggregate, created doc for mongoc_collection_aggregate_with_write_concern.
> CDRIVER-1322: doc for mongoc_collection_aggregate_with_write_concern

- build/autotools/versions.ldscript
- build/cmake/libmongoc-experimental.def
- build/cmake/libmongoc-ssl-experimental.def
- build/cmake/libmongoc-ssl.def
- build/cmake/libmongoc.def
- src/libmongoc.symbols
- src/mongoc/mongoc-database.c
- src/mongoc/mongoc-database.h
- tests/test-mongoc-database.c
Implemented and tested mongoc_database_create_collection_with_write_concern.
> CDRIVER-1322: mongoc_database_create_collection_with_write_concern

- build/autotools/versions.ldscript
- build/cmake/libmongoc-experimental.def
- build/cmake/libmongoc-ssl-experimental.def
- build/cmake/libmongoc-ssl.def
- build/cmake/libmongoc.def
- src/libmongoc.symbols
- src/mongoc/mongoc-collection.c
- src/mongoc/mongoc-collection.h
- tests/test-mongoc-collection.c
Implement and test mongoc_collection_drop_with_write_concern.
> CDRIVER-1322: mongoc_collection_drop_with_write_concern

- doc/mongoc_collection_drop.page
- doc/mongoc_collection_drop_with_write_concern.page
wrote documentation for new symbol mongoc_collection_drop_with_write_concern, and updated documentation for thin wrapper mongoc_collection_drop.
> CDRIVER-1322: doc for mongoc_collection_drop_with_write_concern

- doc/mongoc_database_drop.page
- doc/mongoc_database_drop_with_write_concern.page
wrote documentation for mongoc_database_drop_with_write_concern, updated documentation for mongoc_database_drop.
> CDRIVER-1322: doc for mongoc_database_drop_with_write_concern

- doc/mongoc_collection_drop_index.page
- doc/mongoc_collection_drop_index_with_write_concern.page
wrote documentation for mongoc_collection_drop_index_with_write_concern and updated documentation for mongoc_collection_drop_index
> CDRIVER-1322: doc for mongoc_collection_drop_index_with_write_concern

- doc/mongoc_collection_rename.page
- doc/mongoc_collection_rename_with_write_concern.page
wrote documentation for mongoc_collection_rename_with_write_concern, updated documentation for mongoc_collection_rename.
> CDRIVER-1322: doc for mongoc_collection_rename_with_write_concern

- src/mongoc/mongoc-database.c
- tests/test-mongoc-database.c
mongoc_database_create_collection_with_write_concern: on writeConcernError, parse writeConcernError and return false.
> CDRIVER-1460: database_create_collection, parse wc err and return false

- src/mongoc/mongoc-collection.c
- tests/test-mongoc-collection.c
mongoc_collection_drop_index_on_write_concern: on writeConcernError, parse writeConcernError and return false.
> CDRIVER-1460: drop_index, parse wc err and return false

- CMakeLists.txt
- configure.ac
- metadata_script.py
- src/mongoc/Makefile.am
- src/mongoc/mongoc-config.h.in
- src/mongoc/mongoc-metadata-compiler-private.h
- src/mongoc/mongoc-metadata-private.h
- src/mongoc/mongoc-metadata.c
> CDRIVER-1398 metadata platform field

- src/mongoc/mongoc-topology.c
- src/mongoc/mongoc-uri-private.h
- src/mongoc/mongoc-uri.c
- tests/test-mongoc-uri.c
https://jira.mongodb.org/browse/CDRIVER-2056
https://jira.mongodb.org/browse/CDRIVER-2060
> CDRIVER-2056, CDRIVER-2060: Improve localThresholdMS URI option parsing

- doc/mongoc_cursor_is_alive.rst
- doc/mongoc_cursor_more.rst
- src/mongoc/mongoc-cursor-cursorid.c
- src/mongoc/mongoc-cursor.c
- tests/test-mongoc-cursor.c
Apparently, I don't have push permissions.
> CDRIVER-2093 fix cursor is_alive and more

- CONTRIBUTING.md
Let me know if the wording should be changed.
> add future timeout to contributing.md

- doc/mongoc_bulk_operation_set_client.rst
- doc/mongoc_bulk_operation_set_client_session.rst
- doc/mongoc_bulk_operation_t.rst
- doc/mongoc_collection_create_bulk_operation_with_opts.rst
- src/mongoc/mongoc-bulk-operation.c
- src/mongoc/mongoc-bulk-operation.h
https://jira.mongodb.org/browse/CDRIVER-2419
> CDRIVER-2419 mongoc_bulk_operation_set_client_session

- doc/mongoc_collection_insert_many.rst
Missing * for documents parameter.
> Fix mongoc_collection_insert_many's signature

- src/mongoc/mongoc-openssl.c
https://jira.mongodb.org/browse/CDRIVER-2605
> CDRIVER-2605 unset OpenSSL id callback independently

- tests/json/retryable_writes/bulkWrite.json
- tests/test-mongoc-retryable-writes.c
https://jira.mongodb.org/browse/CDRIVER-2628
Related to: https://github.com/mongodb/specifications/pull/313
> CDRIVER-2628 test retryable write after multi-document op in bulk

- src/libmongoc/examples/aggregation/aggregation1.c
> Correct the sample URI of the aggregation example

- src/libmongoc/src/mongoc/mongoc-cursor.c
- src/libmongoc/tests/test-mongoc-transactions.c
https://jira.mongodb.org/browse/CDRIVER-2744
> CDRIVER-2744: Allow primary RP in _mongoc_cursor_new_with_opts()

- build/opts_templates/mongoc-opts-private.h.template
- src/libmongoc/src/mongoc/mongoc-apm-private.h
- src/libmongoc/src/mongoc/mongoc-opts-helpers-private.h
- src/libmongoc/src/mongoc/mongoc-opts-helpers.c
- src/libmongoc/src/mongoc/mongoc-opts-private.h
- src/libmongoc/src/mongoc/mongoc-stream-gridfs-download-private.h
- src/libmongoc/src/mongoc/mongoc-stream-gridfs-upload-private.h
https://jira.mongodb.org/browse/CDRIVER-2993
> CDRIVER-2993 add missing header include checks and licenses

- src/libmongoc/src/mongoc/mongoc-client-private.h
Increased WIRE_VERSION_MAX to 8 to support 4.2 features.
> CDRIVER-2843 updated wire version max

- src/libmongoc/doc/mongoc_ssl_opt_t.rst
I noticed these are backwards.
> Swap calls to set ssl_opts on client/client pool

- .evergreen/config.yml
- build/evergreen_config_lib/tasks.py
I put the evergreen config regeneration in a separate commit to hopefully make the review a bit less painful.
> CDRIVER-3712 add 4.4 tests to matrix

- src/libmongoc/doc/advanced-connections.rst
Forgotten doc update of CDRIVER-3686.
> CDRIVER-3686 update docs

- .evergreen/install-uninstall-check-windows.cmd
- .evergreen/install-uninstall-check.sh
- .evergreen/link-sample-program-bson.sh
- .evergreen/link-sample-program-mingw-bson.cmd
- .evergreen/link-sample-program-mingw.cmd
- .evergreen/link-sample-program.sh
Full Evergreen patch build: https://evergreen.mongodb.com/version/5eecd68fa4cf47327ca803ca
> CDRIVER-3699 simplify Evergreen scripts

- .evergreen/config.yml
- build/evergreen_config_lib/tasks.py
- build/evergreen_config_lib/variants.py
- src/libmongoc/tests/test-libmongoc.h
- src/libmongoc/tests/test-mongoc-client.c
Now that SERVER-48715 is resolved, these tests should pass again.
> CDRIVER-3708 unskip tests

- src/libmongoc/src/mongoc/mongoc-uri.c
- src/libmongoc/tests/test-mongoc-uri.c
Lower case options set with mongoc_uri_set_options_as_* functions.
> CDRIVER-3476 lower case options

- CMakeLists.txt
- src/libmongoc/doc/installing.rst
Note: no Evergreen patch build since this documentation only.
> CDRIVER-3571 consolidate and simplify installation doc

- src/libmongoc/src/mongoc/mongoc-cmd.c
- src/libmongoc/src/mongoc/mongoc-host-list.c
- src/libmongoc/src/mongoc/mongoc-topology-scanner.c
- src/libmongoc/src/mongoc/mongoc-uri.c
- src/libmongoc/tests/test-mongoc-uri.c
Saved error in out parameters.
> CDRIVER-3513 saved errors in out parameter

- src/libmongoc/src/mongoc/mongoc-client-pool.c
- src/libmongoc/src/mongoc/mongoc-client.c
- src/libmongoc/src/mongoc/mongoc-handshake.c
These are not urgent, and will be released in 1.18.0.
> Minor fixes to issues reported by Coverity

- .evergreen/build_snapshot_rpm.sh
- .evergreen/spec.patch
- build/sphinx/taglist.py
- src/libbson/doc/taglist.py
Patch build: https://spruce.mongodb.com/version/5f172ae832f4173db372d6f1/tasks
> CDRIVER-3509 fix rpm-package-build task

- build/sphinx/taglist.py
> try deprecated module import second

- CMakeLists.txt
- build/cmake/MaintainerFlags.cmake
Full patch build: https://spruce.mongodb.com/version/5f1999ee0ae6063922dac175/tasks
> CDRIVER-3756 eliminate CMake function redefinition

- .evergreen/config.yml
- .evergreen/spec.patch
- build/evergreen_config_lib/functions.py
Patch build: https://spruce.mongodb.com/version/5f1b13397742ae3ba1b1f9a2/tasks
> CDRIVER-3573 only hardcode version for GitHub PRs

- .evergreen/config.yml
- build/evergreen_config_lib/functions.py
Full patch build: https://spruce.mongodb.com/version/5f5936b0d1fe074487ddb3fc/tasks
> CDRIVER-3573 only hardcode version for GitHub PRs and patch builds

- src/libmongoc/tests/test-mongoc-cursor.c
SERVER-51380 changed ping such that it no longer accepts extra parameters.
> fix /Cursor/common/opts/cmd_deprecated

- src/libmongoc/CMakeLists.txt
- src/libmongoc/tests/json/unified/example-insertOne.json
- src/libmongoc/tests/test-conveniences.c
- src/libmongoc/tests/test-conveniences.h
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/unified/runner.c
This is some of the groundwork for the unified test runner and some additional test conveniences.
> CDRIVER-3422 add structure and error helpers

- .evergreen/build_snapshot_rpm.sh
- .evergreen/spec.patch
Task-specific Evergreen patch build: https://spruce.mongodb.com/version/5fc50fbe7742ae57742ec88f/tasks
> Fix rpm package build

- debian/changelog
- debian/control
- debian/watch
Additionally, I will cherry-pick these commits onto `master` after merging this PR.
> Debian packaging for 1.17.3

- src/libmongoc/tests/test-mongoc-mongohouse.c
> fix leak in tests

- src/libmongoc/tests/json-test-monitoring.c
- src/libmongoc/tests/json/client_side_encryption/aggregate.json
- src/libmongoc/tests/json/client_side_encryption/azureKMS.json
- src/libmongoc/tests/json/client_side_encryption/basic.json
- src/libmongoc/tests/json/client_side_encryption/bulk.json
- src/libmongoc/tests/json/client_side_encryption/count.json
- src/libmongoc/tests/json/client_side_encryption/countDocuments.json
- src/libmongoc/tests/json/client_side_encryption/delete.json
- src/libmongoc/tests/json/client_side_encryption/distinct.json
- src/libmongoc/tests/json/client_side_encryption/explain.json
- src/libmongoc/tests/json/client_side_encryption/find.json
- src/libmongoc/tests/json/client_side_encryption/findOneAndDelete.json
- src/libmongoc/tests/json/client_side_encryption/findOneAndReplace.json
- src/libmongoc/tests/json/client_side_encryption/findOneAndUpdate.json
- src/libmongoc/tests/json/client_side_encryption/gcpKMS.json
- src/libmongoc/tests/json/client_side_encryption/getMore.json
- src/libmongoc/tests/json/client_side_encryption/insert.json
- src/libmongoc/tests/json/client_side_encryption/keyAltName.json
- src/libmongoc/tests/json/client_side_encryption/localKMS.json
- src/libmongoc/tests/json/client_side_encryption/localSchema.json
- src/libmongoc/tests/json/client_side_encryption/missingKey.json
- src/libmongoc/tests/json/client_side_encryption/replaceOne.json
- src/libmongoc/tests/json/client_side_encryption/types.json
- src/libmongoc/tests/json/client_side_encryption/updateMany.json
- src/libmongoc/tests/json/client_side_encryption/updateOne.json
The first commit syncs the spec tests. The second is the actual changes.
> CDRIVER-3856 skip CSE listCollections cmds

- .evergreen/build_snapshot_rpm.sh
- .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/605a32a23066152e871a60c5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-3908 fix failing rpm-package-build task

- .evergreen/build_snapshot_rpm.sh
- .evergreen/config.yml
- .evergreen/spec.patch
- debian/gbp.conf
Evergreen patch build: https://spruce.mongodb.com/version/60678617c9ec445641c32e9c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Fix packaging r1.17

- .evergreen/build_snapshot_rpm.sh
- .evergreen/config.yml
- debian/gbp.conf
Evergreen patch build: https://spruce.mongodb.com/version/6067864dc9ec445641c32eed/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Fix packaging

- src/libmongoc/tests/unified/runner.c
This PR fixes the failing builds against sharded clusters on latest. The parsing logic doesn't cover all use-cases and fails with an assertion failure:
```
[2021/03/29 16:49:57.389] /data/mci/b2b314ac4682741d5d35f4b05db75034/mongoc/src/libmongoc/tests/test-conveniences.c:200 bson_iter_bson(): precondition failed: BSON_ITER_HOLDS_DOCUMENT (iter) || BSON_ITER_HOLDS_ARRAY (iter)
[2021/03/29 16:49:57.389] 2021/03/29 16:49:57.0389: [ 8121]:    ERROR:       mongoc: abort handler entered
[2021/03/29 16:49:57.389] ****************************** BEGIN_MONGOC_ERROR ******************************
[2021/03/29 16:49:57.389] test info:
[2021/03/29 16:49:57.389] [/data/mci/b2b314ac4682741d5d35f4b05db75034/mongoc/src/libmongoc/tests/unified/runner.c:1438 run_one_test_file()]
[2021/03/29 16:49:57.389] …
```
> Fix BSON parsing logic in unified test runner

- src/libmongoc/src/mongoc/mongoc-uri.c
https://jira.mongodb.org/browse/CDRIVER-3951
> CDRIVER-3951 Use PRId64 format specifier for int64_t

- src/libbson/src/bson/bson.c
- src/libbson/tests/test-bson.c
- src/libbson/tests/test-json.c
https://jira.mongodb.org/browse/CDRIVER-3958
> CDRIVER-3958 add trailing space after base64 JSON field

- src/common/.gitignore
- src/libbson/.gitignore
- src/libmongoc/.gitignore
This also reorganizes the gitignore for libbson a bit.
> Add more build artifacts to gitignore

- .evergreen/build_snapshot_rpm.sh
- .evergreen/mongo-c-driver.spec
- .evergreen/spec.patch
Single-task patch build: https://spruce.mongodb.com/version/607f455d1e2d17692fd36881/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-3957 vendor Fedora RPM spec file

- src/libmongoc/src/mongoc/mongoc-cursor.c
- src/libmongoc/tests/json/command_monitoring/find.json
- src/libmongoc/tests/json/unified/poc-command-monitoring.json
- src/libmongoc/tests/test-mongoc-cursor.c
CDRIVER-4026
This reverts changes from #793 and updates to the newest spec tests.
> CDRIVER-4026 Specify 5.0 cursor behaviour

- src/libmongoc/tests/json/crud/unified/insertMany-dots_and_dollars.json
- src/libmongoc/tests/json/crud/unified/insertOne-dots_and_dollars.json
- src/libmongoc/tests/json/unified/poc-crud.json
- src/libmongoc/tests/json/unified/poc-retryable-writes.json
https://jira.mongodb.org/browse/CDRIVER-4051
Synced with mongodb/specifications@44f83106033a609f2af40e3e4d99852a03096ba5
> CDRIVER-4051 Sync valid-pass and CRUD unified tests

- .evergreen/mongo-c-driver.spec
- .evergreen/spec.patch
Patch build; https://spruce.mongodb.com/version/60f792e2d6d80a33527d4df7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file for 1.18.0 release

- src/libmongoc/src/mongoc/mongoc-uri.c
- src/libmongoc/tests/json/auth/connection-string.json
- src/libmongoc/tests/json/connection_uri/additional-nonspec-tests.json
> CDRIVER-3502 Lift restriction on authSource without credentials

- src/libmongoc/src/mongoc/mongoc-apm-private.h
- src/libmongoc/src/mongoc/mongoc-apm.c
- src/libmongoc/tests/json/unified/observeSensitiveCommands.json
- src/libmongoc/tests/unified/entity-map.c
> CDRIVER-4104: Filter out events that have been redacted when observeSensitiveComands is false

- .evergreen/spec.patch
Patch build: https://spruce.mongodb.com/version/612d91b80ae60647c94241e3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-4132 update RPM spec patch post-1.19.0 release

- .evergreen/mongo-c-driver.spec
- .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/6137779c1e2d177c30e87ae9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file for 1.19.0 release

- .evergreen/benchmark.yml
Evergreen patch build: https://spruce.mongodb.com/version/617e1b02d6d80a6eb492398f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-4172 use perf.send for sending performance test results

- src/libmongoc/CMakeLists.txt
- src/libmongoc/src/mongoc/mongoc-ssl-private.h
- src/libmongoc/src/mongoc/mongoc-ssl.c
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-mongoc-ssl.c
> CDRIVER-4222 add _mongoc_ssl_opts_from_bson

- .evergreen/benchmark.yml
Evergreen patch build (of perf project): https://spruce.mongodb.com/version/61b0d35761837d22c69b6d29/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-4040 remove duplicate YAML keys

- .evergreen/mongo-c-driver.spec
- .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/61b0cbcc3e8e862ec357e6e5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file for 1.20.0 release

- .evergreen/mongo-c-driver.spec
- .evergreen/spec.patch
Patch build: https://spruce.mongodb.com/version/61fca3d71e2d1734d80b3533/tasks
> sync RPM spec file for 1.21.0 release

- .evergreen/mongo-c-driver.spec
- .evergreen/spec.patch
Evergreen patch build: https://evergreen.mongodb.com/version/62256c063e8e86070df06eac?redirect_spruce_users=true
> sync RPM spec file for 1.21.1 release

- src/libmongoc/doc/mongoc_auto_encryption_opts_set_extra.rst
https://jira.mongodb.org/browse/CDRIVER-4307
> CDRIVER-4307 fix default mongocryptd port in docs

- NEWS
- src/libbson/NEWS
Signed-off-by: Jesse Williamson <jesse.williamson@mongodb.com>
> Updated NEWS for 1.21.1 release.

- src/libmongoc/src/mongoc/mongoc-collection.c
https://jira.mongodb.org/browse/CDRIVER-4373
> CDRIVER-4373 do not set bulk let option unnecessarily

- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/src/mongoc/mongoc-database.c
- src/libmongoc/tests/json/client_side_encryption/legacy/fle2-CreateCollection.json
- Add clusteredIndex option to state collections.
- Drop the data collection after state collections.
See DRIVERS-2326 for the corresponding spec change.
> CDRIVER-4389 Update FLE 2 Create Collection

- src/libmongoc/tests/unified/runner.c
This doesn't fully complete the tasks of CDRIVER-3973, but finishes a
single isolated subtask thereof: Supprt for the `ignoreExtraEvents`
property on `expectedEventsForClient`, which is a prereq for enabling
the new changestreams tests.
In this case, if `ignoreExtraEvents` is specified as `true`, we won't
generate an error if the "actual events" contains more events than
"expected events." Each expected event is still searched for within
the "actual events" list, and anything additional is ignored.
> CDRIVER-3973: Support the ignoreExtraEvents property

- src/libmongoc/tests/json/client_side_encryption/legacy/create-and-createIndexes.json
- src/libmongoc/tests/json/client_side_encryption/legacy/fle2-validatorAndPartialFieldExpression.json
- src/libmongoc/tests/json/client_side_encryption/legacy/validatorAndPartialFieldExpression.json
Syncs the tests added in DRIVERS-2309. No driver changes needed.
> CDRIVER-4390 sync validatorAndPartialFieldExpression + create-and-createIndexes tests

- .evergreen/mongo-c-driver.spec
- .evergreen/spec.patch
Patch build: https://spruce.mongodb.com/version/62a4b0ed32f417299cf2425c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file for 1.21.2 release

- src/libmongoc/tests/json/client_side_encryption/unified/rewrapManyDataKey.json
Applies bugfixes to the CSE unified test files committed in https://github.com/mongodb/specifications/commit/fa046c7887ab61370d36758ffe883e2630940c15.
> CDRIVER-4317 sync CSE unified tests with fa046c78

- src/libmongoc/doc/mongoc_client_encryption_rewrap_many_datakey_result_get_bulk_write_result.rst
- src/libmongoc/src/mongoc/mongoc-client-side-encryption.c
- src/libmongoc/tests/json/client_side_encryption/unified/rewrapManyDataKey.json
- src/libmongoc/tests/unified/operation.c
This PR resolves CDRIVER-4415 and tests the changes proposed in https://github.com/mongodb/specifications/pull/1259.
> CDRIVER-4415 Allow bulkWriteResult to be optional

- src/libmongoc/tests/json/client_side_encryption/unified/addKeyAltName.json
- src/libmongoc/tests/json/client_side_encryption/unified/createDataKey-kms_providers-invalid.json
- src/libmongoc/tests/json/client_side_encryption/unified/deleteKey.json
- src/libmongoc/tests/json/client_side_encryption/unified/getKey.json
- src/libmongoc/tests/json/client_side_encryption/unified/getKeyByAltName.json
- src/libmongoc/tests/json/client_side_encryption/unified/removeKeyAltName.json
- src/libmongoc/tests/json/unified/kmsProviders-unconfigured_kms.json
This PR resolves CDRIVER-4419 and tests the changes proposed in https://github.com/mongodb/specifications/pull/1267.
> CDRIVER-4419 Remove unnecessary on-demand credentials in CSE unified spec tests

- debian/changelog
- debian/control
- debian/source/lintian-overrides
This is the standard post-release cherry-pick to master.
> Debian packaging commits for 1.22.0-1

- build/calc_release_version.py
I will also cherry-pick onto `r1.22` after merging to keep in sync.
> minor formatting fixes

- src/libmongoc/tests/json/client_side_encryption/unified/addKeyAltName.json
- src/libmongoc/tests/json/client_side_encryption/unified/getKey.json
- src/libmongoc/tests/json/client_side_encryption/unified/getKeyByAltName.json
- src/libmongoc/tests/json/client_side_encryption/unified/removeKeyAltName.json
> CDRIVER-4423 Sync CSE unified test files with 79f682a4

- src/libmongoc/tests/json/client_side_encryption/unified/createDataKey-kms_providers-invalid.json
- src/libmongoc/tests/json/client_side_encryption/unified/rewrapManyDataKey.json
Resolves CDRIVER-4443 and tests changes in https://github.com/mongodb/specifications/pull/1285.
> CDRIVER-4443 Update key material for Azure and KMIP datakeys in RewrapManyDataKey

- src/libmongoc/tests/test-mongoc-client-side-encryption.c
This PR resolves CDRIVER-4445.
> CDRIVER-4445 Add CSE Prose Test 16

- src/libmongoc/tests/json/transactions/unified/do-not-retry-read-in-transaction.json
> [CDRIVER-4436] Add do-not-retry-read-in-transaction tests

- src/libmongoc/tests/test-mongoc-client-side-encryption.c
This PR aims to resolve the `/client_side_encryption/single_and_pool_mismatches` test failure on Evergreen due to:
```
mongocryptd error: No suitable servers found: `serverSelectionTimeoutMS` expired: [connection refused calling hello on 'localhost:27020']
```
The unconditional bypassing of mongocryptd spawn was setting up incorrect expectations of a mongocryptd instance being present. This PR ensures the field is only set if `MONGOC_TEST_MONGOCRYPTD_BYPASS_SPAWN` is set accordingly.
> Ensure mongocryptdBypassSpawn is set according to environment

- src/libmongoc/tests/json/client_side_encryption/legacy/fle2-InsertFind-Unindexed.json
- Resync the fle2-InsertFind-Unindexed test to https://github.com/mongodb/specifications/commit/1a911b5e8911f6f57426ec1d451dbdc19480afd8
> CDRIVER-4446 update fle2-InsertFind-Unindexed

- .evergreen/config.yml
- .evergreen/run-tests.sh
- CONTRIBUTING.md
- build/evergreen_config_lib/functions.py
- src/libmongoc/tests/test-mongoc-client-side-encryption.c
Implements changes introduced in https://github.com/mongodb/specifications/commit/6464c0692bd0f81d92d58da0f72bf1642a703056.
> Update mock KMS server ports to avoid load balancer test conflicts

- src/libmongoc/tests/test-mongoc-sample-commands.c
This PR resolves CDRIVER-4506, which was discovered during local testing. I have elected to skip the test until a decision is made regarding update of Examples to account for this issue (see comments in DRIVERS-1846 for details).
> CDRIVER-4506 Conditionally skip Versioned API Example 6

- src/libmongoc/tests/test-mongoc-server-description.c
This PR is a follow-up to https://github.com/mongodb/mongo-c-driver/pull/1222 to address https://github.com/mongodb/mongo-c-driver/pull/1222/files#r1150046196
> CDRIVER-4539 fix test assert

- NEWS
- src/libbson/NEWS
It looks like the 1.22 and 1.23 NEWS changes are trampling each other. Will get that fixed.
> Update NEWS for 1.23.3

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
- .evergreen/scripts/build_snapshot_rpm.sh
Evergreen patch build: https://spruce.mongodb.com/version/645d3a730305b90894705ec4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Sync rpm spec

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/tasks.py
- .evergreen/scripts/link-sample-program-msvc-bson.cmd
- .evergreen/scripts/link-sample-program-msvc.cmd
Evergreen patch build: https://spruce.mongodb.com/version/646fcc2461837d63d6c1806a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> CDRIVER-3831 call batch scripts in the proper way

- src/libbson/src/bson/bson-memory.c
https://jira.mongodb.org/browse/CDRIVER-4654
> CDRIVER-4654 Fix missing aligned_alloc() on Android

- NEWS
- src/libbson/NEWS
- Add news for the recent 1.24.0 release to the master branch.
- Add news for the recent 1.24.1 release to the master branch.
Follows the [C/CXX Driver Process](https://docs.google.com/document/d/1ItyBC7VN383zNXu3oUOQJYR7adfYI8ECjLMJ5kqA9X8/edit):
> On master, copy over the new section from the NEWS files, commit and create a PR.
> copy NEWS for 1.24.0 and 1.24.1

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/649c68d12fbabedb3e5a6e7f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file from downstream

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/649c6e987742ae319be6b64b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file from downstream (r1.24)

- .evergreen/scripts/debian_package_build.sh
Follow-up for 14b37fa0f84beeae1fc458681c1ac26b8233b65e
Evergreen patch build: https://spruce.mongodb.com/version/649c69c90305b9fd6ede20b2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> fix debian-package-build task

- .evergreen/scripts/debian_package_build.sh
Follow-up for d9a5d22ad277b0a19509f6ddc172743b4b7a1c93
Evergreen patch build: https://spruce.mongodb.com/version/649c6b02c9ec441ea2c195a4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> fix debian-package-build task (r1.24)

- .evergreen/scripts/debian_package_build.sh
Follow up for f63348e0b7834063ab9a656d1ba4e6dafef5e784
> Ensure libutf8proc-dev is installed in Debian environment.

- src/libmongoc/tests/test-mongoc-handshake.c
Followup to https://github.com/mongodb/mongo-c-driver/pull/1340.
> libbson header Include consistency in test files

- src/libmongoc/doc/installing.rst
> add link to Docker image and Docker documentation

- src/libbson/src/bson/bson-utf8.c
See [comment of CDRIVER-4747](https://jira.mongodb.org/browse/CDRIVER-4747?focusedCommentId=5831667&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-5831667) for a description.
> CDRIVER-4747 use `size_t`

- build/sphinx/mongoc_common.py
> Fix Debian package build

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/654be1580ae606e85707f93d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file from downstream (r1.25)

- src/libmongoc/tests/json/retryable_writes/legacy/bulkWrite-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/deleteOne-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/findOneAndDelete-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/findOneAndReplace-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/findOneAndUpdate-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/insertMany-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/insertOne-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/replaceOne-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/legacy/updateOne-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/unified/bulkWrite-serverErrors.json
- src/libmongoc/tests/json/retryable_writes/unified/insertOne-serverErrors.json
- src/libmongoc/tests/json/transactions/legacy/error-labels.json
- src/libmongoc/tests/json/transactions/legacy/mongos-recovery-token.json
- src/libmongoc/tests/json/transactions/legacy/retryable-abort.json
- src/libmongoc/tests/json/transactions/legacy/retryable-commit.json
https://jira.mongodb.org/browse/CDRIVER-4210
Synced with mongodb/specifications@564547496b60c1f013c1a2edc27dd690f57ba04c
> CDRIVER-4210 sync tests to make fail point responses consistent with server

- src/libmongoc/tests/json/retryable_writes/legacy/insertOne-errorLabels.json
https://jira.mongodb.org/browse/CDRIVER-4806
Synced with mongodb/specifications@8de81802790c1deedbde438c62ceca4e5d2a6d63
> CDRIVER-4806 sync insertOne-errorLabels retryable writes legacy spec tests

- src/libmongoc/src/mongoc/mongoc-error-private.h
- src/libmongoc/src/mongoc/mongoc-error.c
https://jira.mongodb.org/browse/CDRIVER-4754
See: https://github.com/mongodb/mongo-c-driver/pull/1501/files#r1453763464
> CDRIVER-4754 add const modifier to _mongoc_write_error_handle_labels param

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/65e642a0c9ec443429a0e31f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file from downstream (r1.26)

- src/libbson/src/bson/bson-string.c
> CDRIVER-5504 Use size_t when indexing arrays

- .evergreen/generated_configs/legacy-config.yml
- .evergreen/legacy_config_generator/evergreen_config_lib/variants.py
- .evergreen/scripts/debian_package_build.sh
- build/cmake/SphinxBuild.cmake
Note that I don't have a working patch build, as it seems to still fail on a patch build for some reason that is not clear. I have confirmed that this works locally by manually merging the changes into the `debian/unstable` branch and building the packages directly from that branch.
> Fix debian package build r1.27

- .evergreen/scripts/debian_package_build.sh
No patch build since a patch build will not exercise these changes.
> configure git user/email during debian-package-build

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/66620d7fa0b4680007eafc1a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file from downstream (r1.27)

- src/libmongoc/src/mongoc/mongoc-collection.c
Control flow of estimated_document_count is needlessly complex when we have C99 available to mix declarations. This fixes a false-positive in static analysis on reply_local being destroyed while uninitialized.
**Note:** The `estimated_document_count` contained a call to `mongoc_cluster_stream_for_reads`, but the return value was simply discarded. There was no commentary on why this call occurs, and it isn't clear why it was there. Since it appears unused, it has been deleted. If it _should_ remain present, it should be given a comment to explain this "load bearing quirk". Do any reviewers have insight on the purpose of this call?
> [CDRIVER-5608] Clean up of estimated_document_count

- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/src/mongoc/mongoc-write-command-private.h
- src/libmongoc/src/mongoc/mongoc-write-command.c
- src/libmongoc/tests/test-mongoc-collection.c
insertOne and insertMany now return insertedIds of successful inserts in reply
> CDRIVER-3093: Include inserted _Ids in insert_one() and insert() results

- src/libmongoc/doc/mongoc_collection_insert_one.rst
- src/libmongoc/src/mongoc/mongoc-collection.c
- src/libmongoc/src/mongoc/mongoc-write-command-private.h
- src/libmongoc/src/mongoc/mongoc-write-command.c
- src/libmongoc/tests/test-mongoc-collection.c
https://jira.mongodb.org/browse/CDRIVER-3093
> Updated insert_one() documentation page based on CDRIVER-3093

- src/libbson/src/bson/bson.c
- src/libbson/src/bson/bson.h
- src/libbson/tests/test-bson.c
Two validation functions returning different error information and no one that returns everything at once
> CDRIVER-5574 Add bson_validate_with_error_and_offset

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/66ec5de07b732e00072d41ee/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec file from downstream (r1.28)

- src/libbson/doc/bson_value_copy.rst
- src/libbson/src/bson/bson-value.c
- src/libbson/tests/test-string.c
- src/libbson/tests/test-value.c
- src/libmongoc/tests/test-libmongoc.c
- src/libmongoc/tests/test-libmongoc.h
> CDRIVER-5734 fix max length string handling

- src/libbson/src/bson/bson-timegm.c
- src/libmongoc/src/mongoc/mongoc-crypt.c
Minor follow-up to #1840 to change more `#include "..."` to `#include <...>`.
> CDRIVER-5866 use more `<>` includes

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/67c234a906015800072106c8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> sync RPM spec from downstream

- src/libmongoc/tests/json/server_discovery_and_monitoring/rs/secondary_ipv6_literal.json
Sync to https://github.com/mongodb/specifications/commit/fc495d5a58479a6527d7950c0d4be57f0f8869c4
> CDRIVER-5926 sync test `secondary_ipv6_literal.json`

- .evergreen/config_generator/components/sbom.py
- .evergreen/config_generator/etc/distros.py
- .evergreen/generated_configs/tasks.yml
Similar to https://github.com/mongodb/mongo-cxx-driver/pull/1370.
> Temporarily relocate sbom task from rhel80 to rhel8.8

- build/bottle.py
This change only updates the embedded `bottle.py` for newer Python compatibility, required for running KMS tests with Python 3.13+
> Upgrade bottle.py for Python Compatibility

- .evergreen/scripts/debian_package_build.sh
This is a straight cherry-pick of #2068 to the `r2.0` branch.
> Fix debian package build 2.x

- .evergreen/etc/mongo-c-driver.spec
- .evergreen/etc/spec.patch
- .evergreen/scripts/build_snapshot_rpm.sh
Evergreen patch build: https://spruce.mongodb.com/version/688c0516a985180007d06f2a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> Fix rpm package build 1.x

- src/libbson/doc/bson_error_reset.rst
- src/libmongoc/doc/mongoc_bulkwrite_append_deletemany.rst
- src/libmongoc/doc/mongoc_bulkwrite_append_deleteone.rst
- src/libmongoc/doc/mongoc_bulkwrite_append_insertone.rst
- src/libmongoc/doc/mongoc_bulkwrite_append_replaceone.rst
- src/libmongoc/doc/mongoc_bulkwrite_append_updatemany.rst
- src/libmongoc/doc/mongoc_bulkwrite_append_updateone.rst
- src/libmongoc/doc/mongoc_bulkwrite_check_acknowledged.rst
- src/libmongoc/doc/mongoc_bulkwrite_serverid.rst
- src/libmongoc/examples/example-structured-log.c
- src/libmongoc/src/mongoc/mongoc-gridfs-bucket-file.c
- src/libmongoc/src/mongoc/mongoc-topology.c
- src/libmongoc/src/mongoc/mongoc-write-command-private.h
This PR fixes some miscellaneous typos I encountered while in the process of preparing that last round of Debian packages.
> fix some misc typos
